<style>
<!--
.dataTables_filter{
	float: right;
}

.dataTables_paginate{
	margin: 0px;
	float: right;
}

-->
</style>
<link rel="stylesheet" href="/assets/plugins/data-tables/DT_bootstrap.css" />
<div class="row-fluid" style="margin-top: 20px;">
	<div class="span12">
		<div class="portlet box purple">
			<div class="portlet-title">
				<div class="caption"><i class="icon-wrench"></i>Tipo de procolo de materiais</div>
				<div class="tools">
                    <a href="javascript:;" class="collapse"></a>
                </div>
			</div>
			<div class="portlet-body flip-scroll">
				<div id="sample_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
					<table class="table table-striped table-bordered table-hover" id="datatables">
                        <thead class="flip-content">
                            <tr>
                                <th style="width: 100px !important; text-align: center;">Código</th>
                                <th style="width: 120px">Tipo de movimento</th>
                                <th style="width: 130px">Nome</th>
                                <th style="width: 41px !important">Ação</th>
                            </tr>
                        </thead>
                            <tbody>
                                <?php foreach ($this->tpProtocoloList as $tipo):?>
                                    <tr>
                                        <td style="text-align: center;"><?php echo $tipo->id_tp_protocolo?></td>
                                        <td><?php echo $tipo->getMovimento()->nome?></td>
                                        <td><?php echo $tipo->nome ?></td>
                                        <td>
                                            <a href="/material/tipo-entrada/form/id_tp_protocolo/<?php echo $tipo->id_tp_protocolo?>" class="detail">
                                                <img src="<?php echo $this->baseUrl('images/edit.png')?>" data-tooltip title="Editar">
                                            </a>
                                            <a href="<?php echo $this->baseUrl('/material/tipo-entrada/delete/id_tp_protocolo/'.$tipo->id_tp_protocolo)?>" class="delete">
                                                <img src="<?php echo $this->baseUrl('images/delete.png')?>" data-tooltip title="Excluir">
                                            </a>
                                        </td>
                                    </tr>
                                <?php endforeach;?>
                            </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="<?php echo $this->baseUrl('scripts/material/tipoentrada.grid.js')?>"></script>