<link rel="stylesheet" type="text/css" href="/assets/plugins/bootstrap-datepicker/css/datepicker.css" />
<link rel="stylesheet" type="text/css" href="/styles/rh/ponto.folha-de-ponto.css" />
<!-- BEGIN X-EDITABLE PLUGIN-->
  <link href="/assets/plugins/bootstrap-editable/bootstrap-editable/css/bootstrap-editable.css" rel="stylesheet" type="text/css" media="screen"/>
  <link href="/assets/plugins/bootstrap-editable/inputs-ext/address/address.css" rel="stylesheet" type="text/css" media="screen"/>
<!-- END X-EDITABLE PLUGIN-->
  <link rel="stylesheet" type="text/css" href="/assets/plugins/select2/select2_metro.css" />
  <style>
<!--
td.vertical-align, th.vertical-align{
	vertical-align: middle;
}
-->
</style>
<div class="row-fluid" style="margin-bottom: 20px;"></div>
<div class="row-fluid">
	<div class="portlet box darkorange">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder"></i>Folha de Ponto</div>
			<div class="tools">
				<a href="javascript:;" class="collapse"></a>
			</div>
		</div>
		<div class="portlet-body">
			<form action="#" enctype="multipart/form-data" id="formPonto" method="post">
				<div class="row-fluid">
					<div class="span2">
						<div class="control-goup">
							<div class="control-label">Período</div>
							<div class="controls"><?php echo $this->formText('data', null, array('class' => "m-wrap span12 datepicker date", 'alt' => 'date', 'required'))?></div>
						</div>
					</div>
					<div class="span4">
						<div class="control-goup">
							<div class="control-label">Funcionario</div>
							<div class="controls">
								<?php echo $this->formSelect('id_funcionario',null, array('class' => 'span12'), $this->comboPessoa);?>
							</div>
						</div>
					</div>
					<div class="span5">
						<div class="control-goup">
							<div class="control-label" style="color: #fff">.</div>
							<div class="controls">
								<div class="btn-group">
									<button class="btn green buscar" type="submit">Buscar</button>
								</div>
								<div class="btn-group">
								    <button class="btn blue imprimir">Imprimir</button>
								</div>
								<div class="btn-group">
								    <button id="duplicado" style="display:none" class="btn black">Duplicado <span class="count"></span></button>
								</div>
								<div class="btn-group">
								    <button class="btn green grade-horario" >Grade horaria</button>
								</div>
							</div>
						</div>
					</div>
				</div>
			</form>
			<!--BEGIN TABS-->
			<div class="tabbable tabbable-custom">
				<ul class="nav nav-tabs">
					<li class="active"><a href="#tab_folha_ponto" data-toggle="tab">Folha de ponto</a></li>
					<li><a href="#tab_extra" data-toggle="tab">Extra</a></li>
					<li><a href="#tab_falta" data-toggle="tab">Falta</a></li>
				</ul>
				<div class="tab-content">
					<div class="tab-pane active" id="tab_folha_ponto">
						<div class="row-fluid" id="grid"></div>
					</div>
					<div class="tab-pane" id="tab_extra">
					</div>
					<div class="tab-pane" id="tab_falta">
					</div>
				</div>
			</div>
			<!--END TABS-->
		</div>
	</div>
</div>
<div class="diolog_justificacao" style="display: none;">
	<div class="row-fluid motivo" style="">
		<div class="control-group id_rh_justificacao_ponto">
			<div class="control-label ">Justificativa</div>
			<div class="controls">
				<?php echo $this->formSelect('id_rh_justificacao_ponto',null, array('class' => 'span12'), $this->comboJustivicativa);?>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="control-group">
			<div class="control-label">Descrição</div>
			<div class="controls">
				<?php echo $this->formHidden('id_rh_dados_ponto'); ?>
				<?php echo $this->formHidden('value_hora'); ?>
				<?php echo $this->formHidden('eq_element'); ?>
				<?php echo $this->formHidden('data_select'); ?>
				<?php echo $this->formTextarea('descricao', null, array('class' => 'm-wrap span12', 'style' => 'height: 100px;'))?>
			</div>
		</div>
	</div>
</div>
<div id="dialog_duplicado">
</div>

<div id="dialog-horario">
</div>

    <script type="text/javascript" src="/assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script type="text/javascript" src="/assets/plugins/bootstrap-datepicker/js/locales/bootstrap-datepicker.pt-BR.js"></script>
<!-- BEGIN X-EDITABLE PLUGIN-->
  <script src="/assets/plugins/bootstrap-editable/bootstrap-editable/js/bootstrap-editable.min.js" type="text/javascript"></script>
  <script src="/assets/plugins/bootstrap-editable/inputs-ext/address/address.js" type="text/javascript"></script>
  <script src="/assets/plugins/bootstrap-editable/inputs-ext/wysihtml5/wysihtml5.js" type="text/javascript"></script>
<!-- END X-EDITABLE PLUGIN-->
  <script type="text/javascript" src="/assets/plugins/select2/select2.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/rh/folhadeponto.grid.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/rh/folhadeponto.grid.extra.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/rh/folhadeponto.grid.falta.js')?>"></script>