<?php
    /**
     * formulario do controller relatorio para configurar um relatório
    */
?>
<script type="text/javascript">
function id(el) {
	return document.getElementById(el);
}

function mostra() {
	id('form1').style.display = 'block';

}

function esconde() {
	id('form1').style.display = 'none';

}


</script>
<div class="container-fluid">
        <div class="row-fluid" style="display: none; margin-top: 10px">
          <div class="span12" id="message-box">
            <div class="alert ">
            	<span class="text-message"></span>
                <button class="close" data-dismiss="alert"></button>
            </div>
          </div>
        </div>
</div>

<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Empresas
			 <small>Corporativo</small>
		</h3>
	</div>
</div>
<div class="row-fluid">
    <span class="span12">
	    <div class="portlet box green" id="">
    		<div class="portlet-title">
    			<div class="caption">
                <i class="icon-reorder"></i> Filtro de Relatorio - <span class="step-title">Empresas</span>
                </div>
    		</div>
    </span>
    		<div class="portlet-body form">
    		    <form target="_blank" method="post" class="form-horizontal" id="form_corporativo" novalidate="novalidate">
    		        <div class="form-wizard">
                        <div class="tab-content">
                            <div class="tab-pane active" id="tab1">
                                <div class="row-fluid">
								    <div class="span6 ">
										<div class="control-group">
											<div class="controls">
												<input type="hidden" name="id" value="" id="id">
											</div>
										</div>
									</div>
								</div>
                                <div class="row-fluid">
								    <div class="span6 ">
								        <div class="control-group">
								    		<label class="control-label">Tipo de relatório</label>
											<div class="controls">
												<label class="radio">
    												<div class="radio"><span><input type="radio" name="tp_relatirio" value="option1" checked="checked" onclick="esconde();" value="1"></span></div>
    													Simples
												</label>
												<label class="radio">
    												<div class="radio"><span><input type="radio" name="tp_relatirio" value="option1" onclick="mostra();" value="0"></span></div>
    													Analítico
												</label>
											</div>
										</div>
									</div>
								</div>
								 <div class="row-fluid">
								    <div class="span8 ">
								       <div class="control-group">
											<label class="control-label"><?php echo $this->translate('Estado')?></label>
												<div class="controls">
													<?php echo $this->formSelect('estado', null, array('style' => 'margin-bottom:10px', 'class'=>'m-wrap medium','tabindex'=>1), $this->estado)?>
												</div>
												<label class="control-label"><?php echo $this->translate('Cidade')?></label>
												<div class="controls">
													<?php echo $this->formSelect('cidade', null, array('style' => 'margin-bottom:10px','id'=>'cidade', 'class'=>'m-wrap medium','tabindex'=>1), array(null => 'Selecione'))?>
												</div>
												<label class="control-label"><?php echo $this->translate('Tipo de endereço')?></label>
												<div class="controls">
													<?php echo $this->formSelect('tipoEnd', null, array('style' => 'margin-bottom:10px', 'class'=>'m-wrap medium','tabindex'=>1), $this->tipoEnd)?>
												</div>
										</div>
									</div>
								</div>
								 <div class="row-fluid">
								    <div class="span6 ">
								       <div class="control-group">
											<label class="control-label"><?php echo $this->translate('Tipo de Empresa')?></label>
												<div class="controls">
													<label class="checkbox">
													    <input type="checkbox" id="tipoEmp" <?php echo !empty($this->vo->transportador)? 'CHECKED' :'' ?> name="transportadora" value="1">
														<?php echo $this->translate('Transportador')?>
												    </label>
												</div>
										</div>
									</div>
								</div>
                                <div class="row-fluid">
                                	<div class="span3 " >
                                		<div class="control-group" >
                                			<label class="control-label"><?php echo $this->translate('Tipo de Fornecedor')?></label>
                                			<div class="controls"  style="width: 450px;">
                                				<?php echo $this->formSelect('tipoForn', null, array('style' => 'margin-bottom:10px', 'class'=>'m-wrap span6','tabindex'=>1), $this->tipoForn)?>
                                			</div>
                                		</div>
                                	</div>
                                	<!--/span-->
                                	<div class="span6 ">
                                		<div class="control-group">
                                			<label class="control-label"><?php echo $this->translate('Tipo de Seguimento')?></label>
                                			<div class="controls" >
                                				<?php echo $this->formSelect('tipoSeg', null, array("style" => "margin-bottom:10px; float='left'", 'class'=>'m-wrap span6','tabindex'=>1), $this->tipoSeg)?>
                                			</div>
                                		</div>
                                	</div>
                                	<!--/span-->
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid">
					    <div class="span8 ">
					       <div class="control-group">
					       <div id="form1"  style="margin-bottom: 15px; display:none;">
                                <label class="control-label"><?php echo $this->translate('Quantidade de Transações')?></label>
									<div class="controls">
                                    <span class="help-block"><?php echo $this->translate('Quantidade de Transações')?></span>
    								<?php echo $this->formText('quantTrans1', $this->quantTrans1,array("placeholder" => "DE:")) ?>
    								<?php echo $this->formText('quantTrans2', $this->quantTrans2,array("placeholder" => "ATÉ:")) ?>
                                    <span class="help-block"><?php echo $this->translate('Quantidade de Transações')?></span>
    								 <?php echo $this->formText('transReal1', $this->transReal1,array("placeholder" => "DE:")) ?>
                                     <?php echo $this->formText('transReal2', $this->transReal2,array("placeholder" => "ATÉ:")) ?>

                                    <span class="help-block"><?php echo $this->translate('Quantidade de Transações')?></span>
    								<?php echo $this->formText('transData1', $this->transData1,array("placeholder" => "DE:")) ?>
                                    <?php echo $this->formText('transData2', $this->transData2,array("placeholder" => "ATÉ:")) ?>

    						</div>
    					</div>
    				</div>
    			</div>
    		</div>
         <div class="row-fluid">
    <div class="span6 ">
<div class="control-group" >
    <div class="controls" >
         <div class="row" style="margin-bottom: 15px;">
            <div id="form1" class="row"  style="margin-bottom: 15px; display:none;">
                      <div class="large-4 columns div_fantasia">
                          <label><?php echo $this->translate('Quantidade de Transações')?></label>
                          <?php echo $this->formText('quantTrans1', $this->quantTrans1,array("placeholder" => "DE:")) ?>
                          <?php echo $this->formText('quantTrans2', $this->quantTrans2,array("placeholder" => "ATÉ:")) ?>
                      </div>

                      <div class="large-4 columns div_fantasia">
                          <label><?php echo $this->translate('Transações Realizadas')?></label>
                          <?php echo $this->formText('transReal1', $this->transReal1,array("placeholder" => "DE:")) ?>
                          <?php echo $this->formText('transReal2', $this->transReal2,array("placeholder" => "ATÉ:")) ?>
                      </div>
                      <div class="large-4 columns div_fantasia">
                             <label><?php echo $this->translate('Data de Cadastro')?></label>
                          <?php echo $this->formText('transData1', $this->transData1,array("placeholder" => "DE:")) ?>
                          <?php echo $this->formText('transData2', $this->transData2,array("placeholder" => "ATÉ:")) ?>
                      </div>

                  </div>
                   </div>

                  </div>
                  </div>

    </div>
                  </div>

                  <div class="form-actions">
                        <button class="btn blue blue><i class="icon-print icon-big"></i>Gerar Relatório</button>
                      <a href="<?php echo $this->baseUrl('empresa/empresa/index')?>" class="btn green hidden-print">Voltar</a>


                  </div>
        </form>


					</div>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/empresa/relatorio.empresa-analitica.js')?>"></script>
