<link rel="stylesheet" href="<?php echo $this->baseUrl('assets/plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css');?>" />
<div class="row-fluid" style="margin-bottom: 20px;"></div>
<div class="row-fluid">
	<div class="portlet box darkorange">
		<div class="portlet-title">
			<div class="caption"><i class="fa fa-reorder"></i>Config. Locais</div>
			<div class="tools">
				<a href="javascript:;" class="collapse"></a>
			</div>
			<div class="actions">
			</div>
		</div>
		<div class="portlet-body form">
			<form action="#" class="form-horizontal" id="form_agrupador" method="post">
				<div class="row-fluid">
					<div class="span6">
						<div class="control-group">
							<label class="control-label">Código</label>
							<div class="controls">
								<?php echo $this->formText('id_rh_local', $this->vo->id_rh_local, array('style' => 'width: 90px', 'disable' => 'disable'))?>
								<?php echo $this->formHidden('id_rh_local', $this->vo->id_rh_local)?>
							</div>
						</div>
					</div>					
				</div>
				<div class="row-fluid">
					<div class="span6">
						<div class="control-group">
							<label class="control-label" id="labelCliente">Descrição <span style="color: red">*</span></label>
							<div class="controls">
              	<?php echo $this->formText("descricao",$this->vo->descricao, array("class" => "span12"));?>
							</div>
						</div>
					</div>
				</div>
				<div class="row-fluid">
								<div class="span6">
									<div class="control-group">
										<label class="control-label">Endereço</label>
										<div class="controls">
                 			<?php echo $this->formText('endereco',$this->vo->endereco ,array('class' => 'span12'));?>
                 		</div>
                 	</div>
                </div>
              </div>
              <div class="row-fluid">
								<div class="span6">
									<div class="control-group">
										<label class="control-label">Bairro</label>
										<div class="controls">
                 			<?php echo $this->formText('bairro',$this->vo->bairro,array('class' => 'span12'));?>
                 		</div>
                 	</div>
                </div>
								<div class="span6">
									<div class="control-group">
										<label class="control-label">Estado</label>
										<div class="controls">
                 			<?php echo $this->formText('estado',$this->vo->uf, array('style' => 'width: 90px')); ?>
                 		</div>
                 	</div>
                </div>
              </div>
              <div class="row-fluid">
								<div class="span6">
									<div class="control-group">
										<label class="control-label">Cidade</label>
										<div class="controls">
                 			<?php echo $this->formText('cidade',$this->vo->cidade,array('class' => 'span12'));?>
                 		</div>
                 	</div>
                </div>
								<div class="span6">
									<div class="control-group">
										<label class="control-label">CEP</label>
										<div class="controls">
                 			<?php echo $this->formText('cep',$this->vo->cep, array('style' => 'width: 90px')); ?>
                 		</div>
                 	</div>
                </div>
              </div>
				<div class="row-fluid">
					<div class="span6">
						<div class="control-group">
							<label class="control-label">CNPJ</label>
							<div class="controls">
	         			<?php echo $this->formText('cnpj',$this->vo->cnpj,array('class' => 'span12'));?>
           		</div>
            </div>
          </div>
          <div class="span6">
						<div class="control-group">
							<label class="control-label">CEI</label>
							<div class="controls">
								<?php echo $this->formText('cei',$this->vo->cei, array('class' => 'span12')); ?>
           		</div>
           	</div>
          </div>
				</div>
				<div class="row-fluid">
					<div class="span6">
						<div class="control-group">
							<label class="control-label">Tipo</label>
							<div class="controls">
	         			<?php echo $this->formText('tipo',$this->vo->tipo,array('class' => 'span12'));?>
           		</div>
            </div>
          </div>
          <div class="span6">
						<div class="control-group">
							<label class="control-label">Vale</label>
							<div class="controls">
								<?php echo $this->formText('vales',$this->vo->vales, array('class' => 'span12')); ?>
           		</div>
           	</div>
          </div>
				</div>
				<div class="row-fluid">
					<div class="span6">
						<div class="control-group">
							<label class="control-label">Responsavel</label>
							<div class="controls">
	         			<?php echo $this->formText('responsavel',$this->vo->responsavel,array('class' => 'span12'));?>
           		</div>
            </div>
          </div>
          <div class="span6">
						<div class="control-group">
							<label class="control-label">Centro de Custo</label>
							<div class="controls">
								<?php echo $this->formText('centro_custo',$this->vo->centro_custo, array('class' => 'span12')); ?>
           		</div>
           	</div>
          </div>
				</div>
				<div class="row-fluid">
					<div class="span6">
						<div class="control-group">
							<label class="control-label">Valor da Retenção</label>
							<div class="controls">
	         			<?php echo $this->formText('retencao',$this->vo->retencao,array('class' => 'span12'));?>
           		</div>
            </div>
          </div>
				</div>
				
				<div class="form-actions">
					<a href="<?php echo $this->baseUrl('rh/local/grid'); ?>" class="btn button-previous" style="display: inline-block;">
						<i class="m-icon-swapleft"></i> Voltar 
					</a>
          <button class="btn green" type="submit">
          	Salvar
        	</button>
				</div>
			</form>
		</div>
	</div>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js');?>"></script>
