<style>
<!--
.dataTables_filter{
	float: right;
}

.dataTables_paginate{
	margin: 0px;
	float: right;
}

-->
</style>
<div class="row-fluid">
     <div class="span12">
	      <h3 class="page-title">
	       Centro de Custo
	        <small> no sistema</small>
	      </h3>
     </div>
</div>
<div class="row-fluid">
	<div class="span12">
		<div class="portlet box steelblue">
			<div class="portlet-title">
				<div class="caption"><i class="icon-wrench"></i>Centro de Custo</div>
				<div class="tools">
                    <a href="javascript:;" class="collapse"></a>
                </div><div class="actions">
									<a class="btn" href="<?php echo $this->baseUrl('service/centro-custo/form')?>" data-tooltip title="Adicionar novo Centro de custo">Novo</a>
								</div>
			</div>
			<div class="portlet-body flip-scroll">
				<div id="sample_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
					<table class="table-bordered table-striped table-condensed flip-content" id="perfisTable">
						<thead class="flip-content">
							<tr>
                    <th class="" >Codigo</th>
                    <th class="" >Descrição</th>
                    <th class="hidden-480" >Centro Custo Pai</th>
                    <th class="" style="width: 160px;!important">Operacional</th>
                    <th class="hidden-480" style="width: 160px;!important">Oculta Registro</th>
                    <th class="hidden-480" >Ação</th>
						</thead>

						<tbody>
							<?php if (count($this->listCentroCusto) > 0):?>
                <?php foreach ($this->listCentroCusto as $centroCusto):?>
                    <tr>
                        <td><?php echo empty($centroCusto['cec_codigo']) ? 'N/D' : $centroCusto['cec_codigo']?></td>
                        <td><?php echo $centroCusto['cec_descricao']?></td>
                        <td><?php echo $centroCusto->getPai() ? $centroCusto->getPai()->cec_descricao : 'N/D' ?></td>
                        <td><?php echo $centroCusto['cec_operacional'] ? 'sim' : 'não';?></td>
                        <td><?php echo $centroCusto['cec_oculta'] ? 'sim' : 'não';?></td>
                        <td>
                            <a href="<?php echo $this->baseUrl('service/centro-custo/form/id/'.$centroCusto['cec_id'])?>">
                                <img src="<?php echo $this->baseUrl('images/edit.png')?>" data-tooltip title="Editar">
                            </a>
                            <a name ="<?php echo $centroCusto['cec_descricao'] ?>"href="#" value="<?php echo $centroCusto['cec_id'];?>" class="deleteMoldal">
                                <img src="<?php echo $this->baseUrl('images/delete.png')?>" data-tooltip title="Remover">
                            </a>
                        </td>
                    </tr>
                <?php endforeach;?>
					<?php endif;?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="dialog_delete" style="display: none;">
	<p>Deseja realmente excluir o centro de custo: <span id ="valueDelete"></span></p>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/service/centro-custo.index.js')?>"></script>
<script type="text/javascript">

 $('#perfisTable').dataTable({
     "aLengthMenu": [
         [30, 50, 100, -1],
         [30, 50, 100, "All"] // change per page values here
     ],
     // set the initial value
     "iDisplayLength": 30,
     "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
     "sPaginationType": "bootstrap",
     "oLanguage": {
         "sProcessing": "Aguarde enquanto os dados são carregados ...",
         "sLengthMenu": "Mostrar _MENU_ registros",
         "sZeroRecords": "Não foram encontrados resultados",
         "sInfoEmpty": "Mostrando de 0 até 0 de 0 registros",
         "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
         "sInfoFiltered": "",
         "sSearch": "Procurar",
         "oPaginate": {
            "sFirst":    "Primeiro",
            "sPrevious": "Anterior",
            "sNext":     "Próximo",
            "sLast":     "Último"
         }
      },
     "aoColumnDefs": [{
             'bSortable': true,
             'aTargets': [0]
         }
     ]
 });
</script>