<table class="table table-hover extrato" style="width: 100%;margin: 0;" >
    <thead>
        <tr>
            <th>Descrição</th>
            <th style="text-align: center;">Valor</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Qtd. solicitado</td>
            <td style="text-align: center;"><?php echo $this->formatInteger($this->totalSolicitado)?></td>
        </tr>
        <tr>
            <td>Qtd. em estoque</td>
            <td style="text-align: center;"><?php echo $this->formatInteger($this->totalEstoque['totalEstoque'])?></td>
        </tr>
        <tr>
            <td>Total de Entrada</td>
            <td style="text-align: center;"><?php echo $this->formatInteger($this->totalEstoque['totalEntrada'])?></td>
        </tr>
        <tr>
            <td>Total de Saida</td>
            <td style="text-align: center;"><?php echo $this->formatInteger($this->totalEstoque['totalSaida'])?></td>
        </tr>
    </tbody>
</table>
