<?php
    /**
     * grid do item aonde visualiza todos os produtos cadastrados no sistemas e ativos
     * com link pra criar, alterar e inativar.
    */
?>
<style>
<!--
.dataTables_filter{
	float: right;
}

.dataTables_paginate{
	margin: 0px;
	float: right;
}

-->
</style>
<link rel="stylesheet" href="/assets/plugins/data-tables/DT_bootstrap.css" />
<div class="row-fluid" style="margin-top: 20px;">
	<div class="span12">
		<div class="portlet box purple">
			<div class="portlet-title">
				<div class="caption"><i class="icon-wrench"></i>Estoque</div>
				<div class="tools">
                    <a href="javascript:;" class="collapse"></a>
                </div>
			</div>
			<div class="portlet-body flip-scroll">
				<div id="sample_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
					<table class="table table-striped table-bordered table-hover" id="datatables">
                        <thead class="flip-content">
                            <tr>
                                <th style="width: 100px">Código</th>
                                <th>Nome</th>
                                <th style="width: 120px">Un. Compra</th>
                                <th style="width: 130px">Un. Consumo</th>
                                <th style="width: 140px">Qtd em Estoque</th>
                                <th style="width: 140px; text-align: center;">Qtd em Estoque Geral</th>
                                <th style="width: 140px">Matéria-Prima</th>
                                <th style="width: 135px; text-align:center" >Terceiros para revenda</th>
                                <th style="width: 96px; text-align:center">Produto finalizado</th>
                                <th style="width: 90px">Ação</th>
                            </tr>
                        </thead>
                            <tbody>
                                <?php foreach ($this->itemList as $item):?>
                                    <tr>
                                        <td><?php echo $item['id_item']?></td>
                                        <td><?php echo $item['nome']?></td>
                                        <td><?php echo $item->getUnidadeCompra()->nome ?></td>
                                        <td><?php echo $item->getUnidadeConsumo()->nome ?></td>
                                        <td><?php echo $item->getSumEstoque() ? $this->cortarDecimal($item->getSumEstoque()): "---" ?></td>
                                        <td><?php echo $item->getSumEstoque(false) ? $this->cortarDecimal($item->getSumEstoque(false)): "---" ?></td>
                                        <td style="text-align:center"><?php echo $item['materia_prima'] ? "Sim": "Não";?></td>
                                        <td style="text-align:center"><?php echo $item['revenda'] ? "Sim": "Não";?></td>
                                        <td style="text-align:center"><?php echo $item['produto_finalizado'] ? "Sim": "Não";?></td>
                                        <td>
                                            <a href="<?php echo $item['id_item']?>" class="detail">
                                                <img src="<?php echo $this->baseUrl('images/detail.png')?>" data-tooltip title="Detalhe">
                                            </a>
                                            <a href="<?php echo $this->baseUrl('/material/estoque/lote/idItem/'.$item['id_item'])?>" >
                                                <img src="<?php echo $this->baseUrl('images/view_detail.png')?>" data-tooltip title="Lotes">
                                            </a>
                                        </td>
                                    </tr>
                                <?php endforeach;?>
                            </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="dialog_detail">
</div>
<script src="<?php echo $this->baseUrl('scripts/material/estoque.grid.js')?>"></script>