<style>
td.acoes{
    text-align: center;
}
</style>
<div class="row-fluid">
    <a href="<?php echo $this->baseUrl('/material/estoque/grid')?>" class="icon-btn span2">
        <i class="icon-circle-arrow-left"></i>
        <div>Voltar</div>
    </a>
</div>
<?php //view
$options = array(
    'paginator'            => $this->paginator,
    'title'                => 'Lote',
    'fields'               => array( 'cod_lote/idItem/'.$this->idItem      => "Cod. Lote",
                                     'descricao/idItem/'.$this->idItem     => 'Descrição'
                                   ),
    'desabilitarBotaoNovo' => true,
    'columns'              => array( 'cod_lote'      => "Cod. Lote",
                                     'descricao'     => 'Descrição',
                                     'id_estoque'    => 'Atributo',
                                     'quantidade'    => 'Quantidade',
                                     'vl_unitario'   => 'Valor Unitario',
                                   ),
    'formatter'            => array( 'vl_unitario' => 'real', 'quantidade' => 'formatDecimal', 'id_estoque' => 'textAtributoByEstoque'),
    'actions'              => array(
		"<a title='Transferir' class='transfer' href='%id_estoque%' id_estoque='%id_estoque%' id_workspace='%id_workspace%' cod-lote='%cod_lote%' quantidade='%quantidade%'>
               <i class='icon-random' style='color:black'></i>
        </a>",
		"<a title='Extrato de lote' class='extrato-lote' href='/material/estoque/extrato-lote/id_estoque/%id_estoque%'>
               <i class=' icon-list-alt' style='color:black'></i>
        </a>"
    )
);
echo $this->partial('grid-metronic.phtml', 'default', $options);
?>
<div id="dialog-transfer" style="display:none">
    <div class="row-fluid">
        <div class="span12">
            <div class="control-group">
                <label class="control-label">De:</label>
                <div class="controls">
                   <select name="workspace" id="workspace" disabled="disabled" class="span12">
                       <?php foreach($this->workspaceCombo as $workspace):?>
                           <option value="<?php echo $workspace['id_workspace']?>" ><?php echo $workspace['nome']?></option>
                       <?php endforeach;?>
                   </select>
                   <?php echo $this->formHidden('id_estoque')?>
                </div>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="control-group">
                <label class="control-label">Para:</label>
                <div class="controls">
                   <select name="id_workspace" id="id_workspace" class="span12">
                       <option value="" >---- Selecione ----</option>
                       <?php foreach($this->workspaceCombo as $workspace):?>
                           <option value="<?php echo $workspace['id_workspace']?>" ><?php echo $workspace['nome']?></option>
                       <?php endforeach;?>
                   </select>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="dialog-extrato">
</div>

<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/material/estoque.lote.js')?>"></script>