<?php
    /**
     * formulario de cadastro de plano de contas
    */
?>
<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Registro
			 <small> de plano de contas</small>
		</h3>
	</div>
</div>
<div class="row-fluid">
	<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption"><i class=" icon-dollar"></i> Formulário</div>
			<div class="tools">
				<a href="javascript:;" class="collapse"></a>
			</div>
		</div>
	<div class="portlet-body form">
		<form id="form" method="post" action="">
			<?php echo $this->formHidden('plc_id', $this->vo->plc_id);?>

            <?php $identity = Zend_Auth::getInstance()->getIdentity(); ?>
            <?php echo $this->vo->plc_id ? $this->formHidden("id_grupo",$this->vo->id_grupo) : $this->formHidden("id_grupo",$identity->time['id']); ?>

                  <div class="row-fluid">
                      <div class="span3">
                          <div class="control-group">
								<div id="empresa_sacado_div">
		                          <label class="control-label"><?php echo $this->translate('Plano Pai')?></label>
		                          <?php echo $this->formSelect('plc_id_pai',$this->vo->plc_id_pai,null,array("" => "Selecione")+$this->planoContasCombo); ?>
		                        </div>
                          </div>
                      </div>
                      <div class="span3">
                          <div class="control-group">
	                          <label class=" control-label"><?php echo $this->translate('Código Contábil:')?></label>
	                          <div class="controls">
									<?php echo $this->formText('plc_cod_contabil', $this->vo->plc_cod_contabil); ?>
                          	  </div>
                          </div>
                      </div>
                      <div class="span3">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Código Reduzido')?></label>
	                          <div class="controls">
                          		<?php echo $this->formText('plc_cod_reduzido', $this->vo->plc_cod_reduzido); ?>
	                          </div>
                          </div>
                      </div>
                      <div class="span3">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Ocultar Exibição')?></label>
	                          <div class="controls">
								<?php echo $this->formCheckbox('plc_oculta', $this->vo->plc_oculta,null, array('checked' => '1', 'unChecked' => '0')); ?>
	                          </div>
                          </div>
                      </div>
                  </div>
                  <div class="row-fluid">
						<div class="span12">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Descrição')?><span style="color: red">*</span></label>
	                          <div class="controls">
								<?php echo $this->formTextarea('plc_descricao',$this->vo->plc_descricao,array( 'rows' => 3, 'style' => "width: 70% !important;"));?>
	                          </div>
                          </div>
                      </div>
                  </div>
                  <div class="row-fluid">
	                  <div class="span3">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Grupo de Contas')?><span style="color: red">*</span></label>
	                          <div class="controls">
		                          <?php foreach ($this->grupoContasCombo as $key => $value):?>
			                         		<?php if ($this->vo->grc_id == $key):?>
		                         				<label class="radio"><?php echo $this->translate($value)?> <input name="grc_id" type="radio" checked="checked" value=<?php echo $key; ?> /></label>
		                         			<?php else:?>
		                         				<label class="radio"><?php echo $this->translate($value)?> <input name="grc_id" type="radio" value=<?php echo $key; ?> /></label>
		                         			<?php endif;
		                         			?>

		                         <?php endforeach;?>
	                          </div>
                          </div>
                      </div>
                      <div class="span3">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Registro Público')?></label>
	                          <div class="controls">

                                    <?php echo $this->formCheckbox('register_public', $this->vo->id_grupo ? null : true ,null, array('checked' => '1', 'unChecked' => '0')); ?>
	                          </div>
                          </div>
                      </div>
                  </div>
                  <div class="form-actions">
                      <button type="submit" class="btn blue"><i class="icon-ok"></i>Salvar</button>
                  </div>
        </form>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl("/scripts/financial/plano-contas.form.js")?>">