<style>
<!--
.dataTables_filter{
	float: right;
}

.dataTables_paginate{
	margin: 0px;
	float: right;
}

-->
</style>
<div class="row-fluid">
     <div class="span12">
	      <h3 class="page-title">
	       Plano
	        <small> de Contas</small>
	      </h3>
     </div>
</div>
<div class="row-fluid">
	<div class="span12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption"><i class="icon-dollar"></i>Registro de Plano de Contas</div>
				<div class="tools">
                    <a href="javascript:;" class="collapse"></a>
                </div>
				<div class="actions">
					<a class="btn " href="<?php echo $this->baseUrl("/financial/plano-contas/form") ?>"><i class="icon-pencil"></i> Novo </a>
				</div>
			</div>
			<div class="portlet-body flip-scroll">
				<div id="sample_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
					<table class="table-bordered table-striped table-condensed flip-content" id="planodeContasTable">
						<thead class="flip-content">
							<tr>
								<th>Código</th>
					            <th>Código Contábil</th>
					            <th>Descricão</th>
					            <th>Plano de Conta Pai</th>
					            <th>Tipo</th>
					            <th>Oculto</th>
					            <th>Transferência</th>
					            <th>Resultado</th>
					            <th>Contábil</th>
					            <th>Workspace</th>
					            <th class="action">Ação</th>
							</tr>
						</thead>

						<tbody>
							<?php if (count($this->planoContasList) > 0):?>
				        <?php foreach ($this->planoContasList as $planoContas):?>
				            <tr class="odd gradeX">
				                <td><?php echo $planoContas->plc_id?></td>
				                <td style="width:200px"><?php echo $planoContas['plc_cod_contabil']?></td>
				                <td><?php echo $planoContas->plc_descricao ?></td>
				                <td><?php echo $planoContas->plc_id_pai ? $planoContas->getPlanoContasPai()->plc_cod_contabil." ".$planoContas->getPlanoContasPai()->plc_descricao : ""?></td>
				                <td><?php echo $planoContas->grc_id ? $planoContas->getGrupoContas()->grc_descricao: ""?></td>
				                <td><?php echo $planoContas->plc_oculta ? "Sim" : "Não"?></td>
				                <td><?php echo $planoContas->plc_transferencia ? "Sim" : "Não";?></td>
				                <td><?php echo $planoContas->plc_resultado ? "Sim" : "Não"?></td>
				                <td><?php echo $planoContas->plc_contabil ? "Sim" : "Não"?></td>
				                <td><?php echo $planoContas->id_grupo != "" ? $planoContas->getGrupo()->nome : "Público" ;?></td>
				                <td class="acoes">
				                    <a href="<?php echo $this->baseUrl("financial/plano-contas/form/plc_id/{$planoContas['plc_id']}")?>">
				                        <img title="Editar Plano de Contas" data-tooltip src="<?php echo $this->baseUrl('images/edit.png')?>" />
				                    </a>
				                </td>
				            </tr>
				        <?php endforeach;?>
					<?php endif;?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">

 $('#planodeContasTable').dataTable({
     "aLengthMenu": [
         [30, 50, 100, -1],
         [30, 50, 100, "All"] // change per page values here
     ],
     // set the initial value
     "iDisplayLength": 30,
     "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
     "sPaginationType": "bootstrap",
     "oLanguage": {
         "sProcessing": "Aguarde enquanto os dados são carregados ...",
         "sLengthMenu": "Mostrar _MENU_ registros",
         "sZeroRecords": "Não foram encontrados resultados",
         "sInfoEmpty": "Mostrando de 0 até 0 de 0 registros",
         "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
         "sInfoFiltered": "",
         "sSearch": "Procurar",
         "oPaginate": {
            "sFirst":    "Primeiro",
            "sPrevious": "Anterior",
            "sNext":     "Próximo",
            "sLast":     "Último"
         }
      },
     "aoColumnDefs": [{
             'bSortable': true,
             'aTargets': [0]
         }
     ]
 });
</script>