<?php
    /**
     * formulario de workspace
    */
?>
<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Registro
			 <small> de device</small>
		</h3>
	</div>
</div>
<div class="row-fluid">
	<div class="portlet box grey">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder"></i> Formulário</div>
			<div class="tools">
				<a href="javascript:;" class="collapse"></a>
			</div>
		</div>
	<div class="portlet-body form">
        <form method="post"  class="form-horizontal" id="form_workspace">
                  <?php echo $this->formHidden('id_device', $this->vo->id_device);?>
                  <div class="row-fluid">
                      <div class="span3">
                          <div class="control-group">
	                          <label class=" control-label"><?php echo $this->translate('Nome')?><span class="required">*</span></label>
	                          <div class="controls">
	                          	<?php echo $this->formText('nome',$this->vo->nome, array('class' => 'span10'));?>
	                          </div>
                          </div>
                      </div>
                      <div class="span3">
                          <div class="control-group">
	                          <label class=" control-label"><?php echo $this->translate('Marca')?></label>
	                          <div class="controls">
	                          	<?php echo $this->formText('marca',$this->vo->marca, array('class' => 'span10'));?>
	                          </div>
                          </div>
                      </div>
                      <div class="span3">
                          <div class="control-group">
	                          <label class=" control-label"><?php echo $this->translate('Modelo')?></label>
	                          <div class="controls">
	                          	<?php echo $this->formText('modelo',$this->vo->modelo, array('class' => 'span10'));?>
	                          </div>
                          </div>
                      </div>
                  </div>
                  <div class="row-fluid">
                  	<div class="span3">
                    	<div class="control-group">
	                    	<label class=" control-label"><?php echo $this->translate('UUID')?><span class="required">*</span></label>
							<div class="controls">
	                        	<?php echo $this->formText('uuid',$this->vo->uuid, array('class' => 'span10'));?>
							</div>
                          </div>
					</div>
					<div class="span3">
                    	<div class="control-group">
	                    	<label class=" control-label"><?php echo $this->translate('MAC')?></label>
							<div class="controls">
	                        	<?php echo $this->formText('mac',$this->vo->mac, array('class' => 'span10'));?>
							</div>
						</div>
					</div>
                  </div>
                  <div class="form-actions">
                      <a href="<?php echo $this->baseUrl('mobile/device/grid')?>" class="btn" >Voltar</a>
                      <button type="submit" class="btn blue"><i class="icon-ok"></i> Salvar</button>
                  </div>
        </form>
        </div>
    </div>
</div>
