<style>
td.diferrent_collumns{
    color: #e02222;
}
</style>
    <div class="row-fluid">
        <div class="span12">
            <table class="table-bordered table-striped table-condensed flip-content" style="width: 100%">
                <thead>
                    <tr>
                        <th>Descrição</th>
                        <th>Quantidade</th>
                        <th>valor Unitário</th>
                        <th style="width: 100px; text-align: center;" >valor do pedido</th>
                        <th>Data de entrega</th>
                        <th>Obs. Entrega</th>
                        <th>Status</th>
                        <th>Data de Alteração</th>
                        <th>Usuário</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if(count($this->historicoList)>0):?>
                              <?php $count = 0?>
                        <?php foreach ($this->historicoList as $key=> $historico):?>
                            <?php $count++?>
                            <?php $newHistorico = ($key == count($this->historicoArray) - 1) ? null: $this->historicoArray[$count]?>
                            <tr>
                                <td <?php echo isset($newHistorico->pro_desc_produto) && $newHistorico->pro_desc_produto != $historico->pro_desc_produto ? "class='diferrent_collumns'": ""; ?> ><?php echo $historico->pro_desc_produto ?></td>
                                <td style="text-align: right;" <?php echo isset($newHistorico->pro_quantidade) && $newHistorico->pro_quantidade != $historico->pro_quantidade ? "class='diferrent_collumns'": ""; ?>><?php echo $historico->pro_quantidade?></td>
                                <td  style="text-align: right;" <?php echo isset($newHistorico->pro_vlr_unt) && $newHistorico->pro_vlr_unt != $historico->pro_vlr_unt ? "class='diferrent_collumns'": ""; ?>><?php echo $this->real($historico->pro_vlr_unt) ?></td>
                                <td style="text-align: right;" <?php echo isset($newHistorico->pro_vlr_pedido) && $newHistorico->pro_vlr_pedido != $historico->pro_vlr_pedido ? "class='diferrent_collumns'": ""; ?>><?php echo $this->real($historico->pro_vlr_pedido) ?></td>
                                <td <?php echo isset($newHistorico->pro_data_entrega) && $newHistorico->pro_data_entrega != $historico->pro_data_entrega ? "class='diferrent_collumns'": ""; ?>><?php echo $this->Date($historico->pro_data_entrega)?></td>
                                <td <?php echo isset($newHistorico->pro_prazo_entrega) && $newHistorico->pro_prazo_entrega != $historico->pro_prazo_entrega ? "class='diferrent_collumns'": ""; ?>><?php echo $historico->pro_prazo_entrega ?></td>
                                <td <?php echo isset($newHistorico->sta_id) && $newHistorico->sta_id != $historico->sta_id ? "class='diferrent_collumns'": ""; ?>><?php echo $historico->getStatus()->sta_descricao ?></td>
                                <td><?php echo $this->DateHour($historico->dt_criacao)?></td>
                                <td><?php echo $historico->getUsuario()->nome?></td>
                            </tr>
                        <?php endforeach;?>
                    <?php else: ?>
                        <tr>
                            <td colspan="10">Não possui Historico a este processo</td>
                        </tr>
                    <?php endif;?>
                </tbody>
            </table>
            <div class="footer">
                <?php if($this->limit && count($this->historicoList) >= 5):?>
                    <div style="float: right;">
                        <a href="#" class="limit_historico">Ver mais</a>
                    </div>
                <?php endif;?>
            </div>
        </div>
    </div>