<style>
<!--
.dataTables_filter{
	float: right;
}

.dataTables_paginate{
	margin: 0px;
	float: right;
}

-->
</style>
<div class="row-fluid">
     <div class="span12">
     </div>
</div>
<div class="row-fluid">
	<div class="span12">
		<div class="portlet box steelblue">
			<div class="portlet-title">
				<div class="caption"><i class="icon-wrench"></i>
				<?php
            if (!empty($this->grupo->id_grupo)):
                echo "<strong>Grupo</strong> - ".$this->grupo->nome."  ";
            elseif (!empty($this->subgrupo->id_subgrupo)):
                echo  "<strong>Grupo</strong> - ".$this->subgrupo->getGrupo()->nome." | ";
                echo  "<strong>Subgrupo</strong> - ".$this->subgrupo->nome."";
            elseif (!empty($this->classe->id_classe)):
                echo  "<strong>Grupo</strong> - ".$this->classe->getSubgrupo()->getGrupo()->nome." | ";
                echo  "<strong>Subgrupo</strong> - ".$this->classe->getSubgrupo()->nome." | ";
                echo  "<strong>Classe</strong> - ".$this->classe->nome."";
            endif;
            ?>
				</div>
				<div class="tools">
                    <a href="javascript:;" class="collapse"></a>
                </div>
                <div class="actions">
									<a class="btn cadastro-link" href="<?php echo $this->params('/service/service/form',
                    array('id_grupo'     => $this->grupo->id_grupo,
                          'id_subgrupo'  => $this->subgrupo->id_subgrupo,
                          'id_classe'    => $this->classe->id_classe
                         )
                    )?>"><i class="icon-pencil"></i> Novo </a>
								</div>
			</div>
			<div class="portlet-body flip-scroll">
				<div id="sample_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
					<table class="table-bordered table-striped table-condensed flip-content" id="perfisTable">
						<thead class="flip-content">
                <tr>
                    <th style="width: 25% !important;"><?php echo $this->translate('Nome')?></th>
                    <th style="width: 53% !important;"><?php echo $this->translate('Descrição')?></th>
                    <th class="hidden-480" style="width: 120px !important;"><?php echo $this->translate('Unidade')?></th>
                    <th class="hidden-480" style="width: 50px !important;"><?php echo $this->translate('Ação')?></th>
                </tr>
            </thead>
            <tbody>
            <?php if (count($this->serviceList) > 0):?>
                <?php foreach ($this->serviceList as $servico):?>
                    <tr>
                        <td><?php echo $servico['nome']?></td>
                        <td><?php echo $servico['descricao']?></td>
                        <td><?php echo $servico['unidade']?></td>
                        <td>
                            <a href="<?php echo $this->params('service/service/form/id_servico/'.$servico['id_servico'],
                                                                array('id_grupo'     => $this->grupo->id_grupo,
                                                                      'id_subgrupo'  => $this->subgrupo->id_subgrupo,
                                                                      'id_classe'    => $this->classe->id_classe
                                                                     )
                                                                )?>">
                                <img src="<?php echo $this->baseUrl('images/edit.png')?>" data-tooltip title="Editar">
                            </a>
                            <a href="<?php echo $this->params('service/service/delete/id/'.$servico['id_servico'],
                                                                array('id_grupo'     => $this->grupo->id_grupo,
                                                                      'id_subgrupo'  => $this->subgrupo->id_subgrupo,
                                                                      'id_classe'    => $this->classe->id_classe
                                                                     )
                                                                )?>" class="delete">
                                <img src="<?php echo $this->baseUrl('images/delete.png')?>" data-tooltip title="Remover">
                            </a>
                        </td>
                    </tr>
                <?php endforeach;?>
							<?php endif;?>
            </tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="dialog_delete" style="display: none;">
	<p>Deseja realmente excluir a unidades: <span id ="valueDelete"></span></p>
</div>
<div class="dialog_cadastro" style="display: none;">
  <form class="form-cadastro" style="margin:0 !important;">
  	<label>Nome</label>
    <?php echo $this->formText('nome',null, array('style'=> 'width: 410px;'));?>
	</form>
						
</div>
<script type="text/javascript">

 $('#perfisTable').dataTable({
     "aLengthMenu": [
         [30, 50, 100, -1],
         [30, 50, 100, "All"] // change per page values here
     ],
     // set the initial value
     "iDisplayLength": 30,
     "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
     "sPaginationType": "bootstrap",
     "oLanguage": {
         "sProcessing": "Aguarde enquanto os dados são carregados ...",
         "sLengthMenu": "Mostrar _MENU_ registros",
         "sZeroRecords": "Não foram encontrados resultados",
         "sInfoEmpty": "Mostrando de 0 até 0 de 0 registros",
         "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
         "sInfoFiltered": "",
         "sSearch": "Procurar",
         "oPaginate": {
            "sFirst":    "Primeiro",
            "sPrevious": "Anterior",
            "sNext":     "Próximo",
            "sLast":     "Último"
         }
      },
     "aoColumnDefs": [{
             'bSortable': true,
             'aTargets': [0]
         }
     ]
 });
</script>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/sis/orcamento.grid.js')?>"></script>
