<div class="pricing-table">
	<h3>Basic</h3>
	<div class="desc">
		Duis mollis, est non commodo luctus, nisi erat 
		porttitor ligula, eget lacinia odio sem nec elit.
	</div>
	<ul>
		<li><i class="icon-angle-right"></i> 10 Email Accounts</li>
	</ul>
	<div class="rate">
		<div class="price">
			<div class="currency ">
				$<br>
				Monthly
			</div>
			<div class="amount ">
				99    
			</div>
		</div>
		<a href="#" class="btn">
		<i class="m-icon-swapright m-icon-white"></i>
		</a>  
	</div>
</div>