<link rel="stylesheet" type="text/css" href="/assets/plugins/select2/select2_metro.css" />
<div class="row-fluid" style="margin: 10px"></div>
<div class="row-fluid">
	<div class="portlet box green">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder"></i>Relatorio de Cliente</div>
			<div class="tools">
				<a href="javascript:;" class="collapse"></a>
			</div>
			<div class="actions"></div>
		</div>
		<div class="portlet-body form">
			<form action="<?php echo $this->baseUrl('comercial/relatorio/relatorio')?>" method="post">
				<div class="row-fluid" style="margin-bottom: 15px">
					<div class="span4">
							<div class="control-group">
								<label class="control-label">Tipo de Pessoa</label>
								<div class="controls">
									<?php echo $this->formSelect('tipoPessoa', null, array('class' => 'm-wrap span12'), array('0' => 'Todos', '2' => 'Pessoa Física', '1' => 'Pessoa Jurídica'))?>
								</div>
							</div>
							<div class="control-group" style="margin: 53px"></div>
							<div class="control-group" style="margin-top: 10px">
								<label class="control-label">Responsável</label>
								<div class="controls">
									<?php echo $this->formHidden('empresas_id_pai') ?>
									<?php echo $this->formText('responsavel', null, array('class' => 'm-wrap span12'))?>
								</div>
							</div>
							<div class="control-group">
								<label class="control-label">Grupo Geografico</label>
								<div class="controls">
									<?php echo $this->formHidden('grupoGeografico','', array('class' => 'm-wrap span12 select2'))?>
								</div>	
							</div>
					</div>
					<div class="span8">
						<div class="row-fluid ">
							<div class="pessoa-fisica" style="display: none">
							
								<div class="control-group">
									<label class="control-label">Colunas:</label>
									<div class="controls">
										<div class="row-fluid">
											<div class="span4">
												<label class="checkbox line">
												<input type="checkbox" name="coluna[]" id="coluna[]" value="empresas_id_pai" /> Responsável
												</label>
												<label class="checkbox line">
												<input type="checkbox" name="coluna[]" id="coluna[]" value="nome_razao" /> Nome
												</label>
												<label class="checkbox line">
												<input type="checkbox" name="coluna[]" id="coluna[]" value="cnpj_cpf" /> CPF
												</label>
											</div>
											<div class="span4">
												<label class="checkbox line">
												<input type="checkbox" name="coluna[]" id="coluna[]" value="tel" /> Telefone
												</label>
												<label class="checkbox line">
												<input type="checkbox" name="coluna[]" id="coluna[]" value="site" /> Site
												</label>
												<label class="checkbox line">
												<input type="checkbox" name="coluna[]" id="coluna[]" value="email_corporativo" /> E-mail
												</label>
											</div>
											<div class="span4">
												<label class="checkbox line">
												<input type="checkbox" name="coluna[]" id="coluna[]" value="end" /> Endereço
												</label>
												<label class="checkbox line">
												<input type="checkbox" name="coluna[]" id="coluna[]" value="transacao" /> Quantidade de Transação
												</label>
											</div>
										</div>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">Agrupar por:</label>
									<div class="controls">
										<label class="radio line">
											<input type="radio" name="agrupar" id="agrupar" value="empresa_id_pai" /> Responsável
										</label>
										<label class="radio line grupo-geografico">
											<input type="radio" name="agrupar" id="agrupar" value="grupoGeo" /> Grupo Geografico
										</label>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">Ordenar por:</label>
									<div class="controls">
										<label class="checkbox line">
											<input type="checkbox" name="ordenar[]" id="ordenar[]" value="emrepsas_id_pai" /> Responsável
										</label>
										<label class="checkbox line">
											<input type="checkbox" name="ordenar[]" id="ordenar[]" value="nome_razao" /> Nome
										</label>
										<label class="checkbox line">
											<input type="checkbox" name="ordenar[]" id="ordenar[]" value="cnpj_cpf" /> CPF
										</label>
									</div>
								</div>
								
							</div>
							<div class="pessoa-juridica" style="display: none">
								<div class="control-group">
									<label class="control-label">Colunas</label>
									<div class="controls">
										<div class="row-fluid">
											<div class="span4">
												<label class="checkbox line">
													<input type="checkbox" name="coluna[]" id="coluna[]" value="empresas_id_pai" /> Responsavel
												</label>
												<label class="checkbox line">
													<input type="checkbox" name="coluna[]" id="coluna[]" value="nome_razao" /> Nome / Razão Social
												</label>
												<label class="checkbox line">
													<input type="checkbox" name="coluna[]" id="coluna[]" value="fantasia" /> Nome Fantasia
												</label>
											</div>
											<div class="span4">
												<label class="checkbox line">
													<input type="checkbox" name="coluna[]" id="coluna[]" value="cnpj_cpf" /> CNPJ
												</label>
												<label class="checkbox line">
													<input type="checkbox" name="coluna[]" id="coluna[]" value="tel" /> Telefone
												</label>
												<label class="checkbox line">
													<input type="checkbox" name="coluna[]" id="coluna[]" value="site" /> Site
												</label>
											</div>
											<div class="span4">
												<label class="checkbox line">
													<input type="checkbox" name="coluna[]" id="coluna[]" value="email_corporativo" /> E-mail
												</label>
												<label class="checkbox line">
													<input type="checkbox" name="coluna[]" id="coluna[]" value="end" /> Endereço
												</label>
												<label class="checkbox line">
													<input type="checkbox" name="coluna[]" id="coluna[]" value="transacao" /> Quantidade de Transação
												</label>
											</div>
										</div>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">Agrupar por:</label>
									<div class="controls">
										<label class="radio line">
											<input type="radio" name="agrupar" id="agrupar" value="empresas_id_pai" /> Responsável
										</label>
										<label class="radio line grupo-geografico">
											<input type="radio" name="agrupar" id="agrupar" value="grupoGeo" /> Grupo Geografico
										</label>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">Ordenar por:</label>
									<div class="controls">
										<label class="checkbox line">
											<input type="checkbox" name="ordenar[]" id="ordenar[]" value="empresas_id_pai" /> Responsável
										</label>
										<label class="checkbox line">
											<input type="checkbox" name="ordenar[]" id="ordenar[]" value="nome_razao" /> Razão Social
										</label>
										<label class="checkbox line">
											<input type="checkbox" name="ordenar[]" id="ordenar[]" value="cnpj_cpf" /> CNPJ
										</label>
									</div>
								</div>
								
							</div>
							<div class="todos">
							
								<div class="control-group">
									<label class="control-label">Colunas</label>
									<div class="controls">
										<div class="row-fluid">
											<div class="span4">
												<label class="checkbox line">
													<input type="checkbox" name="coluna[]" id="coluna[]" value="empresas_id_pai" /> Responsavel
												</label>
												<label class="checkbox line">
													<input type="checkbox" name="coluna[]" id="coluna[]" value="nome_razao" /> Nome / Razão Social
												</label>
												<label class="checkbox line">
													<input type="checkbox" name="coluna[]" id="coluna[]" value="fantasia" /> Nome Fantasia
												</label>
											</div>
											<div class="span4">
												<label class="checkbox line">
													<input type="checkbox" name="coluna[]" id="coluna[]" value="cnpj_cpf" /> CPF / CNPJ
												</label>
												<label class="checkbox line">
													<input type="checkbox" name="coluna[]" id="coluna[]" value="tel" /> Telefone
												</label>
												<label class="checkbox line">
													<input type="checkbox" name="coluna[]" id="coluna[]" value="site" /> Site
												</label>
											</div>
											<div class="span4">
												<label class="checkbox line">
													<input type="checkbox" name="coluna[]" id="coluna[]" value="email_corporativo" /> E-mail
												</label>
												<label class="checkbox line">
													<input type="checkbox" name="coluna[]" id="coluna[]" value="end" /> Endereço
												</label>
												<label class="checkbox line">
													<input type="checkbox" name="coluna[]" id="coluna[]" value="transacao" /> Quantidade de Transação
												</label>
											</div>
										</div>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">Agrupar por:</label>
									<div class="controls">
										<label class="radio line">
											<input type="radio" name="agrupar" id="agrupar" value="tps_id" /> Tipo de Pessoa
										</label>
										<label class="radio line">
											<input type="radio" name="agrupar" id="agrupar" value="empresas_id_pai" /> Responsável
										</label>
										<label class="radio line grupo-geografico">
											<input type="radio" name="agrupar" id="agrupar" value="grupoGeo" /> Grupo Geografico
										</label>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">Ordenar por:</label>
									<div class="controls">
										<label class="checkbox line">
											<input type="checkbox" name="ordenar[]" id="ordenar[]" value="empresas_id_pai" /> Responsável
										</label>
										<label class="checkbox line">
											<input type="checkbox" name="ordenar[]" id="ordenar[]" value="nome_razao" /> Nome / Razão Social
										</label>
										<label class="checkbox line">
											<input type="checkbox" name="ordenar[]" id="ordenar[]" value="cnpj_cpf" /> CPF / CNPJ
										</label>
									</div>
								</div>
								
							</div>
						</div>
					</div>  
				</div>                
				<div class="form-actions">
					<?php echo $this->formSubmit('gerarRelatorio', 'Gerar Relatorio', array('class' => 'btn blue'))?>
				</div>
			</form>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl('scripts/comercial/relatorio.form.js')?>"></script>
<script type="text/javascript" src="/assets/plugins/select2/select2.min.js"></script>
<script type="text/javascript">
<!--
	var preload_data = [
	    		<?php 
	    		$i = 0; 
	    		foreach ($this->comboGrupoGeografico as $key => $value): 
	    			$i++;
	    			$volor = addslashes($value);
	    			echo ($i == 1? ' ' : ',');
					echo "{ id: '{$key}', text: '{$volor}'}\n";
	    		endforeach;?>
    ];
	$(document).ready(function(even) {
		$('#grupoGeografico').select2({
		      multiple: true
		      ,query: function (query){
		          var data = {results: []};
		 
		          $.each(preload_data, function(){
		              if(query.term.length == 0 || this.text.toUpperCase().indexOf(query.term.toUpperCase()) >= 0 ){
		                  data.results.push({id: this.id, text: this.text });
		              }
		          });
		 
		          query.callback(data);
		      }
		  });
		  $('#grupoGeografico').select2();
	});
//-->
</script>