<div class="row-fluid">
	<div class="span12"></div>
</div>
<div class="row-fluid">
	<div class="span12">
		<div class="portlet box green">
			<div class="portlet-title">
				<div class="caption">Relatorio</div>
				<div class="actions">
					<a class="btn " href="<?php echo $this->baseUrl("/comercial/relatorio/") ?>">Voltar </a>
				</div>
			</div>
			<div class="portlet-body">
				<?php foreach ($this->dados as $keyGrupo => $grupo):?>
					<?php if(!empty($grupo['dados'][0])):?>
						<table class="table table-striped table-hover">
							<tbody>
								<?php if (!empty($grupo['titulo'])): ?>
									<tr>
										<th colspan="<?php echo count($grupo['dados'][0])?>"><?php echo $grupo['titulo']?></th>
									</tr>
								<?php endif;?>
								<tr>
									<?php foreach ($grupo['dados'][0] as $key => $value):?>
										<?php if($key != 'id'):?>
											<th><?php echo $key?></th>
										<?php endif;?>
									<?php endforeach;?>
								</tr>
								<?php foreach ($grupo['dados'] as $dados):?>
									<tr>
										<?php foreach ($dados as $valor):?>
											<?php if($valor != $dados['id']):?>
												<td><?php echo $valor?></td>
											<?php endif;?>
										<?php endforeach;?>
									</tr>
								<?php endforeach;?>
							</tbody>
						</table>
					<?php endif;?>
				<?php endforeach;?>
			</div>
		</div>
	</div>
</div>