<div class="content">
    <form method="Post" class="form-vertical forget-form" novalidate="novalidate" style="display:block">
        <h3 class="">Alteração de senha</h3>
        <p>Insira o código recebido pelo celular para prosseguir com a alteração de sua senha.</p>
        <div class="control-group">
            <div class="controls">
                <input class="m-wrap placeholder-no-fix" original-title=""
                       name="ticket" id="ticket" autofocus="" placeholder="Ticket"
                       required="" type="text" />
            </div>
        </div>
        <div class="form-actions">
            <a href="<?php echo $this->baseUrl("auth/index/reset-pass/")?>" class="btn">
            <i class="m-icon-swapleft"></i> Voltar
            </a>
            <button type="submit" class="btn green pull-right">
            Enviar <i class="m-icon-swapright m-icon-white"></i>
            </button>
        </div>
    </form>
</div>
