<div class="content">
    <form method="Post" class="form-vertical forget-form" novalidate="novalidate" style="display:block">
        <h3 class="">Esqueceu sua senha ?</h3>
        <p>Insira seu e-mail ou o número do celular e você recebera a instruções para gerar uma nova senha.</p>
        <div class="control-group">
            <div class="controls">
                <input class="m-wrap placeholder-no-fix" original-title=""
                       name="email" id="email" autofocus="" placeholder="E-mail"
                       required="required" type="text" />
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <input class="m-wrap placeholder-no-fix" original-title=""
                       name="celular" id="celular" autofocus=""
                       placeholder="Número do celular"
                       required="required" type="text" />
            </div>
        </div>
        <div class="form-actions">
            <a href="<?php echo $this->baseUrl("auth/index/login/")?>" class="btn">
            <i class="m-icon-swapleft"></i> Voltar
            </a>
            <button type="submit" class="btn green pull-right">
            Enviar <i class="m-icon-swapright m-icon-white"></i>
            </button>
        </div>
    </form>
</div>
