<?php
    /**
     * formulario de menu
    */
?>
<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Cadastro
			 <small> de Menus</small>
		</h3>
	</div>
</div>
<div class="row-fluid">
	<div class="portlet box grey">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder"></i> Formulário</div>
			<div class="tools">
				<a href="javascript:;" class="collapse"></a>
			</div>
		</div>
	<div class="portlet-body form">
        <form method="post"  class="form-horizontal" id="form_menu">
                  <?php echo $this->formHidden('id_au_menu', $this->vo->id_au_menu);?>
                  <?php echo $this->formHidden('id_au_parent_menu', $this->vo->id_au_parent_menu);?>
                  <div class="row-fluid">
                      <div class="span3">
                          <div class="control-group">
	                          <label class=" control-label"><?php echo $this->translate('Nome')?><span class="required">*</span></label>
	                          <div class="controls">
	                          	<?php echo $this->formText('name_menu',$this->vo->name_menu, array('class' => 'span10'));?>
	                          </div>
                          </div>
                      </div>
                      <div class="span3">
                          <div class="control-group">
	                          <label class=" control-label"><?php echo $this->translate('Título')?><span class="required">*</span></label>
	                          <div class="controls">
	                          	<?php echo $this->formText('title_menu',$this->vo->title_menu, array('class' => 'span10'));?>
	                          </div>
                          </div>
                      </div>
                      <div class="span3">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Ação')?></label>
	                          <div class="controls">
	                          	<?php echo $this->formSelect('id_au_resource',$this->vo->id_au_resource, array('class' => 'span12'),array(""=>"Selecione")+$this->resourceList);?>
	                          </div>
                          </div>
                      </div>
                      <div class="span3">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Ícone do menu (referência da classe)')?></label>
	                          <div class="controls">
	                          	<?php echo $this->formText('icon_menu',$this->vo->icon_menu, array('class' => 'span10'));?>
	                          </div>
                          </div>
                      </div>
                  </div>
                  <div class="row-fluid">
	                  <div class="span12">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Descrição')?></label>
	                          <div class="controls">
	                          	<?php echo $this->formTextarea('description_menu',$this->vo->description_menu, array('class'=> 'span12', 'rows' => 3));?>
	                          </div>
                          </div>
                      </div>
                  </div>
                  <div class="form-actions">
                      <button type="submit" class="btn blue"><i class="icon-ok"></i> Salvar</button>
                      <a href="<?php echo $this->baseUrl('auth/menu/grid')?>" class="btn" >Voltar</a>
                  </div>
        </form>
        </div>
    </div>
</div>
<div class="row-fluid">
	<div class="portlet box grey">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder"></i> Classe de ícones</div>
			<div class="tools">
				<a href="javascript:;" class="expand"></a>
			</div>
		</div>
	<div class="portlet-body hide">
		<div class="tab-content">
			<div class="row-fluid">
				<h3>Ícones Gerais</h3>
			</div>
			<div class="row-fluid">
				<div class="span3">
					<ul class="unstyled">
						<li><i class="icon-compass"></i> icon-compass</li>
						<li><i class="icon-eur"></i> icon-eur</li>
						<li><i class="icon-dollar"></i> icon-dollar <span class="muted">(alias)</span></li>
						<li><i class="icon-yen"></i> icon-yen <span class="muted">(alias)</span></li>
						<li><i class="icon-won"></i> icon-won <span class="muted">(alias)</span></li>
						<li><i class="icon-file-text"></i> icon-file-text</li>
						<li><i class="icon-sort-by-attributes-alt"></i> icon-sort-by-attributes-alt</li>
						<li><i class="icon-thumbs-down"></i> icon-thumbs-down</li>
						<li><i class="icon-xing-sign"></i> icon-xing-sign</li>
						<li><i class="icon-instagram"></i> icon-instagram</li>
						<li><i class="icon-bitbucket-sign"></i> icon-bitbucket-sign</li>
						<li><i class="icon-long-arrow-up"></i> icon-long-arrow-up</li>
						<li><i class="icon-windows"></i> icon-windows</li>
						<li><i class="icon-skype"></i> icon-skype</li>
						<li><i class="icon-male"></i> icon-male</li>
						<li><i class="icon-archive"></i> icon-archive</li>
						<li><i class="icon-renren"></i> icon-renren</li>
					</ul>
				</div>
				<div class="span3">
					<ul class="unstyled">
						<li><i class="icon-collapse"></i> icon-collapse</li>
						<li><i class="icon-euro"></i> icon-euro <span class="muted">(alias)</span></li>
						<li><i class="icon-inr"></i> icon-inr</li>
						<li><i class="icon-cny"></i> icon-cny</li>
						<li><i class="icon-btc"></i> icon-btc</li>
						<li><i class="icon-sort-by-alphabet"></i> icon-sort-by-alphabet</li>
						<li><i class="icon-sort-by-order"></i> icon-sort-by-order</li>
						<li><i class="icon-youtube-sign"></i> icon-youtube-sign</li>
						<li><i class="icon-youtube-play"></i> icon-youtube-play</li>
						<li><i class="icon-flickr"></i> icon-flickr</li>
						<li><i class="icon-tumblr"></i> icon-tumblr</li>
						<li><i class="icon-long-arrow-left"></i> icon-long-arrow-left</li>
						<li><i class="icon-android"></i> icon-android</li>
						<li><i class="icon-foursquare"></i> icon-foursquare</li>
						<li><i class="icon-gittip"></i> icon-gittip</li>
						<li><i class="icon-bug"></i> icon-bug</li>
					</ul>
				</div>
				<div class="span3">
					<ul class="unstyled">
						<li><i class="icon-collapse-top"></i> icon-collapse-top</li>
						<li><i class="icon-gbp"></i> icon-gbp</li>
						<li><i class="icon-rupee"></i> icon-rupee <span class="muted">(alias)</span></li>
						<li><i class="icon-renminbi"></i> icon-renminbi <span class="muted">(alias)</span></li>
						<li><i class="icon-bitcoin"></i> icon-bitcoin <span class="muted">(alias)</span></li>
						<li><i class="icon-sort-by-alphabet-alt"></i> icon-sort-by-alphabet-alt</li>
						<li><i class="icon-sort-by-order-alt"></i> icon-sort-by-order-alt</li>
						<li><i class="icon-youtube"></i> icon-youtube</li>
						<li><i class="icon-dropbox"></i> icon-dropbox</li>
						<li><i class="icon-adn"></i> icon-adn</li>
						<li><i class="icon-tumblr-sign"></i> icon-tumblr-sign</li>
						<li><i class="icon-long-arrow-right"></i> icon-long-arrow-right</li>
						<li><i class="icon-linux"></i> icon-linux</li>
						<li><i class="icon-trello"></i> icon-trello</li>
						<li><i class="icon-sun"></i> icon-sun</li>
						<li><i class="icon-vk"></i> icon-vk</li>
					</ul>
				</div>
				<div class="span3">
					<ul class="unstyled">
						<li><i class="icon-expand"></i> icon-expand</li>
						<li><i class="icon-usd"></i> icon-usd</li>
						<li><i class="icon-jpy"></i> icon-jpy</li>
						<li><i class="icon-krw"></i> icon-krw</li>
						<li><i class="icon-file"></i> icon-file</li>
						<li><i class="icon-sort-by-attributes"></i> icon-sort-by-attributes</li>
						<li><i class="icon-thumbs-up"></i> icon-thumbs-up</li>
						<li><i class="icon-xing"></i> icon-xing</li>
						<li><i class="icon-stackexchange"></i> icon-stackexchange</li>
						<li><i class="icon-bitbucket"></i> icon-bitbucket</li>
						<li><i class="icon-long-arrow-down"></i> icon-long-arrow-down</li>
						<li><i class="icon-apple"></i> icon-apple</li>
						<li><i class="icon-dribble"></i> icon-dribble</li>
						<li><i class="icon-female"></i> icon-female</li>
						<li><i class="icon-moon"></i> icon-moon</li>
						<li><i class="icon-weibo"></i> icon-weibo</li>
					</ul>
				</div>
			</div>
			<div class="row-fluid">
				<h3>Ícones Web</h3>
			</div>
			<div class="row-fluid">
				<div class="span3">
					<ul class="unstyled">
						<li><i class="icon-adjust"></i> icon-adjust</li>
						<li><i class="icon-asterisk"></i> icon-asterisk</li>
						<li><i class="icon-ban-circle"></i> icon-ban-circle</li>
						<li><i class="icon-bar-chart"></i> icon-bar-chart</li>
						<li><i class="icon-barcode"></i> icon-barcode</li>
						<li><i class="icon-beaker"></i> icon-beaker</li>
						<li><i class="icon-bell"></i> icon-bell</li>
						<li><i class="icon-bolt"></i> icon-bolt</li>
						<li><i class="icon-book"></i> icon-book</li>
						<li><i class="icon-bookmark"></i> icon-bookmark</li>
						<li><i class="icon-bookmark-empty"></i> icon-bookmark-empty</li>
						<li><i class="icon-briefcase"></i> icon-briefcase</li>
						<li><i class="icon-bullhorn"></i> icon-bullhorn</li>
						<li><i class="icon-calendar"></i> icon-calendar</li>
						<li><i class="icon-camera"></i> icon-camera</li>
						<li><i class="icon-camera-retro"></i> icon-camera-retro</li>
						<li><i class="icon-certificate"></i> icon-certificate</li>
						<li><i class="icon-check"></i> icon-check</li>
						<li><i class="icon-check-empty"></i> icon-check-empty</li>
						<li><i class="icon-cloud"></i> icon-cloud</li>
						<li><i class="icon-cog"></i> icon-cog</li>
						<li><i class="icon-cogs"></i> icon-cogs</li>
						<li><i class="icon-comment"></i> icon-comment</li>
						<li><i class="icon-comment-alt"></i> icon-comment-alt</li>
						<li><i class="icon-comments"></i> icon-comments</li>
						<li><i class="icon-comments-alt"></i> icon-comments-alt</li>
						<li><i class="icon-credit-card"></i> icon-credit-card</li>
						<li><i class="icon-dashboard"></i> icon-dashboard</li>
						<li><i class="icon-download"></i> icon-download</li>
						<li><i class="icon-download-alt"></i> icon-download-alt</li>
						<li><i class="icon-edit"></i> icon-edit</li>
						<li><i class="icon-envelope"></i> icon-envelope</li>
						<li><i class="icon-envelope-alt"></i> icon-envelope-alt</li>
					</ul>
				</div>
				<div class="span3">
					<ul class="unstyled">
						<li><i class="icon-exclamation-sign"></i> icon-exclamation-sign</li>
						<li><i class="icon-external-link"></i> icon-external-link</li>
						<li><i class="icon-eye-close"></i> icon-eye-close</li>
						<li><i class="icon-eye-open"></i> icon-eye-open</li>
						<li><i class="icon-facetime-video"></i> icon-facetime-video</li>
						<li><i class="icon-film"></i> icon-film</li>
						<li><i class="icon-filter"></i> icon-filter</li>
						<li><i class="icon-fire"></i> icon-fire</li>
						<li><i class="icon-flag"></i> icon-flag</li>
						<li><i class="icon-folder-close"></i> icon-folder-close</li>
						<li><i class="icon-folder-open"></i> icon-folder-open</li>
						<li><i class="icon-gift"></i> icon-gift</li>
						<li><i class="icon-glass"></i> icon-glass</li>
						<li><i class="icon-globe"></i> icon-globe</li>
						<li><i class="icon-group"></i> icon-group</li>
						<li><i class="icon-hdd"></i> icon-hdd</li>
						<li><i class="icon-headphones"></i> icon-headphones</li>
						<li><i class="icon-heart"></i> icon-heart</li>
						<li><i class="icon-heart-empty"></i> icon-heart-empty</li>
						<li><i class="icon-home"></i> icon-home</li>
						<li><i class="icon-inbox"></i> icon-inbox</li>
						<li><i class="icon-info-sign"></i> icon-info-sign</li>
						<li><i class="icon-key"></i> icon-key</li>
						<li><i class="icon-leaf"></i> icon-leaf</li>
						<li><i class="icon-legal"></i> icon-legal</li>
						<li><i class="icon-lemon"></i> icon-lemon</li>
						<li><i class="icon-lock"></i> icon-lock</li>
						<li><i class="icon-unlock"></i> icon-unlock</li>
						<li><i class="icon-magic"></i> icon-magic</li>
						<li><i class="icon-magnet"></i> icon-magnet</li>
						<li><i class="icon-map-marker"></i> icon-map-marker</li>
						<li><i class="icon-minus"></i> icon-minus</li>
						<li><i class="icon-minus-sign"></i> icon-minus-sign</li>
					</ul>
				</div>
				<div class="span3">
					<ul class="unstyled">
						<li><i class="icon-money"></i> icon-money</li>
						<li><i class="icon-move"></i> icon-move</li>
						<li><i class="icon-music"></i> icon-music</li>
						<li><i class="icon-off"></i> icon-off</li>
						<li><i class="icon-ok"></i> icon-ok</li>
						<li><i class="icon-ok-circle"></i> icon-ok-circle</li>
						<li><i class="icon-ok-sign"></i> icon-ok-sign</li>
						<li><i class="icon-pencil"></i> icon-pencil</li>
						<li><i class="icon-picture"></i> icon-picture</li>
						<li><i class="icon-plane"></i> icon-plane</li>
						<li><i class="icon-plus"></i> icon-plus</li>
						<li><i class="icon-plus-sign"></i> icon-plus-sign</li>
						<li><i class="icon-print"></i> icon-print</li>
						<li><i class="icon-pushpin"></i> icon-pushpin</li>
						<li><i class="icon-qrcode"></i> icon-qrcode</li>
						<li><i class="icon-question-sign"></i> icon-question-sign</li>
						<li><i class="icon-random"></i> icon-random</li>
						<li><i class="icon-refresh"></i> icon-refresh</li>
						<li><i class="icon-remove"></i> icon-remove</li>
						<li><i class="icon-remove-circle"></i> icon-remove-circle</li>
						<li><i class="icon-remove-sign"></i> icon-remove-sign</li>
						<li><i class="icon-reorder"></i> icon-reorder</li>
						<li><i class="icon-resize-horizontal"></i> icon-resize-horizontal</li>
						<li><i class="icon-resize-vertical"></i> icon-resize-vertical</li>
						<li><i class="icon-retweet"></i> icon-retweet</li>
						<li><i class="icon-road"></i> icon-road</li>
						<li><i class="icon-rss"></i> icon-rss</li>
						<li><i class="icon-screenshot"></i> icon-screenshot</li>
						<li><i class="icon-search"></i> icon-search</li>
						<li><i class="icon-share"></i> icon-share</li>
						<li><i class="icon-share-alt"></i> icon-share-alt</li>
						<li><i class="icon-shopping-cart"></i> icon-shopping-cart</li>
					</ul>
				</div>
				<div class="span3">
					<ul class="unstyled">
						<li><i class="icon-signal"></i> icon-signal</li>
						<li><i class="icon-signin"></i> icon-signin</li>
						<li><i class="icon-signout"></i> icon-signout</li>
						<li><i class="icon-sitemap"></i> icon-sitemap</li>
						<li><i class="icon-sort"></i> icon-sort</li>
						<li><i class="icon-sort-down"></i> icon-sort-down</li>
						<li><i class="icon-sort-up"></i> icon-sort-up</li>
						<li><i class="icon-star"></i> icon-star</li>
						<li><i class="icon-star-empty"></i> icon-star-empty</li>
						<li><i class="icon-star-half"></i> icon-star-half</li>
						<li><i class="icon-tag"></i> icon-tag</li>
						<li><i class="icon-tags"></i> icon-tags</li>
						<li><i class="icon-tasks"></i> icon-tasks</li>
						<li><i class="icon-thumbs-down"></i> icon-thumbs-down</li>
						<li><i class="icon-thumbs-up"></i> icon-thumbs-up</li>
						<li><i class="icon-time"></i> icon-time</li>
						<li><i class="icon-tint"></i> icon-tint</li>
						<li><i class="icon-trash"></i> icon-trash</li>
						<li><i class="icon-trophy"></i> icon-trophy</li>
						<li><i class="icon-truck"></i> icon-truck</li>
						<li><i class="icon-umbrella"></i> icon-umbrella</li>
						<li><i class="icon-upload"></i> icon-upload</li>
						<li><i class="icon-upload-alt"></i> icon-upload-alt</li>
						<li><i class="icon-user"></i> icon-user</li>
						<li><i class="icon-user-md"></i> icon-user-md</li>
						<li><i class="icon-volume-off"></i> icon-volume-off</li>
						<li><i class="icon-volume-down"></i> icon-volume-down</li>
						<li><i class="icon-volume-up"></i> icon-volume-up</li>
						<li><i class="icon-warning-sign"></i> icon-warning-sign</li>
						<li><i class="icon-wrench"></i> icon-wrench</li>
						<li><i class="icon-zoom-in"></i> icon-zoom-in</li>
						<li><i class="icon-zoom-out"></i> icon-zoom-out</li>
					</ul>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span12">
					<h3>Ícones Financeiros</h3>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span3">
					<ul class="unstyled">
						<li><i class="icon-bitcoin"></i> icon-bitcoin <span class="muted">(alias)</span></li>
						<li><i class="icon-eur"></i> icon-eur</li>
						<li><i class="icon-jpy"></i> icon-jpy</li>
						<li><i class="icon-usd"></i> icon-usd</li>
					</ul>
				</div>
				<div class="span3">
					<ul class="unstyled">
						<li><i class="icon-btc"></i> icon-btc</li>
						<li><i class="icon-euro"></i> icon-euro <span class="muted">(alias)</span></li>
						<li><i class="icon-krw"></i> icon-krw</li>
						<li><i class="icon-won"></i> icon-won <span class="muted">(alias)</span></li>
					</ul>
				</div>
				<div class="span3">
					<ul class="unstyled">
						<li><i class="icon-cny"></i> icon-cny</li>
						<li><i class="icon-gbp"></i> icon-gbp</li>
						<li><i class="icon-renminbi"></i> icon-renminbi <span class="muted">(alias)</span></li>
						<li><i class="icon-yen"></i> <span class="muted">(alias)</span></li>
					</ul>
				</div>
				<div class="span3">
					<ul class="unstyled">
						<li><i class="icon-dollar"></i> icon-dollar</li>
						<li><i class="icon-inr"></i> icon-inr</li>
						<li><i class="icon-rupee"></i> icon-rupee <span class="muted">(alias)</span></li>
					</ul>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span12">
					<h3>Ícones de Texto</h3>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span3">
					<ul class="unstyled">
						<li><i class="icon-file"></i> icon-file</li>
						<li><i class="icon-cut"></i> icon-cut</li>
						<li><i class="icon-copy"></i> icon-copy</li>
						<li><i class="icon-paste"></i> icon-paste</li>
						<li><i class="icon-save"></i> icon-save</li>
						<li><i class="icon-undo"></i> icon-undo</li>
						<li><i class="icon-repeat"></i> icon-repeat</li>
						<li><i class="icon-paper-clip"></i> icon-paper-clip</li>
					</ul>
				</div>
				<div class="span3">
					<ul class="unstyled">
						<li><i class="icon-text-height"></i> icon-text-height</li>
						<li><i class="icon-text-width"></i> icon-text-width</li>
						<li><i class="icon-align-left"></i> icon-align-left</li>
						<li><i class="icon-align-center"></i> icon-align-center</li>
						<li><i class="icon-align-right"></i> icon-align-right</li>
						<li><i class="icon-align-justify"></i> icon-align-justify</li>
						<li><i class="icon-indent-left"></i> icon-indent-left</li>
						<li><i class="icon-indent-right"></i> icon-indent-right</li>
					</ul>
				</div>
				<div class="span3">
					<ul class="unstyled">
						<li><i class="icon-font"></i> icon-font</li>
						<li><i class="icon-bold"></i> icon-bold</li>
						<li><i class="icon-italic"></i> icon-italic</li>
						<li><i class="icon-strikethrough"></i> icon-strikethrough</li>
						<li><i class="icon-underline"></i> icon-underline</li>
						<li><i class="icon-link"></i> icon-link</li>
						<li><i class="icon-columns"></i> icon-columns</li>
						<li><i class="icon-table"></i> icon-table</li>
					</ul>
				</div>
				<div class="span3">
					<ul class="unstyled">
						<li><i class="icon-th-large"></i> icon-th-large</li>
						<li><i class="icon-th"></i> icon-th</li>
						<li><i class="icon-th-list"></i> icon-th-list</li>
						<li><i class="icon-list"></i> icon-list</li>
						<li><i class="icon-list-ol"></i> icon-list-ol</li>
						<li><i class="icon-list-ul"></i> icon-list-ul</li>
						<li><i class="icon-list-alt"></i> icon-list-alt</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
    </div>
</div>

<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/auth/menu.form.js')?>"></script>
