<table class="table-bordered table-striped table-condensed flip-content" style="width: 100%">
    <thead>
        <tr>
            <th style="width: 100px">Codigo do Lote</th>
            <th>Descrição produto</th>
            <th style="width: 120px">Quantidade</th>
            <th style="width: 120px">Unidade</th>
        </tr>
    </thead>
    <tbody>
        <?php if(count($this->movimentoList)):?>
            <?php foreach ($this->movimentoList as $movimento):?>
                <tr>
                    <td><?php echo $movimento['cod_lote'] ?></td>
                    <td><?php echo $movimento['nome_item'] ?></td>
                    <td><?php echo $this->real($movimento['quantidade_mov_estoque'],false) ?></td>
                    <td><?php echo $movimento['nome_unidade']?></td>
                </tr>
            <?php endforeach;?>
        <?php else: ?>
            <tr>
                <td colspan="16">Não possui dados</td>
            </tr>
        <?php endif;?>
    </tbody>
</table>
