<div class="row">
<form method="post" action="<?php echo "$this->baseUrl('service/group/form')"?>">
    <fieldset>
        <legend>Grupo</legend>

        <div class="row">
            <div class="large-12 columns">
                <label><?php echo $this->translate('Nome')?>:</label>
                <input type="text" placeholder="Nome">
            </div>
        </div>
    </fieldset>
</form>
</div>