<head>
	<meta charset="utf-8" />
    <base href="<?php echo $this->serverUrl() . $this->baseUrl();?>/">
	<title>ERP | Sistemas Integrados de Gestão Empresarial</title>
	<meta content="width=device-width, initial-scale=1.0" name="viewport" />
	<meta content="" name="description" />
	<meta content="" name="author" />
	<!-- IMPEDINDO QUE ROBOS INDEXEM O SISTEMA EM SERVICOS DE BUSCA 05/08/2013 ass: CARLOS VINICIUS BONFIM DA SILVA -->
	<meta name="robots" content="noindex">

	<link rel="shortcut icon" href="<?php echo $this->baseUrl("assets/hash/imgs/favicon.png") ?>" type="image/x-icon">
	<link rel="icon" href="<?php echo $this->baseUrl("assets/hash/imgs/favicon.png") ?>" type="image/x-icon">

	<!-- BEGIN GLOBAL MANDATORY STYLES -->
	<!--<link href="<?php echo $this->baseUrl('assets/plugins/bootstrap/css/bootstrap.min.css')?>" rel="stylesheet" type="text/css"/>-->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	<link href="<?php echo $this->baseUrl('assets/plugins/bootstrap/css/bootstrap-responsive.min.css')?>" rel="stylesheet" type="text/css"/>
	<link href="<?php echo $this->baseUrl('assets/plugins/font-awesome/css/font-awesome.min.css')?>" rel="stylesheet" type="text/css"/>
	<link href="<?php echo $this->baseUrl('assets/css/style-metro.css')?>" rel="stylesheet" type="text/css"/>
	<link href="<?php echo $this->baseUrl('assets/css/style.css')?>" rel="stylesheet" type="text/css"/>
	<link href="<?php echo $this->baseUrl('assets/css/style-responsive.css')?>" rel="stylesheet" type="text/css"/>
	<link href="<?php echo $this->baseUrl('assets/css/themes/default.css')?>" rel="stylesheet" type="text/css" id="style_color"/>
	<link href="<?php echo $this->baseUrl('assets/plugins/uniform/css/uniform.default.css')?>" rel="stylesheet" type="text/css"/>
	<?php //icons?>
	<link href="<?php echo $this->baseUrl('assets/plugins/glyphicons/css/glyphicons.css')?>" rel="stylesheet" />
	<link href="<?php echo $this->baseUrl('assets/plugins/glyphicons_halflings/css/halflings.css')?>" rel="stylesheet" />
	<!-- END GLOBAL MANDATORY STYLES -->
	<!-- BEGIN PAGE LEVEL STYLES -->
	<link href="<?php echo $this->baseUrl('assets/plugins/gritter/css/jquery.gritter.css')?>" rel="stylesheet" type="text/css"/>
	<link href="<?php echo $this->baseUrl('assets/plugins/bootstrap-daterangepicker/daterangepicker.css')?>" rel="stylesheet" type="text/css" />
	<link href="<?php echo $this->baseUrl('assets/plugins/fullcalendar/fullcalendar/fullcalendar.css')?>" rel="stylesheet" type="text/css"/>
	<link href="<?php echo $this->baseUrl('assets/plugins/jqvmap/jqvmap/jqvmap.css')?>" rel="stylesheet" type="text/css" media="screen"/>
	<link href="<?php echo $this->baseUrl('assets/plugins/jquery-easy-pie-chart/jquery.easy-pie-chart.css')?>" rel="stylesheet" type="text/css" media="screen"/>
	<link href="<?php echo $this->baseUrl('assets/css/pages/profile.css')?>" rel="stylesheet" type="text/css" />
    <link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/css/select2.min.css" rel="stylesheet" />


	<!-- END PAGE LEVEL STYLES -->

	<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
	<!-- BEGIN CORE PLUGINS -->
	<script src="<?php echo $this->baseUrl('assets/plugins/jquery-1.10.1.min.js')?>" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl('assets/plugins/jquery-migrate-1.2.1.min.js')?>" type="text/javascript"></script>
	<!-- IMPORTANT! Load jquery-ui-1.10.1.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
	<script src="<?php echo $this->baseUrl('assets/plugins/jquery-ui/jquery-ui-1.10.1.custom.min.js')?>" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl('assets/plugins/bootstrap/js/bootstrap.min.js')?>" type="text/javascript"></script>
	<!--[if lt IE 9]>
	<script src="<?php echo $this->baseUrl('assets/plugins/excanvas.min.js')?>"></script>
	<script src="<?php echo $this->baseUrl('assets/plugins/respond.min.js')?>"></script>
	<![endif]-->
	<script src="<?php echo $this->baseUrl('assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js')?>" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl('assets/plugins/jquery.blockui.min.js')?>" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl('assets/plugins/jquery.cookie.min.js')?>" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl('assets/plugins/uniform/jquery.uniform.min.js')?>" type="text/javascript" ></script>
	<!-- END CORE PLUGINS -->
	<!-- BEGIN PAGE LEVEL PLUGINS -->

	<script src="<?php echo $this->baseUrl('assets/plugins/flot/jquery.flot.js')?>" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl('assets/plugins/flot/jquery.flot.resize.js')?>" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl('assets/plugins/jquery.pulsate.min.js')?>" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl('assets/plugins/bootstrap-daterangepicker/date.js')?>" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl('assets/plugins/bootstrap-daterangepicker/daterangepicker.js')?>" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl('assets/plugins/gritter/js/jquery.gritter.js')?>" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl('assets/plugins/fullcalendar/fullcalendar/fullcalendar.min.js')?>" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl('assets/plugins/jquery-easy-pie-chart/jquery.easy-pie-chart.js')?>" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl('assets/plugins/jquery.sparkline.min.js')?>" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl('scripts/lib/jquery.meio.masks.js')?>" type="text/javascript"></script>
	<!-- END PAGE LEVEL PLUGINS -->
	<!-- BEGIN PAGE LEVEL SCRIPTS -->
	<link href="<?php echo $this->baseUrl('assets/plugins/jquery-ui/jquery-ui-1.10.1.custom.min.css')?>" rel="stylesheet" type="text/css"  />
	<script src="<?php echo $this->baseUrl('assets/plugins/bootstrap-modal/js/bootstrap-modal.js')?>" type="text/javascript" ></script>
	<script src="<?php echo $this->baseUrl('assets/plugins/bootstrap-modal/js/bootstrap-modalmanager.js')?>" type="text/javascript" ></script>
	<script src="<?php echo $this->baseUrl('assets/scripts/app.js')?>" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl('assets/scripts/index.js')?>" type="text/javascript"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/jquery-validation/dist/jquery.validate.min.js')?>"></script>

<!--	<script type="text/javascript" src="--><?php //echo $this->baseUrl('assets/plugins/select2/select2.min.js') ?><!--"></script>-->

        <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/js/select2.full.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/js/i18n/pt-BR.js"></script>

 	<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/data-tables/jquery.dataTables.js') ?>"></script>
 	<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/data-tables/DT_bootstrap.js') ?>"></script>
 	<script type="text/javascript" src=<?php echo $this->baseUrl('assets/scripts/app.js')?> ></script>
<!--	<script type="text/javascript" src=--><?php //echo $this->baseUrl('assets/scripts/login-soft.js')?><!-- ></script>-->
	<!-- END PAGE LEVEL SCRIPTS -->
	<!-- FEEDBACK SCRIPT -->
<!--	<script type="text/javascript" src=--><?php //echo $this->baseUrl('scripts/sis/feedback.js')?><!-- ></script>-->
	<script type="text/javascript" src=<?php echo $this->baseUrl('scripts/sis/workspace.js')?> ></script>

	<script>
		jQuery(document).ready(function() {
		   App.init(); // initlayout and core plugins
		});
	</script>
	<!-- END JAVASCRIPTS -->
</head>