	<head>

        <title>ERP | Sistemas Integrados de Gestão Empresarial</title>
        <meta name="author" content="Oisin Lavery - Tricycle Labs">
        <meta http-equiv='Content-Type' content='text/html; charset=utf-8'>
        <!-- Scripts -->
          <!-- Set the viewport width to device width for mobile -->
          <meta name="viewport" content="width=device-width" />

          <!-- Included CSS Files -->
          <link rel="stylesheet" href="<?php echo $this->baseUrl('styles/normalize.css')?>">
          <link rel="stylesheet" href="<?php echo $this->baseUrl('styles/foundation.css')?>">
          <link rel="stylesheet" href="<?php echo $this->baseUrl('styles/jquery.treeview.css')?>">
          <link href="<?php echo $this->baseUrl('styles/theme/jquery-ui-1.10.2.custom.css')?>" rel="stylesheet">
          <link rel="stylesheet" href="<?php echo $this->baseUrl('styles/jquery.dataTables.css')?>">
          <link rel="stylesheet" href="<?php echo $this->baseUrl('styles/jquery.dataTables_themeroller.css')?>">
          <link rel="stylesheet" href="<?php echo $this->baseUrl('styles/chosen.css')?>">
          <link rel="stylesheet" href="<?php echo $this->baseUrl('styles/style.css')?>">

        <!-- Load JQuery -->
        <script src="<?php echo $this->baseUrl('scripts/lib/jquery-1.9.1.min.js')?>" type="text/javascript"></script>

        <!-- Load JQuery UI -->
        <script src="<?php echo $this->baseUrl('scripts/lib/jquery-ui-1.10.2.custom.min.js')?>" type="text/javascript"></script>

        <!-- Global -->
        <script src="<?php echo $this->baseUrl('scripts/lib/jquery-ui-timepicker-addon.js')?>" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl('scripts/lib/jquery.meio.masks.js')?>" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl('scripts/vendor/custom.modernizr.js')?>" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl('scripts/foundation/foundation.js')?>"></script>
        <script src="<?php echo $this->baseUrl('scripts/foundation/foundation.alerts.js')?>"></script>
        <script src="<?php echo $this->baseUrl('scripts/foundation/foundation.clearing.js')?>"></script>
        <script src="<?php echo $this->baseUrl('scripts/foundation/foundation.cookie.js')?>"></script>
        <script src="<?php echo $this->baseUrl('scripts/foundation/foundation.dropdown.js')?>"></script>
        <script src="<?php echo $this->baseUrl('scripts/foundation/foundation.forms.js')?>"></script>
        <script src="<?php echo $this->baseUrl('scripts/foundation/foundation.joyride.js')?>"></script>
        <script src="<?php echo $this->baseUrl('scripts/foundation/foundation.magellan.js')?>"></script>
        <script src="<?php echo $this->baseUrl('scripts/foundation/foundation.orbit.js')?>"></script>
        <script src="<?php echo $this->baseUrl('scripts/foundation/foundation.placeholder.js')?>"></script>
        <script src="<?php echo $this->baseUrl('scripts/foundation/foundation.reveal.js')?>"></script>
        <script src="<?php echo $this->baseUrl('scripts/foundation/foundation.section.js')?>"></script>
        <script src="<?php echo $this->baseUrl('scripts/foundation/foundation.tooltips.js')?>"></script>

        <script src="<?php echo $this->baseUrl('scripts/foundation/foundation.topbar.js')?>"></script>
        <script src="<?php echo $this->baseUrl('scripts/lib/jquery.dataTables.min.js')?>"></script>
        <script src="<?php echo $this->baseUrl('scripts/lib/chosen.jquery.js')?>"></script>
        <!-- treeview -->
        <script src="<?php echo $this->baseUrl('scripts/lib/treeview/jquery.treeview.async.js')?>"></script>
        <script src="<?php echo $this->baseUrl('scripts/lib/treeview/jquery.treeview.js')?>"></script>
        <script src="<?php echo $this->baseUrl('scripts/lib/treeview/jquery.treeview.edit.js')?>"></script>
        <script src="<?php echo $this->baseUrl('scripts/lib/treeview/jquery.treeview.sortable.js')?>"></script>

        <script src="<?php echo $this->baseUrl('scripts/lib/jquery.limit-1.2.source.js')?>" ></script>

          <script src="<?php echo $this->baseUrl('scripts/foundation.min.js')?>"></script>
          <script>
            $(document).foundation();
          </script>
          <script>
            $(document).foundation().foundation('joyride', 'start');
          </script>
          <script src="<?php echo $this->baseUrl('scripts/lib/script.js')?>"></script>
    </head>
