<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" id="myViewport">
    <base href="<?php echo $this->serverUrl() . $this->baseUrl();?>/">
    <title>Hash</title>

    <script src="<?php echo $this->baseUrl('library/jquery/jquery-2.1.4.min.js')?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl('library/bootstrap/js/bootstrap.min.js')?>"></script>
    <link href='https://fonts.googleapis.com/css?family=Arimo:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800,300italic,600italic,700italic,800italic,400italic,300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="<?php echo $this->baseUrl('library/fortawesome/css/font-awesome.min.css')?>">
    <link rel="stylesheet" href="<?php echo $this->baseUrl('library/bootstrap/css/bootstrap.min.css')?>" type="text/css" >

    <link rel="stylesheet" href="<?php echo $this->baseUrl('library/bootstrap/css/bootstrap.min.css')?>" type="text/css" >

    <link rel="stylesheet" href="<?php echo $this->baseUrl('library/icofont/css/icofont.css')?>" type="text/css">
<!--    estilo aqui para componentes de navegação ERP-->
    <link href="<?php echo $this->baseUrl('assets/plugins/jquery-ui/jquery-ui-1.10.1.custom.min.css')?>" rel="stylesheet" type="text/css"  />
    <link href="<?php echo $this->baseUrl('assets/plugins/font-awesome/css/font-awesome.min.css')?>" rel="stylesheet" type="text/css"/>
    <link href="<?php echo $this->baseUrl('assets/css/style.css')?>" rel="stylesheet" type="text/css"/>
    <link href="<?php echo $this->baseUrl('assets/plugins/bootstrap-daterangepicker/daterangepicker.css')?>" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->baseUrl('assets/plugins/bootstrap/css/bootstrap-responsive.min.css')?>" rel="stylesheet" type="text/css"/>
    <link href="<?php echo $this->baseUrl('assets/plugins/uniform/css/uniform.default.css')?>" rel="stylesheet" type="text/css"/>
    <link href="css/jquery.mCustomScrollbar.css" rel="stylesheet" type="text/css"/>

    <link href="<?php echo $this->baseUrl('library/select2/css/select2.min.css')?>" rel="stylesheet" type="text/css"/>
    <link href="//cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.brighttheme.min.css" rel="stylesheet" />
    <link href="//cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.core.min.css" rel="stylesheet" />
    <link href="//cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.buttons.min.css" rel="stylesheet" />

<!-- ESTILO MAIS RECENTE -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl('css/general.css')?>" type="text/css" >
<!--    coisas extras -->

    <script src="<?php echo $this->baseUrl('assets/plugins/jquery-ui/jquery-ui-1.10.1.custom.min.js')?>" type="text/javascript"></script>

    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-maskmoney/3.0.2/jquery.maskMoney.min.js" type="text/javascript"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/3.2.7/jquery.inputmask.bundle.min.js"></script>
    <!--<script src="<?php echo $this->baseUrl('scripts/lib/jquery.maskedinput.min.js')?>" type="text/javascript"></script>-->
    <!--<script src="<?php echo $this->baseUrl('scripts/lib/jquery.meio.masks.js')?>" type="text/javascript"></script>-->

    <script src="//cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/js/select2.full.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/js/i18n/pt-BR.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.core.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.buttons.min.js"></script>

    <!-- @todo Os dois scripts abaixo estão estragando os modais, verificar posteriormente se eles são necessários no ERP -->
    <!--script src="<?php echo $this->baseUrl('assets/plugins/bootstrap-modal/js/bootstrap-modal.js')?>" type="text/javascript" ></script>
    <script src="<?php echo $this->baseUrl('assets/plugins/bootstrap-modal/js/bootstrap-modalmanager.js')?>" type="text/javascript" ></script-->
    <script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/data-tables/jquery.dataTables.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/data-tables/DT_bootstrap.js') ?>"></script>
    <script src="<?php echo $this->baseUrl('assets/plugins/uniform/jquery.uniform.min.js')?>" type="text/javascript" ></script>

    <script src="js/jquery.mCustomScrollbar.concat.min.js"></script>

    <script src="<?php echo $this->baseUrl('assets/scripts/app.js')?>" type="text/javascript"></script>
<!--    <script src="--><?php //echo $this->baseUrl('assets/scripts/index.js')?><!--" type="text/javascript"></script>-->
    <script src="<?php echo $this->baseUrl('js/nav.js')?>" type="text/javascript"></script>
    <script src="js/main.js"></script>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
<!--    aqui vai os gatos-->
<!--    <link rel="stylesheet" href="--><?php //echo $this->baseUrl('css/fix.css')?><!--" type="text/css" >-->

</head>
