
<link rel="stylesheet" type="text/css" src="assets/plugins/bootstrap-datepicker/css/datepicker.css" />
<link src="assets/plugins/select2/select2_metro.css" rel="stylesheet" type="text/css"/>
<!-- BEGIN X-EDITABLE PLUGIN-->
  <link src="assets/plugins/bootstrap-editable/bootstrap-editable/css/bootstrap-editable.css" rel="stylesheet" type="text/css" media="screen"/>
  <link src="assets/plugins/bootstrap-editable/inputs-ext/address/address.css" rel="stylesheet" type="text/css" media="screen"/>
<!-- END X-EDITABLE PLUGIN-->
<style>
<!--
.ui-dialog-titlebar-close {
  display: none;
}
.dataTables_filter{
	float: right;
}

.dataTables_paginate{
	margin: 0px;
	float: right;
}

i.acao{
	padding: 5px;
	color: #000;
	cursor: pointer;
	text-decoration: none;
}
i.acao:HOVER{
	text-decoration: none;
}
.Center-Container {
  position: relative;
}

.Absolute-Center {
  width: 50%;
  height: 50%;
  overflow: auto;
  margin: auto;
  position: absolute;
  top: 0; left: 0; bottom: 0; right: 0;
}
.Absolute-Center.is-Fixed {
  position: fixed;
  z-index: 999;
}
.absolutecentercontent .Absolute-Center.is-Variable {
  display: table;
  height: auto;
}
.editable{
    color:black;
}
a.editable-click {
  border-bottom: none;
}
a.editable-click.editable-disabled,a.editable-click:hover {
  border-bottom: none;
}
-->
</style>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('assets/plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css')?>" />
<div class="row-fluid" style="margin: 10px"></div>
<div class="row-fluid">
    <div class="span12">
        <div class="portlet box blue" id="form_wizard_1">
            <div class="portlet-title">
                <div class="caption">
                    <i class="icon-reorder"></i> Formulário de Transações <span id="tmvType"></span> - <span class="step-title">Passo 1 de 2</span>
                </div>
                <div class="tools hidden-phone">
                    <a href="javascript:;" class="collapse"></a>
                </div>
                <div class="actions">
					<a class="btn blue" href="<?php echo $this->baseUrl("/financial/agrupador-financeiro/form/"); ?>"><i class="icon-pencil"></i> Nova Transação </a>
				</div>
            </div>
            <div class="portlet-body form">
                <form action="" class="form-horizontal" id="form_agrupador" method="POST">
                    <div class="form-wizard">
                        <div class="navbar steps">
                            <div class="navbar-inner">
                                <ul class="row-fluid">
                                    <li class="span3" id-tab="1">
                                        <a href="#tab1" data-toggle="tab" class="step active" >
                                        <span class="number">1</span>
                                        <span class="desc"><i class="icon-ok"></i> Transação</span>
                                        </a>
                                    </li>
                                    <li class="span3" id-tab="2">
                                        <a href="#tab2" data-toggle="tab" class="step">
                                        <span class="number">2</span>
                                        <span class="desc"><i class="icon-ok"></i> Gerencial</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div id="bar" class="progress progress-success progress-striped">
                            <div class="bar"></div>
                        </div>

                        <div class="tab-content">
                            <div class="tab-pane active" id="tab1">
                                <?php echo $this->formHidden('id_agrupador_financeiro', $this->vo->id_agrupador_financeiro);?>
                                <?php echo $this->formHidden('tmv_id', $this->vo->tmv_id);?>
                                <?php echo $this->formHidden('transferencia', $this->vo->transferencia?$this->vo->transferencia: 0 );?>
                                  <div class="row-fluid">
								     <div>
									      <h2>
									      	<?php echo $this->vo->id_agrupador_financeiro ? "Código: ".$this->vo->id_agrupador_financeiro : "" ;?>
									      </h2>
								     </div>
								</div>
								<div class="row-fluid">
									<div class="span6">
										<div class="control-group">
											<label class="control-label" id="labelCliente"></label>
											<div class="controls">
				                 				<?php echo $this->formText("nome_pessoa_cliente",$this->vo->id_pessoa_cliente ? $this->vo->getEmpresaCliente()->nome : "", array("placeholder" => "Digite o nome do cliente", "class" => "span12"));?>
				                 				<?php echo $this->formHidden("id_pessoa_cliente",$this->vo->id_pessoa_cliente);?>

                                                <?php $identity = Zend_Auth::getInstance()->getIdentity(); ?>
                                                <?php echo $this->vo->id_agrupador_financeiro ? $this->formHidden("id_grupo",$this->vo->id_grupo) : $this->formHidden("id_grupo",$identity->time['id']); ?>



											</div>
										</div>
									</div>
									<!--/span-->
									<div class="span6 ">
										<div class="control-group ">
											<label class="control-label" for="">Pedido</label>
											<div class="controls">
												<?php echo $this->formSelect('pro_id',$this->vo->pro_id,array("class" => "span12"),array("" => "Selecione")+$this->comboProcesso);?>
											</div>
										</div>
									</div>
									<!--/span-->
								</div>
								<div class="row-fluid">
									<div class="span6 ">
										<div class="control-group ">
											<label class="control-label" for="">Moeda</label>
											<div class="controls">
												<?php if (!$this->vo->moe_id){
						                          		$this->vo->moe_id = 1;//real
						                          	  }?>
						                          <?php echo $this->formSelect('moe_id',$this->vo->moe_id,array('class' =>'span12'),array("" => "Selecione")+$this->comboMoedas);?>
											</div>
										</div>
									</div>
									<!--/span-->
									<div class="span6 ">
										<div class="control-group ">
											<label class="control-label" for="">Valor<span class="required">*</span></label>
											<div class="controls">
												<?php echo $this->formText('fin_valor', $this->formatDecimal($this->vo->fin_valor), array('alt' => 'decimal','class' =>'decimal span10')); ?>
											</div>
										</div>
									</div>
									<!--/span-->
								</div>
								<div class="row-fluid">
									<div class="span6 ">
										<div class="control-group ">
											<label class="control-label" for="">Nota Fiscal</label>
											<div class="controls">
												<?php echo $this->formText('fin_nota_fiscal',$this->vo->fin_nota_fiscal,array("class" => "span12"));?>
											</div>
										</div>
									</div>
									<!--/span-->
								</div>
								<div class="row-fluid">
									<div class="span6">
										<div class="control-group">
											<label class="control-label" for="">Descrição<span class="required">*</span></label>
											<div class="controls">
												<?php echo $this->formTextarea('fin_descricao',$this->vo->fin_descricao,array( 'rows' => 4, 'cols' => 20, 'style' => 'height: 100px;',"class" => "span12" ));?>
											</div>
										</div>
									</div>
									<div class="span6">
										<div class="control-group">
											<label class="control-label" for="">Observação</label>
											<div class="controls">
												<?php echo $this->formTextarea('fin_observacao',$this->vo->fin_observacao,array( 'rows' => 4, 'cols' => 20, 'style' => 'height: 100px;',"class" => "span12" ));?>
											</div>
										</div>
									</div>
								</div>
								<?php if ($this->vo->id_agrupador_financeiro):?>
								<div class="row-fluid">
									<div class="span12">
										<div class="portlet box blue">
											<div id= "headTransacaoGrid"  class="portlet-title blue">
												<div class="caption"><i class=" icon-dollar"></i>Ticket de Transação</div>
												<div class="tools">
								                    <a href="javascript:;" class="collapse"></a>
								                </div>
												<div class="actions">
													<?php if ($this->vo->tmv_id != 3 /*transferencia*/):?>
													<a id = "abrirPagamento" class="btn " href="<?php echo $this->baseUrl("/auth/usuario/form") ?>"><i class="icon-pencil"></i> Novo Ticket </a>
													<?php endif;?>
												</div>
											</div>
											<div class="portlet-body flip-scroll">
												<div id="table-financial" class="dataTables_wrapper form-inline" role="grid">
												</div>
											</div>
										</div>
									</div>
								</div>
								<?php endif;?>
                            </div>
                            <div class="tab-pane" id="tab2">
                                <h3 class="block">Gerencial</h3>
                                <div class="row-fluid">
									<div class="span6">
										<div class="control-group">
											<label class="control-label" for="">Plano de Contas</label>
											<div class="controls">
												<?php echo $this->formSelect('plc_id',$this->vo->plc_id,array("class" => "span6"),array("" => "Selecione"));?>
						       		          	<?php if ($this->vo->id_agrupador_financeiro):?>
						       		          	  	<span style="display: none;" id ="plano_conta_selected"  value = "<?php echo $this->planoContaSaved['plc_id']?>" name = "<?php echo $this->planoContaSaved['plc_descricao']?>"  ></span>
						       		          	<?php endif;?>
											</div>
										</div>
									</div>
									<div class="span6">
										<div class="control-group">
											<label class="control-label" for="">Centro de Custos</label>
											<div class="controls">
												<?php echo $this->formSelect('cec_id',$this->vo->cec_id,array("class" => "span6"),array("" => "Selecione")+$this->comboCentroCusto);?>
											</div>
										</div>
									</div>
								</div>
								<div class="row-fluid">
									<div class="span6">
										<div class="control-group">
											<label class="control-label" for="">Grupo de Operação</label>
											<div class="controls">
												<?php echo $this->formSelect('ope_id',$this->vo->ope_id,array("class" => "span6"),array("" => "Selecione")+$this->comboGrupoOperacao);?>
											</div>
										</div>
									</div>
									<div class="span6">
										<div class="control-group">
											<label class="control-label" for="">Faturado (contra/por)</label>
											<div class="controls">
												<?php echo $this->formSelect('id_pessoa_faturado',$this->vo->id_pessoa_faturado,array("class" => "span6"),array("" => "Selecione")+$this->comboEmpresasGrupo);?>
											</div>
										</div>
									</div>
								</div>
                            </div>
                        </div>
                        <div class="form-actions clearfix">
                            <a href="javascript:;" class="btn button-previous">
                                <i class="m-icon-swapleft"></i> Voltar
                            </a>
                            <a href="javascript:;" class="btn blue button-next">
                                Continuar <i class="m-icon-swapright m-icon-white"></i>
                            </a>
                            <button class="btn green" type="submit">
                                Salvar
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row-fluid" style="display:<?php echo $this->vo->id_agrupador_financeiro ? 'block': 'none'?>">
    <div class="span12">
        <!--BEGIN TABS-->
        <div class="tabbable tabbable-custom">
            <ul class="nav nav-tabs">
                <li class="active"><a href="#grid-arquivo" data-toggle="tab">Caixa</a></li>
                <li><a href="#grid-historico" data-toggle="tab">Histórico Transação</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="grid-arquivo">
                    <div class="tabbable tabbable-custom">
						<div>
							<div class="tab-pane active" id="tab_1_1">
								<div data-always-visible="1" data-rail-visible="0">
									<ul class="feeds">

								<?php if(count($this->transacoesPagas) > 0 ):?>
										<?php $valorPago = 0; $count = 1 /*necessario iniciar com 1 pois este numero sera a referencia do data-parent dos demais accordions*/;?>
										<?php foreach ($this->transacoesPagas as $transacaoPaga): ?>
											<li>
												<div class="accordion" id="accordion1">
													<div class="accordion-group">
														<div class="accordion-heading">
															<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion<?php echo $count?>" href="#collapse_<?php echo $count?>">
															<i class="icon-thumbs-up"></i>
															<?php echo "Cód: ".$transacaoPaga->fin_id?> - <?php echo "Valor: ".$this->formatDecimal($transacaoPaga->fin_valor)?>
															<span class="label label-info">
																	<b ><?php echo  "PAGO"?></b>
															</span>
															</a>
														</div>
														<div id="collapse_<?php echo $count?>" class="accordion-body collapse">
															<div class="accordion-inner">
																<p>
																	CC transação : <?php echo $transacaoPaga->con_codnome?>
																</p>
																<p>
																	Mês de competência : <?php echo $this->Date($transacaoPaga->fin_competencia)?>
																</p>
																<i style="cursor: pointer;" class="icon-external-link editFinancial" name="<?php echo $transacaoPaga->fin_id ?>"></i>
															</div>
														</div>
													</div>
												</div>
											</li>
										<?php $count++; $valorPago = $valorPago + $transacaoPaga->fin_valor; ?>
										<?php endforeach; ?>
								<?php endif;?>
									</ul>
								</div>
							</div>
						</div>
					</div>
                </div>
                <div class="tab-pane" id="grid-historico">
                </div>
            </div>
        </div>
        <!--END TABS-->
    </div>
</div>

<div id="dialog_delete" style="display: none;">
	<p>Deseja realmente excluir este registro: <span id ="valueDelete"></span></p>
</div>
<div id="historicoTicketModal" class="Center-Block is-Variable" style="display: none">
	<div class="" id="grid-historicoTicketModal"></div>
</div>
<div id="tipo_movimento" style="display: none;">
	<div class="row-fluid">
		<div class="span8">
	    	<div class="control-group">
	         	<label class="control-label"><?php echo $this->translate('Tipo de transação')?></label>
	            <div class="controls">
	            	<div class="tmv-toggle-button">
	                	<input type="checkbox" class="toggle" name="tmv_change" id="tmv_change" value="1" />
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div id ="baseHidden" style=" display: none">
	<div class="row-fluid">
		<div class="span6 ">
			<div class="control-group">
				<label class="control-label"><?php echo $this->translate('Valor')?><span class="required">*</span></label>
				<div class="controls">
					<?php echo $this->formHidden("fin_fin_id")?>
					<?php echo $this->formHidden("finIdForDialog", $this->finIdForDialog)?>
					<?php echo $this->formText('fin_fin_valor', null, array('alt' => 'decimal','class' =>'decimal span6')); ?>
				</div>
			</div>
		</div>
		<div id="boxRecibo" style="display: none;" class="span6 ">
			<div class="control-group">
				<label class="control-label">&nbsp</label>
				<div class="controls">
					<a class="btn blue" id ="emitirRecibo" href="#"><i class="icon-print"></i> Emitir Recibo</a>
				</div>
			</div>
		</div>
		<!--/span-->
	</div>
	<div class="row-fluid">
		<div class="span6 ">
			<div class="control-group">
				<label class="control-label"><?php echo $this->translate('Conta')?></label>
				<div class="controls">
					<?php echo $this->formSelect('fin_con_id',null,null,array("" => "Selecione")+$this->comboContas);?>
				</div>
			</div>
		</div>
		<div class="span6">
			<div class="control-group">
				<label class="control-label" id="labelCliente">Entidade</label>
				<div class="controls">
	            	<?php echo $this->formText("empresa_sacado_credor", null, array("placeholder" => "Digite o nome do cliente", "class" => "span12"));?>
	            	<?php echo $this->formHidden("empresa_sacado_selected");?>
				</div>
			</div>
		</div>
		<!--/span-->
	</div>
	<div class="row-fluid">
		<!--/span-->
		<div class="span6 ">
			<div class="control-group ">
				<label class="control-label"><?php echo $this->translate('Tipo de Documento Interno')?></label>
				<div class="controls">
					<?php echo $this->formSelect('fin_tid_id',null,null,array("" => "Selecione")+$this->comboDocumentoInterno);?>
				</div>
			</div>
		</div>
		<!--/span-->
		<div class="span6 ">
			<div class="control-group">
				<label class="control-label"><?php echo $this->translate('Número de Documento Interno')?></label>
				<div class="controls">
					<?php echo $this->formText('fin_fin_numero_doc', null); ?>
				</div>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<!--/span-->
		<div class="span6 ">
			<div class="control-group ">
				<label class="control-label"><?php echo $this->translate('Tipo de Documento Externo')?></label>
				<div class="controls">
					<?php echo $this->formSelect('fin_tie_id',null,null,array("" => "Selecione")+$this->comboDocumentoExterno);?>
				</div>
			</div>
		</div>
		<!--/span-->
		<div class="span6 ">
			<div class="control-group">
				<label class="control-label"><?php echo $this->translate('Número de Documento Externo')?></label>
				<div class="controls">
					<?php echo $this->formText('fin_fin_num_doc_os', null); ?>
				</div>
			</div>
		</div>
		<!--/span-->
	</div>
	<div class="row-fluid">
		<div class="span6 ">
			<div class="control-group ">
				<label class="control-label"><?php echo $this->translate('Competência')?></label>
				<div class="controls">
					<?php echo $this->formText('fin_fin_competencia',null, array("class" => "datepickerMonth"));?>
				</div>
			</div>
		</div>
		<!--/span-->
		<div class="span6 ">
			<div class="control-group">
				<label class="control-label"><?php echo $this->translate('Emissão')?></label>
				<div class="controls">
					<?php echo $this->formText('fin_fin_emissao',null, array("class" => "datepicker"));?>
				</div>
			</div>
		</div>
		<!--/span-->
	</div>
	<div class="row-fluid">
		<div class="span6 ">
			<div class="control-group ">
				<label class="control-label"><?php echo $this->translate('Vencimento')?></label>
				<div class="controls">
					<?php echo $this->formText('fin_fin_vencimento',null, array("class" => "datepicker"));?>
				</div>
			</div>
		</div>
		<!--/span-->
		<div id = "fin_compensacaoDiv" style="display: none;" class="span6 ">
			<div class="control-group">
				<label class="control-label"><?php echo $this->translate('Compensação')?></label>
				<div class="controls">
					<?php echo $this->formText('fin_fin_compensacao',null, array("class" => "datepicker"));?>
				</div>
			</div>
		</div>
		<!--/span-->
	</div>
	<div class="row-fluid">
		<div class="span6">
			<div class="control-group">
				<label class="control-label" for="">Plano de Contas</label>
				<div class="controls">
					<?php echo $this->formSelect('fin_plc_id',null,array("class" => "span6"),array("" => "Selecione"));?>
				</div>
			</div>
		</div>
		<div class="span6">
			<div class="control-group">
				<label class="control-label" for="">Centro de Custos</label>
				<div class="controls">
					<?php echo $this->formSelect('fin_cec_id',null,array("class" => "span6"),array("" => "Selecione")+$this->comboCentroCusto);?>
				</div>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span6">
			<div class="control-group">
				<label class="control-label" for="">Grupo de Operação</label>
				<div class="controls">
					<?php echo $this->formSelect('fin_ope_id',null,array("class" => "span6"),array("" => "Selecione")+$this->comboGrupoOperacao);?>
				</div>
			</div>
		</div>
		<div class="span6">
			<div class="control-group">
				<label class="control-label" for="">Faturado (contra/por)</label>
				<div class="controls">
					<?php echo $this->formSelect('fin_grupo_id',null,array("class" => "span6"),array("" => "Selecione")+$this->comboEmpresasGrupo);?>
				</div>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span6 ">
			<div class="control-group">
				<label class="control-label"><?php echo $this->translate('Descrição')?><span class="required">*</span></label>
				<div class="controls">
					<?php echo $this->formTextarea('fin_fin_descricao',null,array( 'rows' => 4, 'cols' => 20, 'style' => 'height: 100px;',"class" => "span12" ));?>
				</div>
			</div>
		</div>
		<!--/span-->
		<div class="span6 ">
			<div class="control-group">
				<label class="control-label"><?php echo $this->translate('Observação')?></label>
				<div class="controls">
					<?php echo $this->formTextarea('fin_fin_observacao',null,array( 'rows' => 4, 'cols' => 20, 'style' => 'height: 100px;',"class" => "span12" ));?>
				</div>
			</div>
		</div>
		<!--/span-->
	</div>
</div>
<div id="dialogDuplicar" style="display: none;">
	<form class="form-tk">
		<div class="row-fluid">
			<div class="span6 ">
				<div class="control-group mes">
					<label class="control-label" for="">Vencimento</label>
					<div class="controls" id="msgValidate">
						<?php echo $this->formText('vencimento',null, array("class" => "datepicker span12"));?>
						<?php echo $this->formHidden("fin_id")?>
					</div>
				</div>
			</div>
			<div class="span6 ">
				<div class="control-group ">
					<label class="control-label" for="">Competencia</label>
					<div class="controls">
						<?php echo $this->formText('competencia',null, array("class" => "datepicker span12"));?>
					</div>
				</div>
			</div>
		</div>
	</form>
</div>


    <script type="text/javascript" src="assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script type="text/javascript" src="assets/plugins/bootstrap-datepicker/js/locales/bootstrap-datepicker.pt-BR.js"></script>
    <script src="assets/plugins/select2/select2.min.js" type="text/javascript"></script>

<!-- BEGIN X-EDITABLE PLUGIN-->
  <script src="assets/plugins/bootstrap-editable/bootstrap-editable/js/bootstrap-editable.js" type="text/javascript"></script>
  <script src="assets/plugins/bootstrap-editable/inputs-ext/address/address.js" type="text/javascript"></script>
  <script src="assets/plugins/bootstrap-editable/inputs-ext/wysihtml5/wysihtml5.js" type="text/javascript"></script>
<!-- END X-EDITABLE PLUGIN-->

<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('assets/plugins/jquery-multi-select/css/multi-select-metro.css')?>" />
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/jquery-validation/dist/jquery.validate.min.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/jquery-validation/dist/additional-methods.min.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/bootstrap-wizard/jquery.bootstrap.wizard.min.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/jquery-multi-select/js/jquery.multi-select.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("/scripts/financial/agrupador-financeiro.form.js")?>"></script>
