<?php
$request = Zend_Controller_Front::getInstance()->getRequest();
$caminhoForm        = $this->baseUrl("/financial/agrupador-financeiro/form/");
$select = array(
    50 => 50,
    100 => 100,
    200 => 200,
    250 => 250
    );
$request = Zend_Controller_Front::getInstance()->getRequest();
$defaultItens = $request->getParam('itens', 50);
    /**
     * grid do financeiro
     */
?>
<link href="assets/plugins/select2/select2_metro.css" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" type="text/css" href="assets/plugins/bootstrap-datepicker/css/datepicker.css" />
<!-- BEGIN X-EDITABLE PLUGIN-->
  <link href="assets/plugins/bootstrap-editable/bootstrap-editable/css/bootstrap-editable.css" rel="stylesheet" type="text/css" media="screen"/>
  <link href="assets/plugins/bootstrap-editable/inputs-ext/address/address.css" rel="stylesheet" type="text/css" media="screen"/>
<!-- END X-EDITABLE PLUGIN-->
<style>
<!--
th.fin_descricao{
    width: 400px;
}
td.fin_valor{
	text-align: right !important;
}
.acoes{
	max-width: 30px;
	min-width: 15px;
}
.editable{
    color:black;
}
a.editable-click {
  border-bottom: none;
}
a.editable-click.editable-disabled,a.editable-click:hover {
  border-bottom: none;
}
-->
</style>
<div class="row-fluid">
     <div class="span12">
	      <h3 class="page-title">
	       Transações
	        <small> Financeiras</small>
	      </h3>
     </div>
</div>
<div class="row-fluid" style=" ">
	<a href="<?php echo $this->baseUrl("/financial/agrupador-financeiro/form/")?>" class="icon-btn span2 ">
		<i class="icon-usd"></i>
		<div>Nova Transação Financeira</div>
	</a>
	<a href="#" class="icon-btn span2 transContas">
		<i class="icon-credit-card"></i>
		<div>Fazer Transferência Entre Contas</div>
	</a>
	<a href="<?php echo $this->baseUrl("/financial/financial/index/")?>" class="icon-btn span2 ">
		<i class="icon-search"></i>
		<div>Pesquisar Tickets Financeiros</div>
	</a>
	<a href="<?php echo $this->baseUrl("financial/contas/extrato-form")?>" class="icon-btn span2 ">
		<i class="icon-list-alt"></i>
		<div>Extrato de Contas</div>
	</a>
</div>
<div class="row-fluid">
    <div class="span12">
        <div class="portlet box blue">
            <div class="portlet-title">
            	<div class="caption"><i class="icon-group"></i>Registro de Transações</div>
			</div>
			<div class="portlet-body">
            	<div class="clearfix">
					<div class="btn-group">
						<div class="dataTables_length">
							<?php if ($this->paginator->getTotalItemCount() > $defaultItens): ?>
				                    <label>Mostrar <?php {echo $this->formSelect('itens', $defaultItens, array(), $select);}?></label>
				            <?php endif;?>
						</div>
					</div>
					<div class="btn-group pull-right">
						<div class="dataTables_filter">
							<?php
								$this->columns = (array) $this->columns;
				           	?>
							<?php if (!$this->desabilitarPesquisa): ?>
									<?php echo $this->partial('pesquisa.phtml', 'default', array(
											'fields'       => $this->fields,
											'actionSearch' => $this->actionSearch
				                        ))?>
							<?php endif; ?>
						</div>
					</div>
				</div>
				<div class="dataTables_wrapper form-inline" role="grid">
					<table class="table table-striped table-hover table-bordered dataTable" aria-describedby="sample_editable_1_info" id="sample_1">
			            <thead>
			                <tr>
			                    <th></th>
			                    <?php foreach ($this->columns as $col => $alias): ?>
			                    <th column="<?php echo $col?>"
			                        class=" <?php echo $col?>"
			                    >
			                        <div><?php echo $alias?></div>
			                    </th>
			                    <?php endforeach;?>
		                        <th colspan="4" class = "align-center action"><?php echo $this->translate("Ações")?></th>
			                </tr>
			            </thead>
			            <tbody>
			                <?php if (count($this->paginator)): ?>
			                    <?php foreach ($this->paginator as $key => $pageOBJ): ?>
			                        <tr class="<?php echo $key % 2 ? 'erow' : '' ?>">
			                            <?php $page = is_object($pageOBJ) && method_exists($pageOBJ, 'toArray')
			                                        ? $pageOBJ->toArray()
			                                        : $pageOBJ;
			                            ?>
			                            <td><span class="row-details row-details-close" data-id_agrupador_financeiro="<?php echo $pageOBJ['id_agrupador_financeiro']?>"></span></td>
			                            <?php foreach ((array) $this->columns as $col => $alias): ?>
			                                <?php if (array_key_exists($col, $page)): ?>
			                                    <?php $prop_nome = ($col == 'prop_nome' ? explode(' ', $page[$col]): array());?>
			                                    <td style="white-space: normal !important; text-align: justify; padding-right: 5px;" class="<?php echo $col?>" >
			                                        <a href="javascript:;" class="editable <?php echo $col?>" data-name='<?php echo $col?>' data-type="text" data-pk="<?php echo $pageOBJ['id_agrupador_financeiro']?>" data-pk-correlato="<?php echo $pageOBJ['id_agrupador_financeiro_correlato']?>"  data-url="/financial/agrupador-financeiro/form">
			                                        <?php
			                                            if('prop_nome' === $col):
			                                                echo $prop_nome[0];
			                                            else:
			                                                if( isset( $this->formatter ) && isset( $this->formatter[ $col ] ) ):
			                                                    $method = ($this->formatter[ $col ]);
			                                                    echo $this->$method( $page[$col], $page );
			                                                else:
			                                                    echo $page[$col];
			                                                endif;
			                                            endif;
			                                        ?>
			                                        </a>
			                                    </td>
			                                <?php endif;?>
			                            <?php endforeach;?>
											<td class="acoes">
				                                <a title='Duplicar' class='duplicar' data-tooltip href='#' id='<?php echo $pageOBJ['id_agrupador_financeiro'];?>' >
				                                    <img src='<?php echo $this->baseUrl("/images/sync-icon.png") ?>'  />
				                                </a>
				                            </td>
											<td class="acoes">
				                                <a title='Editar' data-tooltip href=' <?php echo $this->baseUrl("/financial/agrupador-financeiro/form/id_agrupador_financeiro/".$pageOBJ['id_agrupador_financeiro']) ?>'    >
				                                    <img src='<?php echo $this->baseUrl("/images/edit.png") ?>'  />
				                                </a>
				                            </td>
				                            <td class="acoes">
				                                <a class='delete' data-tooltip title='Excluir' href='<?php echo $this->baseUrl("/financial/agrupador-financeiro/delete/id_agrupador_financeiro/".$pageOBJ['id_agrupador_financeiro']) ?>'>
				                                    <img src='<?php echo $this->baseUrl("/images/delete.png")?>' />
				                                </a>
				                            </td>
			                        </tr>
			                    <?php endforeach;?>
			                <?php else: ?>
			                    <tr>
			                        <td colspan="<?php echo count($this->columns) + 1/*acoes*/?>"><?php echo $this->translate("Não existem registros")?>!</td>
			                    </tr>
			                <?php endif; ?>
			            </tbody>
			        </table>
				</div>
				<?php if ($this->paginator instanceof Zend_Paginator): ?>
	            		<?php echo $this->paginationControl($this->paginator, 'Elastic', array('pagination-grid-metronic.phtml', 'default'))?>
        		<?php endif;?>
			</div>
		</div>
	</div>
</div>


<div id="dialog_duplicar" style="display: none;">
	<p>Deseja realmente duplicar este registro: <span id ="valueDelete"></span></p>
</div>

	<div id ="baseHidden" style=" display: none">
	<form id="transferenciaConta" method="post" action="<?php echo $this->baseUrl("/financial/agrupador-financeiro/save-transfer")?>">
		<?php $workspaceSession = new Zend_Session_Namespace('workspace');?>
		<?php echo $this->formHidden('id_workspace', $workspaceSession->id_workspace); ?>
		<div class="row-fluid">
			<div class="span3">
				<div class="control-group">
					<label class="control-label"><?php echo $this->translate('Valor')?><span class="required">*</span></label>
					<div class="controls">
						<?php echo $this->formText('fin_valor', null, array('alt' => 'decimal','class' =>'decimal ')); ?>
					</div>
				</div>
			</div>
			<!--/span-->
			<div class="span3">
				<div class="control-group ">
					<label class="control-label" for="">Moeda<span class="required">*</span></label>
					<div class="controls">
						<?php echo $this->formSelect('moe_id',1/*real*/,null,array("" => "Selecione")+$this->comboMoedas);?>
					</div>
				</div>
			</div>
			<div class="span3">
				<div class="control-group ">
					<label class="control-label" for="">Data da Transferência<span class="required">*</span></label>
					<div class="controls">
						<?php echo $this->formText('dateTransacao',null, array("class" => "datepicker"));?>
					</div>
				</div>
			</div>
			<!--/span-->
		</div>
		<div id="boxTemp" style="display: none;" ></div>
		<div id="box1" class="row-fluid">
			<div class="span3 ">
				<div class="control-group">
					<label class="control-label"><?php echo $this->translate('Conta')?><span class="required">*</span></label>
					<div class="controls">
						<?php echo $this->formSelect('de_con_id',null,null,array("" => "Selecione")+$this->comboContas);?>
					</div>
				</div>
			</div>
			<div class="span3">
				<div class="control-group">
					<label class="control-label"><?php echo $this->translate('&nbsp')?></label>
					<div class="controls">
						<div class="input-prepend input-append">
							<span class="add-on"><b>-</b></span><input style="color: red;" id="de_valor" alt="decimal" disabled="disabled" class="span12 decimal m-wrap " type="text">
						</div>
					</div>
				</div>
			</div>
			<!--/span-->
			<div class="span4">
				<div class="control-group">
					<label class="control-label" id="">Quem paga<span class="required">*</span></label>
					<div class="controls">
		            	<?php echo $this->formText("de_empresa_sacado", null, array("placeholder" => "Digite o nome do cliente", "class" => "autoCompleteEmpresa span12"));?>
		            	<?php echo $this->formHidden("de_empresa_sacado_selected");?>
					</div>
				</div>
			</div>
			<!--/span-->
		</div>
		<div class="row-fluid">
			<div style="margin-left: 46%" class="span5 ">
				<img id="buttonShake" style="cursor:pointer; width: 50px;" alt="" src="<?php echo $this->baseUrl("/images/retweet.png")?>">
			</div>
		</div>
		<div id="box2" class="row-fluid">
			<div class="span3 ">
				<div class="control-group">
					<label class="control-label"><?php echo $this->translate('Conta')?><span class="required">*</span></label>
					<div class="controls">
						<?php echo $this->formSelect('para_con_id',null,null,array("" => "Selecione")+$this->comboContas);?>
					</div>
				</div>
			</div>
			<div class="span3">
				<div class="control-group">
					<label class="control-label"><?php echo $this->translate('&nbsp')?></label>
					<div class="controls">
						<div class="input-prepend input-append">
							<span class="add-on"><b>+</b></span><input style="color: blue;" id="ate_valor" alt="decimal" disabled="disabled" class="span12 decimal m-wrap " type="text">
						</div>
					</div>
				</div>
			</div>
			<!--/span-->
			<div class="span4">
				<div class="control-group">
					<label class="control-label" id="">Favorecido<span class="required">*</span></label>
					<div class="controls">
		            	<?php echo $this->formText("para_empresa_sacado", null, array("placeholder" => "Digite o nome do cliente", "class" => "autoCompleteEmpresa span12"));?>
		            	<?php echo $this->formHidden("para_empresa_sacado_selected");?>
					</div>
				</div>
			</div>
			<!--/span-->
		</div>
	</form>
	</div>
    <script src="assets/plugins/select2/select2.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script type="text/javascript" src="assets/plugins/bootstrap-datepicker/js/locales/bootstrap-datepicker.pt-BR.js"></script>

<!-- BEGIN X-EDITABLE PLUGIN-->
  <script src="assets/plugins/bootstrap-editable/bootstrap-editable/js/bootstrap-editable.js" type="text/javascript"></script>
  <script src="assets/plugins/bootstrap-editable/inputs-ext/address/address.js" type="text/javascript"></script>
  <script src="assets/plugins/bootstrap-editable/inputs-ext/wysihtml5/wysihtml5.js" type="text/javascript"></script>
<!-- END X-EDITABLE PLUGIN-->
  <script src="<?php echo $this->baseUrl("/scripts/financial/agrupador-financeiro.grid.editable.js")?>" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("/scripts/financial/agrupador-financeiro.grid.js")?>"></script>