<style>
<!--
.dataTables_filter{
	float: right;
}

.dataTables_paginate{
	margin: 0px;
	float: right;
}

-->
</style>
<div class="row-fluid">
     <div class="span12">
	      <h3 class="page-title">
	       Registro
	        <small> de atributos</small>
	      </h3>
     </div>
</div>
<div class="row-fluid">
	<div class="span12">
		<div class="portlet box purple">
			<div class="portlet-title">
				<div class="caption"><i class="icon-wrench"></i>Atributos</div>
				<div class="tools">
                    <a href="javascript:;" class="collapse"></a>
                </div>
				<div class="actions">
					<a class="btn blue" href="<?php echo $this->baseUrl("material/atributo/form") ?>"><i class="icon-pencil"></i> Novo </a>
				</div>
			</div>
			<div class="portlet-body flip-scroll">
				<div id="sample_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
					<table class="table-bordered table-striped table-condensed flip-content" id="atributoTable">
						<thead class="flip-content">
							<tr>
								<th>Código</th>
					            <th>Nome</th>
					            <th>Opções</th>
					            <th style="width: 45px;" class="action">Ação</th>
							</tr>
						</thead>

						<tbody>
							<?php if (count($this->atributoList) > 0):?>
				        <?php foreach ($this->atributoList as $atributo):?>
				            <tr class="odd gradeX">
				                <td style="width:30px"><?php echo $atributo->id_atributo?></td>
				                <td><?php echo $atributo->nome;?></td>
				                <td>
				                <?php foreach ($atributo->getListOpcao() as $key => $opcao): ?>
				                    <?php echo $key > 0 ? ', ': ''?>
				                    <?php echo $opcao->nome?>
				                <?php endforeach;?>
				                </td>
				                <td class="acoes">
				                    <a href="<?php echo $this->baseUrl("material/atributo/form/id_atributo/{$atributo->id_atributo}")?>">
				                        <img title="Editar" data-tooltip src="<?php echo $this->baseUrl('images/edit.png')?>"/>
				                    </a>
				                    <a class="deleteMoldal" href="<?php echo $this->baseUrl('material/atributo/delete/id_atributo/'.$atributo->id_atributo)?>" name="<?php echo $atributo->nome?>">
				                        <img title="Excluir" data-tooltip src="<?php echo $this->baseUrl('images/delete.png')?>"/>
				                    </a>
				                </td>
				            </tr>
				        <?php endforeach;?>
					<?php endif;?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="dialog_delete" style="display: none;">
	<p>Deseja realmente excluir o atributo: <span id ="valueDelete"></span></p>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/material/atributo.grid.js')?>"></script>