<?php
    /**
     * formulario das acoes do authorization
    */
?>
<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Cadastro
			 <small> de ações</small>
		</h3>
	</div>
</div>
<div class="row-fluid">
	<div class="portlet box grey">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder"></i> Formulário</div>
			<div class="tools">
				<a href="javascript:;" class="collapse"></a>
			</div>
		</div>
	<div class="portlet-body form">
        <form method="post"  class="form-horizontal" id="form_resource">
                  <?php echo $this->formHidden('id_au_resource', $this->vo->id_au_resource);?>
                  <div class="row-fluid">
                      <div class="span3">
                          <div class="control-group">
	                          <label class="label_cnpj control-label"><?php echo $this->translate('Nome')?><span class="required">*</span></label>
	                          <div class="controls">
	                          	<?php echo $this->formText('name_resource',$this->vo->name_resource, array('class' => 'span10'));?>
	                          </div>
                          </div>
                      </div>
                      <div class="span3 div_uasg">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Módulo')?><span class="required">*</span></label>
	                          <div class="controls">
	                          	<?php echo $this->formSelect('module_resource',$this->vo->module_resource, array('class' => 'span12'),array(""=>"Selecione")+$this->modules);?>
	                          </div>
                          </div>
                      </div>
                      <div class="span3 estadual">
                          <div class="control-group">
	                          <label class="label_estadual control-label"><?php echo $this->translate('Controladora')?><span class="required">*</span></label>
	                          <div class="controls">
	                          	<?php echo $this->formText('controller_resource',$this->vo->controller_resource, array('class' => 'span8'));?>
                          	  </div>
                          </div>
                      </div>
                      <div class="span3 municipal">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Ação')?><span class="required">*</span></label>
	                          <div class="controls">
	                          	<?php echo $this->formText('action_resource',$this->vo->action_resource, array('class' => 'span12'));?>
	                          </div>
                          </div>
                      </div>
                  </div>
                  <div class="row-fluid">
	                  <div class="span12">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Descrição')?></label>
	                          <div class="controls">
	                          	<?php echo $this->formTextarea('description_resource',$this->vo->description_resource, array('class'=> 'span12', 'rows' => 3));?>
	                          </div>
                          </div>
                      </div>
                  </div>
                  <div class="form-actions">
                      <button type="submit" class="btn blue"><i class="icon-ok"></i> Salvar</button>
                      <a href="<?php echo $this->baseUrl('resource/resource/grid')?>" class="btn" >Voltar</a>
                  </div>
        </form>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/resource/resource.form.js')?>"></script>
