<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
	<meta charset="utf-8" />
	<meta content="width=device-width, initial-scale=1.0" name="viewport" />
	<meta content="" name="description" />
	<meta content="" name="author" />
	<!-- BEGIN GLOBAL MANDATORY STYLES -->
	<script src="<?php echo $this->baseUrl('assets/plugins/jquery-1.10.1.min.js')?>" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl('assets/plugins/jquery-migrate-1.2.1.min.js')?>" type="text/javascript"></script>
	<!-- IMPORTANT! Load jquery-ui-1.10.1.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
	<script src="<?php echo $this->baseUrl('assets/plugins/jquery-ui/jquery-ui-1.10.1.custom.min.js')?>" type="text/javascript"></script>
	<link href=<?php echo $this->baseUrl("assets/plugins/bootstrap/css/bootstrap.min.css")?> rel="stylesheet" type="text/css"/>
	<link href=<?php echo $this->baseUrl("assets/plugins/bootstrap/css/bootstrap-responsive.min.css")?> rel="stylesheet" type="text/css"/>
	<link href=<?php echo $this->baseUrl("assets/plugins/font-awesome/css/font-awesome.min.css")?> rel="stylesheet" type="text/css"/>
	<link href=<?php echo $this->baseUrl("assets/css/style-metro.css")?> rel="stylesheet" type="text/css"/>
	<link href=<?php echo $this->baseUrl("assets/css/style.css")?> rel="stylesheet" type="text/css"/>
	<link href=<?php echo $this->baseUrl("assets/css/style-responsive.css")?> rel="stylesheet" type="text/css"/>
	<link href=<?php echo $this->baseUrl("assets/css/themes/default.css")?> rel="stylesheet" type="text/css" id="style_color"/>
	<link href=<?php echo $this->baseUrl("assets/plugins/uniform/css/uniform.default.css")?> rel="stylesheet" type="text/css"/>
	<!-- END GLOBAL MANDATORY STYLES -->
	<!-- BEGIN PAGE LEVEL STYLES -->
	<link href=<?php echo $this->baseUrl("assets/css/pages/error.css")?> rel="stylesheet" type="text/css"/>
	<!-- END PAGE LEVEL STYLES -->
	<link rel="shortcut icon" href=<?php echo $this->baseUrl("favicon.ico")?> />
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="page-404-3">
	<div class="page-inner">
		<img src="<?php echo $this->baseUrl("assets/img/pages/earth.jpg")?>" alt="">
	</div>
	<div class="container error-404">
		<h1>Opsss. Me perdi!</h1>
		<h2>A exibição desta página gerou um erro.</h2>
		<p>
			Atualmente nós estamos trabalhando para isto não existir. 
		</p>
		
		<?php if (isset($this->exception)): ?>
      <div class="small-12 columns centered">
          <h3> <a href="#" style="color: white;" class="info btn icn-only red"> Exception information:</a></h3>
          <div class="small-12 columns centered info" style="display: none">
              <p>
                  <b>Mensagem:</b> <?php echo $this->exception->getMessage() ?>
              </p>

              <h3>Stack trace:</h3>
              <pre><?php echo $this->exception->getTraceAsString() ?>
              </pre>
          </div>
      </div>
      <?php endif ?>
      <p>
		<a style="cursor: pointer;" onclick="window.history.back()" class="btn black"><i class="m-icon-swapleft"></i> Voltar</a>
	</p>
		
	</div>
</body>
<!-- END BODY -->
<script type="text/javascript">

$(document).ready(function(){
	$('body').on('click', 'a.info', function(e){
        e.preventDefault();
        $('div.info').slideToggle('slow');
    });
});
	


</script>
</html>