<style>
<!--
img.up{
	margin-top: -15px;
}
-->
</style>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('/assets/plugins/bootstrap-timepicker/compiled/timepicker.css')?>">
<div class="row-fluid">
	<div class="span12">
	</div>
</div>
<div class="row-fluid">
	<div class="portlet box steelblue">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder"></i> Formulário de <?php echo $this->translate('Protocolo de serviço')?></div>
			<div class="tools">
				<a href="javascript:;" class="collapse"></a>
			</div>
		</div>
		<div class="portlet-body form">
      <form action="#" method="post" class="form_protocolo" >
				<div class="row-fluid">
					<div class="span4">
						<div class="control-group">
							<label class="control-label"><?php echo $this->translate('Tipo de entrada')?>*</label>
							<div class="controls">
								<?php echo $this->formSelect('id_tp_entrada',$this->vo->id_tp_entrada, null, $this->tpEntradaCombo);?>
                <img src="<?php echo $this->baseUrl('images/add.png')?>" style="cursor:pointer;" data-tooltip title="Adicionar tipo de entrada" class="up add_tp_protocolo">
								<?php echo $this->formHidden('id_protocolo', $this->vo->id_protocolo);?>
							</div>
						</div>
					</div>
					<div class="span3">
						<div class="control-group">
							<label class="control-label"><?php echo $this->translate('Data de Entrada')?></label>
							<div class="controls">
								<?php echo $this->formText('dt_entrada', $this->vo->dt_entrada ? $this->date($this->vo->dt_entrada) : date('d/m/Y'), array( 'placeholder' => 'Data de entrada' ));?>
							</div>
						</div>
					</div>
					<div class="span3">
						<div class="control-group">
							<label class="control-label"><?php echo $this->translate('Hora de Entrada')?></label>
							<div class="input-append bootstrap-timepicker-component">
								<?php echo $this->formText('hr_entrada', $this->vo->hr_entrada ? $this->vo->hr_entrada : date('H:i:s'), array( 'placeholder' => 'Hora de entrada', 'class' => 'm-wrap m-ctrl-small m-wrap m-ctrl-small timepicker-24' ));?>
								<span class="add-on"><i class="icon-time"></i></span>
							</div>
						</div>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span4">
						<div class="control-group">
							<label class="control-label"><?php echo $this->translate('Quem está entregando')?>* <img src="<?php echo $this->baseUrl('images/help.png')?>" style="left:162px" data-tooltip title="Digite no mínimo dois caracteres que contém no nome da empresa do grupo para aparecer uma lista de empresas." class="help"></label>
							<div class="controls">
								<?php echo $this->formHidden('id_empresa_fornecedor',$this->vo->id_empresa_fornecedor);?>
                <?php echo $this->formText('empresa_fornecedor', $this->vo->getFornecedor() ? $this->vo->getFornecedor()->nome_razao : null, array('placeholder'=> 'Digite o nome ou a razão Social'));?>
							</div>
						</div>
					</div>
					<div class="span2">
						<div class="control-group">
							<label class="control-label"><?php echo $this->translate('CNPJ')?></label>
							<div class="controls">
								<?php echo $this->formText('cnpj_fornecedor',$this->vo->getFornecedor() ? $this->cpf($this->vo->getFornecedor()->cnpj_cpf) : null, array('placeholder'=>'CNPJ'));?>
							</div>
						</div>
					</div>
					<div class="span4">
						<div class="control-group">
							<label class="control-label"><?php echo $this->translate('Requisitante (quem pediu)')?></label>
							<div class="controls">
								<?php echo $this->formSelect('id_operacao_requisitante', $this->vo->id_operacao_requisitante, array('style' => 'width: 90%;'), $this->comboOperacao);?>
                <img src="<?php echo $this->baseUrl('images/add.png')?>" style="top:5px; position: relative;cursor:pointer;" data-tooltip title="Adicionar Grupo de operações" class="up add_grupo_operacao">
							</div>
						</div>
					</div>
					<div class="span2">
						<div class="control-group">
							<label class="control-label"><?php echo $this->translate('Código de controle')?></label>
							<?php if (count($this->controleFornecedor)):?>
              	<?php foreach ($this->controleFornecedor as $key => $controle):
                	$delete = $key > 0 ? true : false;
                  if(is_object($controle)):?>
                  	<div class="controls">
                    	<?php echo $this->formText('controle_fornecedor[]', $controle->codigo, array('style' => 'display: inline-block; width: 60%;', 'placeholder' => 'Código'));?>
                      <img src="<?php echo $delete ? $this->baseUrl('images/delete.png') : $this->baseUrl('images/add.png')?>" style="top:5px; position: relative;cursor:pointer;" data-tooltip title="<?php echo $delete ?  'Remover controle do fornecedor' : 'Adicionar controle do fornecedor'?>" class="up <?php echo $delete ? 'remove_controle_fornecedor' : 'add_controle_fornecedor'?>">
                    </div>
                  <?php else:?>
                  	<div class="controls">
                    	<?php echo $this->formText('controle_fornecedor[]', $controle, array('style' => 'display: inline-block; width: 60%;', 'placeholder' => 'Código'));?>
                      <img src="<?php echo $delete ? $this->baseUrl('images/delete.png') : $this->baseUrl('images/add.png')?>" style="top:5px; position: relative;cursor:pointer;" data-tooltip title="<?php echo $delete ? 'Remover controle do fornecedor' : 'Adicionar controle do fornecedor'?>" class="up <?php echo $delete ? 'remove_controle_fornecedor' : 'add_controle_fornecedor'?>">
                  	</div>
                  <?php endif;?>
                <?php endforeach;?>
							<?php else :?>
              	<div class="controls">                    
              		<?php echo $this->formText('controle_fornecedor[]', null, array('style' => 'display: inline-block; width: 60%;', 'placeholder' => 'Código'));?>
                  <img src="<?php echo $this->baseUrl('images/add.png')?>" style="top:5px; position: relative;cursor:pointer;" data-tooltip title="Adicionar controle do fornecedor" class="up add_controle_fornecedor">
                </div>
              <?php endif;?>
						</div>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span4">
						<div class="control-group">
							<label class="control-label"><?php echo $this->translate('Quem está recebendo')?>* <img src="<?php echo $this->baseUrl('images/help.png')?>" data-tooltip title="Digite no mínimo dois caracteres que contém no nome da empresa do cliente para aparecer uma lista de empresas." style="left: 156px" class="help"></label>
							<div class="controls">
								<?php echo $this->formHidden('id_empresa_receptora',$this->vo->id_empresa_receptora);?>
                <?php echo $this->formText('empresa_receptora',$this->vo->getReceptora() ? $this->vo->getReceptora()->nome_razao : null, array('placeholder'=> 'Digite a razão Social'));?>
							</div>
						</div>
					</div>
					<div class="span2">
						<div class="control-group">
							<label class="control-label"><?php echo $this->translate('CNPJ')?></label>
							<div class="controls">
								<?php echo $this->formText('cnpj_receptora',$this->vo->getReceptora() ? $this->cpf($this->vo->getReceptora()->cnpj_cpf) : null, array('placeholder'=>'CNPJ'));?>
							</div>
						</div>
					</div>
					<div class="span4">
						<div class="control-group">
							<label class="control-label"><?php echo $this->translate('Requisitado')?></label>
							<div class="controls">
								<?php echo $this->formSelect('id_operacao_requisitado', $this->vo->id_operacao_requisitado, array('style' => 'width: 90%;'), $this->comboOperacao);?>
                <img src="<?php echo $this->baseUrl('images/add.png')?>" style="top:5px; position: relative;cursor:pointer;" data-tooltip title="Adicionar Grupo de operações" class="up add_grupo_operacao">
							</div>
						</div>
					</div>
					<div class="span2">
						<div class="control-group">
							<label class="control-label"><?php echo $this->translate('Código de controle')?></label>
							<?php if (count($this->controleReceptora)):?>
              	<?php foreach ($this->controleReceptora as $key => $controle):
                	$delete = $key > 0 ? true : false;
                  if(is_object($controle)):?>
                  	<div class="controls">
                    	<?php echo $this->formText('controle_receptora[]', $controle->codigo, array('style' => 'display: inline-block; width: 60%;', 'placeholder' => 'Código'));?>
                      <img src="<?php echo $delete ? $this->baseUrl('images/delete.png') : $this->baseUrl('images/add.png')?>" style="top:5px; position: relative;cursor:pointer;" data-tooltip title="<?php echo $delete ? 'Remover controle do receptor' : 'Adicionar controle do receptor'?>" class="up <?php echo $delete ? 'remove_controle_receptora' : 'add_controle_receptora'?>">
                    </div>
                    <?php else:?>
                    	<div class="controls">
	                    	<?php echo $this->formText('controle_receptora[]', $controle, array('style' => 'display: inline-block; width: 60%;', 'placeholder' => 'Código'));?>
	                      <img src="<?php echo $delete ? $this->baseUrl('images/delete.png') : $this->baseUrl('images/add.png')?>" style="top:5px; position: relative;cursor:pointer;" data-tooltip title="<?php echo $delete ? 'Remover controle do receptor' : 'Adicionar controle do receptor'?>" class="up <?php echo $delete ? 'remove_controle_receptora' : 'add_controle_receptora'?>">
                    	</div>
                    <?php endif;?>
                  <?php endforeach;?>
                <?php else :?>
                	<div class="controls">
                		<?php echo $this->formText('controle_receptora[]', null, array('style' => 'display: inline-block; width: 60%;', 'placeholder' => 'Código'));?>
                    <img src="<?php echo $this->baseUrl('images/add.png')?>" style="top:5px; position: relative;cursor:pointer;" data-tooltip title="Adicionar controle do receptor" class="up add_controle_receptora">
                  </div>
              <?php endif;?>
						</div>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span4">
						<div class="control-group">
							<label class="control-label"><?php echo $this->translate('Processo')?></label>
							<div class="controls">
								<?php echo $this->formSelect('id_processo', $this->vo->id_processo, array('style' =>'margin-bottom: 20px;'), $this->comboProcesso);?>
							</div>
						</div>
					</div>
					<div class="span4">
						<div class="control-group">
							<label class="control-label"><?php echo $this->translate('Centro de Custo')?></label>
							<div class="controls">
								<?php echo $this->formSelect('id_centro_custo',$this->vo->id_centro_custo, array('style' =>'margin-bottom: 20px;'), $this->comboCentroCusto);?>
							</div>
						</div>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span12">
						<div class="control-group">
							<label class="control-label"><?php echo $this->translate('Observação')?></label>
							<div class="controls">
								<?php echo $this->formTextarea('observacao', $this->vo->observacao, array('placeholder' => 'Observação','class' =>'span12', 'style'=> 'height: 113px ;display: inline;'));?>
                <span id="countDescricao"></span> Caracteres restantes
							</div>
						</div>
					</div>
				</div>
				<div class="form-actions">
          <button type="submit" class="btn blue"><i class="icon-ok"></i> Salvar</button>
        	<a href="<?php echo $this->baseUrl('service/protocolo/grid')?>" class="btn" >Voltar</a>
        </div>
        </form>
        </div>
    </div>
</div>
<div class="add_tipo" style="display:none;">
    <div class="row" style="margin: 0; max-width: 100%;">
        <div class="large-12 columns">
            <label><?php echo $this->translate('Nome')?></label>
            <?php echo $this->formText('nome_tp_entrada');?>
        </div>
    </div>
</div>
<div class="dialog_grupo_operacao" style="display:none;">
    <form action="post" class="form_grupo_operacao" style="margin:0;">
        <div class="row" style="margin: 0; max-width: 100%;">
            <div class="large-12 columns">
                <label><?php echo $this->translate('Nome')?>*</label>
                <?php echo $this->formText('ope_nome');?>
            </div>
            <div class="large-12 columns" style="margin-bottom: 15px;">
                <label><?php echo $this->translate('Empresas do Grupo')?>*</label>
                <?php echo $this->formSelect('empresas_grupo_id', null, null, $this->comboEmpresaGrupo);?>
            </div>
            <div class="large-12 columns">
                <label><?php echo $this->translate('CPF/CNPJ')?></label>
                <?php echo $this->formText('ope_cpf_cnpj');?>
            </div>
            <div class="large-12 columns ope_tel">
                <label><?php echo $this->translate('Telefone')?></label>
                <?php echo $this->formText('ope_telefone1', null, array('style' => 'display: inline-block;width:80%'));?>
                <img src="<?php echo $this->baseUrl('images/add.png')?>" style="top:5px; position: relative;cursor:pointer;" data-tooltip title="Adicionar telefone" class="up add_tel_ope">
            </div>
            <div class="large-12 columns ope_email">
                <label><?php echo $this->translate('Email')?></label>
                <?php echo $this->formText('ope_email1', null, array('style' => 'display: inline-block;width:80%'));?>
                <img src="<?php echo $this->baseUrl('images/add.png')?>" style="top:5px; position: relative;cursor:pointer;" data-tooltip title="Adicionar email" class="up add_email_ope">
            </div>
            <div class="large-12 columns">
                <div style="text-align: center;color: red;">* Campo obrigatório</div>
            </div>
        </div>
    </form>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/service/protocolo.form.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/bootstrap-timepicker/js/bootstrap-timepicker.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('/scripts/lib/jquery.limit-1.2.source.js')?>"></script>