<style>
<!--
.dataTables_filter{
	float: right;
}

.dataTables_paginate{
	margin: 0px;
	float: right;
}

-->
</style>
<div class="row-fluid">
     <div class="span12">
     </div>
</div>
<div class="row-fluid">
	<div class="span12">
		<div class="portlet box steelblue">
			<div class="portlet-title">
				<div class="caption"><i class="icon-wrench"></i>Protocolo de serviço</div>
				<div class="tools">
                    <a href="javascript:;" class="collapse"></a>
                </div>
                <div class="actions">
									<a class="btn cadastro-link" href="<?php echo $this->baseUrl('/service/orcamento/form')?>"><i class="icon-pencil"></i> Novo </a>
								</div>
			</div>
			<div class="portlet-body flip-scroll">
				<div id="sample_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
					<table class="table-bordered table-striped table-condensed flip-content" id="perfisTable">
						<thead class="flip-content">
							<tr>
                <tr>
                    <th class="hidden-480"><?php echo $this->translate('Código')?></th>
                    <th class="hidden-480"><?php echo $this->translate('Tipo de entrada')?></th>
                    <th class=""><?php echo $this->translate('Empresa Receptora')?></th>
                    <th class=""><?php echo $this->translate('Data de entrada')?></th>
                    <th class="hidden-480"><?php echo $this->translate('Hora de entrada')?></th>
                    <th class="hidden-480" style="width: 50px !important;"><?php echo $this->translate('Ação')?></th>
                </tr>
						</thead>

						<tbody>
							<?php if (count($this->listaProtocolo) > 0):?>
				        <?php foreach ($this->listaProtocolo as $protocolo):?>
                    <tr>
                        <td><?php echo $protocolo['id_protocolo']?></td>
                        <td><?php echo $protocolo['nome_tp_entrada']?></td>
                        <td><?php echo $protocolo['nome_receptor']?></td>
                        <td><?php echo $this->date($protocolo['dt_entrada'])?></td>
                        <td><?php echo $protocolo['hr_entrada'] ?></td>
                        <td>
                            <a title='Editar' data-tooltip href='<?php echo $this->baseUrl("/service/protocolo/form/id/".$protocolo['id_protocolo'] )?>'>
                                <img src="<?php echo $this->baseUrl('images/edit.png')?>" data-tooltip title="Editar">
                            </a>
                            <a class='delete' data-tooltip title='Excluir' href='<?php echo $this->baseUrl("/service/protocolo/delete/id/".$protocolo['id_protocolo'] )?>'>
                                <img src="<?php echo $this->baseUrl('images/delete.png')?>" data-tooltip title="Remover">
                            </a>
                        </td>
                    </tr>
                <?php endforeach;?>
							<?php endif;?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="dialog_delete" style="display: none;">
	<p>Deseja realmente excluir a unidades: <span id ="valueDelete"></span></p>
</div>
<script type="text/javascript">

 $('#perfisTable').dataTable({
     "aLengthMenu": [
         [30, 50, 100, -1],
         [30, 50, 100, "All"] // change per page values here
     ],
     // set the initial value
     "iDisplayLength": 30,
     "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
     "sPaginationType": "bootstrap",
     "oLanguage": {
         "sProcessing": "Aguarde enquanto os dados são carregados ...",
         "sLengthMenu": "Mostrar _MENU_ registros",
         "sZeroRecords": "Não foram encontrados resultados",
         "sInfoEmpty": "Mostrando de 0 até 0 de 0 registros",
         "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
         "sInfoFiltered": "",
         "sSearch": "Procurar",
         "oPaginate": {
            "sFirst":    "Primeiro",
            "sPrevious": "Anterior",
            "sNext":     "Próximo",
            "sLast":     "Último"
         }
      },
     "aoColumnDefs": [{
             'bSortable': true,
             'aTargets': [0]
         }
     ]
 });
</script>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/sis/orcamento.grid.js')?>"></script>