<div class="row-fluid">
    <div class="span12">
        <table class="table-bordered table-striped table-condensed flip-content" style="width: 100%">
            <thead>
                <tr>
                    <th>Criado por</th>
                    <th>Entidade</th>
                    <th>Mensagem</th>
                    <th>Data de criação</th>
                </tr>
            </thead>
            <tbody>
                <?php if(count($this->comentarioList)>0):?>
                          <?php $count = 0?>
                    <?php foreach ($this->comentarioList as $key=> $comentario):?>
                        <tr>
                            <td><?php echo $comentario->getUsuario()->nome ?></td>
                            <td><?php echo $comentario->getEmpresa()->nome ?></td>
                            <td><?php echo $comentario->descricao ?></td>
                            <td><?php echo $this->DateHour($comentario->dt_criacao)?></td>
                        </tr>
                    <?php endforeach;?>
                <?php else: ?>
                    <tr>
                        <td colspan="10">Não possui comentário a este processo</td>
                    </tr>
                <?php endif;?>
            </tbody>
        </table>
    </div>
</div>