<link rel="stylesheet" href="/assets/plugins/data-tables/DT_bootstrap.css" />

<div class="row-fluid" style="margin-top: 20px">
	<div class="span12">
		<div class="portlet box purple">
			<div class="portlet-title">
				<div class="caption"><i class="icon-wrench"></i>Pedidos</div>
				<div class="tools">
                    <a href="javascript:;" class="collapse"></a>
                </div>
			</div>
			<div class="portlet-body flip-scroll">
				<div id="sample_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
					<table class="table table-striped table-bordered table-hover" id="table_pedido">
                        <thead class="flip-content">
                            <tr>
                                <th>Status</th>
                                <th>Destinatário</th>
                                <th>Email</th>
                                <th>Aos cuidados</th>
                                <th>cep</th>
                                <th>logradouro</th>
                                <th>numero</th>
                                <th>complemento</th>
                                <th>bairro</th>
                                <th>Observação</th>
                                <th>Solicitado em</th>
                                <th style="width:70px">Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if(count($this->listPedido)):?>
                                <?php foreach ($this->listPedido as $pedido):?>
                                    <tr>
                                        <td><?php echo $pedido->getStatus()->nome ?></td>
                                        <td><?php echo $pedido['destinatario'] ?></td>
                                        <td><?php echo $pedido['email'] ?></td>
                                        <td><?php echo $pedido['aos_cuidados'] ?></td>
                                        <td><?php echo $this->cep($pedido['cep']) ?></td>
                                        <td><?php echo $pedido['logradouro'] ?></td>
                                        <td><?php echo $pedido['numero'] ?></td>
                                        <td><?php echo $pedido['complemento'] ?></td>
                                        <td><?php echo $pedido['bairro'] ?></td>
                                        <td><?php echo $pedido['observacao'] ?></td>
                                        <td><?php echo $this->date($pedido['dt_criacao']) ?></td>
                                        <td>
                                            <a href="<?php echo $pedido['id_entrega']?>" class="view_prod"  title="Visualizar produtos" data-tooltip><img src="<?php echo $this->baseUrl('images/detail.png')?>"></a>
                                            <a href="<?php echo $pedido['id_entrega']?>" id-status="<?php echo $pedido['id_status']?>" protocolo="<?php echo $pedido['protocolo']?>" class="entrega_prod"  title="Entregar produtos" data-tooltip><img src="<?php echo $this->baseUrl('images/cart.png')?>"></a>
                                        </td>
                                    </tr>
                                <?php endforeach;?>
                            <?php endif;?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="view_prod"></div>

    <div class="dialog_entrega" style="display: none">
        <form class="form_entrega" style="margin: 0">
            <div class="row-fluid">
                <div class="span12">
                    <div class="control-group">
                        <label class="control-label">Status</label>
                        <div class="controls">
                            <?php echo $this->formHidden('id');?>
                            <?php echo $this->formHidden('atualizacao', 1);?>
                            <?php echo $this->formSelect('id_status',null, array('class' => 'span12'), $this->comboStatus);?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span12">
                    <div class="control-group">
                        <label class="control-label">Protocolo de entrega do correio</label>
                        <div class="controls">
                            <?php echo $this->formTextarea('protocolo',null, array('placeholder'=> 'Protocolo', 'class'=>'span12', 'rows'=>4));?>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/material/pedido.entrega.js')?>"></script>