<link rel="stylesheet" href="/assets/plugins/data-tables/DT_bootstrap.css" />

<div class="row-fluid" style="margin-top: 20px">
	<div class="span12">
		<div class="portlet box purple">
			<div class="portlet-title">
				<div class="caption"><i class="icon-wrench"></i>Pedidos</div>
				<div class="tools">
                    <a href="javascript:;" class="collapse"></a>
                </div>
				<div class="actions">
					<a class="btn blue" href="<?php echo $this->baseUrl('/material/entrega/empresa')?>" title="Solicitar entrega"><i class="icon-plus"></i> Novo pedido </a>
				</div>
			</div>
			<div class="portlet-body flip-scroll">
				<div id="sample_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
					<table class="table table-striped table-bordered table-hover" id="table_pedido">
                        <thead class="flip-content">
                            <tr>
                                <th>Status</th>
                                <th>Destinatário</th>
                                <th>Email</th>
                                <th>Aos cuidados</th>
                                <th>cep</th>
                                <th>logradouro</th>
                                <th>numero</th>
                                <th>complemento</th>
                                <th>bairro</th>
                                <th>Observação</th>
                                <th>Solicitado em</th>
                                <th style="width:70px">Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if(count($this->listPedido)):?>
                                <?php foreach ($this->listPedido as $pedido):?>
                                    <tr>
                                        <td><?php echo $pedido->getStatus()->nome ?></td>
                                        <td><?php echo $pedido['destinatario'] ?></td>
                                        <td><?php echo $pedido['email'] ?></td>
                                        <td><?php echo $pedido['aos_cuidados'] ?></td>
                                        <td><?php echo $this->cep($pedido['cep']) ?></td>
                                        <td><?php echo $pedido['logradouro'] ?></td>
                                        <td><?php echo $pedido['numero'] ?></td>
                                        <td><?php echo $pedido['complemento'] ?></td>
                                        <td><?php echo $pedido['bairro'] ?></td>
                                        <td><?php echo $pedido['observacao'] ?></td>
                                        <td><?php echo $this->date($pedido['dt_criacao']) ?></td>
                                        <td>
                                            <a href="<?php echo $pedido['id_entrega']?>" class="view_prod"  title="Visualizar produtos" data-tooltip><img src="<?php echo $this->baseUrl('images/detail.png')?>"></a>
                                            <a href="#" class="protocolo" protocolo="<?php echo $pedido['protocolo']?>" title="Visualizar protocolo" data-tooltip><img src="<?php echo $this->baseUrl('images/search.png')?>"></a>
                                        </td>
                                    </tr>
                                <?php endforeach;?>
                            <?php endif;?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="view_prod"></div>
<div class="dialog_protocolo"><p class="protocolo"></p></div>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/material/pedido.index.js')?>"></script>