<head>
<meta charset="utf-8">
<title>Metronic | Extra - Invoice</title>
<meta content="width=device-width, initial-scale=1.0" name="viewport">
<meta content="" name="description">
<meta content="" name="author">
<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link href="<?php echo $this->baseUrl('assets/plugins/bootstrap/css/bootstrap.min.css')?>" rel="stylesheet" type="text/css">
        <link href="<?php echo $this->baseUrl('assets/plugins/bootstrap/css/bootstrap-responsive.min.css')?>" rel="stylesheet" type="text/css" media="screen">
                <link href="<?php echo $this->baseUrl('assets/plugins/font-awesome/css/font-awesome.min.css')?>" rel="stylesheet" type="text/css">
                        <link href="<?php echo $this->baseUrl('assets/css/style-metro.css')?>" rel="stylesheet" type="text/css">
                                <link href="<?php echo $this->baseUrl('assets/css/style.css')?>" rel="stylesheet" type="text/css">
                                        <link href="<?php echo $this->baseUrl('assets/css/style-responsive.css')?>" rel="stylesheet" type="text/css">
                                                <link href="<?php echo $this->baseUrl('assets/css/themes/default.css')?>" rel="stylesheet" type="text/css" id="style_color">
                                                        <link href="<?php echo $this->baseUrl('assets/plugins/uniform/css/uniform.default.css')?>" rel="stylesheet" type="text/css">
                                                                <!-- END GLOBAL MANDATORY STYLES -->
                                                                <!-- BEGIN PAGE LEVEL STYLES -->
                                                                <link href="<?php echo $this->baseUrl('assets/css/pages/invoice.css')?>" rel="stylesheet" type="text/css">
                                                        <link href="<?php echo $this->baseUrl('assets/css/print.css')?>" rel="stylesheet" type="text/css" media="print">
	<!-- END PAGE LEVEL STYLES -->
	<link rel="shortcut icon" href="favicon.ico">

</head>
<style>
table {
    border-collapse: separate;
    border-spacing: 0px;
    font:13px/1.5 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif;
}

table td,
table th {
    background-color: transparent;
    z-index: 1;
    border-right: 0;
    border-bottom: 0;
    width: 150px;
    padding-left: 5px;
    overflow: hidden;
    height: 12px;
}

table th:before,
table td:before {
    content: "";
    padding: 0;
    height: 1px;
    line-height: 1px;
    width: 1px;
    margin: 1px -994px -996px -2px;
    display: block;
    border: 0;
    z-index: -1;
    position:relative;
    top: -6px;
}

table th:before {
    border-top: 999px solid #D6D6D6;
    border-left: 999px solid #D6D6D6;
}

table td:before {
    border-top: 999px solid #F9F9F9;
    border-left: 999px solid #F9F9F9;
}
td div.grid_3{
    overflow: hidden;
}
table .row td{
    border-bottom: #d6d6d6 1px solid;
    width: 110px;
}


</style>

<div class="row-fluid invoice">
    <div class="row-fluid invoice-logo">
         <div class="span6 invoice-logo-space"><img style="width: 100px;" src="<?php echo $this->baseUrl("images/logo4-01.jpg")?>" alt="">

         </div>
         <span style="float: right;">
             <b style="font-size: 25px;">LISTA DE PROCESSOS</b><br>

                         <span style="font-size: 13px"> Emitido em: <?php echo date("d/m/Y H:i:s") ?></span><br>
                         <span style="font-size: 13px"> Por: <?php echo $this->usuario ?></span>

         </span>
         <div class="span6">


         </div>
    </div>

    <div class="row-fluid">
    	<table class=" table-striped " style ="font-size: 10px; width: 40%; ">
    		<thead  style="background-color: black;  color: white; size: 2px" >
    			<tr>
    				<th style="font-size: 10px; width: 1%;" >COD. DO LOTE.</th>
    				<th class="" style=" font-size: 10px; width: 1%;">QTD.</th>
    				<th class="" style="width:15% ; font-size: 10px"> UNID. </th>

    			</tr>
    		</thead>
    		<tbody>

             <?php
    		foreach ($this->protocoloRegistros[0] as $key => $valor){

    		    $itemMostrar = true;
    		    $itemAdicional = true;

    		    $total = 0;
    		    $i = 0;
    		    for($i = 0 ; $i <count($this->protocoloRegistros[1]) ; $i++){

    		        if ($valor ==   $this->protocoloRegistros[1][$i]){
    		            if ($itemMostrar){

    		                echo "<tr>";
                                echo "<td colspan = 3 >";
                                   echo "<pre>Codigo movimento " .$valor ."        item: ".$this->protocoloRegistros[1][$i+1]."</pre>";
                                echo "</td>";
                            echo "</tr>";
    		                $itemMostrar = false;

    		            }
    		           echo '<tr>';
        		            echo "<td style='text-align: center;'> ".$this->protocoloRegistros[1][$i+2]."</td>";
        		            echo "<td style='text-align: right;'>".$this->protocoloRegistros[1][$i+3]."</td>";
        		            echo "<td style='text-align: center;'> ".$this->protocoloRegistros[1][$i+4]."</td>";
    		            echo '</tr>';

                }

                    if ( $itemAdicional){
                        echo "<tr>";
                        echo "<td colspan = 3 >";
                        echo "<pre>Numero de lotes: " .$this->protocoloRegistros[1][$i+6] ."        Saldo em estoque: ".$this->protocoloRegistros[1][$i+5]."</pre>";
                        echo "</td>";
                        echo "</tr>";
                        $itemAdicional = false;
                   }
    		        $i +=6;
    		    }
    		}
           ?>

    		</tbody>
        </table>

    </div>
<div class="row-fluid">
	<div class="span4"></div>
	<div class="span8 invoice-block">
        <ul class="unstyled amounts">
			<li><strong>Total: </strong><?php ?></li>
        </ul><br>
		<a class="btn blue hidden-print" onclick="javascript:window.print();">Print <i class="icon-print icon-big"></i></a>
		<a href="#" class="btn blue hidden-print">Voltar</a>

	</div>
</div>
<div class="span4"></div>
</div>