<?php
    /**
     * grid da empresa aonde visualiza todas as empresas ativa que o grupo se relaciona
     * com link pra criar, alterar e inativar.
     */
?>
<style>
<!--

.pro_nome{
    width: 460px;
}
th.transacao{
    width: 80px;
}
td.transacao{
    text-align: center !important;
}
.dt_entrada{
    width: 130px;
    text-align: center !important;
}
.hr_entrada{
    width: 130px;
    text-align: center !important;
}
.id_protocolo{
    width: 110px;
    text-align: center !important;
}
.nome_tp_entrada{
    width: 170px;
    text-align: center !important;
}
-->
</style>
<div class="row-fluid">
     <div class="span12">
     </div>
</div>
	    <?php //view
    $options = array(
        'paginator'            => $this->paginator,
        'title'                => 'Registro de Protocolo',
        'fields'               => array(
                                         'id_protocolo'        => "Código",
                                         'tpe.nome'            => 'Tipo',
                                         'tpro.pro_codigo'     => 'Código do Processo'
                                       ),
        'caminhoFormBotaoNovo' => $this->baseUrl() . '/material/protocolo/form',
        'colorGrid'            => 'purple',
        'icon'                 => ' icon-reorder',
        'columns'              => array(
                                         'id_protocolo'        => "Codigo",
                                         'nome_tp_protocolo'   => 'Tipo',
                                         'nome_receptor'       => 'Empresa Receptora',
                                         'pro_nome'            => 'Pedido',
                                         'dt_entrada'          => 'Data de entrada',
                                         'hr_entrada'          => 'Hora de entrada'
                                       ),
        'formatter'            => array( 'dt_entrada' => 'date'),
        'actions'              => array(
            //"<a title='Visualizar' data-tooltip href='" . $this->baseUrl() . "/material/protocolo/relatorio/id/%id_protocolo%'>"
            //    . "<img src='" . $this->baseUrl() . "/images/receipts-icon.png' />"
            //    . "</a>",
    		"<a data-tooltip title='Visualizar' class= 'opener' href='%id_protocolo%' id_protocolo='%id_protocolo%'>
                   <img src=".$this->baseUrl('/images/receipts-icon.png').">
            </a>",
            //inativo pois não esta funcionando
            //"<a title='Recibo de Protocolo' class='reciboProtocolo' id_protocolo='%id_protocolo%' data-tooltip href='#'>"
            	//. "<img src='" . $this->baseUrl() . "/images/cart.png' />"
          	//. "</a>",
            "<a title='Editar' data-tooltip href='" . $this->baseUrl() . "/material/protocolo/form/id/%id_protocolo%'>"
                . "<img src='" . $this->baseUrl() . "/images/edit.png' />"
            . "</a>",
            "<a class='delete' data-tooltip title='Excluir' href='" . $this->baseUrl() . "/material/protocolo/delete/id/%id_protocolo%'>"
                . "<img src='" . $this->baseUrl() . "/images/delete.png' />"
            . "</a>"
        )
    );
    echo $this->partial('grid-metronic.phtml', 'default', $options);
    ?>

<div id="dialog" title="Tipo de Relatório">
    <div class="row-fluid">
        <?php echo $this->formHidden('id_protocolo')?>
        <div class="span5">
            <div class="control-group">
                <label class="radio"><input type="radio" class="trel" id="trel"  name="trel" value="1"> <?php echo $this->translate('Simples')?></label>
            </div>
        </div>
        <div class="span6">
            <div class="control-group">
                <label class="radio"><input type="radio" class="trel" id="trel" name="trel" value="0"> <?php echo $this->translate('Analítico')?></label>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12" >
            <label class="checkbox"><input type="checkbox" id="saldo"  name="saldo" value="1"> Saldo em Estoque</label>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/material/protocolo.grid.js?cache')?>"></script>
