<!--<div class="row">-->
<!--	<fieldset>-->
<!--		<legend>Menu Rápido</legend>-->
<!--		<div style="text-align: center" class="small-2 columns">-->
<!--			<h4><a href="--><?php //echo $this->baseUrl("/processo/processo/grid")?><!--"><img style="width: 70%" src="--><?php //echo $this->baseUrl("/images/folder_black_bookmarks.png")?><!--">Processo</a></h4>-->
<!--		</div>-->
<!--		<div style="text-align: center" class="small-2 columns">-->
<!--			<h4><a href="--><?php //echo $this->baseUrl("/material/protocolo/grid")?><!--"><img style="width: 70%" src="--><?php //echo $this->baseUrl("/images/folder_black_library.png")?><!--">Protocolo</a></h4>-->
<!--		</div>-->
<!--		<div style="text-align: center" class="small-2 columns">-->
<!--			<h4><a href="--><?php //echo $this->baseUrl("/financial/financial/grid")?><!--"><img style="width: 70%" src="--><?php //echo $this->baseUrl("/images/folder_black_byte.png")?><!--">Financeiro</a></h4>-->
<!--		</div>-->
<!--	    <div class="small-1 columns">-->
<!--	    </div>-->
<!--	</fieldset>-->
<!--</div>-->

Tela inicial do Sistema