<?php $identity = Zend_Auth::getInstance()->getIdentity(); ?>

<div class="col-md-12">
    <nav class="nav-grupo-times">
        <ul>
            <li>
                <button class="btn btn-menu-open hidden-md hidden-lg visible-sm visible-xs">
                <i class="fa fa-chevron-right"></i></button>
            </li>
            <li>
                <a href="#" class="btn-times">
                    <i class="ico-hash" aria-hidden="true"></i>
                    <span><?php echo $identity->time['nome']; ?></span>
                    <!-- <i class="fa fa-chevron-down"></i> -->
                    <i class="fa fa-angle-right" aria-hidden="true"></i>
                </a>
            </li>
            <li>
                <!-- <a href="#" class="btn-fav">
                    <i class="fa fa-star-o"></i>
                </a> -->
                <a href="#" class="btn-times">
                    <!-- <span class="mark-grupo-hash">#</span> -->
                   <!--  <i class="fa fa-hashtag img-item" aria-hidden="true"></i> -->
                    <span>#<?php echo $identity->grupo['nome'] ?></span>
                    <!-- <i class="fa fa-chevron-down"></i> -->
                    <i class="fa fa-angle-right" aria-hidden="true"></i>
                </a>
            </li>
            <!--<?php if(!empty($this->servico) ){ ?>
                <li>
                    <a href="#" class="btn-times">
                         <span class="mark-grupo-hash">#</span>
                        <span><?php echo $this->servico['nome'] ?></span>
                        <i class="fa fa-angle-right" aria-hidden="true"></i>
                    </a>
                </li>
            <?php } ?>-->
            <li>
                <?php if(!empty($this->rastro)){ ?>
                    <nav class="rastro">
                        <ul>
                            <?php foreach($this->rastro as $rastro){?>
                                <?php if($rastro['id'] ==  $this->servico['id']){ ?>
                                        <li class="active"><?php echo $rastro['nome'] ?></li>
                                <?php }else{ ?>
                                        <li class="active"></li>
                                        <li>
                                            <a href="home.php?servico=<?php echo $rastro['id'] ?>">
                                                <?php echo $rastro['nome'] ?>
                                            </a>
                                            <i class="fa fa-angle-right"></i>
                                        </li>
                                <?php } ?>
                            <?php } ?>
                        </ul>
                    </nav>
                <?php } ?>
            </li>
        </ul>

       <!--  <form id="search-form" class="form-inline" role="form" method="post" action="//www.google.com/search" target="_blank">
            <div class="input-group">
                <input type="text" class="form-control input-search input-sm" placeholder="Search">

                <span class="input-group-btn">
                    <button type="submit" class="btn search-btn btn-circle btn-sm" data-target="#search-form" name="q">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
 -->
    </nav>
</div>
