<?php
    /**
     * formulario de pesquisa de extratos
    */
?>
<link rel="stylesheet" type="text/css" href="assets/plugins/bootstrap-datepicker/css/datepicker.css" />
<style>
<!--
i.add{
    font-size: 26px;
    color: #00CC99;
    cursor: pointer;
    margin-left: 2px;
}
i.remove-conta, i.remove-empresa{
     color: #e02222;
     font-size: 26px;
     cursor: pointer;
     margin-left: 2px;
}
.select-caracteristica{
    display: inline-block;
    padding: 0 !important;
    margin: 0 !important;
    margin-right: 15px !important;
}
-->
</style>
<div class="row-fluid" style="margin-top: 20px;">
	<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption"><i class=" icon-dollar"></i> Registro de extrato</div>
			<div class="tools">
				<a href="javascript:;" class="collapse"></a>
			</div>
		</div>
	<div class="portlet-body form">
		<form id="form" method="post">
                  <div class="row-fluid">
	                  <div class="span12">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Conta')?></label>
	                          <div class="controls grid-conta">
                                <label class="checkbox span3"><input type="checkbox" id="todos-checkbox" class="checkbox">Todos</label>
								<?php echo $this->formMultiCheckbox("contaList", null,array("class" =>"checkbox",'label_class' => 'checkbox span3'), $this->contaPairs, '')?>
	                          </div>
                          </div>
                      </div>
                  </div>
                  <div class="row-fluid">
                      <div class="span2">
                          <div class="control-group">
	                          <label class=" control-label"><?php echo $this->translate('Data de criação')?></label>
	                          <div class="controls">
								<?php echo $this->formText('de_fin_inclusao',null,array("class" => "span6 datepicker", 'placeholder'=> 'De')); ?>
								<?php echo $this->formText('ate_fin_inclusao',null,array("class" => "span6 datepicker", 'placeholder'=> 'Até')); ?>
                          	  </div>
                          </div>
                      </div>
                      <div class="span2">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Competência')?></label>
	                          <div class="controls">
								<?php echo $this->formText('de_fin_competencia',null,array("class" => "span6 datepicker", 'placeholder'=> 'De')); ?>
								<?php echo $this->formText('ate_fin_competencia',null,array("class" => "span6 datepicker", 'placeholder'=> 'Até')); ?>
	                          </div>
                          </div>
                      </div>
	                  <div class="span3">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Status da conta')?></label>
	                          <div class="controls">
								<?php echo $this->formMultiCheckbox("grupoContasList", null,array("class" =>"checkbox",'label_class' => 'checkbox'), array(2 => " Crédito", 1 => " Débito"), '')?>
	                          </div>
                          </div>
                      </div>
                  </div>
                  <div class="row-fluid">
                      <div class="span2">
                          <div class="control-group">
	                          <label class=" control-label"><?php echo $this->translate('Compensação')?></label>
	                          <div class="controls">
								<?php echo $this->formText('de_fin_compensacao',null,array("class" => "span6 datepicker", 'placeholder'=> 'De')); ?>
								<?php echo $this->formText('ate_fin_compensacao',null,array("class" => "span6 datepicker", 'placeholder'=> 'Até')); ?>
                          	  </div>
                          </div>
                      </div>
                      <div class="span2">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Vencimento')?></label>
	                          <div class="controls">
								<?php echo $this->formText('de_fin_vencimento',null,array("class" => "span6 datepicker", 'placeholder'=> 'De')); ?>
								<?php echo $this->formText('ate_fin_vencimento',null,array("class" => "span6 datepicker", 'placeholder'=> 'Até')); ?>
	                          </div>
                          </div>
                      </div>
	                  <div class="span2">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Característica')?></label>
	                          <div class="controls">
	                              <label class="checkbox"><input type="checkbox" name="transferencia" id="transferencia" value="1" class="checkbox">Transferência</label>
	                          </div>
                          </div>
                      </div>
	                  <div class="span4">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Compensado')?></label>
	                          <div class="controls">
	                              <?php echo $this->formSelect("compensado",null,array('class'=>'select-caracteristica'),array(null => '--- Selecione ---',1 => 'compensado', 0 => 'não compensado'));?>
	                          </div>
                          </div>
                      </div>
                  </div>
                  <div class="row-fluid">
                      <div class="span6">
                          <div class="control-group">
								<div id="empresa_sacado_div">
		                          <label class="control-label"><?php echo $this->translate('Entidade')?></label>
		                          <?php echo $this->formText("empresa_sacado",null, array("class" => "span11", "placeholder" => "Digite o nome do cliente"));?>
		                        </div>
                          </div>
                      </div>
                  </div>
	            	 <div class="row-fluid">
	            	    <div class="span6">
	            	        <H3 id="contaSelected">Empresas Selecionadas:</H3>
	                        <div id="localEmpresa">
	                        </div>
						</div>
	            	</div>
                  <div class="form-actions">
                      <button id = "gerarView" type="submit" class="btn blue"><i class="icon-ok"></i> Pesquisar</button>
                      <button id="gerarPdf" class="btn green"><i class="icon-file"></i> Pesquisar e Gerar PDF</button>

                  </div>
        </form>
        </div>
    </div>
</div>

<script type="text/javascript" src="assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
<script type="text/javascript" src="assets/plugins/bootstrap-datepicker/js/locales/bootstrap-datepicker.pt-BR.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("/scripts/financial/contas.extrato-form.js")?>"></script>