<style>
<!--
.dataTables_filter{
	float: right;
}

.dataTables_paginate{
	margin: 0px;
	float: right;
}

-->
</style>
<div class="row-fluid">
     <div class="span12">
	      <h3 class="page-title">
	       Extrato
	        <small> financeiro</small>
	      </h3>
     </div>
</div>
<div class="row-fluid">
	<div class="span12">
		<div class="portlet box blue">
			<div class="portlet-title  ">
				<div class="caption"><i class=" icon-dollar"></i>Extrato Pesquisado</div>
				<div class="tools">
                    <a href="javascript:;" class="collapse"></a>
                </div>
			</div>
			<div class="portlet-body flip-scroll">
				<div id="sample_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
					<table class="table-bordered table-striped table-condensed flip-content" id="extratoTable">
						<thead class="flip-content">
							<tr>
							    <th>Competência</th>
					            <th>Compensação</th>
								<th>Código</th>
					            <th style="width: 45% !important;">Cliente</th>
					            <th class = " hidden-print">Descrição</th>
					            <th>Conta</th>
					            <th style="text-align: right;">Valor</th>
					            <th>Tipo Financeiro</th>
					            <th class="action hidden-print">Ação</th>
							</tr>
						</thead>

						<tbody>
						<?php if (count($this->financialList) > 0):?>
		    			<?php $valor = 0;?>
						<?php foreach ($this->financialList as $financial):?>
				            <tr class="odd gradeX">
				                <td><?php echo $this->date($financial->fin_competencia, 'MM/yyyy')?></td>
				                <td><?php echo $this->date($financial->fin_compensacao)?></td>
								<td><?php echo $financial->fin_id?></td>
				                <td><?php echo $financial->nome_razao ? $financial->nome_razao : "" ?></td>
				                <td class = " hidden-print"><?php echo $financial->fin_descricao?></td>
				                <td><?php echo $financial->con_codnome?></td>
				                <td style="text-align: right;"><?php echo $this->formatDecimal($financial->fin_valor)?></td>
				                <?php if ( $financial->tmv_id == 1 ):$style = "red"; $type = "Débito"; elseif ($financial->tmv_id == 2): $style = "blue";  $type = "Crédito"; endif; ?>
				                <td <?php echo "style='color: {$style} '"?>> <?php echo $type?></td>
				                <td class="acoes hidden-print">
				                    <a href="<?php echo $this->baseUrl("/financial/agrupador-financeiro/form/fin_id/{$financial->fin_id}/id_agrupador_financeiro/{$financial->id_agrupador_financeiro}") ?>">
				                        <img title="Ver Financeiro" data-tooltip src="<?php echo $this->baseUrl('images/detail.png')?>" />
				                    </a>
				                </td>
				            </tr>
		           		<?php $valor = $financial->tmv_id == 1 ?  $valor - $financial->fin_valor : $valor + $financial->fin_valor;?>
				        <?php endforeach;?>
					<?php endif;?>
						</tbody>
					</table>
				</div>
				<div class="row-fluid">
					<div class="span6">
						<div class="dataTables_info" id="">
						</div>
					</div>
					<div class="span6">
						<div class="dataTables_paginate paging_bootstrap pagination">
						</div>
						<div style="float: right;">
							<h4>
								No período pesquisado de <b><?php echo $this->request["de_fin_inclusao"] ? $this->request["de_fin_inclusao"]: "-" ?></b> até <b><?php echo $this->request["ate_fin_inclusao"] ? $this->request["ate_fin_inclusao"]: "-"?></b> o saldo é <b><?php echo isset($valor) ? $this->formatDecimal($valor) : "0,00"; ?></b>
							</h4>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">

 $('#extratoTable').dataTable({
     "aLengthMenu": [
         [30, 50, 100, -1],
         [30, 50, 100, "All"] // change per page values here
     ],
     // set the initial value
     "iDisplayLength": 30,
     "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
     "sPaginationType": "bootstrap",
     "oLanguage": {
         "sProcessing": "Aguarde enquanto os dados são carregados ...",
         "sLengthMenu": "Mostrar _MENU_ registros",
         "sZeroRecords": "Não foram encontrados resultados",
         "sInfoEmpty": "Mostrando de 0 até 0 de 0 registros",
         "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
         "sInfoFiltered": "",
         "sSearch": "Procurar",
         "oPaginate": {
            "sFirst":    "Primeiro",
            "sPrevious": "Anterior",
            "sNext":     "Próximo",
            "sLast":     "Último"
         }
      },
     "aoColumnDefs": [{
             'bSortable': true/*,
             'aTargets': [0]*/
         }
     ]
 });
</script>
<script src="<?php echo $this->baseUrl('scripts/financial/financial.extrato-view.js')?>"></script>