<?php
    /**
     * formulario de cadastro de contas
    */
?>
<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Registro
			 <small> de contas</small>
		</h3>
	</div>
</div>
<div class="row-fluid">
	<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption"><i class=" icon-dollar"></i> Formulário</div>
			<div class="tools">
				<a href="javascript:;" class="collapse"></a>
			</div>
		</div>
	<div class="portlet-body form">
		<form id="form" method="post" action="">
			<?php echo $this->formHidden('con_id', $this->vo->con_id);?>
			<?php $identity = Zend_Auth::getInstance()->getIdentity(); ?>
			<?php echo $this->vo->con_id ? $this->formHidden("id_grupo",$this->vo->id_grupo) : $this->formHidden("id_grupo",$identity->time['id']); ?>
                  <div class="row-fluid">
                      <div class="span3">
                          <div class="control-group">
								<div>
		                          <label class="control-label"><?php echo $this->translate('Codnome da Conta')?></label>
		                          <?php echo $this->formText('con_codnome', $this->vo->con_codnome); ?>
		                        </div>
                          </div>
                      </div>
                      <div class="span3">
                          <div class="control-group">
	                          <label class=" control-label"><?php echo $this->translate('Número da conta')?><span class="required">*</span></label>
	                          <div class="controls">
									<?php echo $this->formText('con_numero', $this->vo->con_numero); ?>
                          	  </div>
                          </div>
                      </div>
                      <div class="span3">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Agência')?><span class="required">*</span></label>
	                          <div class="controls">
									<?php echo $this->formText('con_agencia', $this->vo->con_agencia); ?>
	                          </div>
                          </div>
                      </div>
                      <div class="span3">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Digito da Agência')?></label>
	                          <div class="controls">
								 <?php echo $this->formText('con_age_digito', $this->vo->con_age_digito); ?>
	                          </div>
                          </div>
                      </div>
                  </div>
                  <div class="row-fluid">
                  		<div class="span3">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Dígito da Conta')?><span class="required">*</span></label>
	                          <div class="controls">
								<?php echo $this->formText('con_digito', $this->vo->con_digito); ?>
	                          </div>
                          </div>
                      </div>
	                  <div class="span3">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Banco')?><span class="required">*</span></label>
	                          <div class="controls">
		                         <?php echo $this->formSelect('bco_id',$this->vo->bco_id,null,array("" => "Selecione")+$this->bancoCombo); ?>
	                          </div>
                          </div>
                      </div>
                      <div class="span3">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Tipo da Conta')?></label>
	                          <div class="controls">
		                         <?php echo $this->formSelect('tcb_id',$this->vo->tcb_id,null,array("" => "Selecione")+$this->tipoContaBancoCombo); ?>
	                          </div>
                          </div>
                      </div>
                      <div class="span3">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Registro Público')?></label>
	                          <div class="controls">
		                          	<?php echo $this->formCheckbox('register_public', $this->vo->id_grupo ? null : true ,null, array('checked' => '1', 'unChecked' => '0')); ?>
	                          </div>
                          </div>
                      </div>
                  </div>
                  <div class="form-actions">
                      <button type="submit" class="btn blue"><i class="icon-ok"></i>Salvar</button>
                  </div>
        </form>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl("/scripts/financial/contas.form.js")?>"></script>