<style>
<!--
.dataTables_filter{
	float: right;
}

.dataTables_paginate{
	margin: 0px;
	float: right;
}

-->
</style>
<div class="row-fluid">
     <div class="span12">
	      <h3 class="page-title">
	       Registro
	        <small> de Contas</small>
	      </h3>
     </div>
</div>
<div class="row-fluid">
	<div class="span12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption"><i class="icon-dollar"></i>Registros</div>
				<div class="tools">
                    <a href="javascript:;" class="collapse"></a>
                </div>
				<div class="actions">
					<a class="btn " href="<?php echo $this->baseUrl("/financial/contas/form") ?>"><i class="icon-pencil"></i> Novo </a>
				</div>
			</div>
			<div class="portlet-body flip-scroll">
				<div id="sample_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
					<table class="table-bordered table-striped table-condensed flip-content" id="contasTable">
						<thead class="flip-content">
							<tr>
								<th>Código</th>
					            <th>Codinome</th>
					            <th>Agência</th>
					            <th>Dígito da Agência</th>
					            <th>Número da Conta</th>
					            <th>Dígito da Conta</th>
					            <th>Banco</th>
					            <th>Tipo Conta</th>
					            <th>Workspace</th>
					            <th class="action">Ação</th>
							</tr>
						</thead>

						<tbody>
							<?php if (count($this->contasList) > 0):?>
				        <?php foreach ($this->contasList as $contas):?>
				            <tr class="odd gradeX">
				                <td><?php echo $contas->con_id?></td>
				                <td><?php echo $contas->con_codnome ?></td>
				                <td><?php echo $contas->con_agencia?></td>
				                <td><?php echo $contas->con_age_digito?></td>
				                <td><?php echo $contas->con_numero?></td>
				                <td><?php echo $contas->con_digito?></td>
				                <td><?php echo $contas->bco_id ? $contas->getBancos()->bco_nome : ""?></td>
				                <td><?php echo $contas->tcb_id ? $contas->getTipoContaBanco()->tcb_descricao : ""?></td>
				                <td><?php echo $contas->id_grupo != "" ? $contas->getGrupo()->nome : "Público" ;?></td>
				                <td class="acoes">
				                    <a href="<?php echo $this->baseUrl("financial/contas/form/con_id/{$contas->con_id}")?>">
				                        <img title="Editar Financeiro" data-tooltip src="<?php echo $this->baseUrl('images/edit.png')?>" />
				                    </a>
				                    <a class="deleteMoldal" name = "<?php echo $contas->con_codnome;?>" value = "<?php echo $contas->con_id?>" href="#">
				                        <img title="Excluir" data-tooltip src="<?php echo $this->baseUrl('images/delete.png')?>"/>
				                    </a>
				                </td>
				            </tr>
				        <?php endforeach;?>
					<?php endif;?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="dialog_delete" style="display: none;">
	<p>Deseja realmente excluir o vínculo do usuário: <span id ="valueDelete"></span></p>
</div>
<script type="text/javascript">

 $('#contasTable').dataTable({
     "aLengthMenu": [
         [30, 50, 100, -1],
         [30, 50, 100, "All"] // change per page values here
     ],
     // set the initial value
     "iDisplayLength": 30,
     "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
     "sPaginationType": "bootstrap",
     "oLanguage": {
         "sProcessing": "Aguarde enquanto os dados são carregados ...",
         "sLengthMenu": "Mostrar _MENU_ registros",
         "sZeroRecords": "Não foram encontrados resultados",
         "sInfoEmpty": "Mostrando de 0 até 0 de 0 registros",
         "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
         "sInfoFiltered": "",
         "sSearch": "Procurar",
         "oPaginate": {
            "sFirst":    "Primeiro",
            "sPrevious": "Anterior",
            "sNext":     "Próximo",
            "sLast":     "Último"
         }
      },
     "aoColumnDefs": [{
             'bSortable': true,
             'aTargets': [0]
         }
     ]
 });
</script>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/financial/contas.grid.js')?>"></script>