<?php $proprietarioSession = new Zend_Session_Namespace('proprietario');?>
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
	<meta charset="utf-8" />
	<title>ERP_Web</title>
	<meta content="width=device-width, initial-scale=1.0" name="viewport" />
	<meta content="" name="description" />
	<meta content="" name="author" />
	<!-- BEGIN GLOBAL MANDATORY STYLES --> 
	<link href=<?php echo $this->baseUrl("assets/plugins/bootstrap/css/bootstrap.min.css");?> rel="stylesheet" type="text/css"/>
	<link href=<?php echo $this->baseUrl("assets/plugins/bootstrap/css/bootstrap-responsive.min.css");?> rel="stylesheet" type="text/css"/>
	<link href=<?php echo $this->baseUrl("assets/plugins/font-awesome/css/font-awesome.min.css");?> rel="stylesheet" type="text/css"/>
	<link href=<?php echo $this->baseUrl("assets/css/style-metro.css");?> rel="stylesheet" type="text/css"/>
	<link href=<?php echo $this->baseUrl("assets/css/style.css");?> rel="stylesheet" type="text/css"/>
	<link href=<?php echo $this->baseUrl("assets/css/style-responsive.css");?> rel="stylesheet" type="text/css"/>
	<link href=<?php echo $this->baseUrl("assets/css/themes/default.css");?> rel="stylesheet" type="text/css" id="style_color"/>
	<link href=<?php echo $this->baseUrl("assets/plugins/uniform/css/uniform.default.css");?> rel="stylesheet" type="text/css"/>
	<!-- END GLOBAL MANDATORY STYLES -->
	<!-- BEGIN PAGE LEVEL STYLES -->
	<link href=<?php echo $this->baseUrl("assets/css/pages/lock.css");?> rel="stylesheet" type="text/css"/>
	<!-- END PAGE LEVEL STYLES -->
	<link rel="shortcut icon" href="favicon.ico" />
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body>
	<div class="page-lock">
		<div class="page-logo">
			<a class="brand" href="index.html">
			<img style="width: 20%;" src="<?php echo $proprietarioSession->proprietario['logo'] != null ? $this->baseUrl("images/{$proprietarioSession->proprietario['logo']}") :  $this->baseUrl('images/erp_logo.png') ?>" alt="logo" />
			</a>
		</div>
		<div class="page-body">
			<img class="page-lock-img" src="<?php echo $this->baseUrl('images/profile.png')?>" alt="">
			<div class="page-lock-info">
				<h1><?php echo $this->user ? $this->user : "Amigo..."?></h1>
				<span style="font-size: small;"><?php echo $this->block ? "Sistema Bloqueado" : "Sua sessão expirou e sua última ação não pode ser executada para sua segurança. Revalide suas credenciais e voltará de onde parou."?></span>
				<form class="form-search" method="POST" action="<?php echo $this->baseUrl("auth/index/login/")?>">
					<div class="input-append">
						<?php echo $this->formHidden("cpf",$this->cpf_cnpj)?>
						<?php echo $this->url ? $this->formHidden("redirect", $this->url) : ""?>
						<?php echo $this->idUser ? $this->formHidden("idUser", $this->idUser) : ""?>
						<?php echo $this->formPassword("password",null, array("class"=>"m-wrap", "placeholder" => "senha"))?>
						<button type="submit" class="btn blue icn-only"><i class="m-icon-swapright m-icon-white"></i></button>
					</div>
					<div class="relogin">
						<span><a href="<?php echo $this->baseUrl('auth/index/logout')?>">Não sou <?php echo $this->user ? $this->user : "eu"?>.</a>&nbsp;
							<a href="<?php echo $this->baseUrl('auth/index/logout')?>">Desejo sair do sistema.</a></span>
					</div>
				</form>
			</div>
		</div>
		<div class="page-footer">
			2013 &copy; Copyright Agtic - Todos os Direitos Reservados.
		</div>
	</div>	
	<!-- END COPYRIGHT -->
	<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
	<!-- BEGIN CORE PLUGINS -->
	<script src=<?php echo $this->baseUrl("assets/plugins/jquery-1.10.1.min.js");?> type="text/javascript"></script>
	<script src=<?php echo $this->baseUrl("assets/plugins/jquery-migrate-1.2.1.min.js");?> type="text/javascript"></script>
	<!-- IMPORTANT! Load jquery-ui-1.10.1.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
	<script src=<?php echo $this->baseUrl("assets/plugins/jquery-ui/jquery-ui-1.10.1.custom.min.js");?> type="text/javascript"></script>      
	<script src=<?php echo $this->baseUrl("assets/plugins/bootstrap/js/bootstrap.min.js");?> type="text/javascript"></script>
	<!--[if lt IE 9]>
	<script src=<?php echo $this->baseUrl("assets/plugins/excanvas.min.js");?>></script>
	<script src=<?php echo $this->baseUrl("assets/plugins/respond.min.js");?>></script>  
	<![endif]-->   
	<script src=<?php echo $this->baseUrl("assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js");?> type="text/javascript"></script>
	<script src=<?php echo $this->baseUrl("assets/plugins/jquery.blockui.min.js");?> type="text/javascript"></script>  
	<script src=<?php echo $this->baseUrl("assets/plugins/jquery.cookie.min.js");?> type="text/javascript"></script>
	<script src=<?php echo $this->baseUrl("assets/plugins/uniform/jquery.uniform.min.js");?> type="text/javascript" ></script>
	<!-- END CORE PLUGINS -->
	<!-- BEGIN PAGE LEVEL PLUGINS -->
	<script src=<?php echo $this->baseUrl("assets/plugins/jquery-validation/dist/jquery.validate.min.js");?> type="text/javascript"></script>
	<script src=<?php echo $this->baseUrl("assets/plugins/backstretch/jquery.backstretch.min.js");?> type="text/javascript"></script>
	<!-- END PAGE LEVEL PLUGINS -->
	<!-- BEGIN PAGE LEVEL SCRIPTS -->
	<script src=<?php echo $this->baseUrl("assets/scripts/app.js");?> type="text/javascript"></script>
	<script src=<?php echo $this->baseUrl("assets/scripts/login-soft.js");?> type="text/javascript"></script>      
	<!-- END PAGE LEVEL SCRIPTS --> 
	<script src="<?php echo $this->baseUrl('scripts/lib/jquery.meio.masks.js')?>" type="text/javascript"></script>   
	<script type="text/javascript" src=<?php echo $this->baseUrl('scripts/auth/index.login.js')?> ></script>
	<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
<script type="text/javascript">
	var time = 15*60000;
	
	setTimeout(function(){
		
		window.location.href="<?php echo $this->baseUrl("auth/index/logout");?>";	
		},time/*15 minutos na tela de travamento mata todas as sessoes*/);

</script>
</html>
