<style>
<!--
.dataTables_filter{
	float: right;
}

.dataTables_paginate{
	margin: 0px;
	float: right;
}

-->
</style>
<div class="row-fluid">
     <div class="span12">
	      <h3 class="page-title">
	       Registro de Unidades
	        <small> no sistema</small>
	      </h3>
     </div>
</div>
<div class="row-fluid">
	<div class="span12">
		<div class="portlet box grey">
			<div class="portlet-title">
				<div class="caption"><i class="icon-wrench"></i>Unidades</div>
				<div class="tools">
                    <a href="javascript:;" class="collapse"></a>
                </div>
                <div class="actions">
									<a class="btn cadastro-link" href="#"><i class="icon-pencil"></i> Novo </a>
								</div>
			</div>
			<div class="portlet-body flip-scroll">
				<div id="sample_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
					<table class="table-bordered table-striped table-condensed flip-content" id="perfisTable">
						<thead class="flip-content">
							<tr>
								<th class="hidden-480">Código</th>
					            <th class="hidden-480">Nome</th>
					            <th class="hidden-480">Usuario</th>
					            <th class="hidden-480">Data</th>
					            <th style="width: 45px;" class="hidden-480 action">Ação</th>
							</tr>
						</thead>

						<tbody>
							<?php if (count($this->unidadeList) > 0):?>
				        <?php foreach ($this->unidadeList as $unidade):?>
			            <tr class="odd gradeX">
			                <td class="hidden-480" style="width:30px"><?php echo $unidade->id_tipo_unidade; ?></td>
			                <td><?php echo $unidade->nome; ?></td>
			                <td class="hidden-480"><?php echo $unidade->getUser() ? $unidade->getUser()->getEmpresa()->nome_razao : "Anônimo"; ?></td>
			                <td class="hidden-480"  style="width:150px"><?php echo $this->dateHour($unidade->dt_criacao); ?></td>
			                <td class="acoes">
			                    <a class="editar-link" titulo="<?php echo $unidade->nome; ?>" value="<?php echo $unidade->id_tipo_unidade;?>" href="#">
			                        <img title="Editar" data-tooltip src="<?php echo $this->baseUrl('images/edit.png')?>"/>
			                    </a>
			                    <a class="deleteMoldal" value="<?php echo $unidade->id_tipo_unidade; ?>" href="#">
			                        <img title="Excluir" data-tooltip src="<?php echo $this->baseUrl('images/delete.png')?>"/>
			                    </a>
			                </td>
			            </tr>
				        <?php endforeach;?>
					<?php endif;?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="dialog_delete" style="display: none;">
	<p>Deseja realmente excluir a unidades: <span id ="valueDelete"></span></p>
</div>
<div class="dialog_cadastro" style="display: none;">
  <form class="form-cadastro" style="margin:0 !important;">
  	<label>Nome</label>
    <?php echo $this->formText('nome',null, array('style'=> 'width: 410px;'));?>
	</form>
						
</div>
<script type="text/javascript">

 $('#perfisTable').dataTable({
     "aLengthMenu": [
         [30, 50, 100, -1],
         [30, 50, 100, "All"] // change per page values here
     ],
     // set the initial value
     "iDisplayLength": 30,
     "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
     "sPaginationType": "bootstrap",
     "oLanguage": {
         "sProcessing": "Aguarde enquanto os dados são carregados ...",
         "sLengthMenu": "Mostrar _MENU_ registros",
         "sZeroRecords": "Não foram encontrados resultados",
         "sInfoEmpty": "Mostrando de 0 até 0 de 0 registros",
         "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
         "sInfoFiltered": "",
         "sSearch": "Procurar",
         "oPaginate": {
            "sFirst":    "Primeiro",
            "sPrevious": "Anterior",
            "sNext":     "Próximo",
            "sLast":     "Último"
         }
      },
     "aoColumnDefs": [{
             'bSortable': true,
             'aTargets': [0]
         }
     ]
 });
</script>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/sis/tipounidade.grid.js')?>"></script>