<link rel="stylesheet" href="<?php echo $this->baseUrl('assets/plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css');?>" />
<div class="row-fluid" style="margin-bottom: 20px;"></div>
<div class="row-fluid">
	<div class="portlet box darkorange">
		<div class="portlet-title">
			<div class="caption"><i class="fa fa-reorder"></i>Config. Escala</div>
			<div class="tools">
				<a href="javascript:;" class="collapse"></a>
			</div>
			<div class="actions">
			</div>
		</div>
		<div class="portlet-body form">
			<form action="#" class="form-horizontal" id="form_agrupador" method="post">
				<div class="row-fluid">
					<div class="span6">
						<div class="control-group">
							<label class="control-label">Código</label>
							<div class="controls">
								<?php echo $this->formText('id_rh_escala', $this->vo->id_rh_escala, array('style' => 'width: 90px', 'disable' => 'disable'))?>
								<?php echo $this->formHidden('id_rh_escala', $this->vo->id_rh_escala)?>
							</div>
						</div>
					</div>					
				</div>
				<div class="row-fluid">
					<div class="span6">
						<div class="control-group">
							<label class="control-label" id="labelCliente">Descrição <span style="color: red">*</span></label>
							<div class="controls">
              	<?php echo $this->formText("descricao",$this->vo->descricao, array("class" => "span12"));?>
							</div>
						</div>
					</div>
					<div class="span6">
						<div class="control-group">
							<label class="control-label" id="labelCliente">Revezamento PPP</label>
							<div class="controls">
              	<?php echo $this->formText("revezamento",$this->vo->revezamento, array("class" => "span12"));?>
							</div>
						</div>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span4">
						<div class="control-group">
							<label class="control-label">Total Trabalhado</label>
							<div class="controls"><?php echo $this->formText('dias_trabalhado', $this->vo->dias_trabalhado, array('style' => 'width: 90px'))?></div>
						</div>
					</div>
					<div class="span4">
						<div class="control-group">
							<label class="control-label">Dias Trabalhado por</label>
							<div class="controls"><?php echo $this->formText('dias_trabalho', $this->vo->dias_trabalho, array('style' => 'width: 90px'))?></div>
						</div>
					</div>
					<div class="span4">
						<div class="control-group">
							<label class="control-label">Dias descansados.</label>
							<div class="controls"><?php echo $this->formText('dias_folga', $this->vo->dias_folga, array('style' => 'width: 90px'))?></div>
						</div>
					</div>
				</div>
				<div class="form-actions">
					<a href="<?php echo $this->baseUrl('rh/escala/grid'); ?>" class="btn button-previous" style="display: inline-block;">
						<i class="m-icon-swapleft"></i> Voltar 
					</a>
          <button class="btn green" type="submit">
          	Salvar
        	</button>
				</div>
			</form>
		</div>
	</div>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js');?>"></script>
