<?php
    /**
     * formulario de grupo geografico
    */
?>
<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Cadastro
			 <small> de grupo geográfico</small>
		</h3>
	</div>
</div>
<div class="row-fluid">
	<div class="portlet box grey">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder"></i> Formulário</div>
			<div class="tools">
				<a href="javascript:;" class="collapse"></a>
			</div>
		</div>
	<div class="portlet-body form">
        	<form method="post"  class="form-horizontal" id="form_resource">
                  <?php echo $this->formHidden('id_grupo_geografico', $this->vo->id_grupo_geografico);?>
                  <div class="row-fluid">
                      <div class="span6">
                          <div class="control-group">
	                          <label class=" control-label"><?php echo $this->translate('Nome')?><span class="required">*</span></label>
	                          <div class="controls">
	                          	<?php echo $this->formText('nome',$this->vo->nome, array('class' => 'span10'));?>
	                          </div>
                          </div>
                      </div>
                  </div>
                  <div class="row-fluid">
	                  <div class="span12">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Descrição')?></label>
	                          <div class="controls">
	                          	<?php echo $this->formTextarea('descricao',$this->vo->descricao, array('class'=> 'span8', 'rows' => 3));?>
	                          </div>
                          </div>
                      </div>
                  </div>
                  <div class="form-actions">
                      <button type="submit" class="btn blue"><i class="icon-ok"></i> Salvar</button>
                      <a href="<?php echo $this->baseUrl('sis/grupo-geografico/grid')?>" class="btn" >Voltar</a>
                  </div>
        	</form>
        </div>
    </div>
</div>
