<style>
<!--
.dataTables_filter{
	float: right;
}

.dataTables_paginate{
	margin: 0px;
	float: right;
}

-->
</style>
<div class="row-fluid">
     <div class="span12">
	      <h3 class="page-title">
	       Grupo
	        <small> geográfico</small>
	      </h3>
     </div>
</div>
<div class="row-fluid">
	<div class="span12">
		<div class="portlet box green">
			<div class="portlet-title">
				<div class="caption"><i class="icon-wrench"></i>Ramo de atividades registrados</div>
				<div class="tools">
                    <a href="javascript:;" class="collapse"></a>
                </div>
				<div class="actions">
					<a class="btn blue " href="<?php echo $this->baseUrl("sis/segmento/form") ?>"><i class="icon-pencil"></i> Novo </a>
				</div>
			</div>
			<div class="portlet-body flip-scroll">
				<div id="sample_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
					<table class="table-bordered table-striped table-condensed flip-content" id="grupogeoGraficoTable">
						<thead class="flip-content">
							<tr>
								<th>Código</th>
					            <th>Nome</th>
					            <th class="hidden-480">Descrição</th>
					            <th style="width: 45px;" class="action">Ação</th>
							</tr>
						</thead>

						<tbody>
							<?php if (count($this->grupoGeograficoList) > 0):?>
				        <?php foreach ($this->grupoGeograficoList as $grupoGeografico):?>
				            <tr class="odd gradeX">
				                <td style="width:30px"><?php echo $grupoGeografico->id_grupo_geografico?></td>
				                <td><?php echo $grupoGeografico->nome;?></td>
				                <td><?php echo $grupoGeografico->descricao;?></td>
				                <td class="acoes">
				                    <a href="<?php echo $this->baseUrl("sis/grupo-geografico/form/id_grupo_geografico/{$grupoGeografico->id_grupo_geografico}")?>">
				                        <img title="Editar" data-tooltip src="<?php echo $this->baseUrl('images/edit.png')?>"/>
				                    </a>
				                    <a class="deleteMoldal" name = "<?php echo $grupoGeografico->nome;?>" value = "<?php echo $grupoGeografico->id_grupo_geografico?>" href="#">
				                        <img title="Excluir" data-tooltip src="<?php echo $this->baseUrl('images/delete.png')?>"/>
				                    </a>
				                </td>
				            </tr>
				        <?php endforeach;?>
					<?php endif;?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="dialog_delete" style="display: none;">
	<p>Deseja realmente excluir este grupo geofráfico: <span id ="valueDelete"></span></p>
</div>
<script type="text/javascript">

 $('#grupogeoGraficoTable').dataTable({
     "aLengthMenu": [
         [30, 50, 100, -1],
         [30, 50, 100, "All"] // change per page values here
     ],
     // set the initial value
     "iDisplayLength": 30,
     "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
     "sPaginationType": "bootstrap",
     "oLanguage": {
         "sProcessing": "Aguarde enquanto os dados são carregados ...",
         "sLengthMenu": "Mostrar _MENU_ registros",
         "sZeroRecords": "Não foram encontrados resultados",
         "sInfoEmpty": "Mostrando de 0 até 0 de 0 registros",
         "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
         "sInfoFiltered": "",
         "sSearch": "Procurar",
         "oPaginate": {
            "sFirst":    "Primeiro",
            "sPrevious": "Anterior",
            "sNext":     "Próximo",
            "sLast":     "Último"
         }
      },
     "aoColumnDefs": [{
             'bSortable': true,
             'aTargets': [0]
         }
     ]
 });
</script>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/sis/grupo-geografico.grid.js')?>"></script>