<?php
    /**
     * formulario de ramo de atividade
    */
?>
<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Cadastro
			 <small> de Ramo de atividade</small>
		</h3>
	</div>
</div>
<div class="row-fluid">
	<div class="portlet box green">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder"></i> Formulário</div>
			<div class="tools">
				<a href="javascript:;" class="collapse"></a>
			</div>
		</div>
		<div class="portlet-body form">
	        <form method="post"  class="form-horizontal" id="form_menu">
				<?php echo $this->formHidden('seg_id', $this->vo->seg_id);?>
				<div class="row-fluid">
					<div class="span8">
						<div class="control-group">
								<label class=" control-label"><?php echo $this->translate('Nome/Descrição')?><span class="required">*</span></label>
		                    <div class="controls">
								<?php echo $this->formText('seg_descricacao',$this->vo->seg_descricacao, array('class' => 'span10'));?>
							</div>
						</div>
					</div>
				</div>
				<div class="form-actions">
	                <button type="submit" class="btn blue"><i class="icon-ok"></i> Salvar</button>
	            	<a href="<?php echo $this->baseUrl('sis/segmento/grid')?>" class="btn" >Voltar</a>
	        	</div>
	        </form>
		</div>
    </div>
</div>