<?php
    /**
     * formulario do controller transportador para cadastrar e editar as empresas do tipo transportador e sendo redirecionado para a pagina da grid
    */
?>
<div class="row">
    <div class="large-12 columns">
        <form method="post">
              <fieldset>
                  <legend><?php echo $this->translate('Formulário de Empresa Transportadora')?></legend>
                  <?php echo $this->formHidden('id_item', $this->vo->id_transp_empresa);?>
                  <div class="row">
                      <div class="large-4 columns">
                          <label><?php echo $this->translate('Razão social')?></label>
                          <?php echo $this->formText('nome',$this->vo->razao);?>
                      </div>
                      <div class="large-4 columns">
                          <label><?php echo $this->translate('Nome fantasia')?></label>
                          <?php echo $this->formText('nome',$this->vo->fantasia);?>
                      </div>
                      <div class="large-2 columns">
                          <label><?php echo $this->translate('CNPJ')?></label>
                          <?php echo $this->formText('nome',$this->vo->cnpj);?>
                      </div>
                      <div class="small-1 columns">
                      </div>
                  </div>
                  <div class="row">
                      <div class="large-2 columns">
                          <label><?php echo $this->translate('Inscrição Estadual')?></label>
                          <?php echo $this->formText('nome',$this->vo->estadual);?>
                      </div>
                      <div class="large-4 columns">
                          <label><?php echo $this->translate('Endereço')?></label>
                          <?php echo $this->formText('nome',$this->vo->fantasia);?>
                      </div>
                      <div class="large-1 columns">
                          <label><?php echo $this->translate('Estado')?></label>
                          <?php echo $this->formSelect('estado', null, null, $this->comboEstado);?>
                      </div>
                      <div class="large-2 columns">
                          <label><?php echo $this->translate('Cidade')?></label>
                          <?php echo $this->formSelect('cidade', $this->vo->id_cidade, null, array('---- Selecione ----'));?>
                      </div>
                      <div class="small-1 columns">
                      </div>
                  </div>

                  <div class="row">
                      <div class="large-12 columns">
                          <input type="submit" value="Salvar" class="button radius success" style="float:right" />
                          <a href="<?php echo $this->baseUrl('empresa/transportador/grid')?>" class="button radius alert"  style="float:right; margin-right: 20px;">Voltar</a>
                      </div>
                  </div>
              </fieldset>
        </form>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/empresa/transportador.form.js')?>"></script>
