<table class="table-bordered table-striped table-condensed flip-content datatable-consultor" style="width: 100%">
    <thead class="flip-content">
        <tr>
            <th>Nome_corporativo</th>
            <th>Tipo de comissão</th>
            <th>Comissão</th>
            <th>valor máximo</th>
            <th>Quantidade máxima</th>
            <th style="width: 60px">Ação</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->listCampanhaConsultor as $campanhaConsultor):?>
            <tr class="odd gradeX">
                <td><?php echo $campanhaConsultor->getCorporativo()->nome_razao ?></td>
                <td><?php echo $campanhaConsultor->id_tp_comissao ?$campanhaConsultor->getTipoComissao()->nome : "" ?></td>
                <td><?php echo $campanhaConsultor->porcent_comissao ? $campanhaConsultor->porcent_comissao."%": "" ?></td>
                <td style="text-align: right;"><?php echo  $campanhaConsultor->vl_max_compra ? $this->formatDecimal($campanhaConsultor->vl_max_compra): "" ?></td>
                <td><?php echo $campanhaConsultor->qtd_compra ?></td>
                <td>
                    <a href="<?php echo $this->baseUrl('compra/campanha-corporativo/form/id_campanha_corporativa/'.$campanhaConsultor->id_campanha_corporativa)?>" id_campanha_corporativa="<?php echo $campanhaConsultor->id_campanha_corporativa?>" class="edit_consultor" >
                        <img src="<?php echo $this->baseUrl('images/edit.png')?>" data-tooltip title="Editar consultor">
                    </a>
                    <a href="<?php echo $this->baseUrl('compra/campanha-corporativo/delete/id_campanha_corporativa/'.$campanhaConsultor->id_campanha_corporativa)?>" class="delete_consultor" >
                        <img src="<?php echo $this->baseUrl('images/delete.png')?>" data-tooltip title="Excluir consultor">
                    </a>
                </td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>
<script>
$(document).ready(function(){

    $('.datatable-consultor').dataTable({
        "aLengthMenu": [
            [30, 50, 100, -1],
            [30, 50, 100, "All"] // change per page values here
        ],
        // set the initial value
        "iDisplayLength": 30,
        "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
        "sPaginationType": "bootstrap",
        "oLanguage": {
            "sProcessing": "Aguarde enquanto os dados são carregados ...",
            "sLengthMenu": "Mostrar _MENU_ registros",
            "sZeroRecords": "Não foram encontrados resultados",
            "sInfoEmpty": "Mostrando de 0 até 0 de 0 registros",
            "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
            "sInfoFiltered": "",
            "sSearch": "Procurar",
            "oPaginate": {
               "sFirst":    "Primeiro",
               "sPrevious": "Anterior",
               "sNext":     "Próximo",
               "sLast":     "Último"
            }
         },
        "aoColumnDefs": [{
                'bSortable': true,
                'aTargets': [0]
            }
        ],
    });
});
</script>