<style>
<!--
.dataTables_filter{
	float: right;
}

.dataTables_paginate{
	margin: 0px;
	float: right;
}

-->
</style>
<div class="row-fluid">
     <div class="span12">
	      <h3 class="page-title">
	       Registro
	        <small> da campanha</small>
	      </h3>
     </div>
</div>
<div class="row-fluid">
	<div class="span12">
		<div class="portlet box green">
			<div class="portlet-title">
				<div class="caption"><i class=" icon-bookmark"></i>Campanha</div>
				<div class="tools">
                    <a href="javascript:;" class="collapse"></a>
                </div>
				<div class="actions">
					<a class="btn blue" href="<?php echo $this->baseUrl('compra/campanha/form')?>"><i class="icon-pencil"></i> Nova campanha </a>
				</div>
			</div>
			<div class="portlet-body flip-scroll">
				<div id="sample_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
					<table class="table-bordered table-striped table-condensed flip-content" id="datatables">
                        <thead class="flip-content">
                            <tr>
                                <th>Nome</th>
                                <th style="width: 110px;">data inicio</th>
                                <th style="width: 110px;">data fim</th>
                                <th style="width: 110px;">Valor minimo</th>
                                <th style="width: 110px;">Valor máximo</th>
                                <th style="width: 60px">Ação</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->listCampanha as $campanha):?>
                                <tr class="odd gradeX">
                                    <td><?php echo $campanha['nome']?></td>
                                    <td style="text-align: center;"><?php echo $this->date($campanha['dt_inicio']) ?></td>
                                    <td style="text-align: center;"><?php echo $this->date($campanha['dt_fim'])?></td>
                                    <td style="text-align: right;"><?php echo $this->formatDecimal($campanha['vl_min_compra']);?></td>
                                    <td style="text-align: right;"><?php echo $this->formatDecimal($campanha['vl_max_compra']);?></td>
                                    <td>
                                        <a href="<?php echo $this->baseUrl('compra/campanha/form/id_campanha/'.$campanha['id_campanha'])?>">
                                            <img src="<?php echo $this->baseUrl('images/edit.png')?>" data-tooltip title="Editar">
                                        </a>
                                        <a href="<?php echo $this->baseUrl('compra/campanha/delete/id_campanha/'.$campanha['id_campanha'])?>" class="delete">
                                            <img src="<?php echo $this->baseUrl('images/delete.png')?>" data-tooltip title="Remover">
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach;?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="<?php echo $this->baseUrl('scripts/compra/campanha.grid.js')?>"></script>