<style>
<!--
.ui-dialog-titlebar-close {
  display: none;
}
.dataTables_filter{
	float: right;
}

.dataTables_paginate{
	margin: 0px;
	float: right;
}
a i.acao{
	padding: 5px;
	color: #000;
	cursor: pointer;
}
a i.acao:HOVER{
	text-decoration: none;
}
-->
</style>
<link href="<?php echo $this->baseUrl('assets/plugins/bootstrap-editable/bootstrap-editable/css/bootstrap-editable.css')?>" rel="stylesheet" type="text/css" media="screen"/>
<link href="<?php echo $this->baseUrl('assets/plugins/bootstrap-editable/inputs-ext/address/address.css')?>" rel="stylesheet" type="text/css" media="screen"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('assets/plugins/select2/select2_metro.css')?>" />
<div style="margin-top: 20px"></div>
<div class="row-fluid">
	<div class="portlet box darkorange" id="form_wizard_1">
		<div class="portlet-title">
			<div class="caption"><i class="fa fa-reorder"></i>Folha de Pagamento</div>
			<div class="tools">
				<a href="javascript:;" class="collapse"></a>
			</div>
			<div class="actions">
				<a class="btn" href="<?php echo $this->baseUrl("rh/folha-de-pagamento/grid") ?>">Listar Folha de Pagamento</a>
				<a class="btn" href="<?php echo $this->baseUrl("rh/folha-de-pagamento/form") ?>">Nova Folha de Pagamento</a>
			</div>
		</div>
		<div class="portlet-body form">
			<form action="#" class="form-horizontal" id="form_agrupador" method="post" novalidate="novalidate">
				<div class="form-wizard">
					<div class="navbar steps">
						<div class="navbar-inner">
							<ul class="row-fluid nav nav-pills">
								<li class="span3">
									<a href="#tab1" data-toggle="tab" class="step ">
									<span class="number">1</span>
									<span class="desc"><i class="icon-ok"></i> Funcionario</span>   
									</a>
								</li>
								<li class="span3">
									<a href="#tab2" data-toggle="tab" class="step">
									<span class="number">2</span>
									<span class="desc"><i class="icon-ok"></i> Gerencial</span>   
									</a>
								</li>
							</ul>
						</div>
					</div>
					<div id="bar" class="progress progress-success progress-striped">
						<div class="bar"></div>
					</div>
					<div class="tab-content">
						<div class="tab-pane" id="tab1">
							<div class="row-fluid">
								<div class="span6">
									<div class="control-group">
										<label class="control-label" id="labelCliente">Funcionario <span style="color: red">*</span></label>
										<div class="controls">
                 			<?php echo $this->formSelect('id_empresa',$this->vo->id_empresa, array('class' => 'span12'), $this->comboPessoa);?>
                 			<?php echo $this->formHidden("tss_id",$this->vo->tss_id);?>
                 			<?php echo $this->formHidden("tse_id",$this->vo->tse_id);?>
                 			<?php echo $this->formHidden("id_rh_folha_de_pagamento",$this->vo->id_rh_folha_de_pagamento);?>
                 			<?php $workspaceSession = new Zend_Session_Namespace('workspace');?>
				              <?php echo $this->vo->id_rh_folha_de_pagamento ? $this->formHidden("id_workspace",$this->vo->id_workspace) : $this->formHidden("id_workspace",$workspaceSession->id_workspace); ?>
										</div>
									</div>
								</div>
								<!--/span-->
								<div class="span6 ">
									<div class="control-group ">
										<label class="control-label" for="">Referente ao mês <span style="color: red">*</span></label>
										<div class="controls">
											<?php echo $this->formText('dt_competencia',$this->date($this->vo->dt_competencia), array("class" => "datepickerMonth"));?>
										</div>
									</div>
								</div>
								<!--/span-->
							</div>
							<div class="row-fluid">
							
								<div class="span3 ">
									<div class="control-group ">
										<label class="control-label" for="">Tipo de folha<span style="color: red">*</span></label>
										<div class="controls">
											<?php echo $this->formSelect('id_tp_pagamento',$this->vo->id_tp_pagamento, array('class' => 'span12'), $this->comboTpPagamento);?>
										</div>
									</div>
								</div>
								<div class="span3 ">
									<div class="control-group ">
										<label class="control-label" for="">Moeda</label>
										<div class="controls">
											<?php if (!$this->vo->moe_id){
							                        	$this->vo->moe_id = 1;//real
							                        }?>
						          <?php echo $this->formSelect('moe_id',$this->vo->moe_id,array('class' =>'span12'),array("" => "Selecione")+$this->comboMoedas);?>
										</div>
									</div>
								</div>
								<!--/span-->
								<div class="span3 ">
									<div class="control-group ">
										<label class="control-label" for="">A pagar</label>
										<div class="controls">
											<?php echo $this->formText('apagar', $this->formatDecimal($this->pagar == 0 ? "0.00" : $this->pagar), array('alt' => 'decimal','class' =>'decimal dissable span12', 'disabled' => '')); ?>
										</div>
									</div>
								</div>
								<div class="span3 ">
									<div class="control-group ">
										<label class="control-label" for="">A receber</label>
										<div class="controls">
											<?php echo $this->formText('apagar', $this->formatDecimal($this->receber == 0 ? "0.00" : $this->receber), array('alt' => 'decimal','class' =>'decimal dissable span12', 'disabled' => '')); ?>
										</div>
									</div>
								</div>
								<!--/span-->
							</div>
							<div class="row-fluid">
								<div class="span6">
									<div class="control-group">
										<label class="control-label" for="">Descrição <span style="color: red">*</span></label>
										<div class="controls">
											<?php echo $this->formTextarea('descricao',$this->vo->descricao,array( 'rows' => 4, 'cols' => 20, 'style' => 'height: 100px;',"class" => "span12" ));?>
										</div>
									</div>
								</div>
								<div class="span6">
									<div class="control-group">
										<label class="control-label" for="">Observação</label>
										<div class="controls">
											<?php echo $this->formTextarea('observacao',$this->vo->observacao,array( 'rows' => 4, 'cols' => 20, 'style' => 'height: 100px;',"class" => "span12" ));?>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="tab-pane" id="tab2">
            	<h3 class="block">Gerencial</h3>
              	<div class="row-fluid">
									<div class="span6">
										<div class="control-group">
											<label class="control-label" for="">Plano de Contas</label>
											<div class="controls">
												<?php echo $this->formSelect('plc_id',$this->vo->plc_id,array("class" => "span6"),array("" => "Selecione"));?>
	       		          	<?php if ($this->vo->id_rh_folha_de_pagamento):?>
	       		          		<span style="display: none;" id ="plano_conta_selected"  value = "<?php echo $this->planoContaSaved['plc_id']?>" name = "<?php echo $this->planoContaSaved['plc_descricao']?>"  ></span>
	       		          	<?php endif;?>
											</div>
										</div>
									</div>
									<div class="span6">
										<div class="control-group">
											<label class="control-label" for="">Centro de Custos</label>
											<div class="controls">
												<?php echo $this->formSelect('cec_id',$this->vo->cec_id,array("class" => "span6"),array("" => "Selecione")+$this->comboCentroCusto);?>
											</div>
										</div>
									</div>
								</div>
								<div class="row-fluid">
									<div class="span6">
										<div class="control-group">
											<label class="control-label" for="">Grupo de Operação</label>
											<div class="controls">
												<?php echo $this->formSelect('ope_id',$this->vo->ope_id,array("class" => "span6"),array("" => "Selecione")+$this->comboGrupoOperacao);?>
											</div>
										</div>
									</div>
									<div class="span6">
										<div class="control-group">
											<label class="control-label" for="">Faturado (contra/por)</label>
											<div class="controls">
												<?php echo $this->formSelect('grupo_id',$this->vo->grupo_id,array("class" => "span6"),array("" => "Selecione")+$this->comboEmpresasGrupo);?>
											</div>
										</div>
									</div>
								</div>
						
						</div>
					</div>
					<div class="form-actions clearfix">
						<a href="javascript:;" class="btn button-previous" style="display: inline-block;">
							<i class="m-icon-swapleft"></i> Anterior 
						</a>
						<a href="javascript:;" class="btn blue button-next">
							Próximo <i class="m-icon-swapright m-icon-white"></i>
						</a>
			            <button class="btn green" type="submit">
			            	Salvar
			            </button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<?php if ($this->vo->id_rh_folha_de_pagamento) : ?>
<div class="row-fluid">
	<a href="#" id="migra-tk" class="icon-btn span3" data-competencia='<?php echo $this->date($this->vo->dt_competencia);?>' data-corporativo='<?php echo $this->vo->id_empresa;?>'>
		<i class="icon-group"></i>
		<div>Migrar TK</div>
	</a>
</div>
<div class="row-fluid">
	<div class="portlet box red" id="form_wizard_1">
		<div class="portlet-title">
			<div class="caption"><i class="fa fa-reorder"></i>Ticket de Provento</div>
			<div class="tools">
				<a href="javascript:;" class="collapse"></a>
			</div>
			<div class="actions">
				<a value="<?php echo $this->vo->tss_id;?>" tipoModelo="1" class="btn tk-link">Novo Ticket</a>
			</div>
		</div>
		<div class="portlet-body">
			<div class="grid-itens-<?php echo $this->vo->tss_id;?>">
			</div>
		</div>
	</div>
</div>
<div class="row-fluid">
	<div class="portlet box green" id="form_wizard_1">
		<div class="portlet-title">
			<div class="caption"><i class="fa fa-reorder"></i>Ticket de Desconto</div>
			<div class="tools">
				<a href="javascript:;" class="collapse"></a>
			</div>
			<div class="actions">
				<a value="<?php echo $this->vo->tse_id;?>" tipoModelo="2" class="btn tk-link">Novo Ticket</a>
			</div>
		</div>
		<div class="portlet-body">
			<div class="grid-itens-<?php echo $this->vo->tse_id;?>">
			</div>
		</div>
	</div>
</div>
<?php endif; ?>

<div class="dialog_tk" style="display: none">
	<form class="form-tk">
		<div class="row-fluid">
			<div class="span6 ">
				<div class="control-group ">
					<label class="control-label" for="">Modelo Sintetico <span style="color: red">*</span></label>
					<div class="controls">
						<?php echo $this->formText("fin_descricao",null, array("class" => "span10"));?>
					</div>
				</div>
			</div>
			<div class="span6 referencia-hide" style="display: none;">
				<div class="control-group ">
					<label class="control-label " for="">Referência por</label>
					<div class="controls referencia">
					</div>
				</div>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span4 ">
				<div class="control-group ">
					<label class="control-label" for="">Valor Total <span style="color: red">*</span></label>
					<div class="controls">
						<?php echo $this->formText("fin_valor",null, array("alt" => "decimal" ,"class" => "decimal span12"));?>
						<?php echo $this->formHidden("id_agrupador_financeiro")?>
						<?php echo $this->formHidden("fin_id")?>
						<?php echo $this->formHidden('fin_competencia',$this->date($this->vo->dt_competencia));?>
						<?php echo $this->formHidden('empresa_sacado_selected', $this->vo->id_empresa)?>
						<?php echo $this->formHidden('id_rh_modelo_sintetico')?>
						<?php echo $this->formHidden("rh",'rh')?>
						<?php echo $this->formHidden("tipoModelo")?>
						<?php $workspaceSession = new Zend_Session_Namespace('workspace');?>
				              <?php echo $this->vo->id_rh_folha_de_pagamento ? $this->formHidden("id_workspace",$this->vo->id_workspace) : $this->formHidden("id_workspace",$workspaceSession->id_workspace); ?>
					</div>
				</div>
			</div>
			<div class="span4 ">
				<div class="control-group ">
					<label class="control-label" for="">Valor Unitário</label>
					<div class="controls">
						<?php echo $this->formText("vl_base",null, array("alt" => "decimal" ,"class" => "decimal span12"));?>
					</div>
				</div>
			</div>
			<div class="span4 ">
				<div class="control-group ">
					<label class="control-label" for="">Referência</label>
					<div class="controls">
						<?php echo $this->formText("referencia",null, array("class" => "span12"));?>
					</div>
				</div>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span4 ">
				<div class="control-group ">
					<label class="control-label" for="">Emissão</label>
					<div class="controls">
						<?php echo $this->formText('fin_emissao',null, array("class" => "datepicker span12 date", 'alt' => 'date'));?>
					</div>
				</div>
			</div>
			<div class="span4 ">
				<div class="control-group ">
					<label class="control-label" for="">Vencimento</label>
					<div class="controls">
						<?php echo $this->formText('fin_vencimento',null, array("class" => "datepicker span12 date", 'alt' => 'date'));?>
					</div>
				</div>
			</div>
		</div>
	</form>
</div>

<div id="dialog_migrar" style="display: none;">
	<div id="conteudo-migrar">
		<div class="alert alert-info">
			<button class="close" data-dismiss="alert"></button>
			Selecione a TK que queira migrar! 
		</div>
		<table class="table table-hover">
			<thead class="flip-content">
	                <tr>
	                    <th style="width: 40px">Código</th>
	                    <th>Descrição</th>
	                    <th>Emissão</th>
	                    <th>Valor</th>
	                </tr>
	            </thead>
	            <tbody>
	            <?php if (count($this->migra) > 0):?>
	            <?php $idAtributo = 0?>
	                <?php foreach ($this->migra as $financial):?>
	                    <tr class="id-migrar" data-tss="<?php echo $this->vo->tss_id?>" data-idTk="<?php echo $financial['fin_id']?>" style="cursor: pointer;" >
	                        <td style="text-align: center"><?php echo $financial['fin_id']?></td>
	                        <td><?php echo $financial['fin_descricao'] ?></td>
	                        <td><?php echo $this->date($financial['fin_emissao'], 'dd/MM/yyyy')?></td>
	                        <td style="text-align: right;"><?php echo $this->formatDecimal($financial['fin_valor']);?></td>
	                    </tr>
	                <?php endforeach;?>
	            <?php else:?>
	                    <tr>
	                        <td colspan="11" style="text-align: center">Não possui financeiro vinculado a este funcionario</td>
	                    </tr>
	            <?php endif;?>
	            </tbody>
			</tbody>
		</table>
	</div>
</div>

<div id="dialog_migra_cadastro" style="display: none;">
	<div class="row-fluid">
		<div class="span4">
			<div class="control-group ">
				<label class="control-label" for="">Modelo Sintetico <span style="color: red">*</span></label>
				<div class="controls">
					<?php echo $this->formText("fin_descricao_migra",null, array("class" => "span12"));?>
					<?php echo $this->formHidden('tss_migra')?>
					<?php echo $this->formHidden('idTk_migra')?>
					<?php echo $this->formHidden('id_rh_modelo_sintetico_migra')?>
				</div>
			</div>
		</div>
		<div class="span4 referencia-hide" style="display: none;">
			<div class="control-group ">
				<label class="control-label " for="">Referência por</label>
				<div class="controls referencia">
				</div>
			</div>
		</div>
		<div class="span4">
			<div class="control-group ">
				<label class="control-label" for="">Referência</label>
				<div class="controls">
					<?php echo $this->formText("referencia_migra",null, array("class" => "span12"));?>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="dialog_delete" style="display: none;">
	<p>Deseja realmente excluir este registro: <span id="valueDelete"></span></p>
</div>

<script type="text/javascript">
                        
	jQuery(document).ready(function() {       
	   // initiate layout and plugins
		$(this).GridItens(<?php echo $this->vo->tss_id;?>);
		$(this).GridItens(<?php echo $this->vo->tse_id;?>);
	});
</script>

<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('assets/plugins/jquery-multi-select/css/multi-select-metro.css')?>" />
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/jquery-validation/dist/jquery.validate.min.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/jquery-validation/dist/additional-methods.min.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/bootstrap-wizard/jquery.bootstrap.wizard.min.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/jquery-multi-select/js/jquery.multi-select.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/rh/folhadepagamento.form.js')?>"></script>
<!-- BEGIN X-EDITABLE PLUGIN-->
  <script src="<?php echo $this->baseUrl('assets/plugins/bootstrap-editable/bootstrap-editable/js/bootstrap-editable.min.js')?>" type="text/javascript"></script>
  <script src="<?php echo $this->baseUrl('assets/plugins/bootstrap-editable/inputs-ext/address/address.js')?>" type="text/javascript"></script>
  <script src="<?php echo $this->baseUrl('assets/plugins/bootstrap-editable/inputs-ext/wysihtml5/wysihtml5.js')?>" type="text/javascript"></script>
<!-- END X-EDITABLE PLUGIN-->
<!-- BEGIN SELECT2 PLUGIN-->
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/select2/select2.min.js')?>"></script>
<!-- END SELECT2 PLUGIN-->