<table border="0" cellspacing="2" style="width: 695px; border: 1px solid #000; font-size: 9" cellpadding="1">
    <tr>
        <td style="text-align: center;" colspan="2"><h3>RECIBO DE PAGAMENTO</h3></td>
    </tr>
    <tr>
        <td width="100">Empregador: </td><td><?php echo $this->sis->nome_empresa?></td>
    </tr>
    <tr>
        <td>Endereço: </td><td><?php echo $this->sis->end_proprietario?></td>
    </tr>
    <tr>
        <td>CNPJ: </td><td><?php echo $this->sis->cpf_cnpj?></td>
    </tr>
</table>
<table border="0" style="width: 695px; border: 1px solid #000; font-size: 9" cellpadding="1">
	<tr>
		<td width="50">Chapa</td>
		<td width="190">Nome</td>
		<td width="70">CBO</td>
		<td width="70">Data Pagto</td>
		<td width="60">Mês</td>
		<td width="255">Função</td>
	</tr>
	<tr>
		<td width="50"><?php echo $this->folha->getEmpresa()->id?></td>
		<td width="190"><?php echo $this->folha->getEmpresa()->nome_razao?></td>
		<td width="70"><?php echo $this->cbo->codigo?></td>
		<td width="70">
			<?php 
				$data = $this->ticket->fin_compensacao; 
				$data = new Zend_Date($data); 
				echo $data->toString('d/MM/yyyy');
			?>
		</td>
		<td width="60">
			<?php 
				$data = $this->folha->dt_competencia; 
				$data = new Zend_Date($data); 
				echo $data->toString('MM/yyyy');
			?>
		</td>
		<td width="255"><?php echo $this->cbo->nome?></td>
	</tr>
</table>
<table border="1" style="width: 695px; border: 1px solid #000; font-size: 9" cellpadding="1">
	<tr>
		<td width="50" style="text-align: center;">Código</td>
		<td width="405" style="text-align: center;">Descrição</td>
		<td width="80" style="text-align: center;">Referência</td>
		<td width="80" style="text-align: center;">Vencimentos</td>
		<td width="80" style="text-align: center;">Descontos</td>
	</tr>
	<tr>
		<td width="50" valign="top" style="text-align: center;height: 190px;"><?php echo $this->ticket->getModelo()->getModelo()->codigo?></td>
		<td width="405">
			<?php echo $this->ticket->fin_descricao?><br/>
		</td>
		<td width="80" style="text-align: center;"><?php echo $this->rel->referencia?></td>
		<td width="80" style="text-align: right;">
			<?php 
				if ($this->agrupado->tmv_id == 1) {
					echo $this->formatDecimal($this->ticket->fin_valor);
				}
			?>
		</td>
		<td width="80" style="text-align: right;">
			<?php 
				if ($this->agrupado->tmv_id == 2) {
					echo $this->formatDecimal($this->ticket->fin_valor);
				}
			?>
		</td>
	</tr>
	<tr>
		<td rowspan="2" colspan="3">
			<table cellpadding="3">
				<tr>
					<td style="text-align: center;">Data de Admissão: <?php echo $this->date($this->admissao->dt_admissao)?></td>
					<td style="text-align: center;">Período: 01/11/2013 a 20/11/2013</td>
				</tr>
				<tr>
					<td colspan="2" style="text-align: center;">Empregado, Queira atualizar seus dados cadastrais (PIS)</td>
				</tr>
			</table>
		</td>
		<td><span style="font-size: 8;">Total</span><br/><span style="text-align: right;">
			<?php 
				if ($this->agrupado->tmv_id == 1) {
					echo $this->formatDecimal($this->ticket->fin_valor);
				}
			?>
		</span></td>
		<td><span style="font-size: 8;">Total</span><br/><span style="text-align: right;">
			<?php 
				if ($this->agrupado->tmv_id == 2) {
					echo $this->formatDecimal($this->ticket->fin_valor);
				}
			?>
		</span></td>
	</tr>
	<tr>
		<td>Valor Líquido</td>
		<td style="text-align: right;"><?php echo $this->formatDecimal($this->ticket->fin_valor)?></td>
	</tr>
</table>
<table style="width: 695px; border: 1px solid #000; font-size: 9" cellpadding="1">
	<tr>
		<td style="text-align: center;">Salário Base</td>
		<td style="text-align: center;">Base do INSS</td>
		<td style="text-align: center;">Base do FGTS</td>
		<td style="text-align: center;">FGTS a Recolher</td>
		<td style="text-align: center;">Base do IRFF</td>
	</tr>
	<tr>
		<td style="text-align: center;"><?php echo $this->formatDecimal($this->funcional->salario)?></td>
		<td style="text-align: center;"><?php echo $this->formatDecimal($this->funcional->salario)?></td>
		<td style="text-align: center;"><?php echo $this->formatDecimal($this->funcional->salario)?></td>
		<td style="text-align: center;"><?php //echo $this->formatDecimal($this->funcional->salario)?></td>
		<td style="text-align: center;"><?php echo $this->formatDecimal($this->funcional->salario)?></td>
	</tr>
</table>
<br/>
<br/>
<table border="0" cellspacing="0" style="width: 695px; border: 1px solid #000; font-size: 9" cellpadding="3">
	<tr>
		<td colspan="2" style="text-align: center;">DECLARO TER RECEBIDO A IMPORTÂNCIA LÍQUIDA DISCRIMINADA NESTE RECIBO.</td>
	</tr>
	<tr>
		<td width="10"></td>
		<td width="150" style="border-bottom: 1px dashed #000;"><br/><br/></td>
		<td width="20"></td>
		<td width="505" style="border-bottom: 1px dashed #000;"></td>
		<td width="10"></td>
	</tr>
	<tr>
		<td width="10"></td>
		<td style="text-align: center;">Data</td>
		<td width="20"></td>
		<td style="text-align: center;">Assinatura</td>
		<td width="10"></td>
	</tr>
</table>
<div style="border-bottom: 1px dashed #000; width: 695px;"></div><br/>
<table border="0" cellspacing="2" style="width: 695px; border: 1px solid #000; font-size: 9" cellpadding="1">
    <tr>
        <td style="text-align: center;" colspan="2"><h3>RECIBO DE PAGAMENTO</h3></td>
    </tr>
    <tr>
        <td width="100">Empregador: </td><td><?php echo $this->sis->nome_empresa?></td>
    </tr>
    <tr>
        <td>Endereço: </td><td><?php echo $this->sis->end_proprietario?></td>
    </tr>
    <tr>
        <td>CNPJ: </td><td><?php echo $this->sis->cpf_cnpj?></td>
    </tr>
</table>
<table border="0" style="width: 695px; border: 1px solid #000; font-size: 9" cellpadding="1">
	<tr>
		<td width="50">Chapa</td>
		<td width="190">Nome</td>
		<td width="70">CBO</td>
		<td width="70">Data Pagto</td>
		<td width="60">Mês</td>
		<td width="255">Função</td>
	</tr>
	<tr>
		<td width="50"><?php echo $this->folha->getEmpresa()->id?></td>
		<td width="190"><?php echo $this->folha->getEmpresa()->nome_razao?></td>
		<td width="70"><?php echo $this->cbo->codigo?></td>
		<td width="70">
			<?php 
				$data = $this->ticket->fin_compensacao; 
				$data = new Zend_Date($data); 
				echo $data->toString('d/MM/yyyy');
			?>
		</td>
		<td width="60">
			<?php 
				$data = $this->folha->dt_competencia; 
				$data = new Zend_Date($data); 
				echo $data->toString('MM/yyyy');
			?>
		</td>
		<td width="255"><?php echo $this->cbo->nome?></td>
	</tr>
</table>
<table border="1" style="width: 695px; border: 1px solid #000; font-size: 9" cellpadding="1">
	<tr>
		<td width="50" style="text-align: center;">Código</td>
		<td width="405" style="text-align: center;">Descrição</td>
		<td width="80" style="text-align: center;">Referência</td>
		<td width="80" style="text-align: center;">Vencimentos</td>
		<td width="80" style="text-align: center;">Descontos</td>
	</tr>
	<tr>
		<td width="50" valign="top" style="text-align: center;height: 190px;"><?php echo $this->ticket->getModelo()->getModelo()->codigo?></td>
		<td width="405">
			<?php echo $this->ticket->fin_descricao?><br/>
		</td>
		<td width="80" style="text-align: center;"><?php echo $this->rel->referencia?></td>
		<td width="80" style="text-align: right;">
			<?php 
				if ($this->agrupado->tmv_id == 1) {
					echo $this->formatDecimal($this->ticket->fin_valor);
				}
			?>
		</td>
		<td width="80" style="text-align: right;">
			<?php 
				if ($this->agrupado->tmv_id == 2) {
					echo $this->formatDecimal($this->ticket->fin_valor);
				}
			?>
		</td>
	</tr>
	<tr>
		<td rowspan="2" colspan="3">
			<table cellpadding="3">
				<tr>
					<td style="text-align: center;">Data de Admissão: <?php echo $this->date($this->admissao->dt_admissao)?></td>
					<td style="text-align: center;">Período: 01/11/2013 a 20/11/2013</td>
				</tr>
				<tr>
					<td colspan="2" style="text-align: center;">Empregado, Queira atualizar seus dados cadastrais (PIS)</td>
				</tr>
			</table>
		</td>
		<td><span style="font-size: 8;">Total</span><br/><span style="text-align: right;">
			<?php 
				if ($this->agrupado->tmv_id == 1) {
					echo $this->formatDecimal($this->ticket->fin_valor);
				}
			?>
		</span></td>
		<td><span style="font-size: 8;">Total</span><br/><span style="text-align: right;">
			<?php 
				if ($this->agrupado->tmv_id == 2) {
					echo $this->formatDecimal($this->ticket->fin_valor);
				}
			?>
		</span></td>
	</tr>
	<tr>
		<td>Valor Líquido</td>
		<td style="text-align: right;"><?php echo $this->formatDecimal($this->ticket->fin_valor)?></td>
	</tr>
</table>
<table style="width: 695px; border: 1px solid #000; font-size: 9" cellpadding="1">
	<tr>
		<td style="text-align: center;">Salário Base</td>
		<td style="text-align: center;">Base do INSS</td>
		<td style="text-align: center;">Base do FGTS</td>
		<td style="text-align: center;">FGTS a Recolher</td>
		<td style="text-align: center;">Base do IRFF</td>
	</tr>
	<tr>
		<td style="text-align: center;"><?php echo $this->formatDecimal($this->funcional->salario)?></td>
		<td style="text-align: center;"><?php echo $this->formatDecimal($this->funcional->salario)?></td>
		<td style="text-align: center;"><?php echo $this->formatDecimal($this->funcional->salario)?></td>
		<td style="text-align: center;"><?php //echo $this->formatDecimal($this->funcional->salario)?></td>
		<td style="text-align: center;"><?php echo $this->formatDecimal($this->funcional->salario)?></td>
	</tr>
</table>
<br/>
<br/>
<table border="0" cellspacing="0" style="width: 695px; border: 1px solid #000; font-size: 9" cellpadding="3">
	<tr>
		<td colspan="2" style="text-align: center;">DECLARO TER RECEBIDO A IMPORTÂNCIA LÍQUIDA DISCRIMINADA NESTE RECIBO.</td>
	</tr>
	<tr>
		<td width="10"></td>
		<td width="150" style="border-bottom: 1px dashed #000;"><br/><br/></td>
		<td width="20"></td>
		<td width="505" style="border-bottom: 1px dashed #000;"></td>
		<td width="10"></td>
	</tr>
	<tr>
		<td width="10"></td>
		<td style="text-align: center;">Data</td>
		<td width="20"></td>
		<td style="text-align: center;">Assinatura</td>
		<td width="10"></td>
	</tr>
</table>