<style>
.datepicker table tr td.active.active {
    background-color: #4b8df8 !important;
}
</style>
<table style="width: 100%" class="table table-hover">
    <tr>
        <th style="text-align: center;">Código</th>
        <th>Entidade</th>
        <th>Descrição</th>
        <th>Conta</th>
        <th>Valor</th>
        <th>Emissão</th>
        <th>Vencimento</th>
        <th>Compensação</th>
        <th>Status</th>
        <th>Ação</th>
    </tr>
    <?php $valorTotal = 0;?>
    <?php $valorPago = 0;?>
    <?php if(count($this->financialList) > 0):?>
        <?php foreach ($this->financialList as $financial):?>
            <tr>
                <td style="text-align: center;"><?php echo $financial->fin_id ?></td>
                <td>
                    <a href="javascript:;" class="editable fin_empresa" data-name='fin_empresa' data-type="text" data-pk="<?php echo $financial->fin_id?>" data-url="financial/financial/form">
                        <?php echo $financial->getSacadoFinanceiro() && $financial->getSacadoFinanceiro()->getEmpresa()? $financial->getSacadoFinanceiro()->getEmpresa()->nome: null ?>
                    </a>
                </td>
                <td>
                    <a href="javascript:;" class="editable fin_descricao_ticket" data-name='fin_descricao' data-type="text" data-pk="<?php echo $financial->fin_id?>" data-url="financial/financial/form">
                        <?php echo $financial->fin_descricao?>
                    </a>
                </td>
                <td>
                    <a href="javascript:;" class="editable con_id" data-name='con_id' data-type="text" data-pk="<?php echo $financial->fin_id?>" data-url="financial/financial/form">
                        <?php echo $financial->getConta()?$financial->getConta()->con_codnome: null;?>
                    </a>
                </td>
                <td>
                    <a href="javascript:;" class="editable fin_valor" data-name='fin_valor' data-type="text" data-pk="<?php echo $financial->fin_id?>" data-url="financial/financial/form">
                        <?php echo $this->formatDecimal($financial->fin_valor) ?>
                    </a>
                </td>
                <td>
                    <a href="javascript:;" class="editable fin_emissao" data-name='fin_emissao' data-type="text" data-pk="<?php echo $financial->fin_id?>" data-url="financial/financial/form">
                        <?php echo $this->date($financial->fin_emissao)?>
                    </a>
                </td>
                <td>
                    <a href="javascript:;" class="editable fin_vencimento" data-name='fin_vencimento' data-type="text" data-pk="<?php echo $financial->fin_id?>" data-url="financial/financial/form">
                        <?php echo $this->date($financial->fin_vencimento)?>
                    </a>
                </td>
                <td>
                    <a href="javascript:;" class="editable fin_compensacao" data-name='fin_compensacao' data-type="text" data-pk="<?php echo $financial->fin_id?>" data-url="financial/financial/form">
                        <?php echo $this->date($financial->fin_compensacao)?>
                    </a>
                </td>
                <td>
                    <?php $date = new Zend_Date()?>
                    <?php if ($financial['fin_compensacao'] != "" && $financial['con_id'] ):?>
                        <span style="width: 98%; text-align: center;" class="label label-success"> Pago</span>
                        <?php $valorPago = $valorPago + $financial['fin_valor']; ?>
                    <?php elseif (!$financial['fin_vencimento']):?>
                        <span style="width: 98%; text-align: center;" class="label label-inverse"> Sem Vencimento</span>
                    <?php elseif ($financial['fin_vencimento'] && $date->equals(new Zend_Date($financial['fin_vencimento']), Zend_Date::DATES) ):?>
                        <span style="width: 98%; text-align: center;" class="label label-warning">Vencimento Hoje</span>
                    <?php elseif($financial['fin_vencimento'] && $date->isLater(new Zend_Date($financial['fin_vencimento']), Zend_Date::DATES)):?>
                        <span style="width: 98%; text-align: center;" class="label label-important">Vencida em <?php echo $this->Date($financial['fin_vencimento'])?></span>
                    <?php elseif($financial['fin_vencimento'] && $date->isEarlier(new Zend_Date($financial['fin_vencimento']), Zend_Date::DATES)):?>
                        <span style="width: 98%; text-align: center;" class="label label-info">Vencimento em <?php echo $this->Date($financial['fin_vencimento'])?></span>
                    <?php endif; ?>
                </td>
                <td width="80px">
                    <?php if(!empty($financial->fin_compensacao) && !empty($financial->con_id)):?>
                        <a name="<?php echo $financial->fin_id?>" href="financial/financial/recibo/fin_id/<?php echo $financial->fin_id?>" target="_blank" style="text-decoration: none;">
                            <i class="acao icon-print" title="emitir Recibo"></i>
                        </a>
                    <?php endif;?>
                    <a name="<?php echo $financial->fin_id?>" class="editFinancial" href="#" style="text-decoration: none;">
                        <i class="acao icon-pencil" title="Editar"></i>
                    </a>
                    <a class ="deleteMoldal" id = "<?php echo $financial->fin_id ?>" href="#" style="text-decoration: none;">
                        <i class="acao icon-remove" title="Excluir"></i>
                    </a>
                    <a name="<?php echo $financial->fin_id?>" class="duplicarFinancial" href="#" style="text-decoration: none;">
                        <i class="acao icon-retweet" title="Duplicar Ticket"></i>
                    </a>
                    <a class ="historicoTicket" id = "<?php echo $financial->fin_id ?>" href="#" style="text-decoration: none;">
                        <i class="acao icon-time" title="Historico"></i>
                    </a>
                </td>
            </tr>
        <?php endforeach;?>
    <?php else :?>
        <tr>
            <td colspan="10">Não foram encontrados resultados</td>
        </tr>
    <?php endif;?>
</table>
<?php $restaPagar = $this->agrupadorFinanceiro->fin_valor - $valorPago; ?>
<span style="display: none" id="restaPagar" value="<?php echo $this->formatDecimal($restaPagar); ?>"></span>
<span style="display: none" id="valorTotal" value="<?php echo $this->formatDecimal($valorTotal); ?>"></span>
<span style="display: none" id="valorPago" value="<?php echo $this->formatDecimal($valorPago); ?>"></span>

<script type="text/javascript" src="assets/plugins/bootstrap-datepicker/js/locales/bootstrap-datepicker.pt-BR.js"></script>
<script src="<?php echo $this->baseUrl("/scripts/financial/financial.grid.editable.js")?>" type="text/javascript"></script>
