<?php
$request = Zend_Controller_Front::getInstance()->getRequest();
$moduleName         = $request->getModuleName();
$controllerName     = $request->getControllerName();
$actionName         = $request->getActionName();
$caminhoForm        = $this->baseUrl($moduleName.'/'.$controllerName.'/form');
$select = array(
    50 => 50,
    100 => 100,
    200 => 200,
    250 => 250
    );
$request = Zend_Controller_Front::getInstance()->getRequest();
$defaultItens = $request->getParam('itens', 50);

    /**
     * grid do financeiro
     */
?>
<style>
<!--
th.fin_descricao{
    width: 800px;
}
td.fin_valor{
	text-align: right !important;
}
.acoes{
	max-width: 30px;
	min-width: 15px;
}
-->
</style>
<div class="row-fluid">
     <div class="span12">
	      <h3 class="page-title">
	       Tickets
	        <small>Financeiros</small>
	      </h3>
     </div>
</div>
<div class="row-fluid">
    <div class="span12">
    	<div class="row-fluid" style=" ">
			<a href="<?php echo $this->baseUrl("/financial/agrupador-financeiro/form/")?>" class="icon-btn span2 ">
				<i class="icon-usd"></i>
				<div>Nova Transação Financeira</div>
			</a>
			<a href="<?php echo $this->baseUrl("/financial/financial/index/")?>" class="icon-btn span2 ">
				<i class="icon-search"></i>
				<div>Pesquisar Tickets Financeiros</div>
			</a>
			<a href="<?php echo $this->baseUrl("financial/contas/extrato-form")?>" class="icon-btn span2 ">
				<i class="icon-list-alt"></i>
				<div>Extrato de Contas</div>
			</a>
		</div>
        <div class="portlet box blue">
            <div class="portlet-title">
            	<div class="caption"><i class="icon-group"></i>Tickets Financeiros</div>
			</div>
			<div class="portlet-body">
            	<div class="clearfix">
					<div class="btn-group">
						<div class="dataTables_length">
							<?php if ($this->paginator->getTotalItemCount() > $defaultItens): ?>
				                    <label>Mostrar <?php {echo $this->formSelect('itens', $defaultItens, array(), $select);}?></label>
				            <?php endif;?>
						</div>
					</div>
					<div class="btn-group pull-right">
						<div class="dataTables_filter">
							<?php
								$this->columns = (array) $this->columns;
				           	?>
							<?php if (!$this->desabilitarPesquisa): ?>
									<?php echo $this->partial('pesquisa.phtml', 'default', array(
											'fields'       => $this->fields,
											'actionSearch' => $this->actionSearch
				                        ))?>
							<?php endif; ?>
						</div>
					</div>
				</div>
				<div class="dataTables_wrapper form-inline" role="grid">
					<table class="table table-striped table-hover table-bordered dataTable" aria-describedby="sample_editable_1_info">
			            <thead>
			                <tr>
			                	<th  class = "sustenido align-center action">#</th>
			                    <?php foreach ($this->columns as $col => $alias): ?>
			                    <th column="<?php echo $col?>"
			                        class=" <?php echo $col?>"
			                    >
			                        <div><?php echo $alias?></div>
			                    </th>
			                    <?php endforeach;?>
		                        <th colspan="3" class = "align-center action"><?php echo $this->translate("Ações")?></th>
			                </tr>
			            </thead>
			            <tbody>
			                <?php if (count($this->paginator)): ?>
			                    <?php foreach ($this->paginator as $key => $pageOBJ): ?>
			                        <tr class="<?php echo $key % 2 ? 'erow' : '' ?>">
			                        	<td><input type="checkbox" name="checkbox[]" value="<?php echo $pageOBJ['fin_id']?>" ></td>
			                            <?php $page = is_object($pageOBJ) && method_exists($pageOBJ, 'toArray')
			                                        ? $pageOBJ->toArray()
			                                        : $pageOBJ;
			                            ?>
			                            <?php foreach ((array) $this->columns as $col => $alias): ?>
			                                <?php if (array_key_exists($col, $page)): ?>
			                                    <?php $prop_nome = ($col == 'prop_nome' ? explode(' ', $page[$col]): array());?>
			                                    <td style="white-space: normal !important; text-align: justify; padding-right: 5px;" class="<?php echo $col?>" >
			                                        <?php
			                                            if('prop_nome' === $col):
			                                                echo $prop_nome[0];
			                                            else:
			                                                if( isset( $this->formatter ) && isset( $this->formatter[ $col ] ) ):
			                                                    $method = ($this->formatter[ $col ]);
			                                                    echo $this->$method( $page[$col], $page );
			                                                else:
			                                                    echo $page[$col];
			                                                endif;
			                                            endif;
			                                        ?>
			                                    </td>
			                                <?php endif;?>
			                            <?php endforeach;?>
				                              <td class="acoes">
				                                <a title='Editar' data-tooltip href=' <?php echo $this->baseUrl("/financial/agrupador-financeiro/form/fin_id/{$pageOBJ['fin_id']}/id_agrupador_financeiro/".$pageOBJ['id_agrupador_financeiro']) ?>'    >
				                                    <img src='<?php echo $this->baseUrl("/images/edit.png") ?>'  />
				                                </a>
				                            </td>
				                            <td class="acoes">
				                                <a class='delete' data-tooltip title='Excluir' href='<?php echo $this->baseUrl("/financial/financial/delete/id/".$pageOBJ['fin_id']) ?>'>
				                                    <img src='<?php echo $this->baseUrl("/images/delete.png")?>' />
				                                </a>
				                            </td>
			                        </tr>
			                    <?php endforeach;?>
			                <?php else: ?>
			                    <tr>
			                        <td colspan="<?php echo count($this->columns) + 3/*tres acoes*/?>"><?php echo $this->translate("Não existem registros")?>!</td>
			                    </tr>
			                <?php endif; ?>
			            </tbody>
			        </table>
				</div>
				<?php if ($this->paginator instanceof Zend_Paginator): ?>
	            		<?php echo $this->paginationControl($this->paginator, 'Elastic', array('pagination-grid-metronic.phtml', 'default'))?>
        		<?php endif;?>
			</div>
		</div>
	</div>
</div>
<div id ="baseHidden" style=" display: none">
    <div id="successBox" style=" display: none;" class="alert alert-success">
		<button class="close" data-dismiss="alert"></button>
		<strong>Registro(s)!</strong>  salvo(s) com sucesso.
	</div>
	<div class="row-fluid">
		<div class="span6 ">
			<div class="control-group">
				<label class="control-label"><?php echo $this->translate('Nota Fiscal')?></label>
				<div class="controls">
					<?php echo $this->formText('fin_nota_fiscal',null, null);?>
				</div>
			</div>
		</div>
		<!--/span-->
		<div class="span6 ">
			<div class="control-group ">
				<label class="control-label"><?php echo $this->translate('Data do Vencimento')?></label>
				<div class="controls">
					<?php echo $this->formText('fin_vencimento',null, array("class" => "datepicker"));?>
				</div>
			</div>
		</div>
		<!--/span-->
	</div>
	<div class="row-fluid">
		<div class="span6 ">
			<div class="control-group">
				<label class="control-label"><?php echo $this->translate('Data do Emissão')?></label>
				<div class="controls">
					<?php echo $this->formText('fin_emissao',null, array("class" => "datepicker"));?>
				</div>
			</div>
		</div>
		<!--/span-->
		<div class="span6 ">
			<div class="control-group ">
				<label class="control-label"><?php echo $this->translate('Data da Compensação')?></label>
				<div class="controls">
					<?php echo $this->formText('fin_compensacao',null, array("class" => "datepicker"));?>
				</div>
			</div>
		</div>
		<!--/span-->
	</div>
	<div class="row-fluid">
		<div class="span6 ">
			<div class="control-group ">
				<label class="control-label"><?php echo $this->translate('Status')?></label>
				<div class="controls">
					<?php //echo $this->formSelect('fin_stf_id',null,null,array("" => "Selecione")+$this->comboStatus);?>
					Pago? <input type="checkbox" name="fin_pago" id="fin_pago" value="1" >
				</div>
			</div>
		</div>
		<!--/span-->
		<div class="span6 ">
			<div class="control-group ">
				<label class="control-label"><?php echo $this->translate('Grupo de Operação')?></label>
				<div class="controls">
					<?php echo $this->formSelect("ope_id",null,null,array("" => "Selecione")+$this->comboGrupoOperacao);?>
				</div>
			</div>
		</div>
		<!--/span-->
	</div>
	<div class="row-fluid">
		<div class="span6 ">
			<div class="control-group">
				<label class="control-label"><?php echo $this->translate('Plano de Contas')?></label>
				<div class="controls">
					<?php echo $this->formSelect('plc_id',null,null,array("" => "Selecione")+$this->comboPlanoContas);?>
				</div>
			</div>
		</div>
		<!--/span-->
		<div class="span6 ">
			<div class="control-group ">
				<label class="control-label"><?php echo $this->translate('Centro de Custos')?></label>
				<div class="controls">
					<?php echo $this->formSelect('cec_id',null,null,array("" => "Selecione")+$this->comboCentroCusto);?>
				</div>
			</div>
		</div>
		<!--/span-->
	</div>
	<div class="row-fluid">
		<div class="span6 ">
			<div class="control-group">
				<label class="control-label"><?php echo $this->translate('Conta')?></label>
				<div class="controls">
					<?php echo $this->formSelect('con_id',null,null,array("" => "Selecione")+$this->comboContas);?>
				</div>
			</div>
		</div>
		<!--/span-->
		<div class="span6 ">
			<div class="control-group ">
				<label class="control-label"><?php echo $this->translate('Faturado (contra/por)')?></label>
				<div class="controls">
					<?php echo $this->formSelect('id_pessoa_faturado',null,null,array("" => "Selecione")+$this->comboEmpresasGrupo);?>
				</div>
			</div>
		</div>
		<!--/span-->
	</div>
	<div  style="margin-top:5px; display: ;" >
		<fieldset>
			<legend>Financeiro(s) Selecionado(s)</legend>
			<div id="idsBox">

			</div>
		</fieldset>
    </div>
</div>

<script src="<?php echo $this->baseUrl('scripts/financial/financial.grid.js')?>"></script>
