<link href="<?php echo $this->baseUrl('assets/plugins/bootstrap/css/bootstrap.min.css')?>" rel="stylesheet" type="text/css">
<link href="<?php echo $this->baseUrl('assets/plugins/bootstrap/css/bootstrap-responsive.min.css')?>" rel="stylesheet" type="text/css" media="screen">
<link href="<?php echo $this->baseUrl('assets/plugins/font-awesome/css/font-awesome.min.css')?>" rel="stylesheet" type="text/css">
<link href="<?php echo $this->baseUrl('assets/css/style-metro.css')?>" rel="stylesheet" type="text/css">
<link href="<?php echo $this->baseUrl('assets/css/style.css')?>" rel="stylesheet" type="text/css">
<link href="<?php echo $this->baseUrl('assets/css/style-responsive.css')?>" rel="stylesheet" type="text/css">
<link href="<?php echo $this->baseUrl('assets/css/themes/default.css')?>" rel="stylesheet" type="text/css" id="style_color">
<link href="<?php echo $this->baseUrl('assets/plugins/uniform/css/uniform.default.css')?>" rel="stylesheet" type="text/css">
<link href="<?php echo $this->baseUrl('assets/css/pages/invoice.css')?>" rel="stylesheet" type="text/css">
<link href="<?php echo $this->baseUrl('assets/css/print.css')?>" rel="stylesheet" type="text/css" media="print">

<style>
table {
    border-collapse: separate;
    border-spacing: 0px;
    font:13px/1.5 'Helvetica Neue', Arial, 'Liberation Sans', FreeSans, sans-serif;
}

table td,
table th {
    background-color: transparent;
    z-index: 1;
    border-right: 0;
    border-bottom: 0;
    width: 150px;
    padding-left: 5px;
    overflow: hidden;
    height: 12px;
}

table th:before,
table td:before {
    content: "";
    padding: 0;
    height: 1px;
    line-height: 1px;
    width: 1px;
    margin: 1px -994px -996px -2px;
    display: block;
    border: 0;
    z-index: -1;
    position:relative;
    top: -6px;
}

table th:before {
    border-top: 999px solid #D6D6D6;
    border-left: 999px solid #D6D6D6;
}

table td:before {
    border-top: 999px solid #F9F9F9;
    border-left: 999px solid #F9F9F9;
}
td div.grid_3{
    overflow: hidden;
}
table .row td{
    border-bottom: #d6d6d6 1px solid;
    width: 110px;
}
</style>

<div class="row-fluid invoice">
    <div class="row-fluid invoice-logo">
         <div class="span6 invoice-logo-space"><img style="width: 100px;" src="<?php echo $this->baseUrl("images/logo4-01.jpg")?>" alt=""></div>
         <div class="span6">
			<p> <strong>Movimentação Financeira - <?php echo $this->id ?></strong>
			<span class="muted" >Emitido em: <?php echo date("d/m/Y H:i:s") ?><br>
			    Por: <?php echo $this->usuario ?>
			</span></p>
		</div>
    </div>
    <div class="row-fluid">
		<div class="span6" >
    		<ul class="unstyled" >
        	    <li style="line-height:30px;"><strong>Código: </strong><?php echo $this->registros->fin_id?></li>
                <li style="line-height:30px;"><strong>Moeda: </strong><?php  echo $this->registros->getMoeda() ? $this->registros->getMoeda()->moe_descricao : " " ?></li>
        		<li style="line-height:30px;"><strong>Status: </strong><?php  echo $this->registros->getStatus() ? $this->registros->getStatus()->stf_descricao : " "?></li>
        		<li style="line-height:30px;"><strong>Tipo de Documento Interno: </strong><?php  echo $this->registros->getDocumentoInterno() ? $this->registros->getDocumentoInterno()->tid_descricao : " "?></li>
        		<li style="line-height:30px;"><strong>Tipo de Documento Externo: </strong><?php  echo $this->registros->getDocumentoExterno() ? $this->registros->getDocumentoExterno()->tie_descricao : " "?></li>
        		<li style="line-height:30px;"><strong>Data da Emissão: </strong><?php  echo $this->date($this->registros->fin_emissao)?></li>
        		<li style="line-height:30px;"><strong>Data da Compensação: </strong><?php  echo $this->date($this->registros->fin_compensacao)?></li>
        		<li style="line-height:30px;"><strong> Grupo de Operação: </strong><?php  echo $this->registros->getGrupoOperacao()? $this->registros->getGrupoOperacao()->ope_nome : " "?></li>
        		<li style="line-height:30px;"><strong>Empresa: </strong><?php echo $this->registros->getSacadoFinanceiro()? $this->registros->getSacadoFinanceiro()->getEmpresa()->nome_razao : " "?></li>
                <li style="line-height:30px;"><strong> Processo: </strong><?php  echo $this->registros->pro_id?></li>
                <li style="line-height:30px;"><strong> Centro de Custos: </strong><?php  echo$this->registros->getCentroCusto() ? $this->registros->getCentroCusto()->cec_descricao : " "?></li>
                <li style="line-height:30px;"><strong> Observações: </strong><?php  echo $this->registros->fin_observacao?></li>
    		</ul>
		</div>
		<div class="span4">
    		<ul class="unstyled">
    		    <li style="line-height:30px;"><strong>Tipo de movimento: </strong><?php  echo $this->registros->getTipoMovimento()? $this->registros->getTipoMovimento()->tmv_descricao : " "?></li>
    			<li style="line-height:30px;"><strong>Valor: </strong><?php  echo  $this->registros->fin_valor?></li>
    			<li style="line-height:30px;"><strong>Conta: </strong><?php  echo $this->registros->getConta() ? $this->registros->getConta()->con_codnome : " "?></li>
    			<li style="line-height:30px;"><strong>Número documento interno: </strong><?php  echo $this->registros->fin_numero_doc?></li>
    			<li style="line-height:30px;"><strong>Número documento externo: </strong><?php  echo $this->registros->fin_num_doc_os?></li>
    			<li style="line-height:30px;"><strong>Data do Vencimento: </strong><?php  echo $this->date($this->registros->fin_vencimento)?></li>
    			<li style="line-height:30px;"><strong>Mês da Competência: </strong><?php  echo $this->date($this->registros->fin_competencia)?></li>
    			<li style="line-height:30px;"><strong> Nota Fiscal: </strong><?php  echo $this->registros->fin_nota_fiscal?></li>
                <li style="line-height:30px;"><strong> Faturado (contra/por): </strong><?php  echo $this->faturadoPor?></li>
                <li style="line-height:30px;"><strong> PLano de Contas: </strong><?php  echo $this->registros->getPlanoContas() ? $this->registros->getPlanoContas()->plc_cod_contabil.".".$this->registros->getPlanoContas()->plc_descricao : " "?></li>
                <li style="line-height:30px;"><strong>Descrições: </strong><?php  echo $this->registros->fin_descricao?></li>
			</ul>
		</div>
	</div>
    <div class="row-fluid">
        <div class="span8 invoice-block ">
            <a class="btn blue  hidden-print" onclick="javascript:window.print();">Print <i class="icon-print "></i></a>
            <a class="btn green  hidden-print" href="<?php echo $this->baseUrl("financial/financial/grid")?>">Voltar <i class="m-icon-swapright m-icon-white"></i></a>
        </div>
    </div>
</div>