    <?php
    /**
     * formulario do controller relatorio para configurar um relatório
    */
?>

	<script>
$(document).ready(function(){
    $("#marcarTodos").on("click", function(event){

        if(this.checked){
            $("div .checker").children("span").addClass("checked");
            $('.checkbox').attr("checked", "checked");

        }else{

            $("div .checker").children("span").removeClass("checked");
            $('.checkbox').removeAttr("checked");
        }

    });

    function open_win(url)
    {
    window.open(url);
    }
});

$("empresa").change(function (){
    $("this").val("");
});
$("empresa").focus(function (){
    $("this").val("");
});


</script>





<div class="row-fluid">
    <div class="span12">
        <h3 class="page-title">
            Pesquisa
             <small>Corporativo</small>
        </h3>
    </div>
</div>

<div class="row-fluid">
    <span class="span12">
	    <div class="portlet box green" id="">
    		<div class="portlet-title">
    			<div class="caption">
                <i class="icon-reorder"></i> Pesquisa - <span class="step-title">Processo</span>
                </div>
    		</div>
	        <div class="portlet-body form">
                <form action="<?php echo $this->baseUrl('relatorio/processo/visualizar')?>" method="post" class="form-horizontal" id="form_corporativo" novalidate="novalidate">
                    <div class="form-wizard">
                        <div class="tab-content">
                            <div class="tab-pane active" id="tab1">
                                <div class="row-fluid">
								    <div class="span6 ">
										<div class="control-group">
											<div class="controls">
												<input type="hidden" name="id" value="" id="id">
											</div>
										</div>
									</div>
								</div>
                                <div class="row-fluid">
									<div class="span6 ">
										<div class="control-group">
											<label class="control-label">Corporativo</label>
											<div class="controls">
												 <?php echo $this->formHidden('empresas_id_pai',null, array('class' => 'span6 empresas_pai'));?>
                                              	<?php  echo $this->formText('empresa',null, array('class' => 'span10 empresas'));?>

                                            </div>
										</div>
									</div>
                                </div>
                                 <div class="row-fluid">
									<div class="span6 ">
										<div class="control-group">
											<label class="control-label">Selecione os status desejados</label>
											<div class="controls">
												 <input type="text" name="sta_id_selected" id="sta_id_selected"  class="span10" autocomplete="off"><span role="status" aria-live="polite" class="ui-helper-hidden-accessible">14 results are available, use up and down arrow keys to navigate.</span>                     <input type="hidden" name="sta_id" value="" id="sta_id">                     <img id="addStatus" src="/images/add.png" style="top:5px; position: relative;cursor:pointer;" data-tooltip="" title="Adicionar empresa" class="">
                                            </div>
										</div>
									</div>
                                </div>

                                 <div class="row-fluid">
									<div class="span6 ">
										<div class="control-group">
											<label class="control-label">Status Selecionados: <span id="companySelected">0</span></label>
											<div class="controls">
                                                <div id="grid_status">
                                                 </div>
                                            </div>
										</div>
									</div>
                                </div>
                                <br>
                                <div class="form-actions clearfix">
                                    <button class="btn blue blue"><i class="icon-print icon-big"></i>Gerar Relatório</button>
                                    <a href="<?php echo $this->baseUrl('empresa/empresa/index')?>" class="btn green button-previous">Voltar</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </span>
</div>

<script src="<?php echo $this->baseUrl('scripts/relatorio/processo.grid.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/relatorio/empresa.js')?>"></script>