<?php
    /**
     * formulario perfis do authorization
    */
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('assets/plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css')?>" />
<script type="text/javascript" src="<?php echo $this->baseUrl('/assets/plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js')?>"></script>
<style>
.row-fluid [class*="span"]{
	
	margin-left: 0% !important;
}
</style>
<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Cadastro
			 <small> de perfis</small>
		</h3>
	</div>
</div>
<div class="row-fluid">
	<div class="portlet box grey">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder"></i> Formulário</div>
			<div class="tools">
				<a href="javascript:;" class="collapse"></a>
			</div>
		</div>
	<div class="portlet-body form">
        <form method="post"  class="form-horizontal" id="form_corporativo">
                  <?php echo $this->formHidden('id_au_profile', $this->vo->id_au_profile);?>
                  <?php echo $this->formHidden('duplicate', $this->duplicate ? $this->duplicate : false);?>
                  <h3 class="form-section">Perfil</h3>
                  <div class="row-fluid">
                      <div class="span3">
                          <div class="control-group">
	                          <label class="label_cnpj control-label"><?php echo $this->translate('Nome')?><span class="required">*</span></label>
	                          <div class="controls">
	                          	<?php echo $this->formText('name_profile',$this->vo->name_profile, array('class' => 'span10'));?>
	                          </div>
                          </div>
                      </div>
                      <div class="span3 div_uasg">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Módulo')?><span class="required">*</span></label>
	                          <div class="controls">
	                          	<?php echo $this->formSelect('module_profile',$this->vo->module_profile, array('class' => 'span12'),array(""=>"Selecione")+$this->modules);?>
	                          </div>
                          </div>
                      </div>
                  </div>
                  <div class="row-fluid">
	                  <div class="span12">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Descrição')?></label>
	                          <div class="controls">
	                          	<?php echo $this->formTextarea('description_profile',$this->vo->description_profile, array('class'=> 'span12', 'rows' => 3));?>
	                          </div>
                          </div>
                      </div>
                  </div>
                  <h3 class="form-section">Ações</h3>
                  <h5>Marcar Todos <input id="marcarTodos" type="checkbox"></h5>
                  <div class="row-fluid" id="resourceBox">
                  <?php if (count($this->resourceListComplete)>0):?>
                  			<?php foreach ($this->resourceListComplete as $resourceComplete):?>
		                  				<div class="span2">
									  		<label class="control-label"><b><?php echo $resourceComplete->name_resource ?>:</b>&nbsp;</label>
								  			<div class="basic-toggle-button">
								  				<input type="checkbox" class="toggle" name="resourceList[]" 
                  								<?php foreach ($this->resourceListSaved as $resourceSaved):?>
								  					<?php echo $resourceComplete->id_au_resource == $resourceSaved->id_au_resource  ? 'CHECKED' :'' ?> 
					        					<?php endforeach;?>
					        						value="<?php echo $resourceComplete->id_au_resource ?>" />
								  			</div>
					                    </div>
                  			<?php endforeach;?>
                  <?php endif;?>
                  </div>
                  <div class="form-actions">
                      <button type="submit" class="btn blue"><i class="icon-ok"></i> Salvar</button>
                      <a href="<?php echo $this->baseUrl('profile/profile/grid')?>" class="btn" >Voltar</a>
                  </div>
        </form>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/profile/profile.form.js')?>"></script>