<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
    <meta charset="utf-8" />
    <title>Hash Workspace</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href=<?php echo $this->baseUrl("assets/plugins/bootstrap/css/bootstrap.min.css");?> rel="stylesheet" type="text/css"/>
    <link href=<?php echo $this->baseUrl("assets/plugins/bootstrap/css/bootstrap-responsive.min.css");?> rel="stylesheet" type="text/css"/>
    <link href=<?php echo $this->baseUrl("assets/plugins/font-awesome/css/font-awesome.min.css");?> rel="stylesheet" type="text/css"/>
    <link href=<?php echo $this->baseUrl("assets/css/style-metro.css");?> rel="stylesheet" type="text/css"/>
    <link href=<?php echo $this->baseUrl("assets/css/style.css");?> rel="stylesheet" type="text/css"/>
    <link href=<?php echo $this->baseUrl("assets/css/style-responsive.css");?> rel="stylesheet" type="text/css"/>
    <link href=<?php echo $this->baseUrl("assets/css/themes/default.css");?> rel="stylesheet" type="text/css" id="style_color"/>
    <link href=<?php echo $this->baseUrl("assets/plugins/uniform/css/uniform.default.css");?> rel="stylesheet" type="text/css"/>




    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link href=<?php echo $this->baseUrl("assets/css/pages/login-soft.css");?> rel="stylesheet" type="text/css"/>
    <!-- END PAGE LEVEL STYLES -->
    <link rel="shortcut icon" href="favicon.ico" />



    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl("assets/hash/css/bootstrap-chosen.css");?>"/>
    <link href="//cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.brighttheme.min.css" rel="stylesheet" />
    <link href="//cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.core.min.css" rel="stylesheet" />
    <link href="//cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.buttons.min.css" rel="stylesheet" />

    <link href="<?php echo $this->baseUrl('styles/theme/jquery-ui-1.10.2.custom.css')?>" rel="stylesheet">


    <!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
    <!-- BEGIN CORE PLUGINS -->
    <script src=<?php echo $this->baseUrl("assets/plugins/jquery-1.10.1.min.js");?> type="text/javascript"></script>
    <script src=<?php echo $this->baseUrl("assets/plugins/jquery-migrate-1.2.1.min.js");?> type="text/javascript"></script>
    <!-- IMPORTANT! Load jquery-ui-1.10.1.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
    <script src=<?php echo $this->baseUrl("assets/plugins/jquery-ui/jquery-ui-1.10.1.custom.min.js");?> type="text/javascript"></script>
    <script src=<?php echo $this->baseUrl("assets/plugins/bootstrap/js/bootstrap.min.js");?> type="text/javascript"></script>
    <!--[if lt IE 9]>
    <script src=<?php echo $this->baseUrl("assets/plugins/excanvas.min.js");?>></script>
    <script src=<?php echo $this->baseUrl("assets/plugins/respond.min.js");?>></script>
    <![endif]-->
    <script src=<?php echo $this->baseUrl("assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js");?> type="text/javascript"></script>
    <script src=<?php echo $this->baseUrl("assets/plugins/jquery.blockui.min.js");?> type="text/javascript"></script>
    <script src=<?php echo $this->baseUrl("assets/plugins/jquery.cookie.min.js");?> type="text/javascript"></script>
    <script src=<?php echo $this->baseUrl("assets/plugins/uniform/jquery.uniform.min.js");?> type="text/javascript" ></script>
    <!-- END CORE PLUGINS -->
    <!-- BEGIN PAGE LEVEL PLUGINS -->
<!--    <script src=--><?php //echo $this->baseUrl("assets/plugins/jquery-validation/dist/jquery.validate.min.js");?><!-- type="text/javascript"></script>-->
    <script src=<?php echo $this->baseUrl("assets/plugins/backstretch/jquery.backstretch.min.js");?> type="text/javascript"></script>
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src=<?php echo $this->baseUrl("assets/scripts/app.js");?> type="text/javascript"></script>
    <script src=<?php echo $this->baseUrl("assets/scripts/login-soft.js");?> type="text/javascript"></script>
    <!-- END PAGE LEVEL SCRIPTS -->
    <script src="<?php echo $this->baseUrl('scripts/lib/jquery.meio.masks.js')?>" type="text/javascript"></script>





    <script src="<?php echo $this->baseUrl('assets/hash/extensions/chosen/chosen.jquery.min.js')?>"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.core.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.buttons.min.js"></script>
    <script src="<?php echo $this->baseUrl('assets/hash/extensions/ckeditor/ckeditor.js')?>"></script>

    <script type="text/javascript" src=<?php echo $this->baseUrl('assets/hash/login/sha1.js')?> ></script>
    <script type="text/javascript" src=<?php echo $this->baseUrl('assets/hash/login/pbkdf2.js')?> ></script>
    <script type="text/javascript" src=<?php echo $this->baseUrl('assets/hash/js/watch.js')?> ></script>
    <script type="text/javascript" src=<?php echo $this->baseUrl('assets/hash/js/main.js')?> ></script>



    <!-- END JAVASCRIPTS -->

</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->

<body class="login">
<?php if(is_array($this->messages) && count($this->messages)): ?>
    <?php foreach ($this->messages as $message):?>
        <div class="row-fluid">
            <div class="span12">
                <div class="alert alert-alert" style="margin-top: 10px;">
                    <?php echo $message ?>
                    <button class="close" data-dismiss="alert"></button>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>



<!-- BEGIN LOGO -->
<!--<div class="logo">-->
<!--    <img src="--><?php //echo $this->baseUrl('images/logo-big.png'); ?><!--" alt="" />-->
<!--</div>-->
<!-- END LOGO -->
<!-- BEGIN LOGIN -->
<div class="content">

    <?php echo $this->layout()->content?>

<!-- END COPYRIGHT -->

</body>
<!-- END BODY -->
</html>