<?php
    /**
     * formulario de alteração de senha
    */
?>
<script type="text/javascript" src="<?php echo $this->baseUrl("scripts/lib/jquery.pstrength-min.1.2.js");?>"></script>
<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Editar 
			 <small>Senha</small>
		</h3>
	</div>
</div>
<div class="row-fluid">
	<div class="portlet box grey">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder"></i> Formulário de edição de senha</div>
			<div class="tools">
				<a href="javascript:;" class="collapse"></a>
			</div>
		</div>
	<div class="portlet-body form">
        <form method="post"  class="form-horizontal" id="form_change_password">
			<div class="row-fluid" id="passwordBox">
	        	<div class="span3">
                	<div class="control-group">
	                	<label class="control-label"><?php echo $this->translate('Senha')?><span class="required">*</span></label>
                        <div class="controls">
                          	<?php echo $this->formPassword('usu_senha',null, array('class' => 'span10'));?>
	                    </div>
					</div>
				</div>
                <div class="span3">
                	<div class="control-group">
	                	<label class="control-label"><?php echo $this->translate('Confirmação de Senha')?><span class="required">*</span></label>
                        <div class="controls">
                        	<?php echo $this->formPassword('usu_confirm_senha',null, array('class' => 'span10'));?>
	                    </div>
					</div>
				</div>
			</div>
			<div class="form-actions">
                <button type="submit" class="btn blue"><i class="icon-ok"></i> Salvar</button>
            	<a href="<?php echo $this->baseUrl('auth/menu/grid')?>" class="btn" >Voltar</a>
        	</div>
        </form>
        </div>
    </div>
</div>
<div id="dialog_message" style="display: none;">
	<p>Não pode efetuar o a alteração de senha devido a seguinte(s) pendência(s): <span id ="valueMessage"></span></p>
</div>

<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/auth/usuario.change-password.js')?>"></script>
