<?php
    /**
     * formulario usuario
    */
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('assets/plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css')?>" />
	<script type="text/javascript" src="<?php echo $this->baseUrl('/assets/plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("scripts/lib/jquery.pstrength-min.1.2.js");?>"></script>
<style>
.row-fluid [class*="span"]{
	
	margin-left: 0% !important;
}
</style>
<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Cadastro de Usuários
			 <small> para login</small>
		</h3>
	</div>
</div>
<div class="row-fluid">
	<div class="portlet box grey">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder"></i> Formulário</div>
			<div class="tools">
				<a href="javascript:;" class="collapse"></a>
			</div>
		</div>
	<div class="portlet-body form">
        <form method="post"  class="form-horizontal" id="form_usuario">
                  <?php echo $this->formHidden('usu_id', $this->vo->usu_id);?>
                  <h3 class="form-section">Autorização</h3>
                  <div class="row-fluid">
                      <div class="span6">
                      	  <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Vínculo para acesso')?></label>
	                          <div class="controls">
	                          	<?php echo $this->formHidden('usu_id',$this->vo->usu_id, array('class' => 'span6'));?>
	                          	<?php echo $this->formHidden('id_empresa',$this->vo->id_empresa);?>
	                          	<?php echo $this->formText('vinculo',$this->nome_razao ? $this->nome_razao : "", $this->nome_razao ? array('disable' => 'disable', 'class' => 'span12') : array('class' => 'span12'));?>
	                          </div>
                          </div>
                      </div>
                      <?php if ($this->vo->usu_senha != ""):?>
                      			<div class="span3" style="margin-left: 23px !important;">
                          			<div class="control-group">
		                      			<div class="btn-group">
											<a class="btn dropdown-toggle blue" data-toggle="dropdown" href="#">
											Configurações <i class="icon-angle-down"></i>
											</a>
											<ul class="dropdown-menu">
												<li><a href="#" id="editSenha">Editar Senha</a></li>
											</ul>
										</div>
									</div>
								</div>
                      <?php endif;?>
                  </div>
                  <div class="row-fluid" id="passwordBox" style="display: <?php echo $this->vo->usu_id ? "none" : ""  ?> ">
	                  <div class="span3">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Senha')?><span class="required">*</span></label>
	                          <div class="controls">
	                          	<?php echo $this->formPassword('usu_senha',$this->vo->usu_senha, array('class' => 'span10'));?>
	                          </div>
	                          
                          </div>
                      </div>
                      <div class="span3">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Confirmação de Senha')?><span class="required">*</span></label>
	                          <div class="controls">
	                          	<?php echo $this->formPassword('usu_confirm_senha',null, array('class' => 'span10'));?>
	                          </div>
                          </div>
                      </div>
                  </div>
                  <h3 class="form-section">Módulos & Perfis</h3>
                  <div class="row-fluid" id="profileBox">
                  	<?php foreach ($this->modulesWithProfile as $key => $modules):?>
                  		<h4 class="form-section"><?php echo $modules['name'];?></h4>
                  		<div class="control-group">
							<div class="removido_controls">
                  		<?php foreach ($modules["values"] as $keyProfile => $profile):?>
								<div class="span3">
							  		<label class="removido_control-label"> <b><?php echo $profile['name_profile'];?>:</b>&nbsp; </label>
						  			<div class="basic-toggle-button">
						  				<input type="checkbox" class="toggle" name="profileList[]" 
						  				<?php if (count($this->profileUserSaved)>0):?>
							  				<?php foreach ($this->profileUserSaved as $profileUserSaved):?>
									  					<?php echo $profile['id_au_profile'] == $profileUserSaved->id_au_profile  ? 'CHECKED' :'' ?> 
				        					<?php endforeach;?>
			        					<?php endif;?>
					        					value="<?php echo $profile['id_au_profile']; ?>">
						  			</div>
			                    </div>
                  			<?php endforeach;?>
                  			</div>
						</div>
                  	<?php endforeach;?>
                  </div>
                  <h3 class="form-section">Workspace</h3>
                  <div class="row-fluid">
                  	<?php foreach ($this->workspaceList as $key => $workspace):?>
	                  	<div class="span3">
	                  		<label class=""><b><?php echo $workspace;?></b></label>
	                  			<div class="basic-toggle-button">
					  				<input type="checkbox" class="toggle" name="workspaceList[]" value="<?php echo $key ?>"
					  				<?php if (count($this->workspaceUserSaved)>0):?>
							  				<?php foreach ($this->workspaceUserSaved as $workspaceUserSaved):?>
									  					<?php echo $key == $workspaceUserSaved["id_workspace"]  ? 'CHECKED' :'' ?> 
				        					<?php endforeach;?>
		        					<?php endif;?>
					  				 >
					  			</div>
					  	</div>
                  	<?php endforeach;?>
                  </div>
                  <div class="form-actions">
                      <button type="submit" class="btn blue"><i class="icon-ok"></i> Salvar</button>
                      <a href="<?php echo $this->baseUrl('auth/usuario/grid')?>" class="btn" >Voltar</a>
                  </div>
        </form>
        </div>
    </div>
</div>
<div id="dialog_message" style="display: none;">
	<p>Não pode efetuar o vínculo devido as seguintes pendências: <span id ="valueMessage"></span></p>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/auth/usuario.form.js')?>"></script>