<style>
<!--
.dataTables_filter{
	float: right;
}

.dataTables_paginate{
	margin: 0px;
	float: right;
}

-->
</style>
<div class="row-fluid">
     <div class="span12">
	      <h3 class="page-title">
	       Usuários autorizados
	        <small> no sistema</small>
	      </h3>
     </div>
</div>
<div class="row-fluid">
	<div class="span12">
		<div class="portlet box grey">
			<div class="portlet-title">
				<div class="caption"><i class="icon-wrench"></i>Usuários Autorizado</div>
				<div class="tools">
                    <a href="javascript:;" class="collapse"></a>
                </div>
				<div class="actions">
					<a class="btn " href="<?php echo $this->baseUrl("/auth/usuario/form") ?>"><i class="icon-pencil"></i> Novo </a>
				</div>
			</div>
			<div class="portlet-body flip-scroll">
				<div id="sample_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
					<table class="table-bordered table-striped table-condensed flip-content" id="perfisTable">
						<thead class="flip-content">
							<tr>
								<th class="hidden-480">Código</th>
					            <th class="hidden-480">Nome</th>
					            <th class="hidden-480">CPF/CNPJ</th>
					            <th class="hidden-480">Tipo Pessoa</th>
					            <th class="hidden-480">E-mail</th>
					            <th style="width: 45px;" class="hidden-480 action">Ação</th>
							</tr>
						</thead>

						<tbody>
							<?php if (count($this->userList) > 0):?>
				        <?php foreach ($this->userList as $user):?>
				        	<?php if ($user->getEmpresa()->ativo == 0) continue;?>
				            <tr class="odd gradeX">
				                <td class="hidden-480" style="width:30px"><?php echo $user->usu_id?></td>
				                <td><?php echo $user->getEmpresa()->nome_razao;?></td>
				                <td class="hidden-480"><?php echo $this->cpf($user->getEmpresa()->cnpj_cpf);?></td>
				                <td><?php echo $user->getEmpresa()->tps_id == "1" ? "Jurídica":"Física";?></td>
				                <td class="hidden-480"><a href="mailto:<?php echo $user->getEmpresa()->email_corporativo;?>" target="_top"><?php echo $user->getEmpresa()->email_corporativo;?></a></td>
				                <td class="acoes">
				                    <a href="<?php echo $this->baseUrl("auth/usuario/form/usu_id/{$user->usu_id}")?>">
				                        <img title="Editar" data-tooltip src="<?php echo $this->baseUrl('images/edit.png')?>"/>
				                    </a>
				                    <a class="deleteMoldal" name = "<?php echo $user->getEmpresa()->nome_razao;?>" value = "<?php echo $user->usu_id?>" href="#">
				                        <img title="Excluir" data-tooltip src="<?php echo $this->baseUrl('images/delete.png')?>"/>
				                    </a>
				                </td>
				            </tr>
				        <?php endforeach;?>
					<?php endif;?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="dialog_delete" style="display: none;">
	<p>Deseja realmente excluir o vínculo do usuário: <span id ="valueDelete"></span></p>
</div>
<script type="text/javascript">

 $('#perfisTable').dataTable({
     "aLengthMenu": [
         [30, 50, 100, -1],
         [30, 50, 100, "All"] // change per page values here
     ],
     // set the initial value
     "iDisplayLength": 30,
     "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
     "sPaginationType": "bootstrap",
     "oLanguage": {
         "sProcessing": "Aguarde enquanto os dados são carregados ...",
         "sLengthMenu": "Mostrar _MENU_ registros",
         "sZeroRecords": "Não foram encontrados resultados",
         "sInfoEmpty": "Mostrando de 0 até 0 de 0 registros",
         "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
         "sInfoFiltered": "",
         "sSearch": "Procurar",
         "oPaginate": {
            "sFirst":    "Primeiro",
            "sPrevious": "Anterior",
            "sNext":     "Próximo",
            "sLast":     "Último"
         }
      },
     "aoColumnDefs": [{
             'bSortable': true,
             'aTargets': [0]
         }
     ]
 });
</script>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/auth/usuario.grid.js')?>"></script>