<style>
i.add-entidade {
font-size: 26px;
color: #00CC99;
cursor: pointer;
margin-left: 2px;
}
i.delete-entidade {
color: #e02222;
font-size: 26px;
cursor: pointer;
margin-left: 4px;
}
</style>
<div class="row-fluid" style="margin-top: 10px">
	<div class="portlet box caribbean-green">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder"></i> Extrato de processo</div>
			<div class="tools">
				<a href="javascript:;" class="collapse"></a>
			</div>
		</div>
    	<div class="portlet-body form">
            <form method="post" action="<?php echo $this->baseUrl('processo/extrato/pdf') ?>" target="_blank" >
    			<div class="row-fluid">
    			    <div class="span4">
        				<div class="control-group">
        					<label class="control-label">Data</label>
        					<div class="controls">
        						<?php echo $this->formText('dt_inicio', null, array('class'=> 'span6', 'placeholder' => 'De'));?> -
        						<?php echo $this->formText('dt_fim', null, array('class'=> 'span6', 'placeholder' => 'Até'));?>
        					</div>
        				</div>
    				</div>
    			    <div class="span8">
        				<div class="control-group">
        					<label class="control-label">Entidade</label>
        					<div class="controls">
        						<?php echo $this->formText('entidade', null, array('class'=> 'span8'));?>
        						<i class="icon-plus add-entidade"></i>
        						<?php echo $this->formHidden('id_empresa_selecionado')?>
        					</div>
        				</div>
    				</div>
    			</div>
    			<div class="row-fluid">
    			    <div class="span4">
        				<div class="control-group">
        					<label class="control-label">Status</label>
        					<div class="controls">
        					<label class="checkbox line">
                                <input type="checkbox" id="checkbox-todo" /> Todos
                            </label>
                            <?php foreach ($this->comboStatus as $key => $status):?>
                                <label class="checkbox line">
                                    <input type="checkbox" value="<?php echo $key?>" name="id_status[]" /> <?php echo $status?>
                                </label>
                            <?php endforeach;?>
        					</div>
        				</div>
    				</div>
    			    <div class="span8">
        				<div class="control-group">
        					<label class="control-label">Entidade selecionada</label>
        					<div class="controls empresa-selecionada">
        					</div>
        				</div>
    				</div>
    			</div>
    			<div class="row-fluid">
    			    <div class="span6">
                        <div class="control-group">
                            <label class="control-label">Financeiro compensado</label>
                            <div class="controls">
                                <label class="radio">
                                <input type="radio" name="compensado" value="1" />
                                Sim
                                </label>
                                <label class="radio">
                                <input type="radio" name="compensado" value="0" checked />
                                não
                                </label>
                            </div>
                        </div>
    			    </div>
    			</div>
    			<div class="form-actions">
                    <button class="btn green salvar_planejamento"><i class="icon-file"></i> Pesquisar e gerar PDF</button>
            	</div>
            </form>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span12" id="grid-planejamento">

    </div>
</div>
<script src="<?php echo $this->baseUrl('scripts/processo/extrato.search.js')?>" type="text/javascript"></script>
