<style>
<!--
.dataTables_filter{
	float: right;
}

.dataTables_paginate{
	margin: 0px;
	float: right;
}
a i.acao{
	padding: 5px;
	color: #000;
	cursor: pointer;
}
a i.acao:HOVER{
	text-decoration: none;
}
div.pesquisa-grid{
	background: #f9f9f9;
	padding: 10px;
	display: none;
}
-->
</style>
<div class="row-fluid">
	<div class="span12">
		<div class="portlet box darkorange">
			<div class="portlet-title">
				<div class="caption"><i class="icon-group"></i>Funcionário</div>
				<div class="tools">
					<a href="javascript:;" class="collapse"></a>
		        </div>
				<div class="actions">
					<a href="<?php echo $this->baseUrl('rh/horario-funcionario/form')?>" class="btn novo-funcionario">Novo</a>
				</div>
			</div>
			<div class="portlet-body flip-scroll">
				<div id="sample_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
					<table class="table-bordered table-striped table-condensed flip-content" id="perfisTable">
						<thead class="flip-content">
							<tr>
					            <th class="hidden-480">Funcionário</th>
					            <th class="hidden-480">Data</th>
					            <th style="width: 85px;" class="hidden-480 action">Ação</th>
							</tr>
						</thead>

						<tbody>
							<?php if (count($this->funcionarioList) > 0):?>
				        <?php foreach ($this->funcionarioList as $funcionario):?>
			            <tr class="odd gradeX">
			                <td><?php echo $funcionario->getFuncionario()->getEmpresa() ?></td>
			                <td><?php echo $this->date($funcionario->data) ?></td>
			                <td class="acoes">
			                	<a href="<?php echo $this->baseUrl('rh/horario/form/id_horario/'. $funcionario->id_horario_funcionario)?>" value="<?php echo $funcionario->id_horario_funcionario?>" title="Editar" class="editar-funcionario">
			                		<i class="icon-pencil acao" title="Editar"></i>					
			                	</a>
			                    <a class="delete-funcionario" value="<?php echo $funcionario->id_horario_funcionario ?>" href="#">
	                    			<i class="acao  icon-remove" title="Excluir"></i>
			                    </a>
			                </td>
			            </tr>
				        <?php endforeach;?>
					<?php else:?>
			            <tr>
			                <td colspan="3">Não existem registros!</td>
			            </tr>
					<?php endif;?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="dialog_delete" style="display: none;">
	<p>Deseja realmente excluir este registro: <span id="valueDelete"></span></p>
</div>