<style>
<!--
button.btn.green {
	border-top-right-radius: 7px !important;
	border-bottom-right-radius: 7px !important;
}
button.btn.red {
	border-top-right-radius: 7px !important;
	border-bottom-right-radius: 7px !important;
}
div.nivel{
	margin-top: 10px;
}

div.nivel:first-child{
	margin-top: 0;
}
-->
</style>
<div class="row-fluid" style="margin-top: 20px;">
	<div class="portlet box darkorange">
		<div class="portlet-title">
			<div class="caption"><i class="fa fa-reorder"></i>Configuração</div>
			<div class="tools">
				<a href="javascript:;" class="collapse"></a>
			</div>
			<div class="actions">
			</div>
		</div>
		<div class="portlet-body form">
			<form action="#" class="form-horizontal" method="post">
			<?php if($this->vo->id_configuracao):?>
				<div class="row-fluid">
					<div class="span6">
						<div class="control-group">
							<label class="control-label">Código</label>
							<div class="controls">
								<?php echo $this->formText('cod', $this->vo->id_configuracao, array('disabled'=> 'disabled', 'class'=> 'span2'))?>
							</div>
						</div>
					</div>
				</div>
			<?php endif;?>
				<div class="row-fluid">
					<div class="span6">
						<div class="control-group">
							<label class="control-label">Inicio de folha <span style="color: red">*</span></label>
							<div class="controls">
								<?php echo $this->formHidden('id_configuracao', $this->vo->id_configuracao)?>
				              	<?php echo $this->formHidden('id_workspace', $this->vo->id_workspace)?>
				              	<?php echo $this->formSelect("dia_inicio_folha",$this->vo->dia_inicio_folha, array("class" => "span4"), $this->comboDia);?>
							</div>
						</div>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span6">
						<div class="control-group">
							<label class="control-label">Nivel 1 <span style="color: red">*</span></label>
							<div class="controls">
								<?php if(!empty($this->configUsuarioNivel1) && count($this->configUsuarioNivel1) > 0):?>
									<?php $i = 0?>
									<?php foreach ($this->configUsuarioNivel1 as $configUsuario):?>
			                        <div class="input-append hidden-phone nivel">  
			                        	<?php echo $this->formSelect("nivel_1",$configUsuario->id_usuario, array("class" => "m-wrap medium nivel_1"), $this->comboUsuario);?>
			                        	<?php if($i == 0):?>
											<button class="btn green add nivel1">+</button>
										<?php else :?>
											<button class="btn red remove nivel1">-</button>
										<?php endif;?>
										<?php $i++ ?>
									</div>
									<?php endforeach;?>
								<?php else:?>
									<div class="input-append hidden-phone nivel">
										<?php echo $this->formSelect("nivel_1",null, array("class" => "m-wrap medium nivel_1"), $this->comboUsuario);?>
										<button class="btn green add nivel1">+</button>
									</div>
								<?php endif;?>
							</div>
						</div>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span6">
						<div class="control-group">
							<label class="control-label">Nivel 2 <span style="color: red">*</span></label>
							<div class="controls">
								<?php if(!empty($this->configUsuarioNivel2) && count($this->configUsuarioNivel2) > 0):?>
									<?php $i = 0?>
									<?php foreach ($this->configUsuarioNivel2 as $configUsuario):?>
			                        <div class="input-append hidden-phone nivel">  
			                        	<?php echo $this->formSelect("nivel_2",$configUsuario->id_usuario, array("class" => "m-wrap medium nivel_2"), $this->comboUsuario);?>
			                        	<?php if($i == 0):?>
											<button class="btn green add nivel2">+</button>
										<?php else :?>
											<button class="btn red remove nivel2">-</button>
										<?php endif;?>
										<?php $i++ ?>
									</div>
									<?php endforeach;?>
								<?php else:?>
									<div class="input-append hidden-phone nivel">
										<?php echo $this->formSelect("nivel_2",null, array("class" => "m-wrap medium nivel_2"), $this->comboUsuario);?>
										<button class="btn green add nivel2">+</button>
									</div>
								<?php endif;?>
							</div>
						</div>
					</div>
				</div>
				<div class="form-actions">
					<a href="<?php echo $this->baseUrl('rh/configuracao/grid'); ?>" class="btn button-previous" style="display: inline-block;">
						<i class="m-icon-swapleft"></i> Voltar 
					</a>
		          	<button class="btn green" type="submit">
		          		Salvar
		        	</button>
				</div>
			</form>
		</div>
	</div>
</div>
  <script src="/scripts/rh/configuracao.form.js" type="text/javascript"></script>
