    <?php
    /**
     * formulario do controller relatorio para configurar um relatório
    */
?>

	<script>
$(document).ready(function(){
    $("#marcarTodos").on("click", function(event){

        if(this.checked){
            $("div .checker").children("span").addClass("checked");
            $('.checkbox').attr("checked", "checked");

        }else{

            $("div .checker").children("span").removeClass("checked");
            $('.checkbox').removeAttr("checked");
        }

    });

    function open_win(url)
    {
    window.open(url);
    }
});

$("empresa").change(function (){
    $("this").val("");
});
$("empresa").focus(function (){
    $("this").val("");
});


</script>





<div class="row-fluid">
    <div class="span12">
        <h3 class="page-title">
            Pesquisa
             <small>Funcionarios</small>
        </h3>
    </div>
</div>

<div class="row-fluid">
    <span class="span12">
	    <div class="portlet box green" id="">
    		<div class="portlet-title">
    			<div class="caption">
                <i class="icon-reorder"></i> Pesquisa - <span class="step-title">Funcionarios</span>
                </div>
    		</div>

	        <div class="portlet-body form">
                <form action="<?php echo $this->baseUrl('relatorio/funcionario/relatorio')?>" method="post" class="form-horizontal" id="form_corporativo" novalidate="novalidate">
                    <div class="form-wizard">
                        <div class="tab-content">
                            <div class="tab-pane active" id="tab1">
                                <div class="row-fluid">
								    <div class="span6 ">
										<div class="control-group">
											<div class="controls">
												<input type="hidden" name="id" value="" id="id">
											</div>
										</div>
									</div>
								</div>
                                <br>
                                <div class="form-actions clearfix">
                                    <button class="btn blue blue"><i class="icon-print icon-big"></i>Gerar Relatório</button>
                                    <a href="<?php echo $this->baseUrl('empresa/empresa/index')?>" class="btn green button-previous">Voltar</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </span>
</div>

<script src="<?php echo $this->baseUrl('scripts/relatorio/processo.grid.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/relatorio/empresa.js')?>"></script>