<link rel="stylesheet" href="<?php echo $this->baseUrl('assets/plugins/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css');?>" />
<div class="row-fluid" style="margin-bottom: 20px;"></div>
<div class="row-fluid">
	<div class="portlet box darkorange">
		<div class="portlet-title">
			<div class="caption"><i class="fa fa-reorder"></i>Config. Passagens</div>
			<div class="tools">
				<a href="javascript:;" class="collapse"></a>
			</div>
			<div class="actions">
			</div>
		</div>
		<div class="portlet-body form">
			<form action="#" class="form-horizontal" id="form_agrupador" method="post">
				<div class="row-fluid">
					<div class="span6">
						<div class="control-group">
							<label class="control-label">Código</label>
							<div class="controls">
								<?php echo $this->formText('id_rh_passagem', $this->vo->id_rh_passagem, array('style' => 'width: 90px', 'disable' => 'disable'))?>
								<?php echo $this->formHidden('id_rh_passagem', $this->vo->id_rh_passagem)?>
							</div>
						</div>
					</div>					
				</div>
				<div class="row-fluid">
					<div class="span6">
						<div class="control-group">
							<label class="control-label" id="labelCliente">Descrição <span style="color: red">*</span></label>
							<div class="controls">
              	<?php echo $this->formText("descricao",$this->vo->descricao, array("class" => "span12"));?>
							</div>
						</div>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span3">
						<div class="control-group">
							<label class="control-label">Valor</label>
							<div class="controls"><?php echo $this->formText('valor1', $this->vo->valor1, array('style' => 'width: 90px'))?></div>
						</div>
					</div>
					<div class="span3">
						<div class="control-group">
							<label class="control-label">Quantidade</label>
							<div class="controls"><?php echo $this->formText('quantidade1', $this->vo->quantidade1, array('style' => 'width: 90px'))?></div>
						</div>
					</div>
					<div class="span6">
						<div class="control-group">
							<label class="control-label">Linhas.</label>
							<div class="controls"><?php echo $this->formText('linhas1', $this->vo->linhas1, array('class' => 'span12'))?></div>
						</div>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span3">
						<div class="control-group">
							<label class="control-label">Valor</label>
							<div class="controls"><?php echo $this->formText('valor2', $this->vo->valor2, array('style' => 'width: 90px'))?></div>
						</div>
					</div>
					<div class="span3">
						<div class="control-group">
							<label class="control-label">Quantidade</label>
							<div class="controls"><?php echo $this->formText('quantidade2', $this->vo->quantidade2, array('style' => 'width: 90px'))?></div>
						</div>
					</div>
					<div class="span6">
						<div class="control-group">
							<label class="control-label">Linhas.</label>
							<div class="controls"><?php echo $this->formText('linhas2', $this->vo->linhas2, array('class' => 'span12'))?></div>
						</div>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span3">
						<div class="control-group">
							<label class="control-label">Valor</label>
							<div class="controls"><?php echo $this->formText('valor3', $this->vo->valor3, array('style' => 'width: 90px'))?></div>
						</div>
					</div>
					<div class="span3">
						<div class="control-group">
							<label class="control-label">Quantidade</label>
							<div class="controls"><?php echo $this->formText('quantidade3', $this->vo->quantidade3, array('style' => 'width: 90px'))?></div>
						</div>
					</div>
					<div class="span6">
						<div class="control-group">
							<label class="control-label">Linhas.</label>
							<div class="controls"><?php echo $this->formText('linhas3', $this->vo->linhas3, array('class' => 'span12'))?></div>
						</div>
					</div>
				</div>
				<div class="form-actions">
					<a href="<?php echo $this->baseUrl('rh/passagem/grid'); ?>" class="btn button-previous" style="display: inline-block;">
						<i class="m-icon-swapleft"></i> Voltar 
					</a>
          <button class="btn green" type="submit">
          	Salvar
        	</button>
				</div>
			</form>
		</div>
	</div>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js');?>"></script>
