<style>
<!--
.dataTables_filter{
	float: right;
}

.dataTables_paginate{
	margin: 0px;
	float: right;
}
a i.acao{
	padding: 5px;
	color: #000;
	cursor: pointer;
}
a i.acao:HOVER{
	background-color: #000;
	text-decoration: none;
}
-->
</style>
<div class="row-fluid">
     <div class="span12">
     </div>
</div>
<div class="row-fluid">
	<div class="span12">
		<div class="portlet box darkorange">
			<div class="portlet-title">
				<div class="caption"><i class="icon-group"></i>Tabela de Passagem</div>
				<div class="tools">
        	<a href="javascript:;" class="collapse"></a>
        </div>
				<div class="actions">
					<a href="<?php echo $this->baseUrl('rh/passagem/form')?>" class="btn">Novo</a>
				</div>
			</div>
			<div class="portlet-body flip-scroll">
				<div id="sample_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
					<table class="table-bordered table-striped table-condensed flip-content" id="perfisTable">
						<thead class="flip-content">
							<tr>
								<th class="" style="width: 45px;">Código</th>
		            <th class="">Descrição</th>
		            <th class="hidden-480" style="width: 45px;">Ação</th>
							</tr>
						</thead>

						<tbody>
							<?php if (count($this->iten) > 0):?>
				        <?php foreach ($this->iten as $iten):?>
			            <tr class="odd gradeX">
			                <td style="width:30px"><?php echo $iten->id_rh_passagem; ?></td>
			                <td><?php echo $iten->descricao; ?></td>
			                <td class="hidden-480">
			                	<a href="<?php echo $this->baseUrl("/rh/passagem/form/id_rh_passagem/{$iten->id_rh_passagem}")?>" >
							          	<i class="icon-pencil acao" title="Editar"></i>					
							          </a>
			                	<a class="deleteMoldal" value="<?php echo $iten->id_rh_passagem; ?>" href="#">
                    			<i class="acao  icon-remove" title="Excluir"></i>
		                    </a>
			                </td>
			            </tr>
				        <?php endforeach;?>
					<?php endif;?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="dialog_delete" style="display: none;">
	<p>Deseja realmente excluir este registro: <span id="valueDelete"></span></p>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/rh/passagem.grid.js')?>"></script>
<script type="text/javascript">

 $('#perfisTable').dataTable({
     "aLengthMenu": [
         [30, 50, 100, -1],
         [30, 50, 100, "All"] // change per page values here
     ],
     // set the initial value
     "iDisplayLength": 30,
     "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
     "sPaginationType": "bootstrap",
     "oLanguage": {
         "sProcessing": "Aguarde enquanto os dados são carregados ...",
         "sLengthMenu": "Mostrar _MENU_ registros",
         "sZeroRecords": "Não foram encontrados resultados",
         "sInfoEmpty": "Mostrando de 0 até 0 de 0 registros",
         "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
         "sInfoFiltered": "",
         "sSearch": "Procurar",
         "oPaginate": {
            "sFirst":    "Primeiro",
            "sPrevious": "Anterior",
            "sNext":     "Próximo",
            "sLast":     "Último"
         }
      },
     "aoColumnDefs": [{
             'bSortable': true,
             'aTargets': [0]
         }
     ]
 });
</script>