<style>
table tr.different_financial td{
    color: #e02222 !important;
}
.dataTables_filter{
	float: right;
}

.dataTables_paginate{
	margin: 0px;
	float: right;
}
i.acao{
    color:#000;
    padding: 0 2px;
}
td.acoes{
    text-align: center;
}

</style>
<?php //App_Util_Functions::debug($this->pedidoList)?>
<script type="text/javascript" src="assets/plugins/data-tables/DT_bootstrap.js"></script>
<div class="row-fluid" style="margin-top:20px">
    <div class="span12">
        <div class="portlet box caribbean-green">
                <div class="portlet-title">
                	<div class="caption"><i class="icon-cogs"></i>Meus Pedidos</div>
    			</div>
    			<div class="portlet-body">
                    <!--BEGIN TABS-->
                            		<table class="grid_datatable table-bordered table-striped table-condensed flip-content table" style="width: 100%">
                            		    <thead>
                            		        <tr>
                            		            <th style="width: 100px;">Código</th>
                            		            <th>Descrição</th>
                            		            <th style="width: 325px">Status</th>
                            		            <th>Quantidade</th>
                            		            <th>Valor Unitário</th>
                            		            <th style="width: 140px">Valor Pedido</th>
                            		        </tr>
                            		    </thead>
                            		    <tbody>
                            		    <?php if (count($this->pedidoList) > 0):?>
                            		        <?php foreach ($this->pedidoList as $processo):?>
                            		            <tr>
                            		                <td style="text-align: center"><?php echo $processo->pro_codigo?></td>
                            		                <td><?php echo $processo->pro_desc_produto?></td>
                            		                <td><?php echo $processo->getStatus()->sta_descricao?></td>
                            		                <td style="text-align: center;"><?php echo $processo->pro_quantidade?></td>
                            		                <td style="text-align: right;"><?php echo $this->real($processo->pro_vlr_unt) ?></td>
                            		                <td style="text-align: right;"><?php echo $this->real($processo->pro_vlr_pedido) ?></td>
                            		            </tr>
                            		        <?php endforeach;?>
                            		    <?php endif;?>
                            		    </tbody>
                            		</table>
                </div>
            </div>
    </div>
</div>
<script>
$(document).ready(function(){
	 $('.grid_datatable').dataTable({
	     "aLengthMenu": [
	         [30, 50, 100, -1],
	         [30, 50, 100, "All"] // change per page values here
	     ],
	     // set the initial value
	     "iDisplayLength": 30,
	     "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
	     "sPaginationType": "bootstrap",
	     "oLanguage": {
	         "sProcessing": "Aguarde enquanto os dados são carregados ...",
	         "sLengthMenu": "Mostrar _MENU_ registros",
	         "sZeroRecords": "Não foram encontrados resultados",
	         "sInfoEmpty": "Mostrando de 0 até 0 de 0 registros",
	         "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
	         "sInfoFiltered": "",
	         "sSearch": "Procurar",
	         "oPaginate": {
	            "sFirst":    "Primeiro",
	            "sPrevious": "Anterior",
	            "sNext":     "Próximo",
	            "sLast":     "Último"
	         }
	      },
	     "aoColumnDefs": [{
	             'bSortable': true,
	             'aTargets': [0]
	         }
	     ]
	 });
});
</script>
