<link href="/assets/plugins/bootstrap-timepicker/compiled/timepicker.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="/assets/plugins/bootstrap-datepicker/css/datepicker.css" />
<link href="/assets/plugins/select2/select2_metro.css" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" type="text/css" href="/assets/plugins/bootstrap-datepicker/css/datepicker.css" />
<!-- BEGIN X-EDITABLE PLUGIN-->
  <link href="/assets/plugins/bootstrap-editable/bootstrap-editable/css/bootstrap-editable.css" rel="stylesheet" type="text/css" media="screen"/>
  <link href="/assets/plugins/bootstrap-editable/inputs-ext/address/address.css" rel="stylesheet" type="text/css" media="screen"/>
  <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('assets/plugins/select2/select2_metro.css')?>" />
<!-- END X-EDITABLE PLUGIN-->
<style>
<!--
.editable{
    color:black;
}
a.editable-click {
  border-bottom: none;
}
a.editable-click.editable-disabled,a.editable-click:hover {
  border-bottom: none;
}
td{
  text-align: center;
}
a.banco-hora {
visibility: hidden;
float: right;
padding: 2px 5px;
display: inline-block;
text-decoration: none;
color: #000;
}
td:hover a.banco-hora{
visibility:visible;
}
.icon-time:before{
	cursor: pointer;
}
-->
</style>
<div class="row-fluid" style="margin-top: 20px;">
	<div class="portlet box darkorange">
		<div class="portlet-title">
			<div class="caption"><i class="fa fa-reorder"></i>Horário</div>
			<div class="tools">
				<a href="javascript:;" class="collapse"></a>
			</div>
			<div class="actions">
			</div>
		</div>
		<div class="portlet-body form">
			<form action="#" class="form-horizontal" id="form_agrupador" method="post">
			<?php if($this->vo->id_horario):?>
				<div class="row-fluid">
					<div class="span6">
						<div class="control-group">
							<label class="control-label">Código</label>
							<div class="controls">
								<?php echo $this->formText('cod', $this->vo->id_horario, array('disabled'=> 'disabled', 'class'=> 'span2'))?>
							</div>
						</div>
					</div>
				</div>
			<?php endif;?>
				<div class="row-fluid">
					<div class="span6">
						<div class="control-group">
							<label class="control-label">Nome <span style="color: red">*</span></label>
							<div class="controls">
								<?php echo $this->formHidden('id_horario', $this->vo->id_horario)?>
				              	<?php echo $this->formHidden('id_workspace', $this->vo->id_workspace?$this->vo->id_workspace:null)?>
				              	<?php echo $this->formText("nome",$this->vo->nome, array("class" => "span12"));?>
							</div>
						</div>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span12">
						<div class="control-group">
							<label class="control-label">Tolerância extra</label>
							<div class="controls">
				              	<?php echo $this->formText("tolerancia_extra",$this->vo->tolerancia_extra, array("class" => "span2"));?>
				              	minutos/por semana
							</div>
						</div>
					</div>
				</div>
				<?php if($this->vo->id_horario):?>
				
					<!--BEGIN TABS-->
					<div class="tabbable tabbable-custom">
						<ul class="nav nav-tabs">
							<li class="active"><a href="#tab_horario" data-toggle="tab">Horário</a></li>
							<li><a href="#tab_extra" data-toggle="tab">Extra</a></li>
						</ul>
						<div class="tab-content">
							<div class="tab-pane active" id="tab_horario">
								<table class="table-bordered table-striped table-condensed flip-content" style="width: 100%;">
									<thead class="flip-content">
										<tr>
											<th style="width: 100px"></th>
								            <th>Entrada 1</th>
								            <th>saída 1</th>
								            <th>Entrada 2</th>
								            <th>Saída 2</th>
								            <th>Tolerância de Extra</th>
								            <th>Tolerância de falta</th>
								            <th>Fechamento</th>
								            <th>Almoço livre</th>
								            <th>Compensado</th>
								            <th>Carga horária</th>
										</tr>
									</thead>
									<tbody>
										<?php if (count($this->configHorarioList) > 0):?>
							        <?php foreach ($this->configHorarioList as $semana):?>
							            <tr>
							                <td style="font-weight: bold;"><?php echo $semana['nome_semana']?></td>
							                <td>
							                	<a href="javascript:;" class="editable entrada1" data-semana="<?php echo $semana['num_semana']?>" data-name='entrada1' data-type="text" data-pk="<?php echo count($semana['config']) > 0 ?$semana['config']->id_config_horario:null?>"  data-url="/rh/config-horario/form">
							                		<?php echo $semana['config']? substr($semana['config']->entrada1, 0, -3): null?>
							                	</a>
							                </td>
							                <td>
							                	<a href="javascript:;" class="editable saida1" data-semana="<?php echo $semana['num_semana']?>" data-name='saida1' data-type="text" data-pk="<?php echo count($semana['config']) > 0 ?$semana['config']->id_config_horario:null?>" data-url="/rh/config-horario/form">
							                		<?php echo $semana['config']? substr($semana['config']->saida1, 0, -3): null?>
							                	</a>
							                </td>
							                <td>
							                	<a href="javascript:;" class="editable entrada2" data-semana="<?php echo $semana['num_semana']?>" data-name='entrada2' data-type="text" data-pk="<?php echo count($semana['config']) > 0 ?$semana['config']->id_config_horario:null?>" data-url="/rh/config-horario/form">
							                		<?php echo $semana['config']? substr($semana['config']->entrada2, 0, -3): null?>
							                	</a>
							                </td>
							                <td>
							                	<a href="javascript:;" class="editable saida2" data-semana="<?php echo $semana['num_semana']?>" data-name='saida2' data-type="text" data-pk="<?php echo count($semana['config']) > 0 ?$semana['config']->id_config_horario:null?>"  data-url="/rh/config-horario/form">
							                		<?php echo $semana['config']? substr($semana['config']->saida2, 0, -3): null?>
							                	</a>
						                	</td>
							                <td>
							                	<a href="javascript:;" class="editable tolerancia_extra" data-semana="<?php echo $semana['num_semana']?>" data-name='tolerancia_extra' data-pk="<?php echo count($semana['config']) > 0 ?$semana['config']->id_config_horario:null?>" data-type="text"  data-url="/rh/config-horario/form">
							                		<?php echo $semana['config']? $semana['config']->tolerancia_extra: null?>
							                	</a>
						                	</td>
							                <td>
							                	<a href="javascript:;" class="editable tolerancia_falta" data-semana="<?php echo $semana['num_semana']?>" data-name='tolerancia_falta' data-pk="<?php echo count($semana['config']) > 0 ?$semana['config']->id_config_horario:null?>" data-type="text"  data-url="/rh/config-horario/form">
							                		<?php echo $semana['config']?$semana['config']->tolerancia_falta: null?>
							                	</a>
						                	</td>
							                <td>
							                	<a href="javascript:;" class="editable fechamento" data-semana="<?php echo $semana['num_semana']?>" data-name='fechamento' data-pk="<?php echo count($semana['config']) > 0 ?$semana['config']->id_config_horario:null?>" data-type="text"  data-url="/rh/config-horario/form">
							                		<?php echo $semana['config']?$semana['config']->fechamento: null?>
							                	</a>
						                	</td>
							                <td>
							                	<a href="javascript:;" class="editable almoco_livre" data-semana="<?php echo $semana['num_semana']?>" data-name='almoco_livre' data-type="text" data-pk="<?php echo count($semana['config']) > 0 ?$semana['config']->id_config_horario:null?>" data-value="<?php echo $semana['config'] ? $semana['config']->almoco_livre:null?>" data-url="/rh/config-horario/form">
							                		<?php echo $semana['config']?$this->booleanTranslate( $semana['config']->almoco_livre): $this->booleanTranslate(false)?>
							                	</a>
						                	</td>
							                <td>
							                	<a href="javascript:;" class="editable compensado" data-semana="<?php echo $semana['num_semana']?>" data-name='compensado' data-type="text" data-pk="<?php echo count($semana['config']) > 0 ?$semana['config']->id_config_horario:null?>" data-value="<?php echo $semana['config']?$semana['config']->compensado:null?>" data-url="/rh/config-horario/form">
							                		<?php echo $semana['config']? $this->booleanTranslate($semana['config']->compensado):$this->booleanTranslate(false)?>
							                	</a>
						                	</td>
							                <td>
							                	<a href="javascript:;" class="editable carga" data-semana="<?php echo $semana['num_semana']?>" data-pk="<?php echo count($semana['config']) > 0 ?$semana['config']->id_config_horario:null?>" >
							                		<?php echo $semana['config']? $this->sumTime($semana['config']->entrada1,$semana['config']->saida1,$semana['config']->entrada2, $semana['config']->saida2, 'H:i' ):'-------'?>
							                	</a>
						                	</td>
							            </tr>
							        <?php endforeach;?>
								<?php endif;?>
									</tbody>
								</table>
							</div>
							<div class="tab-pane" id="tab_extra">
								<table class="table-bordered table-striped table-condensed flip-content" style="width: 100%;">
									<thead class="flip-content">
										<tr>
											<th style="width: 100px"></th>
								            <th>abaixo de 2h</th>
								            <th>2h a 4h</th>
								            <th>acima de 4h</th>
										</tr>
									</thead>
									<tbody>
											<?php foreach ($this->configExtraList as $configExtra):?>
											<tr>
											<td>
												<?php echo $configExtra['name_tipo']?>
											</td>
											<?php for($i=0; $i < 3; $i++):?>
												<td>
								                	<a href="javascript:;" class="editable extra" data-tipo_dia="<?php echo $configExtra['tipo_dia']?>" data-name='porcentagem_desconto' data-pk="<?php echo !empty($configExtra['config'][$i])? $configExtra['config'][$i]['id_config_extra']:null ?>" data-type="text" data-horario_inicio="<?php echo getHorarioInicial($i)?>" data-horario_fim="<?php echo getHorarioFim($i)?>" data-url="/rh/config-extra/form">
								                		<?php if(!empty($configExtra['config'][$i])):?>
								                			<?php echo $configExtra['config'][$i]['banco_horas']? "Banco de horas":$configExtra['config'][$i]['porcentagem_desconto'] ?>
								                		<?php endif;?>
								                	</a>
								                	<a class="banco-hora" title="Banco de horas" href="javascript:;"><i class="icon-time"></i></a>
												</td>
											<?php endfor;?>
											</tr>
											<?php endforeach;?>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>
					<!--END TABS-->
				<?php endif;?>
				<div class="form-actions">
					<a href="<?php echo $this->baseUrl('rh/horario/grid'); ?>" class="btn button-previous" style="display: inline-block;">
						<i class="m-icon-swapleft"></i> Voltar 
					</a>
		          	<button class="btn green" type="submit">
		          		Salvar
		        	</button>
		        	<button class="btn blue duplicar-semana">
		          		Duplicar
		        	</button>
				</div>
			</form>
		</div>
	</div>
</div>
<div id="grid-funcionario-horario">
</div>

<div id="dialog-funcionario" style="display: none">
	<div class="row-fluid">
		<div class="span12">
			<div class="control-group">
				<label class="control-label">Funcionário</label>
				<div class="controls">
					<?php echo $this->formHidden('id_horario_funcionario')?>
					<?php echo $this->formSelect('id_funcionario', null,array('class'=> 'span12'),$this->comboFuncionario)?>
				</div>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<div class="control-group">
				<label class="control-label">Data</label>
				<div class="controls">
					<?php echo $this->formText('data', null, array('class'=> 'span6'))?>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="dialog-semana" style="display: none">
	<div class="row-fluid">
		<div class="span12">
			<div class="control-group">
				<label class="control-label">Semana de:</label>
				<div class="controls">
					<?php echo $this->formSelect('semana_de', null,array('class'=> 'span6'),$this->semanaList)?>
				</div>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<div class="control-group">
				<label class="control-label">Semana para:</label>
				<div class="controls">
					<div class="btn-group">
						<button class="btn semana_para" value="1" style="display:none">SEG</button>
						<button class="btn semana_para" value="2">TER</button>
						<button class="btn semana_para" value="3">QUA</button>
						<button class="btn semana_para" value="4">QUI</button>
						<button class="btn semana_para" value="5">SEX</button>
						<button class="btn semana_para" value="6">SAB</button>
						<button class="btn semana_para" value="7">DOM</button>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="dialog-delete-func" style="display: none">
	<p>Deseja realmente excluir este registro.</p>
</div>
<script type="text/javascript" src="/assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
<script type="text/javascript" src="/assets/plugins/bootstrap-datepicker/js/locales/bootstrap-datepicker.pt-BR.js"></script>
<script src="/assets/plugins/bootstrap-timepicker/js/bootstrap-timepicker.js" type="text/javascript"></script>
<!-- BEGIN X-EDITABLE PLUGIN-->
  <script src="/assets/plugins/bootstrap-editable/bootstrap-editable/js/bootstrap-editable.js" type="text/javascript"></script>
  <script src="/assets/plugins/bootstrap-editable/inputs-ext/address/address.js" type="text/javascript"></script>
  <script src="/assets/plugins/bootstrap-editable/inputs-ext/wysihtml5/wysihtml5.js" type="text/javascript"></script>
<!-- END X-EDITABLE PLUGIN-->
  <script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/select2/select2.min.js')?>"></script>
  <script src="/scripts/rh/calculo.time.js" type="text/javascript"></script>
  <script src="/scripts/rh/horario.form.js" type="text/javascript"></script>
  
  <?php 
  function getHorarioInicial($i){
	switch ($i) {
		case 0:
			return '0:00';
			break;
		case 1:
			return '2:00';
			break;
		case 2:
			return '4:00';
			break;
		}
  }
  function getHorarioFim($i){
	switch ($i) {
		case 0:
			return '2:00';
			break;
		case 1:
			return '4:00';
			break;
		case 2:
			return '23:59';
			break;
	}
  }
  ?>
