<div class="row-fluid">
	<div class="span12">
		<?php if(count($this->configHorarioPadrao)>1):?>
		
		<div class="tabbable tabbable-custom">
			<ul class="nav nav-tabs">
				<?php $i = 0?>
				<?php foreach ($this->configHorarioPadrao as $key => $configHorarioPadrao): ?>
				<li <?php echo $i == 0? "class='active'": null?>><a href="#horario-padrao-<?php echo $i?>" data-toggle="tab"><?php echo $this->date($key) ?></a></li>
				<?php $i++?>
				<?php endforeach;?>
			</ul>
			<div class="tab-content">
		<?php endif;?>
			<?php $i = 0?>
			<?php foreach ($this->configHorarioPadrao as $key=>$configHorarioPadrao):?>
				<div class="tab-pane  <?php echo $i == 0? 'active': null?>" id="horario-padrao-<?php echo $i?>">
					<table class="table table-striped table-hover table-bordered grid-horario" style="margin-bottom: 0">
						<thead>
							<tr>
								<th></th>
								<th>Entrada 1</th>
								<th>Saída 1</th>
								<th>Entrada 2</th>
								<th>Saída 2</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($configHorarioPadrao as $configHorario):?>
							    <tr>
							        <td><?php echo $configHorario['nome_semana']?></td>
							        <td><?php echo $configHorario['config'] ? $configHorario['config']->entrada1: null?></td>
							        <td><?php echo $configHorario['config'] ? $configHorario['config']->saida1 : null?></td>
							        <td><?php echo $configHorario['config'] ? $configHorario['config']->entrada2: null?></td>
							        <td><?php echo $configHorario['config'] ? $configHorario['config']->saida2: null?></td>
							    </tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>
				<?php $i++?>
			<?php endforeach;?>
		
		<?php if(count($this->configHorarioPadrao)>1):?>
			</div>
		</div>
		<?php endif;?>
	</div>
</div>