<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('/assets/plugins/bootstrap-datetimepicker/css/datetimepicker.css')?>" />
<div class="row-fluid">
  <div class="span12">
    <h3 class="page-title">
      Registro
      <small> de Freelancer</small>
    </h3>
  </div>
</div>
<div class="row-fluid">
  <div class="portlet box blue">
    <div class="portlet-title">
      <div class="caption"><i class=" icon-dollar"></i> Formulário</div>
      <div class="tools">
        <a href="javascript:;" class="collapse"></a>
      </div>
      <div class="actions">
        <a class="btn " href="<?php echo $this->baseUrl("/freelancer/tarefa/form") ?>"><i class="icon-pencil"></i> Novo </a>
      </div>
    </div>
    <div class="portlet-body form">
      <form id="form" method="post" action="">
        <?php echo $this->formHidden('id_tarefa', $this->vo->id_tarefa);?>
        <div class="row-fluid">
          <div class="span3">
            <div class="control-group">
              <div>
                <label class="control-label"><?php echo $this->translate('Freelancer')?><span class="required">*</span></label>
                <?php echo $this->formHidden('id_empresa', $this->vo->id_empresa); ?>
                <?php echo $this->formText('id_empresa_selected', $this->vo->id_empresa ? $this->vo->getEmpresa()->nome_razao : ''); ?>
              </div>
            </div>
          </div>
          <div class="span4">
              <div class="control-group">
                <label class=" control-label"><?php echo $this->translate('Data')?><span class="required">*</span></label>
                <div class="controls">
                     <div class="input-append date form_datetime">
                        <?php echo $this->formText('dt_inicio',$this->date($this->vo->dt_inicio,'dd/MM/yyyy HH:mm'), array('class'=>'m-wrap span5','placeholder' => "Início"));?>
                        <span class="add-on" style="margin-right: 5px;"><i class="icon-calendar"></i> </span>
                        <?php echo $this->formText('dt_fim',$this->date($this->vo->dt_fim, 'dd/MM/yyyy HH:mm'), array( 'class'=>'m-wrap span5','placeholder' => "Fim"));?>
                        <span class="add-on"><i class="icon-calendar"></i> </span>
                    </div>
                </div>
              </div>
          </div>
          <div class="span3">
            <div class="control-group">
              <label class="control-label"><?php echo $this->translate('Percentual Completado')?></label>
              <div class="controls">
                <?php echo $this->formText('percentual_completado', $this->vo->percentual_completado,array('readonly' => 'readonly' )); ?>%
                <div id='slider-range'></div>
              </div>
            </div>
          </div>
        </div>
        <div class="row-fluid">
          <div class="span12">
            <div class="control-group">
              <label class="control-label"><?php echo $this->translate('Descrição da Tarefa')?><span class="required">*</span></label>
              <div class="controls">
                <textarea name='descricao' id='descricao' rows="4" cols="50" style='width: 80%'><?php echo $this->vo->descricao ?></textarea>
              </div>
            </div>
          </div>
        </div>
        <div class="row-fluid">
          <div class="span3">
            <div class="control-group">
              <label class="control-label"><?php echo $this->translate('Horas Trabalhadas')?></label>
              <div class="controls">
                <?php echo $this->formText('horas_trabalhadas', $this->vo->horas_trabalhadas); ?>
              </div>
            </div>
          </div>
          <div class="span3">
            <div class="control-group">
              <label class="control-label"><?php echo $this->translate('Tarefa Concluida')?></label>
              <div class="controls">
                <input type='checkbox' name='concluido' value ='1' <?php echo $this->vo->concluido == 1 ? 'checked = checked ': '' ?>></input>
              </div>
            </div>
          </div>
        </div>
        <div class="form-actions">
          <a href='/freelancer/tarefa/grid' class="btn blue">Voltar</a>
          <button type="submit" class="btn green"><i class="icon-ok"></i>Salvar</button>
        </div>
      </form>
    </div>
  </div>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl('/assets/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js')?>" charset="UTF-8"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('/assets/plugins/bootstrap-datetimepicker/js/locales/bootstrap-datetimepicker.pt-BR.js')?>" charset="UTF-8"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("/scripts/freelancer/tarefa.form.js")?>"></script>
