<style>
<!--
.dataTables_filter{
  float: right;
}

.dataTables_paginate{
  margin: 0px;
  float: right;
}

-->
</style>
<div class="row-fluid">
     <div class="span12">
        <h3 class="page-title">
         Registro
          <small> de freelancer</small>
        </h3>
     </div>
</div>
<div class="row-fluid">
  <div class="span12">
    <div class="portlet box blue">
      <div class="portlet-title">
        <div class="caption"><i class="icon-dollar"></i>Registros</div>
        <div class="tools">
                    <a href="javascript:;" class="collapse"></a>
                </div>
        <div class="actions">
          <a class="btn " href="<?php echo $this->baseUrl("/freelancer/tarefa/form") ?>"><i class="icon-pencil"></i> Novo </a>
        </div>
      </div>
      <div class="portlet-body flip-scroll">
        <div id="sample_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
          <table class="table-bordered table-striped table-condensed flip-content" id="tarefaTable">
            <thead class="flip-content">
              <tr>
                <th>Código</th>
                <th>Freelancer</th>
                <th>Descrição</th>
                <th>Data de início</th>
                <th>Data de término</th>
                <th>Percentual</th>
                <th>Concluído</th>
                <th>Horas trabalhadas</th>
                <th class="action">Ação</th>
              </tr>
            </thead>

            <tbody>
              <?php if (count($this->freelancerList) > 0):?>
                <?php foreach ($this->freelancerList as $tarefa):?>
                    <tr class="odd gradeX">
                        <td><?php echo $tarefa->id_tarefa?></td>
                        <td><?php echo $tarefa->getEmpresa()->nome_razao?></td>
                        <td><?php echo $tarefa->descricao?></td>
                        <td><?php echo $this->Date($tarefa->dt_inicio,'dd/MM/yyyy HH:mm')?></td>
                        <td><?php echo $this->Date($tarefa->dt_fim,'dd/MM/yyyy HH:mm')?></td>
                        <td>
                          <div class='progress'>
                            <div class='progress-bar progress-bar-info' role='progressbar' aria-valuenow='<?php echo $tarefa->percentual_completado?>' aria-valuemin='0' aria-valuemax='100' style='width:70%;background-color: greenyellow;text-align: center;'>
                              <?php echo $tarefa->percentual_completado?>%
                            </div>
                          </div>
                          </td>
                        <td><?php echo $tarefa->concluido == 1 ? 'Sim' : 'Não'?></td>
                        <td><?php echo $tarefa->horas_trabalhadas?></td>
                        <td class="acoes">
                            <a href="<?php echo $this->baseUrl("freelancer/tarefa/form/id_tarefa/{$tarefa->id_tarefa}")?>">
                                <img title="Editar Tarefa" data-tooltip src="<?php echo $this->baseUrl('images/edit.png')?>" />
                            </a>
                            <a class="deleteMoldal" name = "<?php echo $tarefa->id_tarefa ?>" value = "<?php echo $tarefa->id_tarefa?>" href="#">
                                <img title="Excluir" data-tooltip src="<?php echo $this->baseUrl('images/delete.png')?>"/>
                            </a>
                        </td>
                    </tr>
                <?php endforeach;?>
          <?php endif;?>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="dialog_delete" style="display: none;">
  <p>Deseja realmente excluir a tarefa: <span id ="valueDelete"></span></p>
</div>
<script src='<?php echo $this->baseUrl('/scripts/freelancer/tarefa.grid.js')?>'></script>
