<?php
    /**
     * formulario do controller item para cadastrar e editar os item e sendo redirecionado para a pagina da grid
    */
?>
<link href="<?php echo $this->baseUrl('/assets/plugins/dropzone/css/dropzone.css')?>" rel="stylesheet"/>
<style>
<!--
.dropzone .dz-default.dz-message {
    background-image: none;
}
.zoom .zoom-icon {
    background-image: none;
}
-->
</style>
<div class="row-fluid">
    <div class="span12">
        <h3 class="page-title">
            Cadastro
             <small> de Produto</small>
        </h3>
    </div>
</div>
<ul class="breadcrumb">
    <?php
    if (!empty($this->grupo->id_grupo)):
        echo "<li><a href='/material/grupo/index'> <strong>Grupo</strong> - ".$this->grupo->nome."</a></li>";
    elseif (!empty($this->subgrupo->id_subgrupo)):
        echo  "<li><a href='/material/grupo/index'><strong>Grupo</strong> - ".$this->subgrupo->getGrupo()->nome."</a><i class='icon-angle-right'></i></li>";
        echo  "<li><a href='/material/grupo/index'><strong>Subgrupo</strong> - ".$this->subgrupo->nome."</a></li>";
    elseif (!empty($this->classe->id_classe)):
        echo  "<li> <a href='/material/grupo/index'><strong>Grupo</strong> - ".$this->classe->getSubgrupo()->getGrupo()->nome."</a> <i class='icon-angle-right'></i></li>";
        echo  "<li><a href='/material/grupo/index'><strong>Subgrupo</strong> - ".$this->classe->getSubgrupo()->nome." </a><i class='icon-angle-right'></i></li>";
        echo  "<li><a href='/material/grupo/index'><strong>Classe</strong> - ".$this->classe->nome."</a></li>";
    endif;
    ?>
</ul>
<div class="row-fluid">
    <div class="portlet box purple" id="form_wizard">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-reorder"></i> Formulário - <span class="step-title">Passo 1 de 3</span>
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse"></a>
            </div>
        </div>
        <div class="portlet-body form">
            <form method="post" id="form_item">
                    <div class="form-wizard">
                        <div class="navbar steps">
                            <div class="navbar-inner">
                                <ul class="row-fluid">
                                    <li class="span3" id-tab="1">
                                        <a href="#tab1" data-toggle="tab" class="step active" >
                                        <span class="number">1</span>
                                        <span class="desc"><i class="icon-ok"></i> Principal</span>
                                        </a>
                                    </li>
                                    <li class="span3" id-tab="2">
                                        <a href="#tab2" data-toggle="tab" class="step">
                                        <span class="number">2</span>
                                        <span class="desc"><i class="icon-ok"></i> Imagem</span>
                                        </a>
                                    </li>
                                    <li class="span3" id-tab="3">
                                        <a href="#tab3" data-toggle="tab" class="step">
                                        <span class="number">3</span>
                                        <span class="desc"><i class="icon-ok"></i> Atributo</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div id="bar" class="progress progress-success progress-striped">
                            <div class="bar"></div>
                        </div>
                        <div class="tab-content">
                            <div class="tab-pane active" id="tab1">
                              <?php echo $this->formHidden('id_item', $this->vo->id_item);?>
                              <?php echo $this->formHidden('id_grupo', $this->grupo->id_grupo);?>
                              <?php echo $this->formHidden('id_subgrupo', $this->subgrupo->id_subgrupo);?>
                              <?php echo $this->formHidden('id_classe', $this->classe->id_classe);?>
                              <?php if($this->disableGroup):?>
                              <div class="row-fluid">
                                  <div class="span4">
            						<div class="control-group">
            								<label class=" control-label"><?php echo $this->translate('Grupo')?></label>
            		                    <div class="controls">
            								<?php echo $this->formSelect('combo_grupo',$this->vo->id_grupo, array('class' => 'span10'), $this->grupoCombo);?>
            							</div>
            						</div>
                                  </div>
                                  <div class="span4">
            						<div class="control-group">
            								<label class=" control-label"><?php echo $this->translate('Sub-Grupo')?></label>
            		                    <div class="controls">
            								<?php echo $this->formSelect('combo_subgrupo',$this->vo->id_subgrupo, array('class' => 'span10'), array('---- Selecione ----'));?>
            							</div>
            						</div>
                                  </div>
                                  <div class="span4">
            						<div class="control-group">
            								<label><?php echo $this->translate('Classe')?></label>
            		                    <div class="controls">
            								<?php echo $this->formSelect('combo_classe',$this->vo->id_classe, array('class' => 'span10'), array('---- Selecione ----'));?>
            							</div>
            						</div>
                                  </div>
                              </div>
                          <?php endif;?>
            				<div class="row-fluid">
            					<div class="span6">
            						<div class="control-group">
            								<label class=" control-label"><?php echo $this->translate('Nome')?> <span class="required">*</span></label>
            		                    <div class="controls">
            								<?php echo $this->formText('nome',$this->vo->nome, array('class' => 'span12'));?>
            							</div>
            						</div>
            					</div>
            					<div class="span6">
            					    <div class="control-group">
            					       <label class=" control-label"><?php echo $this->translate('Tipo de produto')?> <span class="required">*</span></label>
            					       <div class="controls">
                                            <div class="span4">
                                                <label class="inline"><input type="checkbox" <?php echo !empty($this->vo->materia_prima)? 'CHECKED' :'' ?> name="materia_prima" value="1"> <?php echo $this->translate('Matéria Prima')?></label>
                                            </div>
                                            <div class="span4">
                                                <label class="inline"><input type="checkbox" <?php echo !empty($this->vo->revenda)? 'CHECKED' :'' ?> name="revenda" value="1"> <?php echo $this->translate('Terceiros pra revenda')?></label>
                                            </div>
                                            <div class="span4">
                                                <label class="inline"><input type="checkbox" <?php echo !empty($this->vo->produto_finalizado)? 'CHECKED' :'' ?> name="produto_finalizado" value="1"> <?php echo $this->translate('Produto finalizado')?></label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
            				</div>
                          <div class="row-fluid">
                              <div class="span3">
                                <div class="control-group">
                                  <label class=" control-label"><?php echo $this->translate('Unidade de compra')?><span class="required">*</span> <a href="#" class="btn add-unidade" style="padding: 0 10px;"><i class="icon-plus"></i> Nova unidade</a></label>
                                  <div class="controls">
                                    <?php echo $this->formSelect('id_tipo_unidade_compra', $this->vo->id_tipo_unidade_compra, array('class' => 'span12'), $this->tipoUnidade)?>
                                  </div>
                                </div>
                              </div>
                              <div class="span3">
                                <div class="control-group">
                                  <label class=" control-label"><?php echo $this->translate('Unidade de consumo')?><span class="required">*</span> <a href="#" class="btn add-unidade" style="padding: 0 10px;"><i class="icon-plus"></i> Nova unidade</a></label>
                                  <div class="controls">
                                      <?php echo $this->formSelect('id_tipo_unidade_consumo', $this->vo->id_tipo_unidade_consumo, array('class' => 'span12'), $this->tipoUnidade)?>
                                  </div>
                                </div>
                              </div>
                              <div class="span3">
                                <div class="control-group">
                                  <label class=" control-label" title="Nomenclatura Comum do Mercosul/Sistema Harmonizado"><?php echo $this->translate('NCM/SH')?></label>
                                  <div class="controls">
                                      <?php echo $this->formText('ncm_sh', $this->vo->ncm_sh, array('class' => 'span12'))?>
                                  </div>
                                </div>
                              </div>
                          </div>
                          <div class="row-fluid">
                              <div class="span3">
                                <div class="control-group">
                                  <label class=" control-label"><?php echo $this->translate('Referência')?></label>
                                  <div class="controls">
                                      <?php echo $this->formText('referencia', $this->vo->referencia, array('class' => 'span12'))?>
                                  </div>
                                </div>
                              </div>
                              <div class="span3">
                                <div class="control-group">
                                  <label class=" control-label"><?php echo $this->translate('Valor de revenda')?></label>
                                  <div class="controls">
                                      <?php echo $this->formText('valor_revenda', $this->formatDecimal(floatval($this->vo->valor_revenda)), array('class' => 'span12 decimal', 'alt' => 'decimal'))?>
                                  </div>
                                </div>
                              </div>
                          </div>
                          <div class="row-fluid">
                              <div class="span12">
                                <div class="control-group">
                                  <label class=" control-label" title="Nomenclatura Comum do Mercosul/Sistema Harmonizado"><?php echo $this->translate('Descrição')?></label>
                                  <div class="controls">
                                      <?php echo $this->formTextarea('descricao', $this->vo->descricao, array('rows' => "5", 'class' => 'span'))?>
                                      <span id="countDescricao"></span> Caracteres restantes
                                  </div>
                                </div>
                              </div>
                          </div>
                          <div class="form-actions">
                            <a href="javascript:history.back()" class="btn" >Voltar</a>
                            <button type="submit" class="btn blue"><i class="icon-ok"></i> Salvar</button>
                          </div>
                        </div>
                        <div class="tab-pane" id="tab2">
                            <h3 class="block">Imagem</h3>
                            <div class="row-fluid">
                            	<div class="span6">
                                    <div class="control-group">
                                      <label class=" control-label"><?php echo $this->translate('Upload de imagem')?> (Arraste os arquivos para fazer o upload ou click)</label>
                                    </div>
                            		<div class="dropzone" id="my-awesome-dropzone"></div>
                            		<p>
                            			<span class="label label-important">OBSERVAÇÃO:</span>&nbsp;
                            			Somente arquivos de imagem jpg, jpeg, png e gif.
                            		</p>
                            	</div>
                            	<div class="span6" id="grid_image">
                            	</div>

                        	</div>
                        </div>
                        <div class="tab-pane" id="tab3">
                            <h3 class="block">Atributo</h3>
                            <div class="row-fluid" style=" <?php echo $this->vo->id_item ? "": 'display:none'?>">
                            <a href="#" class="icon-btn span2 new atributo">
                                <i class="icon-list-ol"></i>
                                <div>Atributo</div>
                            </a>
                        </div>
                        <div id="grid_atributo"></div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div id="dialog-unidade" style="display:none">
    <div class="row-fluid">
        <div class="span12">
                <div class="control-group">
                    <label class="control-label"><?php echo $this->translate('Nome')?></label>
                    <div class="controls">
                        <?php echo $this->formText('nome_unidade')?>
                    </div>
                </div>
        </div>
    </div>
</div>
<div class="dialog_atributo" style=" display: none">
    <form action="" id="formAtributo" style="margin: 0;">
        <div class="row-fluid">
            <div class="span12 ">
                <div class="control-group">
                    <label class="control-label"><?php echo $this->translate('Atributo')?></label>
                    <div class="controls">
                        <?php echo $this->formSelect('id_atributo', null, array('class'=> 'span12'), $this->comboAtributo)?>
                    </div>
                </div>
            </div>
            <div class="span12 " style="margin-left: 0">
                <div class="control-group">
                    <label class="control-label"><?php echo $this->translate('Opções')?></label>
                    <div class="controls htmlOpcao">
                        <select multiple="multiple" id="mult_opcao" name="opcao[]" style="margin-left: 0">
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<div id="dialog_delete" style="display: none;">
	<p style="font-size: 16px;padding-top: 6px;margin-bottom: 0;">Deseja realmente excluir este atributo?</p>
</div>

<div id="dialog_delete_arquivo" style="display: none;">
	<p style="font-size: 16px;padding-top: 6px;margin-bottom: 0;">Deseja realmente excluir esta imagem?</p>
</div>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('/assets/plugins/jquery-multi-select/css/multi-select-metro.css')?>" />
<script type="text/javascript" src="<?php echo $this->baseUrl('/scripts/lib/jquery.limit-1.2.source.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/jquery-multi-select/js/jquery.multi-select.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('/assets/plugins/dropzone/dropzone.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/bootstrap-wizard/jquery.bootstrap.wizard.min.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/material/item.form.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/material/item.form.dropzone.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/material/item.form.wizard.js')?>"></script>
