<?php
    /**
     * grid do item aonde visualiza todos os produtos cadastrados no sistemas e ativos
     * com link pra criar, alterar e inativar.
    */
?>
<style>
<!--
.dataTables_filter{
	float: right;
}

.dataTables_paginate{
	margin: 0px;
	float: right;
}

-->
</style>
<div class="row-fluid">
     <div class="span12">
	      <h3 class="page-title">
	       Registro
	        <small> do produto</small>
	      </h3>
     </div>
</div>
<ul class="breadcrumb">
    <?php
    if (!empty($this->grupo->id_grupo)):
        echo "<li><a href='/material/grupo/index'> <strong>Grupo</strong> - ".$this->grupo->nome."</a></li>";
    elseif (!empty($this->subgrupo->id_subgrupo)):
        echo  "<li><a href='/material/grupo/index'><strong>Grupo</strong> - ".$this->subgrupo->getGrupo()->nome."</a><i class='icon-angle-right'></i></li>";
        echo  "<li><a href='/material/grupo/index'><strong>Subgrupo</strong> - ".$this->subgrupo->nome."</a></li>";
    elseif (!empty($this->classe->id_classe)):
        echo  "<li> <a href='/material/grupo/index'><strong>Grupo</strong> - ".$this->classe->getSubgrupo()->getGrupo()->nome."</a> <i class='icon-angle-right'></i></li>";
        echo  "<li><a href='/material/grupo/index'><strong>Subgrupo</strong> - ".$this->classe->getSubgrupo()->nome." </a><i class='icon-angle-right'></i></li>";
        echo  "<li><a href='/material/grupo/index'><strong>Classe</strong> - ".$this->classe->nome."</a></li>";
    endif;
    ?>
</ul>
<div class="row-fluid">
	<div class="span12">
		<div class="portlet box purple">
			<div class="portlet-title">
				<div class="caption"><i class="icon-wrench"></i>Produto</div>
				<div class="tools">
                    <a href="javascript:;" class="collapse"></a>
                </div>
				<div class="actions">
					<a class="btn blue" href="<?php echo $this->params('material/item/form', array('id_grupo'     => $this->grupo->id_grupo,
                                                                                                'id_subgrupo'  => $this->subgrupo->id_subgrupo,
                                                                                                'id_classe'    => $this->classe->id_classe
                                                                                              ))?>" "><i class="icon-plus"></i> Novo produto </a>

                    <div class="btn-group">
                        <button id="mudar-grupo" class="btn green">
                        <i class="icon-random"></i> Mudar grupo
                        </button>
                    </div>
				</div>
			</div>
			<div class="portlet-body flip-scroll">
				<div id="sample_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
					<table class="table-bordered table-striped table-condensed flip-content" id="datatables">
                        <thead class="flip-content">
                            <tr>
                                <th style="width: 50px"><input type="checkbox" class="all-checkbox" /></th>
                                <th style="width: 100px">Código</th>
                                <th>Nome</th>
                                <th style="width: 120px">Unidade de compra</th>
                                <th style="width: 130px">Unidade de consumo</th>
                                <th style="width: 140px">Matéria-Prima</th>
                                <th style="width: 135px; text-align:center" >Terceiros para revenda</th>
                                <th style="width: 96px; text-align:center">Produto finalizado</th>
                                <th style="width: 90px">Ação</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->listItem as $item):?>
                                <tr class="odd gradeX">
                                    <td style="text-align: center;"><input type="checkbox" value="<?php echo $item['id_item']?>" class="produto-checkbox" name="produto-checkbox[]" /></td>
                                    <td  style="text-align:center"><?php echo $item['id_item']?></td>
                                    <td><?php echo $item['nome']?></td>
                                    <td><?php echo $item['nome_unidade_compra'] ?></td>
                                    <td><?php echo $item['nome_unidade_consumo']?></td>
                                    <td style="text-align:center"><?php echo $item['materia_prima'] ? "Sim": "Não";?></td>
                                    <td style="text-align:center"><?php echo $item['revenda'] ? "Sim": "Não";?></td>
                                    <td style="text-align:center"><?php echo $item['produto_finalizado'] ? "Sim": "Não";?></td>
                                    <td>
                                        <a href="<?php echo $this->params('material/item/form', array('id'           => $item['id_item'],
                                                                                                      'id_grupo'     => $this->grupo->id_grupo,
                                                                                                      'id_subgrupo'  => $this->subgrupo->id_subgrupo,
                                                                                                      'id_classe'    => $this->classe->id_classe
                                                                                                      ))?>">
                                            <img src="<?php echo $this->baseUrl('images/edit.png')?>" data-tooltip title="Editar">
                                        </a>
                                        <a href="<?php echo $this->params('material/item/delete', array('id'           => $item['id_item'],
                                                                                                      'id_grupo'     => $this->grupo->id_grupo,
                                                                                                      'id_subgrupo'  => $this->subgrupo->id_subgrupo,
                                                                                                      'id_classe'    => $this->classe->id_classe
                                                                                                      ))?>" class="delete">
                                            <img src="<?php echo $this->baseUrl('images/delete.png')?>" data-tooltip title="Remover">
                                        </a>
                                        <a href="<?php echo $this->params('material/item/form', array('id_duplicate' => $item['id_item'],
                                                                                                      'id_grupo'     => $this->grupo->id_grupo,
                                                                                                      'id_subgrupo'  => $this->subgrupo->id_subgrupo,
                                                                                                      'id_classe'    => $this->classe->id_classe
                                                                                                      ))?>">
                                            <img style="width: 16px" src="<?php echo $this->baseUrl('images/duplicate.png')?>" data-tooltip title="Duplicar">
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach;?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="dialog-muda-grupo" style="display:none">
    <div class="row-fluid">
        <div class="span4">
                <div class="control-group">
                    <label class="control-label"><?php echo $this->translate('Grupo')?></label>
                    <div class="controls">
                        <?php echo $this->formSelect('grupo', null, array('class'=> 'span12'), array('' => '---- Selecione ----')+$this->comboGrupo)?>
                    </div>
                </div>
        </div>
        <div class="span4">
                <div class="control-group">
                    <label class="control-label"><?php echo $this->translate('Subgrupo')?></label>
                    <div class="controls">
                        <?php echo $this->formSelect('subgrupo', null, array('class'=> 'span12'), array('' => '---- Selecione ----'))?>
                    </div>
                </div>
        </div>
        <div class="span4">
                <div class="control-group">
                    <label class="control-label"><?php echo $this->translate('Classe')?></label>
                    <div class="controls">
                        <?php echo $this->formSelect('classe', null, array('class'=> 'span12'), array('' => '---- Selecione ----'))?>
                    </div>
                </div>
        </div>
    </div>
</div>
<script src="<?php echo $this->baseUrl('scripts/material/item.grid.js')?>"></script>