<div class="row-fluid">
    <div class="span12">
        <table class="table-bordered table-striped table-condensed flip-content" style="width: 100%;">
            <thead class="flip-content">
                <tr>
                    <th style="width: 120px">Atributo</th>
                    <th>Opção</th>
                    <th class="action" colspan="2">Ação</th>
                </tr>
            </thead>
            <tbody>
            <?php if (count($this->itemOpcaoList) > 0):?>
            <?php $idAtributo = 0?>
                <?php foreach ($this->itemOpcaoList as $atributo):?>
                    <tr>
                        <td><?php echo $atributo['nome_atributo'] ?></td>
                        <td>
                            <?php foreach ($atributo['opcao'] as $key => $opcao):?>
                                <?php echo $key > 0 ? " | ": ""?>
                                <?php echo $opcao['nome_opcao']?>
                            <?php endforeach;?>
                        </td>
                        <td class="acoes" style="width: 20px">
                            <a href="<?php echo $atributo['id_atributo']?>" id_atributo="<?php echo $atributo['id_atributo']?>" class="editar_atributo tooltips" title="Editar atributo">
                                <img  src="<?php echo $this->baseUrl('images/edit.png')?>" />
                            </a>
                        </td>
                        <td class="acoes" style="width: 20px">
                            <a href="<?php echo $atributo['id_atributo']?>" id_atributo="<?php echo $atributo['id_atributo']?>" class="delete_atributo tooltips" title="excluir atributo">
                                <img   src="<?php echo $this->baseUrl('images/delete.png')?>" />
                            </a>
                        </td>
                    </tr>
                <?php endforeach;?>
            <?php else:?>
                    <tr>
                        <td colspan="8" style="text-align: center">Não existem registros!</td>
                    </tr>
            <?php endif;?>
            </tbody>
        </table>
        <div class="row-fluid">
            <div class="span6">
                <div style="padding-top: 8px;"> Mostrando <?php echo count($this->itemOpcaoList)?> registros</div>
            </div>
        </div>
    </div>
</div>