
<div class="dialog_tipo" style="display:none">
	<div class="control-group">
		<label class="control-label"><?php echo $this->translate('Nome')?></label>
						<div class="controls">
            	<?php echo $this->formText('nome_tp');?>
		</div>
	</div>
</div>
<div id="table_componente">
</div>

<div class="dialog_componente" style="display:none">
<div class="portlet-body form">
      	<form class="form_componente" style="margin: 0">
	      	<div class="row-fluid">
						<div class="control-group">
							<label class="control-label"><?php echo $this->translate('Serviço')?></label>
							<div class="controls">
                <?php echo $this->formHidden('id_servico');?>
                <?php echo $this->formText('nome_servico');?>
							</div>
						</div>
						<div class="row-fluid">
							<div class="span4">
								<div class="control-group">
									<label class="control-label"><?php echo $this->translate('Tipo de Serviço')?></label>
									<div class="controls">
		                <?php echo $this->formSelect('id_tp_servico', null, array('style' => 'margin-bottom: 10px;', 'class' => 'm-wrap small'), $this->comboTpServico);?>
									</div>
								</div>
							</div>
							<div class="span5" style="float: left;">
								<div class="control-group">
									<label class="control-label"><?php echo $this->translate('Componente')?></label>
									<div class="controls">
										<?php echo $this->formSelect('id_tp_componente', null, array('style' => 'margin-bottom: 10px;', 'class' => 'm-wrap'), $this->comboComponente);?>
		                <img src="/images/add_small.png" data-tooltip style="position:relative; cursor:pointer" class="add_tp_componente" title="Adicionar tipo de componente">
									</div>
								</div>
							</div>
						</div>
						<div class="row-fluid">
							<div class="span4">
								<div class="control-group">
									<label class="control-label"><?php echo $this->translate('Valor Unitário')?></label>
									<div class="controls">
										<?php echo $this->formText('id_valor_servico', null, array('disabled' => 'disabled', 'style' => 'display:inline-block;',  'class' => 'm-wrap small'));?>
									</div>
								</div>
							</div>
							<div class="span4">
								<div class="control-group">
									<label class="control-label"><?php echo $this->translate('Quantidade')?></label>
									<div class="controls">
		                <?php echo $this->formText('quantidade_valor',null, array( 'class' => 'm-wrap small'));?>
									</div>
								</div>
							</div>
							<div class="span4">
								<div class="control-group">
									<label class="control-label"><?php echo $this->translate('Valor Total')?></label>
									<div class="controls">
										<?php echo $this->formText('total', null, array('disabled' => 'disabled',  'class' => 'm-wrap small'));?>
									</div>
								</div>
							</div>
						</div>
						<div class="control-group">
							<label class="control-label"><?php echo $this->translate('Caracteristicas')?></label>
							<div class="controls">
								<?php echo $this->formTextarea('caracteristica',null, array( 'style'=> 'width: 395px; height: 113px ;display: inline;'));?>
							</div>
						</div>
		      </div>
	      </form>
      </div>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/service/orcamento.form.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('/scripts/lib/jquery.limit-1.2.source.js')?>"></script>
<script type="text/javascript">
$(document).ready(function(){
    $('#cec_descricao').limit('255','#especificacao');
});
</script>

