<?php
$request = Zend_Controller_Front::getInstance()->getRequest();
$moduleName         = $request->getModuleName();
$controllerName     = $request->getControllerName();
$actionName         = $request->getActionName();
$caminhoForm        = $this->baseUrl($moduleName.'/'.$controllerName.'/form');
$select = array(
    50 => 50,
    100 => 100,
    200 => 200,
    250 => 250
    );
$request = Zend_Controller_Front::getInstance()->getRequest();
$defaultItens = $request->getParam('itens', 250);
    /**
     * grid de processo aonde visualiza todas os processos ativos
     * com link pra criar, alterar e inativar.
     */
?>

<link href="assets/plugins/select2/select2_metro.css" rel="stylesheet" type="text/css"/>
<!-- BEGIN X-EDITABLE PLUGIN-->
  <link href="assets/plugins/bootstrap-editable/bootstrap-editable/css/bootstrap-editable.css" rel="stylesheet" type="text/css" media="screen"/>
  <link href="assets/plugins/bootstrap-editable/inputs-ext/address/address.css" rel="stylesheet" type="text/css" media="screen"/>
<!-- END X-EDITABLE PLUGIN-->
<style>
<!--
.editable{
    color:black;
}
a.editable-click {
  border-bottom: none;
}
a.editable-click.editable-disabled,a.editable-click:hover {
  border-bottom: none;
}
th.transacao{
    width: 80px;
}
td.transacao{
    text-align: center !important;
}
table tr.different_financial td{
    color: #e02222 !important;
}
table tr.different_financial td a.editable{
    color: #e02222 !important;
}
.acoes {
    max-width: 30px;
    min-width: 15px;
}
td.pro_quantidade{
    text-align: center !important;
}
i.acao{
    color:#000;
}
-->
</style>
<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid">
            <a href="<?php echo $this->baseUrl("/processo/processo/form")?>" class="icon-btn span2">
                <i class="icon-cog"></i>
                <div> Novo Pedido </div>
            </a>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <div class="portlet box caribbean-green">
            <div class="portlet-title">
                <div class="caption"><i class="icon-cogs"></i>Listar pedido industrial</div>
            </div>
            <div class="portlet-body">
                <div class="clearfix">
                    <div class="btn-group">
                        <div class="dataTables_length">
                            <?php if ($this->paginator->getTotalItemCount() > $defaultItens): ?>
                                    <label>Mostrar <?php {echo $this->formSelect('itens', $defaultItens, array(), $select);}?></label>
                            <?php endif;?>
                        </div>
                    </div>
                    <div class="btn-group pull-right">
                        <div class="dataTables_filter">
                            <?php
                                $this->columns = (array) $this->columns;
                                $this->actions = (array) $this->actions;
                            ?>
                            <?php if (!$this->desabilitarPesquisa): ?>
                                    <?php echo $this->partial('pesquisa.phtml', 'default', array(
                                            'fields'       => array(	'pro_codigo'        => "Código",
                                                                        'pro_desc_produto'  => 'Descrição',
                                                                        'pro_quantidade'    => 'Quantidade',
                                                                        'pro_vlr_unt'       => 'Valor Unitário',
                                                                        'pro_vlr_pedido'    => 'Valor Pedido',
                                                                        'emp.nome'    => 'Cliente'
                                                                ),
                                            'actionSearch' => $this->actionSearch
                                        ))?>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <div class="dataTables_wrapper form-inline" role="grid">
                    <table class="table table-striped table-hover table-bordered dataTable" aria-describedby="sample_editable_1_info"">
                        <thead>
                            <tr>
                                <th class="pro_codigo">
                                    <div><?php echo $this->translate('Código')?></div>
                                </th>
                                <th class="cliente">
                                    <div><?php echo $this->translate('Cliente')?></div>
                                </th>
                                <th class="sta_descricao" style="width:15%;">
                                    <div><?php echo $this->translate('Status')?></div>
                                </th>
                                <th class="pro_desc_produto" style="width: 30%">
                                    <div><?php echo $this->translate('Descrição')?></div>
                                </th>
                                <th class="pro_quantidade" style="text-align: center">
                                    <div><?php echo $this->translate('Quantidade')?></div>
                                </th>
                                <th class="pro_vlr_unt" style="text-align: right;">
                                    <div><?php echo $this->translate('Valor unitário')?></div>
                                </th>
                                <th class="pro_vlr_pedido"  style="text-align: right;">
                                    <div><?php echo $this->translate('Valor pedido')?></div>
                                </th>
                                <?php if($this->workspaceSession->free_access):?>
                                    <th class="pro_vlr_pedido"  style="text-align: right;">
                                        <div><?php echo $this->translate('Workspace')?></div>
                                    </th>
                                <?php endif;?>
                                <th class="pro_vlr_pedido"  style="text-align: center;">
                                    <div><?php echo $this->translate('Valor da transação')?></div>
                                </th>
                                <th class="pro_vlr_pedido"  style="text-align: center;">
                                    <div><?php echo $this->translate('Data de criação')?></div>
                                </th>
                                <th colspan="4" class = "action" style="text-align: center"><?php echo $this->translate("Ações")?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (count($this->paginator)): ?>
                                <?php foreach ($this->paginator as $key => $pageOBJ): ?>
                                    <?php $page = is_object($pageOBJ) && method_exists($pageOBJ, 'toArray')
                                                ? $pageOBJ->toArray()
                                                : $pageOBJ;
                                    ?>
                                    <tr class="<?php echo $page['total_financeiro'] != $page['pro_vlr_pedido']  ? 'different_financial' : '' ?>" >
                                        <td style="white-space: normal !important; text-align: center; padding-right: 5px;" class="pro_codigo" >
                                            <?php echo $page['pro_codigo']?>
                                        </td>
                                        <td style="white-space: normal !important; text-align: justify; padding-right: 5px;" class="cliente" >
                                            <a href="javascript:;" class="editable cliente" data-name='cliente' data-type="text" data-pk="<?php echo $page['pro_id']?>" data-url="processo/processo/form">
                                                <?php echo $page['cliente']?>
                                            </a>
                                        </td>
                                        <td style="white-space: normal !important; text-align: justify; padding-right: 5px;" class="sta_descricao" >
                                            <a href="javascript:;" class="editable status" data-name='status' data-type="text" data-pk="<?php echo $page['pro_id']?>" data-url="processo/processo/form">
                                                <?php echo $page['sta_descricao']?>
                                            </a>
                                        </td>
                                        <td style="white-space: normal !important; text-align: justify; padding-right: 5px;" class="pro_desc_produto" >
                                            <a href="javascript:;" class="editable pro_desc_produto" data-name='pro_desc_produto' data-type="text" data-pk="<?php echo $page['pro_id']?>" data-url="processo/processo/form">
                                                <?php echo $page['pro_desc_produto']?>
                                            </a>
                                        </td>
                                        <td style="white-space: normal !important; text-align: center; padding-right: 5px;" class="pro_quantidade" >
                                            <a href="javascript:;" class="editable pro_quantidade" data-name='pro_quantidade' data-type="text" data-pk="<?php echo $page['pro_id']?>" data-url="processo/processo/form">
                                                <?php echo number_format($page['pro_quantidade'], 0, ',', '.') ?>
                                            </a>
                                        </td>
                                        <td style="white-space: normal !important; text-align: right; padding-right: 5px;" class="pro_vlr_unt" >
                                            <a href="javascript:;" class="editable pro_vlr_unt" data-name='pro_vlr_unt' data-type="text" data-pk="<?php echo $page['pro_id']?>" data-url="processo/processo/form">
                                                <?php echo $this->formatDecimal($page['pro_vlr_unt'])?>
                                            </a>
                                        </td>
                                        <td style="white-space: normal !important; text-align: right; padding-right: 5px;" class="pro_vlr_pedido" >
                                            <a href="javascript:;" class="editable pro_vlr_pedido" data-name='pro_vlr_pedido' data-type="text" data-pk="<?php echo $page['pro_id']?>" data-url="processo/processo/form">
                                                <?php echo $this->formatDecimal($page['pro_vlr_pedido'])?>
                                            </a>
                                        </td>
                                        <?php if($this->workspaceSession->free_access):?>
                                            <td style="white-space: normal !important; text-align: center; padding-right: 5px;" class="pro_vlr_pedido" >
                                                <?php echo $page['name_workspace']?>
                                            </td>
                                        <?php endif;?>
                                        <td style="white-space: normal !important; text-align: center; padding-right: 5px;" class="pro_vlr_pedido" >
                                            <?php echo $this->formatDecimal($page['total_financeiro'])?>
                                        </td>
                                        <td style="white-space: normal !important; text-align: center; padding-right: 5px;" class="pro_vlr_pedido" >
                                            <?php echo $this->dateHour($page['pro_data_inc'])?>
                                        </td>
                                        <?php //ações do processo ?>
                                        <td class="acoes">
                                            <a href="<?php echo $this->baseUrl("processo/pedido-workspace/form/id_processo/{$pageOBJ['pro_id']}")?>">
                                                <i class="icon-group acao"  title="Pedido por workspace" ></i>
                                            </a>
                                        </td>
                                        <td class="acoes">
                                            <a href="<?php echo $this->baseUrl("financial/agrupador-financeiro/grid-financial-processo-ajax/id_processo/{$pageOBJ['pro_id']}")?>" class="visualizar_financeiro">
                                                <i class="icon-money acao"  title="Dados do financeiros" ></i>
                                            </a>
                                        </td>
                                        <td class="acoes">
                                            <a href="<?php echo $this->baseUrl("material/movimento/movimento-by-processo/pro_id/{$pageOBJ['pro_id']}")?>" class="visualizar_processo">
                                                <i title="Produtos utilizados" class="acao icon-legal"></i>
                                            </a>
                                        </td>
                                          <td class="acoes">
                                            <a title='Editar' href=' <?php echo $this->baseUrl("processo/processo/form/pro_id/".$pageOBJ['pro_id']) ?>'    >
                                                <i  class="acao icon-pencil" ></i>
                                            </a>
                                        </td>
                                    </tr>
                                <?php endforeach;?>
                            <?php else: ?>
                                <tr>
                                    <td colspan="10"><?php echo $this->translate("Não existem registros")?>!</td>
                                </tr>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>
                <?php if ($this->paginator instanceof Zend_Paginator): ?>
                        <?php echo $this->paginationControl($this->paginator, 'Elastic', array('pagination-grid-metronic.phtml', 'default'))?>
                <?php endif;?>
            </div>
        </div>
    </div>
</div>
<div id="dialogProcesso">
    <div class="row-fluid">
        <div class="span12">
        </div>
    </div>
</div>
<div id="dialogFinancial">
    <div class="row-fluid">
        <div class="span12">
        </div>
    </div>
</div>
<script src="assets/plugins/select2/select2.min.js" type="text/javascript"></script>
<!-- BEGIN X-EDITABLE PLUGIN-->
  <script src="assets/plugins/bootstrap-editable/bootstrap-editable/js/bootstrap-editable.js" type="text/javascript"></script>
  <script src="assets/plugins/bootstrap-editable/inputs-ext/address/address.js" type="text/javascript"></script>
  <script src="assets/plugins/bootstrap-editable/inputs-ext/wysihtml5/wysihtml5.js" type="text/javascript"></script>
<!-- END X-EDITABLE PLUGIN-->
<script src="<?php echo $this->baseUrl('scripts/processo/processo.grid.editable.js')?>"></script>
<script src="<?php echo $this->baseUrl('scripts/processo/processo.grid.js')?>"></script>
