<?php
$request = Zend_Controller_Front::getInstance()->getRequest();
$moduleName         = $request->getModuleName();
$controllerName     = $request->getControllerName();
$actionName         = $request->getActionName();
$caminhoForm        = $this->baseUrl($moduleName.'/'.$controllerName.'/form');
$select = array(
    50 => 50,
    100 => 100,
    200 => 200,
    250 => 250
    );
$request = Zend_Controller_Front::getInstance()->getRequest();
$defaultItens = $request->getParam('itens', 250);
    /**
     * grid de processo aonde visualiza todas os processos ativos
     * com link pra criar, alterar e inativar.
     */
?>
<style>
<!--
th.transacao{
    width: 80px;
}
td.transacao{
    text-align: center !important;
}
table tr.different_financial td{
    /** color: #e02222 !important;*/
}
.acoes {
    max-width: 30px;
    min-width: 15px;
}
td.pro_quantidade{
    text-align: center !important;
}
i.acao{
    color:#000;
}
-->
</style>
<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid">
            <a href="<?php echo $this->baseUrl("/processo/processo/form")?>" class="icon-btn span2">
                <i class="icon-cog"></i>
                <div> Novo Pedido </div>
            </a>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <div class="portlet box caribbean-green">
            <div class="portlet-title">
            	<div class="caption"><i class="icon-cogs"></i>Registro de pedido industrial - Pendência</div>
			</div>
			<div class="portlet-body">
            	<div class="clearfix">
					<div class="btn-group">
						<div class="dataTables_length">
							<?php if ($this->paginator->getTotalItemCount() > $defaultItens): ?>
				                    <label>Mostrar <?php {echo $this->formSelect('itens', $defaultItens, array(), $select);}?></label>
				            <?php endif;?>
						</div>
					</div>
					<div class="btn-group pull-right">
						<div class="dataTables_filter">
							<?php
								$this->columns = (array) $this->columns;
								$this->actions = (array) $this->actions;
				           	?>
							<?php if (!$this->desabilitarPesquisa): ?>
									<?php echo $this->partial('pesquisa.phtml', 'default', array(
											'fields'       => array(	'pro_codigo'     => "Código",
                                                                		'pro_desc_produto'    => 'Descrição',
                                                                		'pro_quantidade'    => 'Quantidade',
                                                                		'pro_vlr_unt'    => 'Valor Unitário',
                                                                		'pro_vlr_pedido'      => 'Valor Pedido'
                                                                ),
											'actionSearch' => $this->actionSearch
				                        ))?>
							<?php endif; ?>
						</div>
					</div>
				</div>
				<div class="dataTables_wrapper form-inline" role="grid">
					<table class="table table-striped table-hover table-bordered dataTable" aria-describedby="sample_editable_1_info"">
			            <thead>
			                <tr>
			                    <th class="pro_codigo">
			                        <div><?php echo $this->translate('Código')?></div>
			                    </th>
			                    <th class="cliente">
			                        <div><?php echo $this->translate('Cliente')?></div>
			                    </th>
			                    <th class="sta_descricao" style="width:17%;">
			                        <div><?php echo $this->translate('Status')?></div>
			                    </th>
			                    <th class="pro_desc_produto">
			                        <div><?php echo $this->translate('Descrição')?></div>
			                    </th>
			                    <th class="pro_quantidade" style="text-align: center">
			                        <div><?php echo $this->translate('Quantidade')?></div>
			                    </th>
			                    <th class="pro_vlr_unt" style="text-align: right;">
			                        <div><?php echo $this->translate('Valor unitário')?></div>
			                    </th>
			                    <th class="pro_vlr_pedido"  style="text-align: right;">
			                        <div><?php echo $this->translate('Valor pedido')?></div>
			                    </th>
			                    <th class="pro_vlr_pedido"  style="text-align: right;">
			                        <div><?php echo $this->translate('Valor da transação')?></div>
			                    </th>
			                    <th colspan="3" class = "action" style="text-align: center"><?php echo $this->translate("Ações")?></th>
			                </tr>
			            </thead>
			            <tbody>
			                <?php if (count($this->paginator)): ?>
			                    <?php foreach ($this->paginator as $key => $pageOBJ): ?>
		                            <?php $page = is_object($pageOBJ) && method_exists($pageOBJ, 'toArray')
		                                        ? $pageOBJ->toArray()
		                                        : $pageOBJ;
		                            ?>
			                        <tr class="<?php echo $page['total_financeiro'] != $page['pro_vlr_pedido']  ? 'different_financial' : '' ?>" >
			                            <td style="white-space: normal !important; text-align: center; padding-right: 5px;" class="pro_codigo" >
			                                <?php echo $page['pro_codigo']?>
	                                    </td>
			                            <td style="white-space: normal !important; text-align: justify; padding-right: 5px;" class="cliente" >
			                                <?php echo $page['cliente']?>
	                                    </td>
			                            <td style="white-space: normal !important; text-align: justify; padding-right: 5px;" class="sta_descricao" >
			                                <?php echo $page['sta_descricao']?>
	                                    </td>
			                            <td style="white-space: normal !important; text-align: justify; padding-right: 5px;" class="pro_desc_produto" >
			                                <?php echo $page['pro_desc_produto']?>
	                                    </td>
			                            <td style="white-space: normal !important; text-align: center; padding-right: 5px;" class="pro_quantidade" >
			                                <?php echo number_format($page['pro_quantidade'], 0, ',', '.') ?>
	                                    </td>
			                            <td style="white-space: normal !important; text-align: right; padding-right: 5px;" class="pro_vlr_unt" >
			                                <?php echo $this->formatDecimal($page['pro_vlr_unt'])?>
	                                    </td>
			                            <td style="white-space: normal !important; text-align: right; padding-right: 5px;" class="pro_vlr_pedido" >
			                                <?php echo $this->formatDecimal($page['pro_vlr_pedido'])?>
	                                    </td>
			                            <td style="white-space: normal !important; text-align: right; padding-right: 5px;" class="total_financeiro" >
			                                <?php echo $this->formatDecimal($page['total_financeiro'])?>
	                                    </td>
                                        <?php //ações do processo?>
                                        <td class="acoes">
                		                    <a href="<?php echo $this->baseUrl("financial/agrupador-financeiro/grid-financial-processo-ajax/id_processo/{$pageOBJ['pro_id']}")?>" class="visualizar_financeiro">
                		                        <i class="icon-money acao"  title="Dados do financeiros" ></i>
                		                    </a>
                                        </td>
                                        <td class="acoes">
                		                    <a href="<?php echo $this->baseUrl("material/movimento/movimento-by-processo/pro_id/{$pageOBJ['pro_id']}")?>" class="visualizar_processo">
                		                        <i title="Produtos utilizados" class="acao icon-legal"></i>
                		                    </a>
                                        </td>
                                          <td class="acoes">
                                            <a title='Editar' href=' <?php echo $this->baseUrl("/processo/processo/form/pro_id/".$pageOBJ['pro_id']) ?>'    >
                                                <i  class="acao icon-pencil" ></i>
                                            </a>
                                        </td>
			                        </tr>
			                    <?php endforeach;?>
			                <?php else: ?>
			                    <tr>
			                        <td colspan="10"><?php echo $this->translate("Não existem registros")?>!</td>
			                    </tr>
			                <?php endif; ?>
			            </tbody>
			        </table>
				</div>
				<?php if ($this->paginator instanceof Zend_Paginator): ?>
	            		<?php echo $this->paginationControl($this->paginator, 'Elastic', array('pagination-grid-metronic.phtml', 'default'))?>
        		<?php endif;?>
			</div>
		</div>
	</div>
</div>
<div id="dialogProcesso">
    <div class="row-fluid">
        <div class="span12">
        </div>
    </div>
</div>
<div id="dialogFinancial">
    <div class="row-fluid">
        <div class="span12">
        </div>
    </div>
</div>
<script src="<?php echo $this->baseUrl('scripts/processo/processo.grid.js')?>"></script>
