<style>
<!--
.ui-dialog-titlebar-close {
  display: none;
}
.dataTables_filter{
	float: right;
}

.dataTables_paginate{
	margin: 0px;
	float: right;
}
a i.acao{
	padding: 5px;
	color: #000;
	cursor: pointer;
}
a i.acao:HOVER{
	text-decoration: none;
}
.entidade{
	display: none;
}
-->
</style>
<link href="<?php echo $this->baseUrl('assets/plugins/bootstrap-editable/bootstrap-editable/css/bootstrap-editable.css')?>" rel="stylesheet" type="text/css" media="screen"/>
<link href="<?php echo $this->baseUrl('assets/plugins/bootstrap-editable/inputs-ext/address/address.css')?>" rel="stylesheet" type="text/css" media="screen"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('assets/plugins/select2/select2_metro.css')?>" />
<div style="margin-top: 20px"></div>
<div class="row-fluid">
	<div class="portlet box darkorange" id="form_wizard_1">
		<div class="portlet-title">
			<div class="caption"><i class="fa fa-reorder"></i>Cadastro de Funcionario</div>
			<div class="tools">
				<a href="javascript:;" class="collapse"></a>
			</div>
			<div class="actions">
				<a class="btn" href="<?php echo $this->baseUrl("rh/funcionario/grid") ?>">Listar Funcionario</a>
				<a class="btn" href="<?php echo $this->baseUrl("rh/funcionario/form") ?>">Novo Funcionario</a>
			</div>
		</div>
		<div class="portlet-body form">
			<form action="#" class="form-horizontal" id="form_agrupador" method="post" novalidate="novalidate">
				<div class="form-wizard">
					<div class="navbar steps">
						<div class="navbar-inner">
							<ul class="row-fluid nav nav-pills">
								<li class="span3">
									<a href="#tab1" data-toggle="tab" class="step ">
									<span class="number">1</span>
									<span class="desc"><i class="icon-ok"></i> Dados Pessoais</span>
									</a>
								</li>
								<li class="span3">
									<a href="#tab2" data-toggle="tab" class="step">
									<span class="number">2</span>
									<span class="desc"><i class="icon-ok"></i> Documentos</span>
									</a>
								</li>
								<li class="span3">
									<a href="#tab3" data-toggle="tab" class="step">
									<span class="number">3</span>
									<span class="desc"><i class="icon-ok"></i> Admissão</span>
									</a>
								</li>
								<li class="span3">
									<a href="#tab4" data-toggle="tab" class="step">
									<span class="number">4</span>
									<span class="desc"><i class="icon-ok"></i> Dados Funcionais</span>
									</a>
								</li>
							</ul>
						</div>
					</div>
					<div id="bar" class="progress progress-success progress-striped">
						<div class="bar"></div>
					</div>
					<div class="tab-content">
						<div class="tab-pane" id="tab1">
							<div class="row-fluid entidade">
								<div class="span6">
									<div class="control-group">
										<label class="control-label">Codigo</label>
										<div class="controls">
	                 			<?php echo $this->formText('lol', $this->comboFuncionario ? $this->comboFuncionario->id_rh_funcionario : null, array('disabled' => 'disabled',  'style' => 'width: 90px'));?>
	                 			<?php echo $this->formHidden('id_rh_funcionario', $this->comboFuncionario ? $this->comboFuncionario->id_rh_funcionario : null);?>
	                 			<?php $workspaceSession = new Zend_Session_Namespace('workspace');?>
				              <?php echo isset($this->comboFuncionario->id_rh_funcionario) ? $this->formHidden("id_workspace",$this->comboFuncionario->id_workspace) : $this->formHidden("id_workspace",$workspaceSession->id_workspace); ?>
				              <?php echo $this->formHidden('id_rh_documento_identidade', $this->comboDocumento ? $this->comboDocumento->id_rh_documento_identidade : null);?>
				              <?php echo $this->formHidden('id_rh_certidao_civil', $this->comboCertidao ? $this->comboCertidao->id_rh_certidao_civil : null);?>
				              <?php echo $this->formHidden('id_rh_servico_militar', $this->comboServico ? $this->comboServico->id_rh_servico_militar : null);?>
				              <?php echo $this->formHidden('id_rh_fgts', $this->comboFgts ? $this->comboFgts->id_rh_fgts : null);?>
				              <?php echo $this->formHidden('id_rh_ci', $this->comboCi ? $this->comboCi->id_rh_ci : null);?>
				              <?php echo $this->formHidden('id_rh_outro', $this->comboOutro ? $this->comboOutro->id_rh_outro : null);?>
				              <?php echo $this->formHidden('id_rh_admissao', $this->comboAdmissao ? $this->comboAdmissao->id_rh_admissao : null);?>
				              <?php echo $this->formHidden('id_rh_dados_funcionais', $this->comboFuncionais ? $this->comboFuncionais->id_rh_dados_funcionais : null);?>
                 		</div>
                 	</div>
                </div>
              </div>
              <div class="row-fluid">
								<div class="span6">
									<div class="control-group">
										<label class="control-label">Funcionario <span style="color: red">*</span></label>
										<div class="controls">
                 			<?php $this->vo->id_rh_funcionario ? $disa = "disabled" : $disa = null;
                 			 echo $this->formSelect('id_empresa',$this->comboFuncionario ? $this->comboFuncionario->id_empresa : null, array('class' => 'span12', $disa => $disa ? $disa : null ), $this->comboPessoa);?>
                 		</div>
                 	</div>
                </div>
              </div>
              <div class="row-fluid entidade">
								<div class="span6">
									<div class="control-group">
										<label class="control-label">Endereço</label>
										<div class="controls">
                 			<?php echo $this->formText('endereco',null,array('disabled' => 'disabled', 'class' => 'span12'));?>
                 		</div>
                 	</div>
                </div>
              </div>
              <div class="row-fluid entidade">
								<div class="span6">
									<div class="control-group">
										<label class="control-label">Bairro</label>
										<div class="controls">
                 			<?php echo $this->formText('bairro',null,array('disabled' => 'disabled', 'class' => 'span12'));?>
                 		</div>
                 	</div>
                </div>
								<div class="span6">
									<div class="control-group">
										<label class="control-label">Estado</label>
										<div class="controls">
                 			<?php echo $this->formText('estado', null, array('disabled' => 'disabled', 'style' => 'width: 90px')); ?>
                 		</div>
                 	</div>
                </div>
              </div>
              <div class="row-fluid entidade">
								<div class="span6">
									<div class="control-group">
										<label class="control-label">Cidade</label>
										<div class="controls">
                 			<?php echo $this->formText('cidade',null,array('disabled' => 'disabled', 'class' => 'span12'));?>
                 		</div>
                 	</div>
                </div>
								<div class="span6">
									<div class="control-group">
										<label class="control-label">CEP</label>
										<div class="controls">
                 			<?php echo $this->formText('cep', null, array('disabled' => 'disabled', 'style' => 'width: 90px')); ?>
                 		</div>
                 	</div>
                </div>
              </div>
              <div class="row-fluid entidade">
              	<div class="span6">
	              	<div class="control-group">
	              		<label class="control-label">Telefones</label>
	              		<div class="controls">
	              			<?php echo $this->formText('telefone1', null, array('disabled' => 'disabled', 'class' => 'telefone span8', 'style' => 'margin: 3px;')); ?>
	              		</div>
	              		<div class="controls">
	              			<?php echo $this->formText('telefone2', null, array('disabled' => 'disabled', 'class' => 'telefone span8', 'style' => 'margin: 3px;')); ?>
	              		</div>
	              		<div class="controls">
	              			<?php echo $this->formText('telefone3', null, array('disabled' => 'disabled', 'class' => 'telefone span8', 'style' => 'margin: 3px;')); ?>
	              		</div>
	              	</div>
              	</div>
              </div>
              <div class="row-fluid entidade">
              	<div class="span6">
	              	<div class="control-group">
	              		<label class="control-label">E-mail</label>
	              		<div class="controls">
	              			<?php echo $this->formText('email', null, array('disabled' => 'disabled', 'class' => 'span12')); ?>
	              		</div>
              		</div>
              	</div>
              </div>
              <div class="row-fluid entidade">
								<div class="span6">
									<div class="control-group">
										<label class="control-label">Data Nasc. <span style="color: red">*</span></label>
										<div class="controls">
											<?php echo $this->formText('dt_nascimento', $this->comboFuncionario ? $this->date($this->comboFuncionario->dt_nascimento) : null , array('class' => 'span4 data')); ?>
										</div>
									</div>
								</div>
              </div>
              <div class="row-fluid entidade">
								<div class="span6">
									<div class="control-group">
										<label class="control-label">Naturalidade</label>
										<div class="controls">
											<?php echo $this->formText('naturalidade', $this->comboFuncionario ? $this->comboFuncionario->naturalidade : null , array('class' => 'span12')); ?>
										</div>
									</div>
								</div>
              </div>
              <div class="row-fluid entidade">
								<div class="span6">
									<div class="control-group">
										<label class="control-label">Nome da Mãe</label>
										<div class="controls">
											<?php echo $this->formText('nome_mae', null, array('disabled' => 'disabled', 'class' => 'span12')); ?>
										</div>
									</div>
								</div>
								<div class="span6">
									<div class="control-group">
										<label class="control-label">Nacionalidade</label>
										<div class="controls">
											<?php echo $this->formSelect('nacionalidade_mae', $this->comboFuncionario ? $this->comboFuncionario->nacionalidade_mae : '10' , array('class' => 'span12'), $this->comboNacionalidade); ?>
										</div>
									</div>
								</div>
              </div>
              <div class="row-fluid entidade">
								<div class="span6">
									<div class="control-group">
										<label class="control-label">Nome do Pai</label>
										<div class="controls">
											<?php echo $this->formText('nome_pai', null, array('disabled' => 'disabled', 'class' => 'span12')); ?>
										</div>
									</div>
								</div>
								<div class="span6">
									<div class="control-group">
										<label class="control-label">Nacionalidade</label>
										<div class="controls">
											<?php echo $this->formSelect('nacionalidade_pai', $this->comboFuncionario ? $this->comboFuncionario->nacionalidade_pai : '10' , array('class' => 'span12'), $this->comboNacionalidade); ?>
										</div>
									</div>
								</div>
              </div>
              <div class="row-fluid entidade">
              	<div class="span6">
              		<div class="control-group">
              			<label class="control-label">Estado Civil</label>
              			<div class="controls"><?php echo $this->formSelect('estado_civil', $this->comboFuncionario ? $this->comboFuncionario->estado_civil : null , array('class' => 'span12'), array('Solteiro(a)' => 'Solteiro(a)', 'Casado(a)' => 'Casado(a)', 'Divorciado(a)' => 'Divorciado(a)', 'Viuvo(a)' => 'Viuvo(a)')); ?></div>
              		</div>
              	</div>
              </div>
              <div class="row-fluid entidade">
              	<div class="span6">
              		<div class="control-group">
              			<label class="control-label">Nome do Cônjuge</label>
              			<div class="controls"><?php echo $this->formText('nome_conjuge', $this->comboFuncionario ? $this->comboFuncionario->nome_conjuge : null , array('class' => 'span12')); ?></div>
              		</div>
              	</div>
              </div>
              <div class="row-fluid entidade">
              	<div class="span6">
              		<div class="control-group">
              			<label class="control-label">Sexo</label>
              			<div class="controls"><?php echo $this->formSelect('sexo', $this->comboFuncionario ? $this->comboFuncionario->sexo : null , array('class' => 'span8'), array('1' => '1 - Masculino', '2' => '2 - Feminino')); ?></div>
              		</div>
              	</div>
              </div>
            </div>
            <div class="tab-pane" id="tab2">
            	<div class="row-fluid">
            		<div class="span6">
	            		<div class="control-group">
	            			<label class="control-label">Tipo de Identidade</label>
	            			<div class="controls">
	            				<?php echo $this->formSelect('tipo_identidade', $this->comboDocumento ? $this->comboDocumento->tipo_identidade : null, array('class'=>'span12'), array('0' => '0 - CI (Carteira de Identidade)', '1' => '1 - RIC (Registro de Identificação Civil)'))?>
	            			</div>
	            		</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Identidade</label>
            				<div class="controls">
            					<?php echo $this->formText('identidade', $this->comboDocumento ? $this->comboDocumento->identidade : null, array('class'=>'span4 rg'))?>
            				</div>
            			</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
	            		<div class="control-group">
	            			<label class="control-label">Expedida em</label>
	            			<div class="controls">
	            				<?php echo $this->formText('expedida', $this->comboDocumento ? $this->date($this->comboDocumento->expedida) : null, array('class'=>'span4 data'))?>
	            			</div>
	            		</div>
            		</div>
            		<div class="span6">
	            		<div class="control-group">
	            			<label class="control-label">Órgão Expedidor</label>
	            			<div class="controls"><?php echo $this->formText('orgao_expididor', $this->comboDocumento ? $this->comboDocumento->orgao_expididor : null, array('class' => 'span4'))?></div>
	            		</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
	            		<div class="control-group">
	            			<label class="control-label">Município Expedidor</label>
	            			<div class="controls"><?php echo $this->formText('municipio_expedida', $this->comboDocumento ? $this->comboDocumento->municipio_expedida : null, array('class' => 'span4'))?></div>
	            		</div>
            		</div>
            		<div class="span6">
	            		<div class="control-group">
	            			<label class="control-label">CPF</label>
	            			<div class="controls"><?php echo $this->formText('cpf', null, array('class' => 'span8', 'disabled' => 'disabled'))?></div>
	            		</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
	            		<div class="control-group">
	            			<label class="control-label">CTPS <span style="color: red">*</span></label>
	            			<div class="controls">
	            				<?php echo $this->formText('ctps', $this->comboDocumento ? $this->comboDocumento->ctps : null, array('style' => 'width:80px'))?>
	            			</div>
	            		</div>
            		</div>
            		<div class="span6">
	            		<div class="control-group">
	            			<label class="control-label">Série / UF</label>
	            			<div class="controls">
	            				<?php echo $this->formText('serie',  $this->comboDocumento ? $this->comboDocumento->serie : null, array('style' => 'width:80px'))?>
	            				<?php echo $this->formSelect('uf', $this->comboDocumento ? $this->comboDocumento->uf : null, array('style' => 'width: 90px'), $this->comboEstado); ?>
	            			</div>
	            		</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
	            		<div class="control-group">
	            			<label class="control-label">Expedida em</label>
	            			<div class="controls">
	            				<?php echo $this->formText('ctps_expedida', $this->comboDocumento ? $this->date($this->comboDocumento->ctps_expedida) : null, array('class' => 'span4 data'))?>
	            			</div>
	            		</div>
            		</div>
            		<div class="span6">
	            		<div class="control-group">
	            			<label class="control-label">Opta pelo PIS</label>
	            			<div class="controls">
	            				<?php echo $this->formSelect('opta_pis', $this->comboDocumento ? $this->comboDocumento->opta_pis : null, array('style' => 'width:80px'), array('1' => 'Sim', '0' => 'Não'))?>
	            			</div>
	            		</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
	            		<div class="control-group">
	            			<label class="control-label">PIS  <span style="color: red">*</span></label>
	            			<div class="controls">
	            				<?php echo $this->formText('pis', $this->comboDocumento ? $this->comboDocumento->pis : null, array('class' => 'span8'))?>
	            			</div>
	            		</div>
            		</div>
            		<div class="span6">
	            		<div class="control-group">
	            			<label class="control-label">Data da Opção</label>
	            			<div class="controls">
	            				<?php echo $this->formText('dt_opta_pis', $this->comboDocumento ? $this->date($this->comboDocumento->dt_opta_pis) : null, array('class' => 'span4 data'))?>
	            			</div>
	            		</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
	            		<div class="control-group">
	            			<label class="control-label">Titulo Eleitoral</label>
	            			<div class="controls">
	            				<?php echo $this->formText('titulo_eleitoral', $this->comboDocumento ? $this->comboDocumento->titulo_eleitoral : null, array('class' => 'span8'))?>
	            			</div>
	            		</div>
            		</div>
            		<div class="span6">
	            		<div class="control-group">
	            			<label class="control-label">Zona e Seção</label>
	            			<div class="controls">
	            				<?php echo $this->formText('zona', $this->comboDocumento ? $this->comboDocumento->zona : null, array('style' => 'width:80px'))?>
	            				<?php echo $this->formText('secao', $this->comboDocumento ? $this->comboDocumento->secao : null, array('style' => 'width:80px'))?>
	            			</div>
	            		</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
	            		<div class="control-group">
	            			<label class="control-label">CNH</label>
	            			<div class="controls">
	            				<?php echo $this->formText('cnh', $this->comboDocumento ? $this->comboDocumento->cnh : null, array())?>
	            			</div>
	            		</div>
            		</div>
            	</div>
							<div class="accordion in collapse" id="accordion1" style="height: auto;">
								<div class="accordion-group">
									<div class="accordion-heading">
										<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#certidao">
										<i class="icon-angle-left"></i>
										Certidão Civil
										</a>
									</div>
									<div id="certidao" class="accordion-body collapse" style="height: 0px;">
										<div class="accordion-inner">
											<div class="row-fluid">
												<div class="span6">
													<div class="control-group">
														<label class="control-label">Tipo de Certidão</label>
														<div class="controls"><?php echo $this->formSelect('tipo_certidao_civil', $this->comboCertidao ? $this->comboCertidao->tipo_certidao_civil : null, array('class' => 'span8'), array('0' => '0 - Certidão de Nascimento', '1' => '1 - Certidão de Casamento', '2' => '2 - Certidão Administrativa', '3' => '3 - Certidão de Óbito'))?></div>
													</div>
												</div>
												<div class="span6">
													<div class="control-group">
														<label class="control-label">Termo/Matrícula</label>
														<div class="controls"><?php echo $this->formText('termo_matricula', $this->comboCertidao ? $this->comboCertidao->termo_matricula : null, array('class' => 'span8'))?></div>
													</div>
												</div>
											</div>
											<div class="row-fluid">
												<div class="span6">
													<div class="control-group">
														<label class="control-label">Livro</label>
														<div class="controls"><?php echo $this->formText('livro', $this->comboCertidao ? $this->comboCertidao->livro : null, array('class' => 'span8'))?></div>
													</div>
												</div>
												<div class="span6">
													<div class="control-group">
														<label class="control-label">Folha</label>
														<div class="controls"><?php echo $this->formText('folha', $this->comboCertidao ? $this->comboCertidao->folha : null, array('class' => 'span8'))?></div>
													</div>
												</div>
											</div>
											<div class="row-fluid">
												<div class="span6">
													<div class="control-group">
														<label class="control-label">Cartório</label>
														<div class="controls"><?php echo $this->formText('cartorio', $this->comboCertidao ? $this->comboCertidao->cartorio : null, array('class' => 'span8'))?></div>
													</div>
												</div>
												<div class="span6">
													<div class="control-group">
														<label class="control-label">Estado</label>
														<div class="controls"><?php echo $this->formSelect('uf_certidao', $this->comboCertidao ? $this->comboCertidao->uf_certidao : null, array('style' => 'width: 90px'), $this->comboEstado); ?></div>
													</div>
												</div>
											</div>
											<div class="row-fluid">
												<div class="span6">
													<div class="control-group">
														<label class="control-label">Município</label>
														<div class="controls"><?php echo $this->formText('municipio', $this->comboCertidao ? $this->comboCertidao->municipio : null, array('class' => 'span8'))?></div>
													</div>
												</div>
												<div class="span6">
													<div class="control-group">
														<label class="control-label">Emissão</label>
														<div class="controls"><?php echo $this->formText('dt_emissao', $this->comboCertidao ? $this->date($this->comboCertidao->dt_emissao) : null, array('class' => 'span4 data'))?></div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="accordion-group">
									<div class="accordion-heading">
										<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#servico">
										<i class="icon-angle-left"></i>
										Serviço Militar
										</a>
									</div>
									<div id="servico" class="accordion-body collapse" style="height: 0px;">
										<div class="accordion-inner">
											<div class="row-fluid">
												<div class="span6">
													<div class="control-group">
														<label class="control-label">Reservista</label>
														<div class="controls"><?php echo $this->formText('reservista', $this->comboServico ? $this->comboServico->reservista : null, array('class' => 'span8'))?></div>
													</div>
												</div>
												<div class="span6">
													<div class="control-group">
														<label class="control-label">Série</label>
														<div class="controls"><?php echo $this->formText('serie_militar', $this->comboServico ? $this->comboServico->serie_militar : null, array('class' => 'span8'))?></div>
													</div>
												</div>
											</div>
											<div class="row-fluid">
												<div class="span6">
													<div class="control-group">
														<label class="control-label">Categoria</label>
														<div class="controls"><?php echo $this->formText('categoria', $this->comboServico ? $this->comboServico->categoria : null, array('class' => 'span8'))?></div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="accordion-group">
									<div class="accordion-heading">
										<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#fgts">
										<i class="icon-angle-left"></i>
										FGTS
										</a>
									</div>
									<div id="fgts" class="accordion-body collapse" style="height: 0px;">
										<div class="accordion-inner">
											<div class="row-fluid">
												<div class="span6">
													<div class="control-group">
														<label class="control-label">Opta pelo FGTS</label>
														<div class="controls"><?php echo $this->formSelect('opta', $this->comboFgts ? $this->comboFgts->opta : null, array('style' => 'width:80px'), array('1' => 'Sim', '0' => 'Não'))?></div>
													</div>
												</div>
												<div class="span6">
													<div class="control-group">
														<label class="control-label">Data da Opção</label>
														<div class="controls"><?php echo $this->formText('dt_opcao', $this->comboFgts ? $this->date($this->comboFgts->dt_opcao) : null, array('class' => 'span4 data'))?></div>
													</div>
												</div>
											</div>
											<div class="row-fluid">
												<div class="span6">
													<div class="control-group">
														<label class="control-label">Data de Retratação</label>
														<div class="controls"><?php echo $this->formText('dt_retratacao', $this->comboFgts ? $this->date($this->comboFgts->dt_retratacao) : null, array('class' => 'span4 data'))?></div>
													</div>
												</div>
												<div class="span6">
													<div class="control-group">
														<label class="control-label">Código no SEFIP</label>
														<div class="controls"><?php echo $this->formText('codigo_sefip', $this->comboFgts ? $this->comboFgts->codigo_sefip : null, array('class' => 'span8'))?></div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="accordion-group">
									<div class="accordion-heading">
										<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#ci">
										<i class="icon-angle-left"></i>
										CI
										</a>
									</div>
									<div id="ci" class="accordion-body collapse" style="height: 0px;">
										<div class="accordion-inner">
											<div class="row-fluid">
												<div class="span6">
													<div class="control-group">
														<label class="control-label">Inscrição do CI</label>
														<div class="controls"><?php echo $this->formText('inscricao', $this->comboCi ? $this->comboCi->inscricao : null, array('class' => 'span8'))?></div>
													</div>
												</div>
												<div class="span6">
													<div class="control-group">
														<label class="control-label">Cadastro do CI</label>
														<div class="controls"><?php echo $this->formText('dt_cadastro', $this->comboCi ? $this->date($this->comboCi->dt_cadastro) : null, array('class' => 'span4 data'))?></div>
													</div>
												</div>
											</div>
											<div class="row-fluid">
												<div class="span6">
													<div class="control-group">
														<label class="control-label">Gera GPS do CI</label>
														<div class="controls"><?php echo $this->formSelect('gera_gps', $this->comboCi ? $this->comboCi->gera_gps : null, array('style' => 'width:80px'), array('1' => 'Sim', '0' => 'Não'))?></div>
													</div>
												</div>
												<div class="span6">
													<div class="control-group">
														<label class="control-label">Dedução da GPS</label>
														<div class="controls"><?php echo $this->formText('deducao_gps', $this->comboCi ? $this->comboCi->deducao_gps : null, array('class' => 'span8'))?></div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="accordion-group">
									<div class="accordion-heading">
										<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#outros">
										<i class="icon-angle-left"></i>
										Outros
										</a>
									</div>
									<div id="outros" class="accordion-body collapse" style="height: 0px;">
										<div class="accordion-inner">
											<div class="row-fluid">
												<div class="span6">
													<div class="control-group">
														<label class="control-label">Cartão Fácil</label>
														<div class="controls"><?php echo $this->formText('cartao_facil', $this->comboOutro ? $this->comboOutro->cartao_facil : null, array('class' => 'span8'))?></div>
													</div>
												</div>
												<div class="span6">
													<div class="control-group">
														<label class="control-label">Alvará Judicial</label>
														<div class="controls"><?php echo $this->formText('alvara_judicial', $this->comboOutro ? $this->comboOutro->alvara_judicial : null, array('class' => 'span8'))?></div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
            </div>
            <div class="tab-pane" id="tab3">
            	<div class="row-fluid">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Data da Admissão <span style="color: red">*</span></label>
            				<div class="controls"><?php echo $this->formText('dt_admissao', $this->comboAdmissao ? $this->date($this->comboAdmissao->dt_admissao) : null, array('class' => 'span4 data'))?></div>
            			</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Tipo de Admissão</label>
            				<div class="controls">
            					<div class="input-append span12">
												<?php echo $this->formText('id_rh_tipo_admissao', $this->comboAdmissao ? $this->comboAdmissao->id_rh_tipo_admissao : null, array('class' => 'm-wrap', 'style' => 'width: 90px'))?><span class="add-on"><i class="icon-reorder"></i></span>
											</div>
										</div>
            			</div>
            		</div>
            	</div>
            	<div class="row-fuild">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Vencto da Experiência</label>
            				<div class="controls"><?php echo $this->formText('dt_vencto_experiencia', $this->comboAdmissao ? $this->date($this->comboAdmissao->dt_vencto_experiencia) : null, array('class' => 'span4 data'))?></div>
            			</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Prorrog da Experiência</label>
            				<div class="controls"><?php echo $this->formText('dt_prorrog_experiencia', $this->comboAdmissao ? $this->date($this->comboAdmissao->dt_prorrog_experiencia) : null, array('class' => 'span4 data'))?></div>
            			</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Vencto Prazo</label>
            				<div class="controls"><?php echo $this->formText('dt_vencto_prazo', $this->comboAdmissao ? $this->date($this->comboAdmissao->dt_vencto_prazo) : null, array('class' => 'span4 data'))?></div>
            			</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Alteração End. SEFIP</label>
            				<div class="controls"><?php echo $this->formText('alteracao_sefip', $this->comboAdmissao ? $this->comboAdmissao->alteracao_sefip : null, array('class' => 'span8'))?></div>
            			</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Registro de Empregado</label>
            				<div class="controls"><?php echo $this->formText('registro_emprego', $this->comboAdmissao ? $this->comboAdmissao->registro_emprego : null, array('class' => 'span8'))?></div>
            			</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Folha</label>
            				<div class="controls"><?php echo $this->formText('folha_admissao', $this->comboAdmissao ? $this->comboAdmissao->folha_admissao : null, array('class' => 'span8'))?></div>
            			</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Categoria</label>
            				<div class="controls">
            					<div class="input-append span12">
												<?php echo $this->formText('id_rh_categoria', $this->comboAdmissao ? $this->comboAdmissao->id_rh_categoria : null, array('class' => 'm-wrap', 'style' => 'width: 90px'))?><span class="add-on"><i class="icon-reorder"></i></span>
											</div>
            				</div>
            			</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Ocorrência</label>
            				<div class="controls">
            					<div class="input-append span12">
												<?php echo $this->formText('id_rh_ocorrencia', $this->comboAdmissao ? $this->comboAdmissao->id_rh_ocorrencia : null, array('class' => 'm-wrap', 'style' => 'width: 90px'))?><span class="add-on"><i class="icon-reorder"></i></span>
											</div>
            				</div>
            			</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Movimentação do CAGED</label>
            				<div class="controls">
            					<div class="input-append span12">
												<?php echo $this->formText('id_rh_caged', $this->comboAdmissao ? $this->comboAdmissao->id_rh_caged : null, array('class' => 'm-wrap', 'style' => 'width: 90px'))?><span class="add-on"><i class="icon-reorder"></i></span>
											</div>
										</div>
            			</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Vínculo</label>
            				<div class="controls">
            					<div class="input-append span12">
												<?php echo $this->formText('id_rh_vinculo', $this->comboAdmissao ? $this->comboAdmissao->id_rh_vinculo : null, array('class' => 'm-wrap', 'style' => 'width: 90px'))?><span class="add-on"><i class="icon-reorder"></i></span>
											</div>
            				</div>
            			</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Grau de Instrução</label>
            				<div class="controls">
            					<div class="input-append span12">
												<?php echo $this->formText('id_rh_instrucao', $this->comboAdmissao ? $this->comboAdmissao->id_rh_instrucao : null, array('class' => 'm-wrap', 'style' => 'width: 90px'))?><span class="add-on"><i class="icon-reorder"></i></span>
											</div>
            				</div>
            			</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Nacionalidade</label>
            				<div class="controls"><?php echo $this->formSelect('id_rh_nacionalidade', $this->comboAdmissao ? $this->comboAdmissao->id_rh_nacionalidade : '10', array('class' => 'span6'), $this->comboNacionalidade)?></div>
            			</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Raça / Cor</label>
            				<div class="controls"><?php echo $this->formSelect('id_rh_raca', $this->comboAdmissao ? $this->comboAdmissao->id_rh_raca : null, array('class' => 'span6'), $this->comboRaca)?></div>
            			</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Portado de Deficiencia</label>
            				<div class="controls"><?php echo $this->formSelect('id_rh_deficiencia', $this->comboAdmissao ? $this->comboAdmissao->id_rh_deficiencia : null, array('class' => 'span6'), $this->comboDficiente)?></div>
            			</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Data da Transferência</label>
            				<div class="controls"><?php echo $this->formText('dt_transferencia', $this->comboAdmissao ? $this->date($this->comboAdmissao->dt_transferencia) : null, array('class' => 'span4 data'))?></div>
            			</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Mês da Database</label>
            				<div class="controls"><?php echo $this->formText('mes_database', $this->comboAdmissao ? $this->comboAdmissao->mes_database : null, array('class' => 'span8'))?></div>
            			</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Profissão Regulam. na DRT</label>
            				<div class="controls"><?php echo $this->formText('prof_drt', $this->comboAdmissao ? $this->comboAdmissao->prof_drt : null, array('class' => 'span8'))?></div>
            			</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Tipo de Contrato</label>
            				<div class="controls">
            					<div class="input-append span12">
												<?php echo $this->formText('id_rh_contrato', $this->comboAdmissao ? $this->comboAdmissao->id_rh_contrato : null, array('class' => 'm-wrap', 'style' => 'width: 90px'))?><span class="add-on"><i class="icon-reorder"></i></span>
											</div>
            				</div>
            			</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Data Formação Profissional</label>
            				<div class="controls"><?php echo $this->formText('dt_formacao_prof', $this->comboAdmissao ? $this->date($this->comboAdmissao->dt_formacao_prof) : null, array('class' => 'span4 data'))?></div>
            			</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Data Última Recilagem</label>
            				<div class="controls"><?php echo $this->formText('dt_ultima_reciclagem', $this->comboAdmissao ? $this->date($this->comboAdmissao->dt_ultima_reciclagem) : null, array('class' => 'span4 data'))?></div>
            			</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Nº de Registro</label>
            				<div class="controls"><?php echo $this->formText('n_registro', $this->comboAdmissao ? $this->comboAdmissao->n_registro : null, array('class' => 'span4'))?></div>
            			</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Nº do Livro</label>
            				<div class="controls"><?php echo $this->formText('n_livro', $this->comboAdmissao ? $this->comboAdmissao->n_livro : null, array('class' => 'span4'))?></div>
            			</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Nº de Folha</label>
            				<div class="controls"><?php echo $this->formText('n_folha', $this->comboAdmissao ? $this->comboAdmissao->n_folha : null, array('class' => 'span4'))?></div>
            			</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Tipo Sanguíneo e RH</label>
            				<div class="controls"><?php echo $this->formText('tipo_sangue_rh', $this->comboAdmissao ? $this->comboAdmissao->tipo_sangue_rh : null, array('class' => 'span4'))?></div>
            			</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Sindicalizado</label>
            				<div class="controls"><?php echo $this->formSelect('sindicalizado', $this->comboAdmissao ? $this->comboAdmissao->sindicalizado : null, array('style' => 'width: 90px;'), array('0' => 'Não', '1' => 'Sim'))?></div>
            			</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Desconta Cont. Sindical</label>
            				<div class="controls"><?php echo $this->formSelect('desconta_sindica', $this->comboAdmissao ? $this->comboAdmissao->desconta_sindica : null, array('style' => 'width: 90px;'), array('0' => 'Não', '1' => 'Sim'))?></div>
            			</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Data de demissão</label>
            				<div class="controls"><?php echo $this->formText('dt_demissao', $this->vo->dt_demissao ? $this->date($this->vo->dt_demissao): null, array('class' => 'span4 data valid'))?></div>
            			</div>
            		</div>
            	</div>
            </div>
            <div class="tab-pane" id="tab4">
            	<div class="row-fluid">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">CBO</label>
            				<div class="controls"><?php echo $this->formText('codigo_cbo', $this->comboCbo ? $this->comboCbo->codigo : null, array('class' => '', 'style' => 'width: 90px'))?></div>
            			</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Vencto do Atestado</label>
            				<div class="controls"><?php echo $this->formText('vencto_atestado', $this->comboFuncionais ? $this->date($this->comboFuncionais->vencto_atestado) : null, array('class' => 'span4 data'))?></div>
            			</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Função <span style="color: red">*</span></label>
            				<div class="controls">
            					<div class="input-append span12">
												<?php echo $this->formText('funcao_cbo', $this->comboCbo ? $this->comboCbo->nome : null, array('class' => 'm-wrap span12'))?><span class="add-on"><i class="icon-reorder"></i></span>
            					<?php echo $this->formHidden('id_rh_cbo', $this->comboFuncionais ? $this->comboFuncionais->id_rh_cbo : null)?>
											</div>
            				</div>
            			</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Função PPP</label>
            				<div class="controls"><?php echo $this->formText('funcao_ppp', $this->comboFuncionais ? $this->comboFuncionais->funcao_ppp : null, array('class' => 'span8'))?></div>
            			</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Local</label>
            				<div class="controls">
            					<div class="input-append span12">
												<?php echo $this->formText('id_rh_local', $this->comboFuncionais ? $this->comboFuncionais->id_rh_local : null, array('class' => 'm-wrap', 'style' => 'width: 90px;'))?><span class="add-on"><i class="icon-reorder"></i></span>
											</div>
										</div>
            			</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Código do Município</label>
            				<div class="controls"><?php echo $this->formText('codigo_municipio', $this->comboFuncionais ? $this->comboFuncionais->codigo_municipio : null, array('class' => 'span8'))?></div>
            			</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Escala</label>
            				<div class="controls">
            					<div class="input-append span12">
												<?php echo $this->formText('id_rh_escala', $this->comboFuncionais ? $this->comboFuncionais->id_rh_escala : null, array('class' => 'm-wrap', 'style' => 'width: 90px;'))?><span class="add-on"><i class="icon-reorder"></i></span>
											</div>
            				</div>
            			</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Início da Escala</label>
            				<div class="controls"><?php echo $this->formText('dt_inicio_escala', $this->comboFuncionais ? $this->date($this->comboFuncionais->dt_inicio_escala) : null, array('class' => 'span4 data'))?></div>
            			</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Passagem</label>
            				<div class="controls">
            					<div class="input-append span12">
												<?php echo $this->formText('id_rh_passagem', $this->comboFuncionais ? $this->comboFuncionais->id_rh_passagem : null, array('class' => 'm-wrap', 'style' => 'width: 90px;'))?><span class="add-on"><i class="icon-reorder"></i></span>
											</div>
            				</div>
            			</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Sindicato</label>
            				<div class="controls">
            					<div class="input-append span12">
												<?php echo $this->formText('id_rh_sindicado', $this->comboFuncionais ? $this->comboFuncionais->id_rh_sindicado : null, array('class' => 'm-wrap', 'style' => 'width: 90px;'))?><span class="add-on"><i class="icon-reorder"></i></span>
											</div>
            				</div>
            			</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Horas Semanais</label>
            				<div class="controls"><?php echo $this->formText('hora_semanal', $this->comboFuncionais ? $this->comboFuncionais->hora_semanal : null, array('style' => 'width: 90px'))?></div>
            			</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Horas Mensais</label>
            				<div class="controls"><?php echo $this->formText('hora_mensal', $this->comboFuncionais ? $this->comboFuncionais->hora_mensal : null, array('style' => 'width: 90px'))?></div>
            			</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Salário <span style="color: red">*</span></label>
            				<div class="controls"><?php echo $this->formText('salario', $this->comboFuncionais ? $this->comboFuncionais->salario : null, array("alt" => "decimal" ,"class" => "decimal span8"));?></div>
            			</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Tipo de Salário</label>
            				<div class="controls"><?php echo $this->formSelect('tipo_de_salario', $this->comboFuncionais ? $this->comboFuncionais->tipo_de_salario : null, array('class' => 'span8'), array('1' => 'Mensal',  '3' => 'Semanal', '5' => 'Horário', '7' => 'Outros', '2' => 'Quinzenal', '4' => 'Diário', '6' => 'Tarefa'))?></div>
            			</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Entrada</label>
            				<div class="controls"><?php echo $this->formText('entrada', $this->comboFuncionais ? $this->comboFuncionais->entrada : null, array('style' => 'width: 90px', 'class' => 'hora'))?></div>
            			</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Saida</label>
            				<div class="controls"><?php echo $this->formText('saida', $this->comboFuncionais ? $this->comboFuncionais->saida : null, array('style' => 'width: 90px', 'class' => 'hora'))?></div>
            			</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Refeição</label>
            				<div class="controls"><?php echo $this->formText('refeicao_entrada', $this->comboFuncionais ? $this->comboFuncionais->refeicao_entrada : null, array('style' => 'width: 90px', 'class' => 'hora'))?><span style="margin: 0 5px 0 5px">a</span><?php echo $this->formText('refeicao_saida', $this->comboFuncionais ? $this->comboFuncionais->refeicao_saida : null, array('style' => 'width: 90px', 'class' => 'hora'))?></div>
            			</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Descanso</label>
            				<div class="controls"><?php echo $this->formText('descanso', $this->comboFuncionais ? $this->comboFuncionais->descanso : null, array('class' => 'span8'))?></div>
            			</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Horário Especial</label>
            				<div class="controls"><?php echo $this->formText('horario_especial', $this->comboFuncionais ? $this->comboFuncionais->horario_especial : null, array('class' => 'span8 time', 'class' => 'hora'))?></div>
            			</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Faixa de Reajuste</label>
            				<div class="controls"><?php echo $this->formText('faixa_reajuste', $this->comboFuncionais ? $this->comboFuncionais->faixa_reajuste : null, array('class' => 'span4 decimal'))?></div>
            			</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Tem Adiantamento</label>
            				<div class="controls"><?php echo $this->formSelect('adiantamento', $this->comboFuncionais ? $this->comboFuncionais->adiantamento : null, array('style' => 'width: 90px;'), array('0' => 'Não', '1' => 'Sim'))?></div>
            			</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Tem Vale-Alimentação</label>
            				<div class="controls"><?php echo $this->formSelect('vale_alimentacao', $this->comboFuncionais ? $this->comboFuncionais->vale_alimentacao : null, array('style' => 'width: 90px;'), array('0' => 'Não', '1' => 'Sim'))?></div>
            			</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Banco</label>
            				<div class="controls"><?php echo $this->formText('banco', $this->comboFuncionais ? $this->comboFuncionais->banco : null, array('class' => 'span8'))?></div>
            			</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Agência</label>
            				<div class="controls"><?php echo $this->formText('agencia', $this->comboFuncionais ? $this->comboFuncionais->agencia : null, array('class' => 'span4'))?></div>
            			</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Conta Bancária</label>
            				<div class="controls"><?php echo $this->formText('conta_bancaria', $this->comboFuncionais ? $this->comboFuncionais->conta_bancaria : null, array('class' => 'span8'))?></div>
            			</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Operaçõ Bancária</label>
            				<div class="controls"><?php echo $this->formText('operacao_bancaria', $this->comboFuncionais ? $this->comboFuncionais->operacao_bancaria : null, array('class' => 'span4'))?></div>
            			</div>
            		</div>
            	</div>
            	<div class="row-fluid">
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Últimas Férias</label>
            				<div class="controls"><?php echo $this->formText('dt_ultima_ferias', $this->comboFuncionais ? $this->date($this->comboFuncionais->dt_ultima_ferias) : null, array('class' => 'span4 data'))?></div>
            			</div>
            		</div>
            		<div class="span6">
            			<div class="control-group">
            				<label class="control-label">Previsão de Férias</label>
            				<div class="controls"><?php echo $this->formText('dt_previcao_ferias', $this->comboFuncionais ? $this->date($this->comboFuncionais->dt_previcao_ferias) : null, array('class' => 'span4 data'))?></div>
            			</div>
            		</div>
            	</div>

            </div>
					</div>
				</div>
					<div class="form-actions clearfix">
						<a href="javascript:;" class="btn button-previous" style="display: inline-block;">
							<i class="m-icon-swapleft"></i> Anterior
						</a>
						<a href="javascript:;" class="btn blue button-next">
							Próximo <i class="m-icon-swapright m-icon-white"></i>
						</a>
			            <button class="btn green salvar" type="submit">
			            	Salvar
			            </button>
					</div>
			</form>
		</div>
	</div>
</div>
<div id="dialog_tipo_admissao">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Código</th>
				<th>Descrição</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($this->comboTipo as $tipo):?>
			<tr class="tipo-admissao" data-value="<?php echo $tipo->id_rh_tipo_admissao?>">
				<td><?php echo $tipo->id_rh_tipo_admissao?></td>
				<td><?php echo $tipo->nome ?></td>
			</tr>
		<?php endforeach;?>
		</tbody>
	</table>
</div>
<div id="dialog_categoria">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Código</th>
				<th>Descrição</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($this->comboCategoria as $tipo):?>
			<tr class="tipo-categoria" data-value="<?php echo $tipo->id_rh_categoria?>">
				<td><?php echo $tipo->id_rh_categoria?></td>
				<td><?php echo $tipo->nome ?></td>
			</tr>
		<?php endforeach;?>
		</tbody>
	</table>
</div>
<div id="dialog_ocorrencia">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Código</th>
				<th>Descrição</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($this->comboOcorrencia as $tipo):?>
			<tr class="tipo-ocorrencia" data-value="<?php echo $tipo->id_rh_ocorrencia?>">
				<td><?php echo $tipo->id_rh_ocorrencia?></td>
				<td><?php echo $tipo->nome ?></td>
			</tr>
		<?php endforeach;?>
		</tbody>
	</table>
</div>
<div id="dialog_caged">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Código</th>
				<th>Descrição</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($this->comboCaged as $tipo):?>
			<tr class="tipo-caged" data-value="<?php echo $tipo->id_rh_caged?>">
				<td><?php echo $tipo->id_rh_caged?></td>
				<td><?php echo $tipo->nome ?></td>
			</tr>
		<?php endforeach;?>
		</tbody>
	</table>
</div>
<div id="dialog_vinculo">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Código</th>
				<th>Descrição</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($this->comboVinculo as $tipo):?>
			<tr class="tipo-vinculo" data-value="<?php echo $tipo->id_rh_vinculo?>">
				<td><?php echo $tipo->id_rh_vinculo?></td>
				<td><?php echo $tipo->nome ?></td>
			</tr>
		<?php endforeach;?>
		</tbody>
	</table>
</div>

<div id="dialog_instrucao">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Código</th>
				<th>Descrição</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($this->comboInstrucao as $tipo):?>
			<tr class="tipo-instrucao" data-value="<?php echo $tipo->id_rh_instrucao?>">
				<td><?php echo $tipo->id_rh_instrucao?></td>
				<td><?php echo $tipo->nome ?></td>
			</tr>
		<?php endforeach;?>
		</tbody>
	</table>
</div>

<div id="dialog_contrato">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Código</th>
				<th>Descrição</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($this->comboContrato as $tipo):?>
			<tr class="tipo-contrato" data-value="<?php echo $tipo->id_rh_contrato?>">
				<td><?php echo $tipo->id_rh_contrato?></td>
				<td><?php echo $tipo->nome ?></td>
			</tr>
		<?php endforeach;?>
		</tbody>
	</table>
</div>

<div id="dialog_escala">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Código</th>
				<th>Descrição</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($this->comboEscala as $tipo):?>
			<tr class="tipo-escala" data-value="<?php echo $tipo->id_rh_escala?>">
				<td><?php echo $tipo->id_rh_escala?></td>
				<td><?php echo $tipo->descricao ?></td>
			</tr>
		<?php endforeach;?>
		</tbody>
	</table>
</div>

<div id="dialog_passagem">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Código</th>
				<th>Descrição</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($this->comboPassagem as $tipo):?>
			<tr class="tipo-passagem" data-value="<?php echo $tipo->id_rh_passagem?>">
				<td><?php echo $tipo->id_rh_passagem?></td>
				<td><?php echo $tipo->descricao ?></td>
			</tr>
		<?php endforeach;?>
		</tbody>
	</table>
</div>

<div id="dialog_local">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Código</th>
				<th>Descrição</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($this->comboLocal as $tipo):?>
			<tr class="tipo-local" data-value="<?php echo $tipo->id_rh_local?>">
				<td><?php echo $tipo->id_rh_local?></td>
				<td><?php echo $tipo->descricao ?></td>
			</tr>
		<?php endforeach;?>
		</tbody>
	</table>
</div>

<div id="dialog_sindicato">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Código</th>
				<th>Descrição</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($this->comboSindicato as $tipo):?>
			<tr class="tipo-sindicato" data-value="<?php echo $tipo['id_empresa']?>">
				<td><?php echo $tipo['id_empresa']?></td>
				<td><?php echo $tipo['nome_razao'] ?></td>
			</tr>
		<?php endforeach;?>
		</tbody>
	</table>
</div>

<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('assets/plugins/jquery-multi-select/css/multi-select-metro.css')?>" />
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/jquery-validation/dist/jquery.validate.min.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/jquery-validation/dist/additional-methods.min.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/bootstrap-wizard/jquery.bootstrap.wizard.min.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/jquery-multi-select/js/jquery.multi-select.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/rh/funcionario.form.js')?>"></script>