    <table class="table-bordered table-striped table-condensed flip-content" style="width: 100%">
        <thead>
            <tr>
                <th style="width:140px">Status</th>
                <th>Descrição</th>
                <th style="width:100px">Qtd Baixado</th>
                <th style="width:90px">Quantidade</th>
                <th style="width:120px; text-align: right;">Valor Unitário</th>
                <th style="width:110px;  text-align: right;">Total</th>
                <th>Unidade</th>
                <th>Observação</th>
                <th>Usuário</th>
                <th>Data</th>
            </tr>
        </thead>
        <tbody>
            <?php if(count($this->historicoList)):?>
                <?php foreach ($this->historicoList as $historico):?>
                        <tr>
                            <td><?php echo $historico->getStatus()?$historico->getStatus()->nome: null; ?></td>
                            <td><?php echo $historico->getItem()?$historico->getItem()->nome: $historico->nome ?></td>
                            <td><?php echo $this->formatDecimal($historico->qtd_baixado) ?></td>
                            <td><?php echo $this->formatDecimal($historico->quantidade) ?></td>
                            <td style="text-align: right;"><?php echo $this->real($historico->vl_unitario) ?></td>
                            <td style="text-align: right;"><?php echo $this->real($historico->total) ?></td>
                            <td><?php echo $historico->getUnidade() ? $historico->getUnidade()->nome : null ?></td>
                            <td><?php echo $historico->observacao ?></td>
                            <td><?php  echo $historico->getUsuario()->getEmpresa()->nome_razao ?></td>
                            <td><?php echo $this->dateHour($historico->dt_criacao) ?></td>
                        </tr>
                <?php endforeach;?>
            <?php else:?>
                    <tr>
                        <td colspan="10">Não há dados</td>
                    </tr>
            <?php endif;?>
        </tbody>
    </table>
    <div class="footer" style="margin-bottom: 10px;">
    </div>
