


INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES ('5d97d2b8-1a8e-433a-ba58-c4c370ae0919', null, 'Pedido','Pedido','Pedido','Pedido/Pedido', null,  null, null, null, null, true);

INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES ('0fa6a63e-caf4-4d5b-93d8-4bac5f914d3e', '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'Registros de pedidos','Registros de pedidos','Registros de pedidos','processo/processo/grid', null,  null, null, null, 1, true);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES ('69d8c493-f01e-4868-998b-970979695974', '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'Pedidos por status','Pedidos por status','Pedidos por status','processo/processo/grid-status', null,  null, null, null, 2, true);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES ('7625fda3-47f7-46d9-8369-e68ae63b81c2', '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'Pedidos com pendências','Pedidos com pendências','Pedidos com pendências','processo/processo/grid-pendencia', null,  null, null, null, 3, true);


INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '0fa6a63e-caf4-4d5b-93d8-4bac5f914d3e', 'processo/processo/quick-search-ajax', 'processo/processo/quick-search-ajax', 'processo/processo/quick-search-ajax', 'processo/processo/quick-search-ajax',  null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '0fa6a63e-caf4-4d5b-93d8-4bac5f914d3e', 'processo/processo/grid-pedido', 'processo/processo/grid-pedido', 'processo/processo/grid-pedido', 'processo/processo/grid-pedido',  null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '0fa6a63e-caf4-4d5b-93d8-4bac5f914d3e', 'processo/processo/ordem-servico', 'processo/processo/ordem-servico', 'processo/processo/ordem-servico', 'processo/processo/ordem-servico',  null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '0fa6a63e-caf4-4d5b-93d8-4bac5f914d3e', 'processo/processo/ordem-producao', 'processo/processo/ordem-producao', 'processo/processo/ordem-producao', 'processo/processo/ordem-producao',  null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '0fa6a63e-caf4-4d5b-93d8-4bac5f914d3e', 'processo/processo/autocomplete', 'processo/processo/autocomplete', 'processo/processo/autocomplete', 'processo/processo/autocomplete',  null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '0fa6a63e-caf4-4d5b-93d8-4bac5f914d3e', 'processo/processo/get', 'processo/processo/get', 'processo/processo/get', 'processo/processo/get',  null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '0fa6a63e-caf4-4d5b-93d8-4bac5f914d3e', 'processo/processo/autocomplete-codigo', 'processo/processo/autocomplete-codigo', 'processo/processo/autocomplete-codigo', 'processo/processo/autocomplete-codigo',  null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '0fa6a63e-caf4-4d5b-93d8-4bac5f914d3e', 'processo/processo/delete', 'processo/processo/delete', 'processo/processo/delete', 'processo/processo/delete',  null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '0fa6a63e-caf4-4d5b-93d8-4bac5f914d3e', 'processo/processo/form', 'processo/processo/form', 'processo/processo/form', 'processo/processo/form', null,  null, null, null, null, false);


INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '69d8c493-f01e-4868-998b-970979695974', 'processo/processo/quick-search-ajax', 'processo/processo/quick-search-ajax', 'processo/processo/quick-search-ajax', 'processo/processo/quick-search-ajax',  null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '69d8c493-f01e-4868-998b-970979695974', 'processo/processo/grid-pedido', 'processo/processo/grid-pedido', 'processo/processo/grid-pedido', 'processo/processo/grid-pedido',  null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '69d8c493-f01e-4868-998b-970979695974', 'processo/processo/ordem-servico', 'processo/processo/ordem-servico', 'processo/processo/ordem-servico', 'processo/processo/ordem-servico',  null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '69d8c493-f01e-4868-998b-970979695974', 'processo/processo/ordem-producao', 'processo/processo/ordem-producao', 'processo/processo/ordem-producao', 'processo/processo/ordem-producao',  null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '69d8c493-f01e-4868-998b-970979695974', 'processo/processo/autocomplete', 'processo/processo/autocomplete', 'processo/processo/autocomplete', 'processo/processo/autocomplete',  null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '69d8c493-f01e-4868-998b-970979695974', 'processo/processo/get', 'processo/processo/get', 'processo/processo/get', 'processo/processo/get',  null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '69d8c493-f01e-4868-998b-970979695974', 'processo/processo/autocomplete-codigo', 'processo/processo/autocomplete-codigo', 'processo/processo/autocomplete-codigo', 'processo/processo/autocomplete-codigo',  null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '69d8c493-f01e-4868-998b-970979695974', 'processo/processo/delete', 'processo/processo/delete', 'processo/processo/delete', 'processo/processo/delete',  null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '69d8c493-f01e-4868-998b-970979695974', 'processo/processo/form', 'processo/processo/form', 'processo/processo/form', 'processo/processo/form', null,  null, null, null, null, false);



INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '7625fda3-47f7-46d9-8369-e68ae63b81c2', 'processo/processo/quick-search-ajax', 'processo/processo/quick-search-ajax', 'processo/processo/quick-search-ajax', 'processo/processo/quick-search-ajax',  null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '7625fda3-47f7-46d9-8369-e68ae63b81c2', 'processo/processo/grid-pedido', 'processo/processo/grid-pedido', 'processo/processo/grid-pedido', 'processo/processo/grid-pedido',  null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '7625fda3-47f7-46d9-8369-e68ae63b81c2', 'processo/processo/ordem-servico', 'processo/processo/ordem-servico', 'processo/processo/ordem-servico', 'processo/processo/ordem-servico',  null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '7625fda3-47f7-46d9-8369-e68ae63b81c2', 'processo/processo/ordem-producao', 'processo/processo/ordem-producao', 'processo/processo/ordem-producao', 'processo/processo/ordem-producao',  null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '7625fda3-47f7-46d9-8369-e68ae63b81c2', 'processo/processo/autocomplete', 'processo/processo/autocomplete', 'processo/processo/autocomplete', 'processo/processo/autocomplete',  null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '7625fda3-47f7-46d9-8369-e68ae63b81c2', 'processo/processo/get', 'processo/processo/get', 'processo/processo/get', 'processo/processo/get',  null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '7625fda3-47f7-46d9-8369-e68ae63b81c2', 'processo/processo/autocomplete-codigo', 'processo/processo/autocomplete-codigo', 'processo/processo/autocomplete-codigo', 'processo/processo/autocomplete-codigo',  null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '7625fda3-47f7-46d9-8369-e68ae63b81c2', 'processo/processo/delete', 'processo/processo/delete', 'processo/processo/delete', 'processo/processo/delete',  null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '7625fda3-47f7-46d9-8369-e68ae63b81c2', 'processo/processo/form', 'processo/processo/form', 'processo/processo/form', 'processo/processo/form', null,  null, null, null, null, false);



INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES ('a55cfacf-111d-44b0-b245-5828d3813eb3', '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'Status','Status','Status','processo/status/grid', null,  null, null, null, 4, true);


insert into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), 'a55cfacf-111d-44b0-b245-5828d3813eb3', 'processo/status/get', 'processo/status/get', 'processo/status/get', 'processo/status/get', null,  null, null, null, null, false);
insert into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), 'a55cfacf-111d-44b0-b245-5828d3813eb3', 'processo/status/delete', 'processo/status/delete', 'processo/status/delete', 'processo/status/delete', null,  null, null, null, null, false);
insert into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), 'a55cfacf-111d-44b0-b245-5828d3813eb3', 'processo/status/autocomplete', 'processo/status/autocomplete', 'processo/status/autocomplete', 'processo/status/autocomplete', null,  null, null, null, null, false);
insert into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), 'a55cfacf-111d-44b0-b245-5828d3813eb3', 'processo/status/form', 'processo/status/form', 'processo/status/form', 'processo/status/form', null,  null, null, null, null, false);


INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES ('e55427fd-5415-4a71-8845-fd258db207fe', '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'Relatório','Relatório','Relatório','processo/relatorio/index', null,  null, null, null, 5, true);

insert into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), 'e55427fd-5415-4a71-8845-fd258db207fe', 'processo/relatorio/grid', 'processo/relatorio/grid', 'processo/relatorio/grid', 'processo/relatorio/grid', null,  null, null, null, null, false);
insert into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), 'e55427fd-5415-4a71-8845-fd258db207fe', 'processo/relatorio/pdf', 'processo/relatorio/pdf', 'processo/relatorio/pdf', 'processo/relatorio/pdf', null,  null, null, null, null, false);
insert into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), 'e55427fd-5415-4a71-8845-fd258db207fe', 'processo/relatorio/pdf-analitico', 'processo/relatorio/pdf-analitico', 'processo/relatorio/pdf-analitico', 'processo/relatorio/pdf-analitico', null,  null, null, null, null, false);
insert into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), 'e55427fd-5415-4a71-8845-fd258db207fe', 'processo/relatorio/delete', 'processo/relatorio/delete', 'processo/relatorio/delete', 'processo/relatorio/delete', null,  null, null, null, null, false);
insert into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), 'e55427fd-5415-4a71-8845-fd258db207fe', 'processo/relatorio/autocomplete', 'processo/relatorio/autocomplete', 'processo/relatorio/autocomplete', 'processo/relatorio/autocomplete', null,  null, null, null, null, false);
insert into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), 'e55427fd-5415-4a71-8845-fd258db207fe', 'processo/relatorio/form', 'processo/relatorio/form', 'processo/relatorio/form', 'processo/relatorio/form', null,  null, null, null, null, false);

INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES ('8351b8ce-df6d-489d-8b98-07a2cff8bf9a', '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'Meus pedidos','Meus pedidos','Meus pedidos','processo/pedido/meus-pedidos', null,  null, null, null, 6, true);

insert into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '8351b8ce-df6d-489d-8b98-07a2cff8bf9a', 'processo/pedido/meus-pedidos', 'processo/pedido/meus-pedidos', 'processo/pedido/meus-pedidos', 'processo/pedido/meus-pedidos', null,  null, null, null, null, false);
insert into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '8351b8ce-df6d-489d-8b98-07a2cff8bf9a', 'processo/pedido/delete', 'processo/pedido/delete', 'processo/pedido/delete', 'processo/pedido/delete', null,  null, null, null, null, false);
insert into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '8351b8ce-df6d-489d-8b98-07a2cff8bf9a', 'processo/pedido/autocomplete', 'processo/pedido/autocomplete', 'processo/pedido/autocomplete', 'processo/pedido/autocomplete', null,  null, null, null, null, false);
insert into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '8351b8ce-df6d-489d-8b98-07a2cff8bf9a', 'processo/pedido/form', 'processo/pedido/form', 'processo/pedido/form', 'processo/pedido/form', null,  null, null, null, null, false);
insert into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '8351b8ce-df6d-489d-8b98-07a2cff8bf9a', 'processo/pedido-workspace/form', 'processo/pedido-workspace/form', 'processo/pedido-workspace/form', 'processo/pedido-workspace/form', null,  null, null, null, null, false);
insert into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '8351b8ce-df6d-489d-8b98-07a2cff8bf9a', 'processo/pedido-workspace/delete', 'processo/pedido-workspace/delete', 'processo/pedido-workspace/delete', 'processo/pedido-workspace/delete', null,  null, null, null, null, false);
insert into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel")
VALUES (uuid_generate_v4(), '8351b8ce-df6d-489d-8b98-07a2cff8bf9a', 'processo/pedido-workspace/autocomplete', 'processo/pedido-workspace/autocomplete', 'processo/pedido-workspace/autocomplete', 'processo/pedido-workspace/autocomplete', null,  null, null, null, null, false);




INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/abertura/delete', 'processo/abertura/delete', 'processo/abertura/delete', 'processo/abertura/delete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/abertura/autocomplete', 'processo/abertura/autocomplete', 'processo/abertura/autocomplete', 'processo/abertura/autocomplete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/abertura/form', 'processo/abertura/form', 'processo/abertura/form', 'processo/abertura/form', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/acabamento/delete', 'processo/acabamento/delete', 'processo/acabamento/delete', 'processo/acabamento/delete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/acabamento/autocomplete', 'processo/acabamento/autocomplete', 'processo/acabamento/autocomplete', 'processo/acabamento/autocomplete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/acabamento/form', 'processo/acabamento/form', 'processo/acabamento/form', 'processo/acabamento/form', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/arquivo/get-arquivo', 'processo/arquivo/get-arquivo', 'processo/arquivo/get-arquivo', 'processo/arquivo/get-arquivo', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/arquivo/grid-processo', 'processo/arquivo/grid-processo', 'processo/arquivo/grid-processo', 'processo/arquivo/grid-processo', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/arquivo/delete', 'processo/arquivo/delete', 'processo/arquivo/delete', 'processo/arquivo/delete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/arquivo/autocomplete', 'processo/arquivo/autocomplete', 'processo/arquivo/autocomplete', 'processo/arquivo/autocomplete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/arquivo/form', 'processo/arquivo/form', 'processo/arquivo/form', 'processo/arquivo/form', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/categoria/delete', 'processo/categoria/delete', 'processo/categoria/delete', 'processo/categoria/delete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/categoria/autocomplete', 'processo/categoria/autocomplete', 'processo/categoria/autocomplete', 'processo/categoria/autocomplete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/categoria/form', 'processo/categoria/form', 'processo/categoria/form', 'processo/categoria/form', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/comentario/chat', 'processo/comentario/chat', 'processo/comentario/chat', 'processo/comentario/chat', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/comentario/get', 'processo/comentario/get', 'processo/comentario/get', 'processo/comentario/get', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/comentario/grid-by-processo', 'processo/comentario/grid-by-processo', 'processo/comentario/grid-by-processo', 'processo/comentario/grid-by-processo', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/comentario/delete', 'processo/comentario/delete', 'processo/comentario/delete', 'processo/comentario/delete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/comentario/autocomplete', 'processo/comentario/autocomplete', 'processo/comentario/autocomplete', 'processo/comentario/autocomplete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/comentario/form', 'processo/comentario/form', 'processo/comentario/form', 'processo/comentario/form', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/costura-caderno/delete', 'processo/costura-caderno/delete', 'processo/costura-caderno/delete', 'processo/costura-caderno/delete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/costura-caderno/autocomplete', 'processo/costura-caderno/autocomplete', 'processo/costura-caderno/autocomplete', 'processo/costura-caderno/autocomplete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/costura-caderno/form', 'processo/costura-caderno/form', 'processo/costura-caderno/form', 'processo/costura-caderno/form', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/extrato/search', 'processo/extrato/search', 'processo/extrato/search', 'processo/extrato/search', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/extrato/pdf', 'processo/extrato/pdf', 'processo/extrato/pdf', 'processo/extrato/pdf', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/extrato/delete', 'processo/extrato/delete', 'processo/extrato/delete', 'processo/extrato/delete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/extrato/autocomplete', 'processo/extrato/autocomplete', 'processo/extrato/autocomplete', 'processo/extrato/autocomplete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/extrato/form', 'processo/extrato/form', 'processo/extrato/form', 'processo/extrato/form', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/form-impressao/delete', 'processo/form-impressao/delete', 'processo/form-impressao/delete', 'processo/form-impressao/delete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/form-impressao/autocomplete', 'processo/form-impressao/autocomplete', 'processo/form-impressao/autocomplete', 'processo/form-impressao/autocomplete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/form-impressao/form', 'processo/form-impressao/form', 'processo/form-impressao/form', 'processo/form-impressao/form', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/historico/grid', 'processo/historico/grid', 'processo/historico/grid', 'processo/historico/grid', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/historico/email-history', 'processo/historico/email-history', 'processo/historico/email-history', 'processo/historico/email-history', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/historico/delete', 'processo/historico/delete', 'processo/historico/delete', 'processo/historico/delete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/historico/autocomplete', 'processo/historico/autocomplete', 'processo/historico/autocomplete', 'processo/historico/autocomplete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/historico/form', 'processo/historico/form', 'processo/historico/form', 'processo/historico/form', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/historico-material/grid', 'processo/historico-material/grid', 'processo/historico-material/grid', 'processo/historico-material/grid', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/historico-material/delete', 'processo/historico-material/delete', 'processo/historico-material/delete', 'processo/historico-material/delete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/historico-material/autocomplete', 'processo/historico-material/autocomplete', 'processo/historico-material/autocomplete', 'processo/historico-material/autocomplete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/historico-material/form', 'processo/historico-material/form', 'processo/historico-material/form', 'processo/historico-material/form', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/material-processo/grid', 'processo/material-processo/grid', 'processo/material-processo/grid', 'processo/material-processo/grid', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/material-processo/get', 'processo/material-processo/get', 'processo/material-processo/get', 'processo/material-processo/get', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/material-processo/validar', 'processo/material-processo/validar', 'processo/material-processo/validar', 'processo/material-processo/validar', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/material-processo/delete', 'processo/material-processo/delete', 'processo/material-processo/delete', 'processo/material-processo/delete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/material-processo/autocomplete', 'processo/material-processo/autocomplete', 'processo/material-processo/autocomplete', 'processo/material-processo/autocomplete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/material-processo/form', 'processo/material-processo/form', 'processo/material-processo/form', 'processo/material-processo/form', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/montagem/delete', 'processo/montagem/delete', 'processo/montagem/delete', 'processo/montagem/delete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/montagem/autocomplete', 'processo/montagem/autocomplete', 'processo/montagem/autocomplete', 'processo/montagem/autocomplete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/montagem/form', 'processo/montagem/form', 'processo/montagem/form', 'processo/montagem/form', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/pcp-timer/grid-processo', 'processo/pcp-timer/grid-processo', 'processo/pcp-timer/grid-processo', 'processo/pcp-timer/grid-processo', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/pcp-timer/delete', 'processo/pcp-timer/delete', 'processo/pcp-timer/delete', 'processo/pcp-timer/delete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/pcp-timer/autocomplete', 'processo/pcp-timer/autocomplete', 'processo/pcp-timer/autocomplete', 'processo/pcp-timer/autocomplete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/pcp-timer/form', 'processo/pcp-timer/form', 'processo/pcp-timer/form', 'processo/pcp-timer/form', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/planejamento/grid-by-date', 'processo/planejamento/grid-by-date', 'processo/planejamento/grid-by-date', 'processo/planejamento/grid-by-date', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/planejamento/get', 'processo/planejamento/get', 'processo/planejamento/get', 'processo/planejamento/get', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/planejamento/pdf-by-date', 'processo/planejamento/pdf-by-date', 'processo/planejamento/pdf-by-date', 'processo/planejamento/pdf-by-date', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/planejamento/delete', 'processo/planejamento/delete', 'processo/planejamento/delete', 'processo/planejamento/delete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/planejamento/autocomplete', 'processo/planejamento/autocomplete', 'processo/planejamento/autocomplete', 'processo/planejamento/autocomplete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/planejamento/form', 'processo/planejamento/form', 'processo/planejamento/form', 'processo/planejamento/form', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/posicao/delete', 'processo/posicao/delete', 'processo/posicao/delete', 'processo/posicao/delete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/posicao/autocomplete', 'processo/posicao/autocomplete', 'processo/posicao/autocomplete', 'processo/posicao/autocomplete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/posicao/form', 'processo/posicao/form', 'processo/posicao/form', 'processo/posicao/form', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/prioridade/delete', 'processo/prioridade/delete', 'processo/prioridade/delete', 'processo/prioridade/delete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/prioridade/autocomplete', 'processo/prioridade/autocomplete', 'processo/prioridade/autocomplete', 'processo/prioridade/autocomplete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/prioridade/form', 'processo/prioridade/form', 'processo/prioridade/form', 'processo/prioridade/form', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/processo-servico/grid', 'processo/processo-servico/grid', 'processo/processo-servico/grid', 'processo/processo-servico/grid', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/processo-servico/get', 'processo/processo-servico/get', 'processo/processo-servico/get', 'processo/processo-servico/get', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/processo-servico/delete', 'processo/processo-servico/delete', 'processo/processo-servico/delete', 'processo/processo-servico/delete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/processo-servico/autocomplete', 'processo/processo-servico/autocomplete', 'processo/processo-servico/autocomplete', 'processo/processo-servico/autocomplete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/processo-servico/form', 'processo/processo-servico/form', 'processo/processo-servico/form', 'processo/processo-servico/form', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/recibo/ordem-servico', 'processo/recibo/ordem-servico', 'processo/recibo/ordem-servico', 'processo/recibo/ordem-servico', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/recibo/delete', 'processo/recibo/delete', 'processo/recibo/delete', 'processo/recibo/delete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/recibo/autocomplete', 'processo/recibo/autocomplete', 'processo/recibo/autocomplete', 'processo/recibo/autocomplete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/recibo/form', 'processo/recibo/form', 'processo/recibo/form', 'processo/recibo/form', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/tam-chapa/delete', 'processo/tam-chapa/delete', 'processo/tam-chapa/delete', 'processo/tam-chapa/delete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/tam-chapa/autocomplete', 'processo/tam-chapa/autocomplete', 'processo/tam-chapa/autocomplete', 'processo/tam-chapa/autocomplete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/tam-chapa/form', 'processo/tam-chapa/form', 'processo/tam-chapa/form', 'processo/tam-chapa/form', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/tam-papel/delete', 'processo/tam-papel/delete', 'processo/tam-papel/delete', 'processo/tam-papel/delete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/tam-papel/autocomplete', 'processo/tam-papel/autocomplete', 'processo/tam-papel/autocomplete', 'processo/tam-papel/autocomplete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/tam-papel/form', 'processo/tam-papel/form', 'processo/tam-papel/form', 'processo/tam-papel/form', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/tipo-produto/delete', 'processo/tipo-produto/delete', 'processo/tipo-produto/delete', 'processo/tipo-produto/delete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/tipo-produto/autocomplete', 'processo/tipo-produto/autocomplete', 'processo/tipo-produto/autocomplete', 'processo/tipo-produto/autocomplete', null,  null, null, null, null, false);
INSERT into tb_servico ("id", "id_pai", "descricao","metanome", "nome", "rota", "dtype", "fluxo", "id_grupo", "id_tib", "ordem", "visivel") VALUES (uuid_generate_v4(), '5d97d2b8-1a8e-433a-ba58-c4c370ae0919', 'processo/tipo-produto/form', 'processo/tipo-produto/form', 'processo/tipo-produto/form', 'processo/tipo-produto/form', null,  null, null, null, null, false);


