	<div class="span12">
		<div class="portlet box green">
			<div class="portlet-title">
				<div class="caption"><i class=icon-shopping-cart></i>Compras</div>
				<div class="tools">
                    <a href="javascript:;" class="collapse"></a>
                </div>
			</div>
			<div class="portlet-body flip-scroll">
				<div id="sample_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
					<table class="table-bordered table-striped table-condensed flip-content" id="perfisTable">
						<thead class="flip-content">
							<tr>
								<th class="hidden-480">Código</th>
					            <th>Campanha</th>
					            <th>Consultor</th>
					            <th class="hidden-480">Status</th>
					            <th>Data</th>
					            <th style="width: 48px;" class="action">Ação</th>
							</tr>
						</thead>
						<tbody>
							<?php if (count($this->compraList) > 0):?>
				        <?php foreach ($this->compraList as $compras):?>
			            <tr class="odd gradeX">
			                <td style="width:30px"><?php echo $compras->id_compra; ?></td>
			                <td><?php echo $compras->getCampanha()->nome; ?></td>
			                <td><?php echo $compras->getUser()->nome_razao; ?></td>
			                <td class="hidden-480"><?php echo $compras->finalizado == 0 ? "Cancelado" : "Finalizado" ; ?></td>
			                <td style="width:150px"><?php echo $this->dateHour($compras->dt_criacao); ?></td>
			                <td class="acoes" align="center">
			                		<a class="Edit" href="<?php echo $this->baseUrl('compra/relatorio-compra/view-compra/id_compra/'.$compras->id_compra.'/id_campanha/'.$compras->id_campanha);?>">
			                				<img title="Visualizar" data-tooltip src="<?php echo $this->baseUrl('images/detail.png')?>"/>
	                				</a>
			                </td>
			            </tr>
				        <?php endforeach;?>
					<?php endif;?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
<div id="dialog_delete" style="display: none;">
	<p>Deseja realmente excluir a compra: <span id ="valueDelete"></span></p>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/compra/compra.grid.js')?>"></script>
<script type="text/javascript">

 $('#perfisTable').dataTable({
     "aLengthMenu": [
         [30, 50, 100, -1],
         [30, 50, 100, "All"] // change per page values here
     ],
     // set the initial value
     "iDisplayLength": 30,
     "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
     "sPaginationType": "bootstrap",
     "oLanguage": {
         "sProcessing": "Aguarde enquanto os dados são carregados ...",
         "sLengthMenu": "Mostrar _MENU_ registros",
         "sZeroRecords": "Não foram encontrados resultados",
         "sInfoEmpty": "Mostrando de 0 até 0 de 0 registros",
         "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
         "sInfoFiltered": "",
         "sSearch": "Procurar",
         "oPaginate": {
            "sFirst":    "Primeiro",
            "sPrevious": "Anterior",
            "sNext":     "Próximo",
            "sLast":     "Último"
         }
      },
     "aoColumnDefs": [{
             'bSortable': true,
             'aTargets': [0]
         }
     ]
 });
</script>