<!-- Jurupinga -->
<style>
<!--
.dataTables_filter{
	float: right;
}

.dataTables_paginate{
	margin: 0px;
	float: right;
}

-->
</style>

<div class="row-fluid">
     <div class="span12">
	      <h3 class="page-title">
	       Registro de Compras
	        <small> finalizadas</small>
	      </h3>
     </div>
</div>
<div class="row-fluid">
	<a href="#" class="icon-btn span2 campanha">
		<i class="icon-reorder"><i></i></i>
		<div>Busca por Campanhas</div>
	</a>
	<a href="#" class="icon-btn span2 compra">
		<i class="icon-reorder"><i></i></i>
		<div>Busca por Compras</div>
	</a>
</div>
<div class="row-fluid" id="grids">

</div>

<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/compra/relatorio-compra.js')?>"></script>