<link href="<?php echo $this->baseUrl('assets/css/pages/invoice.css')?>" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->baseUrl('assets/css/print.css')?>" media="print" rel="stylesheet" type="text/css"/>
<div class="container-fluid">
	<!-- BEGIN PAGE HEADER-->
	<div class="row-fluid hidden-print">
		<div class="span12">
			<!-- BEGIN PAGE TITLE & BREADCRUMB-->
			<h3 class="page-title">

				 <small></small>
			</h3>
			<!-- END PAGE TITLE & BREADCRUMB-->
		</div>
	</div>
	<!-- END PAGE HEADER-->
	<!-- BEGIN PAGE CONTENT-->
	<div class="row-fluid invoice">
		<div class="row-fluid invoice-logo">
			<div class="span6 invoice-logo-space"><img src="/images/logo4-01.jpg" width="150"/></div>
			<div class="span6">
				<p><?php echo $this->listCampanha['nome'];?><span class="muted">De <?php echo $this->date($this->listCampanha['dt_inicio']) ;?> a <?php echo $this->date($this->listCampanha['dt_fim']);?></span></p>
			</div>
		</div>
		<hr />
		<div class="row-fluid">
			<table class="table table-striped table-hover">
				<thead>
					<tr>
						<th>Codígo</th>
						<th>Produto</th>
						<th class="hidden-480">Atributos</th>
						<th class="hidden-480">Quantidade</th>
					</tr>
				</thead>
				<tbody>
				<?php foreach ($this->listaItens as $listaItens):?>
					<tr>
						<td><?php echo $listaItens['id_compra']; ?></td>
						<td><?php echo $listaItens['nome']; ?></td>
						<td class="hidden-480">
							<?php foreach ($listaItens['id_opcao'] as $key => $opcao):?>
								<?php echo $listaItens['nome_opcao'][$key]['nome_atributo'].' : '.$listaItens['nome_opcao'][$key]['nome'].' <b>|</b> ';?>
							<?php endforeach; ?>
						</td>
						<td class="hidden-480"><?php echo $listaItens['quantidade']?></td>
					</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
		</div>
		<div class="row-fluid">
			<div class="span4">
			</div>
			<div class="span8 invoice-block">
				<a class="btn blue big hidden-print" onclick="javascript:window.print();">Imprimir <i class="icon-print icon-big"></i></a>
				<a class="btn big hidden-print" href="<?php echo $this->baseUrl('/compra/relatorio-compra/grid'); ?>">Voltar</a>
			</div>
		</div>
	</div>
	<!-- END PAGE CONTENT-->
</div>