<link href="<?php echo $this->baseUrl('assets/css/pages/invoice.css')?>" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->baseUrl('assets/css/print.css')?>" media="print" rel="stylesheet" type="text/css"/>
<div class="container-fluid">
	<!-- BEGIN PAGE HEADER-->
	<div class="row-fluid hidden-print">
		<div class="span12">
			<!-- BEGIN PAGE TITLE & BREADCRUMB-->
			<h3 class="page-title">

				 <small></small>
			</h3>
			<!-- END PAGE TITLE & BREADCRUMB-->
		</div>
	</div>
	<!-- END PAGE HEADER-->
	<!-- BEGIN PAGE CONTENT-->
	<div class="row-fluid invoice">
		<div class="row-fluid invoice-logo">
			<div class="span6 invoice-logo-space"><img src="/images/logo4-01.jpg" width="150"/></div>
			<div class="span6">
				<p><?php echo $this->listCampanha['nome'];?><span class="muted">De <?php echo $this->date($this->listCampanha['dt_inicio']) ;?> a <?php echo $this->date($this->listCampanha['dt_fim']);?></span></p>
			</div>
		</div>
		<hr />
		<div class="row-fluid">
			<div style="width: 30%; float: left;">
				<h4>Cliente:</h4>
				<ul class="unstyled">
					<li style="line-height:30px;"><b>Nome: </b><?php echo $this->compra->getUser()->nome_razao; ?></li>
					<li style="line-height:30px;"><b>E-mail: </b><?php echo $this->compra->getUser()->email_corporativo; ?></li>
					<li style="line-height:30px;"><b>CPF: </b><?php echo $this->compra->getUser()->cnpj_cpf; ?></li>
					<li style="line-height:30px;"><b>Telefones: </b><?php echo $this->telefone($this->compra->getUser()->telefone1); ?></li>
					<li style="line-height:30px;"><b>Telefones: </b><?php echo $this->telefone($this->compra->getUser()->telefone2); ?></li>
					<li style="line-height:30px;"><b>Telefones: </b><?php echo $this->telefone($this->compra->getUser()->telefone3); ?></li>
				</ul>
			</div>
			<?php if(count($this->compra->getUser()->getListEndereco()) > 0 ) : ?>
				<?php $i = 0?>
				<?php foreach ($this->compra->getUser()->getListEndereco() as $endereco) : ?>
						<?php if($i < 2) :?>
					<div style="width: 30%; float: left;">
						<h4>Endereço:</h4>
						<ul class="unstyled">
							<li style="line-height:30px;"><b>CEP: </b><?php echo $this->cep($endereco->cep);?></li>
							<li style="line-height:30px;"><b>Logradouro: </b><?php echo $endereco->tipo_logradouro;?></li>
							<li style="line-height:30px;"><b>Endereço: </b><?php echo $endereco->nome_logradouro.' Nº '.$endereco->numero;?></li>
							<li style="line-height:30px;"><b>Bairro: </b><?php echo $endereco->bairro;?></li>
							<li style="line-height:30px;"><b>Cidade: </b><?php echo $endereco->getCidade()->cid_nome ;?></li>
							<li style="line-height:30px;"><b>Estado: </b><?php echo $endereco->getEstado()->ufs_nome;?></li>
						</ul>
					</div>
					<?php $i++;?>
					<?php endif;?>
				<?php endforeach; ?>
			<?php endif;?>
		</div>
		<hr />
		<div class="row-fluid">
			<table class="table table-striped table-hover">
				<thead>
					<tr>
						<th>Código</th>
						<th class="hidden-480">Referencia</th>
						<th>Produto</th>
						<th>Atributos</th>
						<th class="hidden-480">Quantidade</th>
					</tr>
				</thead>
				<tbody>
				<?php if (count($this->compraList) > 0):?>
			        <?php foreach ($this->compraList as $produto):?>
				          <tr class="odd gradeX">
										<td style="width: 30px"><?php echo $produto->id_compra_item; ?></td>
										<td class="hidden-480"><?php echo $produto->getItem()->referencia; ?></td>
										<td><?php echo $produto->getItem()->nome ; ?></td>
										<td>
				                <?php if( isset($this->opcao[$produto->id_compra_item]) > 0):?>
				                <?php foreach ($this->opcao[$produto->id_compra_item] as $opcao) : ?>
				                		<?php echo $opcao['nome_atributo'].' : '.$opcao['nome']; ?> <b>|</b>
				               	<?php endforeach;?>
				               	<?php  else :?>
				               		Sem atributo
				               	<?php endif;?>
				          	</td>
										<td class="hidden-480"><?php echo $produto->quantidade; ?></td>
									</tr>
				      <?php endforeach;?>
				<?php endif;?>
				</tbody>
			</table>
		</div>
		<div class="row-fluid">
			<div class="span4">
			</div>
			<div class="span8 invoice-block">
				<a class="btn blue big hidden-print" onclick="javascript:window.print();">Imprimir <i class="icon-print icon-big"></i></a>
				<a class="btn big hidden-print" href="javascript:history.go(-1)">Voltar</a>
			</div>
		</div>
	</div>
	<!-- END PAGE CONTENT-->
</div>