<div class="row-fluid">
	<table id="horas" class="table table-striped table-hover table-bordered">
		<thead>
			<tr>
				<th style="width: 60px;text-align: center">Dia</th>
				<th style="width: 60px;text-align: center">Data</th>
				<th style="width: 70px;text-align: center">Hora total</th>
				<th style="width: 70px;text-align: center">Hora</th>
				<th style="text-align: center;width: 155px;">Falta</th>
				<th style="text-align: center;width: 155px;">DSR</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->faltaList as $calculoFalta):?>
				<tr data-hora_extra ="<?php echo $calculoFalta->hora_falta?>" class="<?php echo $calculoFalta->hasHoraFaltaEquals()?null:'linha-folga'?>" >
					<?php $data = new Zend_Date($calculoFalta->data)?>
					<td class="vertical-align" rowspan="<?php echo count($calculoFalta->getFaltaList()) ?>">
						<?php echo $data->toString(Zend_Date::WEEKDAY)?>
					</td>
					<td class="vertical-align" rowspan="<?php echo count($calculoFalta->getFaltaList()) ?>">
						<?php echo $data->toString('dd/MM/YYYY')?>
					</td>
					<td class="vertical-align" rowspan="<?php echo count($calculoFalta->getFaltaList()) ?>">
						<?php echo $calculoFalta->hora_falta?>
					</td>
					<?php foreach ($calculoFalta->getFaltaList() as $keyFalta => $falta):?>
						<?php if($keyFalta != 0):?>
							<tr class="<?php echo $calculoFalta->hasHoraFaltaEquals()?null:'linha-folga'?>" >
						<?php endif;?>
						<td class="vertical-align">
							 <a style="display: inline" href="javascript:;" class="hora_falta editable" data-data="<?php echo $data->toString('dd/MM/YYYY')?>" data-pk="<?php echo $falta->id_falta?>" >
								<?php echo $falta->hora?>
							</a>
						</td>
						<td class="vertical-align">
							<a style="display: inline" href="javascript:;" class="tipo_falta editable" data-data="<?php echo $data->toString('dd/MM/YYYY')?>" data-pk="<?php echo $falta->id_falta?>" >
								<?php echo $falta->banco_horas ? 'Banco de horas':"Desconto"?>
							</a>
						</td>
						<td class="vertical-align">
							<a style="display: inline" href="javascript:;" class="dsr_falta editable" data-dsr="<?php echo $falta->dsr?>" data-data="<?php echo $data->toString('dd/MM/YYYY')?>" data-pk="<?php echo $falta->id_falta?>" >
								<?php echo $falta->dsr ? 'Sim':"Não"?>
							</a>
						</td>
						</tr>
					<?php endforeach;?>
				</tr>
			<?php endforeach;?>
		</tbody>
	</table>
</div>