<?php
    /**
     * formulario do controller status para cadastrar e editar os status
    */
?>
<div class="row-fluid" style="margin-top: 10px">
	<div class="portlet box caribbean-green">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder"></i> Formulário Status de processo <?php if($this->vo->sta_id): echo "#{$this->vo->sta_id} "; endif; ?></div>
			<div class="tools">
				<a href="javascript:;" class="collapse"></a>
			</div>
		</div>
	<div class="portlet-body form">
        <form method="post"  class="form-horizontal">
            <?php echo $this->formHidden('sta_id', $this->vo->sta_id);?>

            <?php $identity = Zend_Auth::getInstance()->getIdentity(); ?>

            <?php echo $this->vo->sta_id ? $this->formHidden("id_grupo",$this->vo->id_grupo) : $this->formHidden("id_grupo",$identity->time['id']); ?>


            <div class="row-fluid">
			    <div class="span6">
    				<div class="control-group">
    					<label class="control-label">Nome</label>
    					<div class="controls">
    						<?php echo $this->formText('sta_descricao', $this->vo->sta_descricao, array('class'=> 'span12'));?>
    					</div>
    				</div>
				</div>
				<div class="span6">
    				<div class="control-group">
    					<label class="control-label">Registro público</label>
    					<div class="controls">
    						<input type="checkbox" name="register_public" id="register_public" value="1" <?php echo $this->vo->id_grupo == null  && $this->vo->sta_id? "checked='checked'" : '' ?> >
    					</div>
    				</div>
				</div>
				<div class="row-fluid">
				    <div class="span6">
        				<div class="control-group">
        					<label class="control-label">Ordem/Número</label>
        					<div class="controls">
        						<?php echo $this->formText('sta_numero', $this->vo->sta_numero, array('class'=> 'span12'));?>
        					</div>
        				</div>
    				</div>
    				<div class="span6">
        				<div class="control-group">
        					<label class="control-label">Finalizado</label>
        					<div class="controls">
        						<input type="checkbox" name="sta_finalizado" id="sta_finalizado" value="1" <?php echo $this->vo->sta_finalizado != 0  ? "checked='checked'" : '' ?> >
        					</div>
        				</div>
    				</div>
				</div>
			</div>
			<div class="form-actions">
			    <a href="<?php echo $this->baseUrl('processo/status/grid')?>" class="btn" >Voltar</a>
                <button type="submit" class="btn blue"><i class="icon-ok"></i> Salvar</button>
        	</div>
        </form>
        </div>
    </div>
</div>

<script type="text/javascript" src="<?php echo $this->baseUrl("/scripts/processo/status.form.js")?>">
</script>
