<style>
<!--

i.acao{
    color:#000;
}
.dataTables_filter{
	float: right;
}

.dataTables_paginate{
	margin: 0px;
	float: right;
}

-->
</style>
<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid">
            <a href="<?php echo $this->baseUrl("/processo/status/form")?>" class="icon-btn span2">
                <i class="icon-cog"></i>
                <div> Novo Status </div>
            </a>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <div class="portlet box caribbean-green">
                <div class="portlet-title">
                	<div class="caption"><i class="icon-cogs"></i>Status</div>
    			</div>
    			<div class="portlet-body flip-scroll">
            		<table class="table-bordered table-striped table-condensed flip-content grid_datatable" style="width: 100%">
            		    <thead  class="flip-content">
            		        <tr>
            		            <th>Código</th>
            		            <th>Nome/Descrição</th>
            		            <th>Ordem/Número</th>
            		            <th class="action" style="width: 66px">Ação</th>
            		        </tr>
            		    </thead>
            		    <tbody>
            		    <?php if (count($this->statusList) > 0):?>
            		        <?php foreach ($this->statusList as $status):?>
            		            <tr>
            		                <td style="text-align: center;"><?php echo $status->sta_id?></td>
            		                <td><?php echo $status->sta_descricao ?></td>
            		                <td style="text-align: center"><?php echo $status->sta_numero?></td>
            		                <td class="acoes" style="text-align: center;">
            		                    <a href="<?php echo $this->baseUrl("processo/status/form/sta_id/{$status->sta_id}")?>">
            		                        <i title="Editar Status" class="icon-pencil acao" ></i>
            		                    </a>
            		                </td>
            		            </tr>
            		        <?php endforeach;?>
            		    <?php endif;?>
            		    </tbody>
            		</table>
        		</div>
    		</div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
    var oTable =$('.grid_datatable').dataTable({
        "bJQueryUI": true,
        "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
        "sPaginationType": "bootstrap",
        "aLengthMenu": [[50, 100, 200], [50, 100, 200]],
        "iDisplayLength": 50,
        "oLanguage": {
            "sProcessing": "Aguarde enquanto os dados são carregados ...",
            "sLengthMenu": "Mostrar _MENU_ registros",
            "sZeroRecords": "Não foram encontrados resultados",
            "sInfoEmpty": "Mostrando de 0 até 0 de 0 registros",
            "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
            "sInfoFiltered": "",
            "sSearch": "Procurar",
            "oPaginate": {
               "sFirst":    "Primeiro",
               "sPrevious": "Anterior",
               "sNext":     "Próximo",
               "sLast":     "Último"
            },
            "aoColumnDefs": [{
                'bSortable': true,
                'aTargets': [0]
            }
        ]

         }
    });
});
</script>