<?php
    /**
     * formulario de pesquisa de extratos
    */
?>
<link rel="stylesheet" type="text/css" href="assets/plugins/bootstrap-datepicker/css/datepicker.css" />
<style>
<!--
i.add{
    font-size: 26px;
    color: #00CC99;
    cursor: pointer;
    margin-left: 2px;
}
i.remove-conta, i.remove-empresa{
     color: #e02222;
     font-size: 26px;
     cursor: pointer;
     margin-left: 2px;
}
-->
</style>
<div class="row-fluid" style="margin-top: 20px;">
	<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption"><i class=" icon-dollar"></i> Registro de extrato</div>
			<div class="tools">
				<a href="javascript:;" class="collapse"></a>
			</div>
		</div>
	<div class="portlet-body form">
		<form id="form" method="post" target="_blank" action="processo/relatorio/grid">
				<div class="row-fluid">
					<div class="span3">
                          <div class="control-group">
	                          <label class=" control-label"><?php echo $this->translate('Data de emissão')?></label>
	                          <div class="controls">
								<?php echo $this->formText('de_pro_data_inc',null,array("class" => "span6 datepicker", 'placeholder'=> 'De')); ?>
								<?php echo $this->formText('para_pro_data_inc',null,array("class" => "span6 datepicker", 'placeholder'=> 'Até')); ?>
                          	  </div>
                          </div>
					</div>
					<div class="span3">
                          <div class="control-group">
	                          <label class=" control-label"><?php echo $this->translate('Compensado')?></label>
	                          <div class="controls">
								<?php echo $this->formSelect('compensado',null,array("class" => "span12"), array(null=>'----- Selecione -----', 1=>'Compensado', 2=>'Não compensado')); ?>
                          	  </div>
                          </div>
					</div>
				</div>
                  <div class="row-fluid">
                      <div class="span6">
                          <div class="control-group">
								<div id="empresa_sacado_div">
		                          <label class="control-label"><?php echo $this->translate('Entidade')?></label>
		                          <?php echo $this->formText("empresa_sacado",null, array("class" => "span12", "placeholder" => "Digite o nome do cliente"));?>
		                          <?php echo $this->formHidden("empresas_id");?>
		                        </div>
                          </div>
                      </div>
                      <?php $identity = Zend_Auth::getInstance()->getIdentity(); ?>

                      <?php echo $this->formHidden("id_grupo",$identity->time['id']);  ?>
                  </div>
            	 <div class="row-fluid">
            	    <div class="span6" >
            	        <H3 id="contaSelected" style="display: none">Empresas Selecionadas:</H3>
                        <div id="localEmpresa">
                        </div>
					</div>
            	</div>
                  <div class="row-fluid">
	                  <div class="span12">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Status do processo')?></label>
	                          <div class="controls">
	                            <label class="checkbox span3"><input type="checkbox" id="todos-checkbox" class="checkbox">Todos</label>
								<?php echo $this->formMultiCheckbox("statusList", null,array("class" =>"checkbox",'label_class' => 'checkbox span3'), $this->statusPairs, '')?>
	                          </div>
                          </div>
                      </div>
                  </div>
                  <div class="form-actions">
                      <button id = "gerarView" type="submit" class="btn blue"><i class="icon-ok"></i> Pesquisar</button>
                      <button id="gerarPdf" class="btn green"><i class="icon-file"></i> Gerar relatório sintético</button>
					  <button id="gerarAnalitico" class="btn green"><i class="icon-file"></i> Financeiro por cliente</button>
                  </div>
        </form>
        </div>
    </div>
</div>

<script type="text/javascript" src="assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
<script type="text/javascript" src="assets/plugins/bootstrap-datepicker/js/locales/bootstrap-datepicker.pt-BR.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("/scripts/processo/relatorio.index.js")?>"></script>