<ul class="pagination pull-left">
    <?php if ($this->pageCount){ ?>

            <?php /*echo $this->firstItemNumber; ?> à <?php echo $this->lastItemNumber; ?> de <?php echo $this->totalItemCount; ?> Resultado(s) */ ?>

            <?php if (isset($this->previous)){ ?>
                    <li class="ng-scope disabled">
                        <a class="ng-scope" ng-switch-when="prev" href="<?php echo $this->url(array('page' => $this->previous)); ?>">
                            «
                        </a>
                    </li>
            <?php } ?>

            <!-- Numeracao das paginas -->
            <?php foreach ($this->pagesInRange as $page) { ?>

                    <?php if ($page != $this->current){ ?>

                        <li class="ng-scope">
                            <a class="ng-scope" ng-switch-when="first" href="<?php echo $this->url(array('page' => $page)); ?>">
                                <span class="ng-binding"><?php echo $page; ?></span>
                            </a>
                        </li>

                    <?php } else { ?>

                        <li class="ng-scope active">
                            <a class="ng-scope" ng-switch-when="page" href="">
                                <span class="ng-binding"><?php print $page; ?></span>
                            </a>
                        </li>

                    <?php }?>
            <?php } ?>

            <!-- Proxima -->
            <?php if (isset($this->next)){ ?>
                    <li class="ng-scope">
                        <a class="ng-scope" ng-switch-when="next" href="<?php echo $this->url(array('page' => $this->next,'ord'=>$this->ordem,'ordcampo'=>$this->ordem_campo)); ?>">
                            »
                        </a>
                    </li>
            <?php } ?>

    <?php } ?>
</ul>
