<?php
    /**
     * formulario configurações funcionario
    */
?>

<link href="<?php echo $this->baseUrl('assets/plugins/bootstrap-timepicker/compiled/timepicker.css')?>" rel="stylesheet" type="text/css" media="screen"/>

<style>
.row-fluid [class*="span"]{
	
	margin-left: 0% !important;
}
</style>
<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Cadastro
			 <small> de configurações de funcionários</small>
		</h3>
	</div>
</div>
<div class="row-fluid">
	<div class="portlet box green">
		<div class="portlet-title">
			<div class="caption"><i class="icon-reorder"></i> Formulário</div>
			<div class="tools">
				<a href="javascript:;" class="collapse"></a>
			</div>
		</div>
	<div class="portlet-body form">
        <form method="post"  class="form-horizontal" id="form_config">
                  <?php echo $this->formHidden('id_config_empresa', $this->vo->id_config_empresa);?>
                  <h3 class="form-section">Configurações de Funcionários</h3>
                  <div class="row-fluid">
						<div class="span3">
                          <div class="control-group">
	                          <label class=" control-label"><?php echo $this->translate('Empresa')?></label>
	                          <div class="controls">
	                          	<?php echo $this->formSelect('empresas_id',$this->vo->empresas_id, array('class' => 'span10'), array("" => "Selecione")+$this->funcionarioList);?>
	                          </div>
                          </div>
                      </div>
                      <div class="span3">
                          <div class="control-group">
	                         <label class="control-label"><?php echo $this->translate('Carga Horária')?></label>
	                         <div class="controls ">
	                          	<?php echo $this->formText('carga_horaria',$this->vo->carga_horaria, array('class' => ' m-wrap m-ctrl-small timepicker-24'));?>
	                          </div>
                          </div>
                      </div>
                      <div class="span3 ">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Horas de Almoço')?></label>
	                          <div class="controls">
	                          	<?php echo $this->formText('almoco',$this->vo->almoco, array('class' => 'm-wrap m-ctrl-small timepicker-24'));?>
	                          </div>
                          </div>
                      </div>
                  </div>
                  <div class="row-fluid">
                      <div class="span3">
                          <div class="control-group">
	                          <label class="label_cnpj control-label"><?php echo $this->translate('Início do Expediente')?></label>
	                          <div class="controls">
	                          	<?php echo $this->formText('inicio_expediente',$this->vo->inicio_expediente, array('class' => 'm-wrap m-ctrl-small timepicker-24'));?>
	                          </div>
                          </div>
                      </div>
                      <div class="span3 ">
                          <div class="control-group">
	                          <label class="control-label"><?php echo $this->translate('Fim do Expediente')?></label>
	                          <div class="controls">
	                          	<?php echo $this->formText('fim_expediente',$this->vo->fim_expediente, array('class' => 'm-wrap m-ctrl-small timepicker-24'));?>
	                          </div>
                          </div>
                      </div>
                  </div>
                  <div class="form-actions">
                      <button type="submit" class="btn blue"><i class="icon-ok"></i> Salvar</button>
                      <a href="<?php echo $this->baseUrl('pcp/config/grid')?>" class="btn" >Voltar</a>
                  </div>
        </form>
        </div>
    </div>
</div>
<script src="<?php echo $this->baseUrl('assets/plugins/bootstrap-timepicker/js/bootstrap-timepicker.js')?>" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/pcp/config.form.js')?>"></script>