<style>
<!--
.dataTables_filter{
	float: right;
}

.dataTables_paginate{
	margin: 0px;
	float: right;
}

-->
</style>
<div class="row-fluid">
     <div class="span12">
	      <h3 class="page-title">
	       	Usuários do Pcp
	        <small> do sistema</small>
	      </h3>
     </div>
</div>
<div class="row-fluid">
	<div class="span12">
		<div class="portlet box green">
			<div class="portlet-title">
				<div class="caption"><i class="icon-wrench"></i>Configurações Cadastrados</div>
				<div class="tools">
                    <a href="javascript:;" class="collapse"></a>
                </div>
				<div class="actions">
					<a class="btn " href="<?php echo $this->baseUrl("/pcp/config/form") ?>"><i class="icon-pencil"></i> Novo </a>
				</div>
			</div>
			<div class="portlet-body flip-scroll">
				<div id="sample_1_wrapper" class="dataTables_wrapper form-inline" role="grid">
					<table class="table-bordered table-striped table-condensed flip-content" id="configTable">
						<thead class="flip-content">
							<tr>
								<th class="hidden-480">Código</th>
					            <th>Nome</th>
					            <th>Carga Horária</th>
					            <th class="hidden-480">Almoço</th>
					            <th class="hidden-480">Início do Expediente</th>
					            <th class="hidden-480">Fim do Expediente</th>
					            <th style="width: 60px;">Ação</th>
							</tr>
						</thead>

						<tbody>
							<?php if (count($this->configList) > 0):?>
				        <?php foreach ($this->configList as $config):?>
				            <tr class="odd gradeX">
				            	<td class=""><?php echo $config->id_config_empresa?></td>
				                <td class="" style="width:30px"><?php echo $config->empresas_id?></td>
				                <td class=""><?php echo $config->carga_horaria?></td>
				                <td class=""><?php echo $config->almoco ?></td>
								<td class=""><?php echo $config->inicio_expediente ?></td>
								<td class=""><?php echo $config->fim_expediente ?></td>
				                <td class=" acoes">
				                    <a href="<?php echo $this->baseUrl("pcp/config/form/id_config_empresa/{$config->id_config_empresa}")?>">
				                        <img title="Editar" data-tooltip src="<?php echo $this->baseUrl('images/edit.png')?>"/>
				                    </a>
				                    <a name ="<?php echo $config->id_config_empresa?>" value="<?php echo $config->id_config_empresa?>" href="#" class="deleteMoldal">
				                        <img title="Excluir" data-tooltip src="<?php echo $this->baseUrl('images/delete.png')?>"/>
				                    </a>
				                </td>
				            </tr>
				        <?php endforeach;?>
					<?php endif;?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="dialog_delete" style="display: none;">
	<p>Deseja realmente excluir a configuração: <span id ="valueDelete"></span></p>
</div>
<script type="text/javascript">


 $('#configTable').dataTable({
     "aLengthMenu": [
         [30, 50, 100, -1],
         [30, 50, 100, "All"] // change per page values here
     ],
     // set the initial value
     "iDisplayLength": 30,
     "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
     "sPaginationType": "bootstrap",
     "oLanguage": {
         "sProcessing": "Aguarde enquanto os dados são carregados ...",
         "sLengthMenu": "Mostrar _MENU_ registros",
         "sZeroRecords": "Não foram encontrados resultados",
         "sInfoEmpty": "Mostrando de 0 até 0 de 0 registros",
         "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
         "sInfoFiltered": "",
         "sSearch": "Procurar",
         "oPaginate": {
            "sFirst":    "Primeiro",
            "sPrevious": "Anterior",
            "sNext":     "Próximo",
            "sLast":     "Último"
         }
      },
     "aoColumnDefs": [{
             'bSortable': true,
             'aTargets': [0]
         }
     ]
 });
</script>
<script type="text/javascript" src="<?php echo $this->baseUrl('scripts/pcp/time.grid.js')?>"></script>